### ISSUE TITLE
Add how many MB each file has downloaded

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#101]
For large files, this along with % downloaded would help determine if the file can fit on the hard drive it's being sent to.

PS: Thank you for opening issue 100!

PPS: Do you happen to know an active, multipurpose forum that might answer how I stream and download the same stream simultaneously? In my investigations, I've asked Youtube-DL, Windows Powershell, VLC, and am about to ask sevenforums. I've gotten good directions but each leading me to another specialised forum.

**Comment by Franiac** [comment]
#46
