### ISSUE TITLE
AntiVirus False Positive

### ISSUE THREAD

**Issue by cantoris** [Franiac/TwitchLeecher#102]
Hi,
Version 1.3.6 x64 is generating False Positives from BitDefender amongst others.
 - http://preview.tinyurl.com/zcdfpbp
Thanks for looking and for making a great app!

**Comment by Franiac** [comment]
Cool, but now what? I cannot change my code to be not FALSE positive, because my code is not positive, right :)

Source code is free and open source, there's nothing more that I can do. Thx for the heads up, though :D
