### ISSUE TITLE
"Cutting" video does not work as expected

### ISSUE THREAD

**Issue by notAtable** [Franiac/TwitchLeecher#103]
Hello Sir,

I noticed that the time I'm trying to cut the video to and the actual length of the video after downloading doesn't match.

Specs: Win10 64x
Version: 1.3.6
Channel: Sevadus
Video: https://www.twitch.tv/videos/80998614

example:
![20170214](https://cloud.githubusercontent.com/assets/22797943/22933621/6a5f20d2-f2cc-11e6-8a25-78d20fa9109b.PNG)

Cheers

**Comment by Franiac** [comment]
Please provide the download log so I can see to what values you tried to crop the VOD.

**Comment by notAtable** [comment]
Ah, I knew I forgot something. I already closed the application. Are the logs stored somewhere even after closing?
I tried to cut the first five minutes of the video to 4:30:00 like Twitch Leecher is displaying. The original Video is exactly 04:35:00 long. Does that help?

**Comment by Franiac** [comment]
No, download logs are not being stored persistantly. Did you crop the start at 05:00 or the end to 04:30:00?

**Comment by notAtable** [comment]
I cropped at the start. I could download one more time if that helps you.

**Comment by Franiac** [comment]
I actually found the reason for all this while investigation another issue #96 

I will release a new version of TL in the near future

**Comment by Franiac** [comment]
Fixed with checkin for issue #96
