### ISSUE TITLE
Tiny Spelling Mistake

### ISSUE THREAD

**Issue by JohnStephenEvil** [Franiac/TwitchLeecher#104]
On the "Authorise your Twitch account..." tab, you've written

> This is the only way that Twitch Leecher can verify that **your are** subscribed to the channel...

"your are"

It should be:
"you are"
or
"you're"

As I'm sure you are aware.
It's only tiny, but it is in fact an error.

**Comment by Franiac** [comment]
Whops... must have been late when I wrote it :P 

I do not download sub-only VODs myself, thx for the info!
