### ISSUE TITLE
ER: Looking up all the vods starting at a certain date

### ISSUE THREAD

**Issue by notAtable** [Franiac/TwitchLeecher#105]
Hello Sir,

it would be great if the users could input a certain date when searching for vods in a channel and TL would then return all the vods starting at that date. That would safe a lot of scrolling.

Cheers

**Comment by Franiac** [comment]
Yes, you're totally right but I have a problem with that. The Twitch API does not provide a query parameter where I could define a date. I can only query VODs in terms of "give me the last X VODs".

I could go for the brute force approach and just query them all and filter them in TL but that is very slow on very large channels. Look at the channel "Cirno_TV". If I query all VODs, I get over 1600 broadcasts and highlights. That takes quite some time (>10s) just to make the API calls and receive the data. The local filtering is not a problem.

Let me do some testing for that and then I'll decide if I want to substitute the "how many drop down box" for a date input field.

**Comment by notAtable** [comment]
Is there a way to only check vor the meta-data of the VOD? Thinking out loud here, but maybe then could you do it kind of in a heap-search way? The way I'm imagining it is like this:

```
1. TL queries a chanel for the total number of vids.
2. TL get's the 1/2 * nth VOD and checks the date.
3. If date > requested date get 1/2 * n - 1/4 * n video
```

Repeat until date found or at least it can't be approached any closer.

**Comment by Franiac** [comment]
no, no meta data. pretty stupid API to be honest. the API only works with limit and offset. like "query 100, offset 200" will give you VODs 200-300. so i have to query the first 100 (ordered by date desc) and see if the date is in there. if not, query the next 100 with offset 100 and check again for the date. a more optimized way to do it doesn't exist. so basically we actually end up with a heap based search.

**Comment by Franiac** [comment]
oh and i want to add that the query limit is 100 VODs with a single request. so with 1600 VODs in a channel we could end up with 16 web requests. like i said, kinda bullshit API.

**Comment by notAtable** [comment]
Ah, that's sad.

**Comment by Franiac** [comment]
See #152 

Closing this one
