### ISSUE TITLE
Chat data download

### ISSUE THREAD

**Issue by miniqwerty** [Franiac/TwitchLeecher#106]
Hey Franiac, thanks for the amazing software. It would be awesome to have the ability to download the chat data with the vod and then use the data to search for timestamps with a lot of "lol" "PogChamp" "haha" etc. to make finding highlights as easy as looking through a few places to determine if the highlight is good enough. Thanks again.

**Comment by Franiac** [comment]
Ther is no API support for that.

**Comment by zefie** [comment]
> Ther is no API support for that.

This is no longer true. Perhaps it was a the time of this issue.

But as of now, with a little research into how they do it on their site, you'll find api.twitch.tv/v5/videos/(vodid)/comments (requires clientID)

If you know PHP check out my script I wrote for a guy on reddit.

https://pastebin.com/PdT86E2k

**Comment by Franiac** [comment]
I know it is possible now but the v5 API will be shutdown on 12/31/2018. So if I implemented that right now I would use the new Helix API. But other than that I don't see me doing it anytime soon. There are so many things I want to implement on the VOD side (#46 for example) first. The amount of users really wanting this feature is farely small compared to the rest. It's kinda like the guys who want a TL Linux port. It takes a huge effort for pleasing like 10 people -> not worth.

I don't really get, why the Twitch API is not capable of just returning "big" responses (the whole chat of a video). I mean it's not an issue making multiple requests with offsets but then they want you to only make 2 calls per second. Why not making a single request with a content size of like 1MB (how big is a 3hr chat anyways??? Cannot be THAT big, right?). I don't get it but they probably have an idiotic reason for it :P
