### ISSUE TITLE
Input string was not in the correct format

### ISSUE THREAD

**Issue by dbkynd** [Franiac/TwitchLeecher#107]
Attempting to leech VOD ID# 119015737

There seems to be an error parsing the playlist.
https://hastebin.com/iziqowavox.sql

Comparing the m3u8 playlist between the ID above and a different one that downloaded correctly, I noticed the one that errors does not have the ``start_offset`` and ``end_offset`` parameters.

**Comment by Franiac** [comment]
This is not related to any offsets. Twitch is again being creative with the m3u8 playlist specification. They throw a negative value in the last EXTINF tag where only positive values are allowed. Well played, Twitch :/

**Comment by dbkynd** [comment]
Ah-ha! Thanks for looking into it.
