### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ppp789** [Franiac/TwitchLeecher#108]
when the download done i get error
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 124461743
Selected Quality: 1920x1080@60fps
Download Url: https://www.twitch.tv/videos/124461743
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\*\Downloads\20170224_124461743_League of Legends.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\*\AppData\Local\Temp\TL_6578c10d-8310-4e19-b7a8-97660229bcc8

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A124461743%2C%22expires%22%3A1488100117%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: e8ff373877e3b0d7fbab3518dd9eb2321b255e49
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\*\AppData\Local\Temp\TL_6578c10d-8310-4e19-b7a8-97660229bcc8'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/chunked/index-muted-OCAVM225XE.m3u8
https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/high/index-muted-OCAVM225XE.m3u8
https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/medium/index-muted-OCAVM225XE.m3u8
https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/low/index-muted-OCAVM225XE.m3u8
https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/mobile/index-muted-OCAVM225XE.m3u8
https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/audio_only/index-muted-OCAVM225XE.m3u8

Playlist url for selected quality 1920x1080@60fps is https://vod190-ttvnw.akamaized.net/v1/AUTH_system/vods_07e8/mushisgosu_24618793168_607345075/chunked/index-muted-OCAVM225XE.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 5428

Starting parallel video chunk download
Number of video chunks to download: 5428
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\*\AppData\Local\Temp\TL_6578c10d-8310-4e19-b7a8-97660229bcc8\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\*\AppData\Local\Temp\TL_6578c10d-8310-4e19-b7a8-97660229bcc8\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\*\Downloads\20170224_124461743_League of Legends.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\*\AppData\Local\Temp\TL_6578c10d-8310-4e19-b7a8-97660229bcc8'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
I can download the given VOD without any problems.

But take a look at your temporary download path: "C:\Users*\AppData\Local\Temp\"

What is the "*" doing there. That could very well be the problem.

**Comment by ppp789** [comment]
I did nothing there, its save on download folder, it worked until the last update

**Comment by Franiac** [comment]
But does it work without the "*"??

**Comment by Franiac** [comment]
You definitely have to remove the "*" from the download folder and the temporary download folder in the preferences.

**Comment by ppp789** [comment]
Its not cuz the *

**Comment by Franiac** [comment]
please be more specific in your answers, i cannot read your mind. did you try it without the * or not? like i said, i have no problems at all downloading the VOD.

**Comment by ppp789** [comment]
give me the 1.3.6

**Comment by Franiac** [comment]
Dude if you don't answer my questions and keep communicating like a 10 year old YouTube troll, I really can't help you. I don't waste my freetime for this. Closed.

**Comment by ppp789** [comment]
I just need the 1.3.6 version
