### ISSUE TITLE
There should be a persistent log of operations.

### ISSUE THREAD

**Issue by alanhuang122** [Franiac/TwitchLeecher#109]

**Comment by Franiac** [comment]
Why do you think this is necessary? If you encounter an error, you see that in the app and you can copy it wherever you want if you need to (for GitHub issue for example). In my opinion an app should just work and provide as few logs as possible. Users should not have to care about debug information.

**Comment by alanhuang122** [comment]
Admittedly, it's mostly trying to make up for personal mismanagement – I forget which streams I've downloaded and which I haven't, because I (probably) delete streams sooner than I should; i.e. I should probably just keep track myself.

**Comment by Franiac** [comment]
I get what you say. But this has then nothing to do with the logs but with the fact that you want to know the download history of your VODs. Maybe this is something I can think about while implementing the new download manager (see issue #46).

**Comment by alanhuang122** [comment]
Yeah, if a feature like that could be added, it would take care of this.

**Comment by Franiac** [comment]
I take that on the list for the download manager and close this one.
