### ISSUE TITLE
Minimize to system tray

### ISSUE THREAD

**Issue by JohnMcLear** [Franiac/TwitchLeecher#110]
Feature request

**Comment by Franiac** [comment]
What are your thoughts behind that? Is it just "get out of my taskbar"? I understand that argument for background apps like TL so I do not entirely dislike the suggestion. But in my opinion the system tray should have more use than just showing that the app is running (which is the job of the taskbar actually). So the tray should have more valuable features to it like showing the title of the currently active VOD or something like that. Any thoughts about that?

**Comment by Franiac** [comment]
Stale issue: Closed
