### ISSUE TITLE
Multiple active downloads at once

### ISSUE THREAD

**Issue by JohnMcLear** [Franiac/TwitchLeecher#111]
Feature request

**Comment by Franiac** [comment]
That makes no sense. A VOD consists out of thousands of little parts (usually 2mb big). So one VOD download in TL is actually 11000 downloads behind the scenes for example. And those 11000 downloads are indeed performed in a parallel manner (10 parallel downloads with multiple open connections). So there is absolutely no improvement if I enabled parallel VOD downloads. You still have to wait the exact same amount of time to download 5 entire VODs.
