### ISSUE TITLE
Can't install Twitch Leecher

### ISSUE THREAD

**Issue by HardFump** [Franiac/TwitchLeecher#115]
I uninstalled Twitch Leecher a long time ago and recently tried to reinstall it, but every time I run the .exe nothing happens. Really confused. Have already tried to run as administrator.

**Comment by Franiac** [comment]
You can run the installer (the exe) in the command line with the parameter -l "[logfile]".

Example: TwitchLeecher_1.3.7_x64.exe -l "log.txt"

The logfile should be created in the same folder as the installer. if the logfile gets created please send it over to me. if the logfile does not get created, you have a problem with your PC, preferrably the .NET Framework. Please make sure .NET Framework 4.5 or higher is installed on your system.

And please consider ploviding more information when opening an issue:

https://github.com/Franiac/TwitchLeecher#support--issues

**Comment by HardFump** [comment]
Can you explain what I do? I am computer illiterate first computer I ever owned

**Comment by Franiac** [comment]
- Press windows key
- type "cmd" and hit enter
- navigate to the directory where you saved the installer
- type TwitchLeecher_1.3.7_x64.exe -l "log.txt" and hit enter

**Comment by HardFump** [comment]
http://i.imgur.com/4ItUqFq.png

I get this and nothing happens. What am I doing wrong?

**Comment by Franiac** [comment]
yea, and now? did the log file get created or not?

**Comment by HardFump** [comment]
No nothing happened

**Comment by Franiac** [comment]
then you definitely have an issue not related to TL I'm afraid. If the logfile does not get created, not even a single line of code of the installer is actually run. so i cannot help you on this one. have you installed recent updates or something related to the .NET framework or something? I cannot really remote-debug this, i'm sorry.
