### ISSUE TITLE
Twitch Leecher 1.3.7 sync bug

### ISSUE THREAD

**Issue by xender99** [Franiac/TwitchLeecher#117]
I make a video where i explain the problem i have https://www.youtube.com/watch?v=PCaV0r8zMWU

**Comment by Franiac** [comment]
You are using Window Media Player to play the video. It is known that it has issues with some Twitch VODs depending on the encoding settings (which are again dependent on the streamer). If I download the VOD and play it back with VLC or Sony Vegas Pro everything is fine.

Despite all that, the streamer plays back copyright protected music that makes the stream get muted all over the place. Depending on the playback software this also can introduce issues.

TL cannot fix either bad encoding settings or sync issues related to muted audio. TL only downloads the VOD as it is. TL does not encode anything.
