### ISSUE TITLE
Windows 10 Creators Update

### ISSUE THREAD

**Issue by onsamyj** [Franiac/TwitchLeecher#119]
TL stopped working after update.

I’m not sure what additional information do you need (I can see Report.wer, for example), so ask me if you need any.

**Comment by Franiac** [comment]
did you try to reinstall?

**Comment by onsamyj** [comment]
Of course.

**Comment by Franiac** [comment]
well, i highly doublt this is a TL issue to be honest. microsoft fucks the system over with these big updates lately. i strongly recommend not updating for at least 3 months or more.

can you be more specific. what exactly does not work? the installer or TL or downloading or what. please provide as much information as you can. if nothing happens when you double click the installer then you probably have an issue with the .NET framework. you also could take a look at the application logs in the windows event viewer.

**Comment by onsamyj** [comment]
It installs ok. Then I start the program, in Process Explorer I can see it loads with werfault.exe and disappears in a second. Compatibility mode does nothing.

Here is renamed Report.wer: [Report.txt](https://github.com/Franiac/TwitchLeecher/files/908341/Report.txt)

**Comment by Franiac** [comment]
the report is of no use for me. but if werfault pops up, probably there is something in the event viewer. please go check that.

windows key -> event viewer -> windows logs -> application

**Comment by onsamyj** [comment]
**Information:**
Fault bucket 120721783793, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: TwitchLeecher.exe
P2: 1.3.7.0
P3: 58a34625
P4: d3d9.dll
P5: 10.0.15063.0
P6: 631de416
P7: c0000005
P8: 000000000000fd0c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2484.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2531.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER253F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2550.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TwitchLeecher.ex_e72cb418477da0e1ca9537e93c569fd3e21afe_9c6b0bc5_26e82b5a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8813b9db-ef80-43fd-a16d-9d5b29fac396
Report Status: 268435456
Hashed bucket: a0c9e7b5a8f76c6679896699d9270237

**Error:**
Faulting application name: TwitchLeecher.exe, version: 1.3.7.0, time stamp: 0x58a34625
Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
Exception code: 0xc0000005
Fault offset: 0x000000000000fd0c
Faulting process id: 0x3070
Faulting application start time: 0x01d2b14e6ea5d5da
Faulting application path: C:\Program Files\Twitch Leecher\TwitchLeecher.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 8813b9db-ef80-43fd-a16d-9d5b29fac396
Faulting package full name: 
Faulting package-relative application ID: 

**Error:**
Application: TwitchLeecher.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFBF47DFD0C

**Comment by onsamyj** [comment]
If it’s DirectX fault, then it make sense: I have one game that doesn't work in windowed mode anymore.

**Comment by Franiac** [comment]
so i guess MS have messed up again. yep, d3d9.dll faulted -> TL uses WPF which is DirectX9 accelerated. nothing i could do here...

**Comment by huyns-melbourne** [comment]
A workaround to MS breaking this: copying C:\WINDOWS\SYSTEM32\d3d9.dll to the Twitch Leecher's folder seems to fix it.

**Comment by Franiac** [comment]
I have done some research on this topic and I am pretty sure that it is a problem caused by the graphics card driver. Windows doesn't update Nvidia or AMD display drivers after the update. Both manufacturers have released new drivers specifically for the Creators Update. If you could check those out and try again without the 3d39.dll in the TL directory it would be very helpful. I personally cannot update to CU right now.

**Comment by onsamyj** [comment]
It wasn’t Windows problem, it was MSI Afterburner problem. Well, at least, for me. It was misbehaving before, but after CU it just started killing some programs. So, check if you have something that can “hijack” rendering.

To @HnwT comment: didn’t tried it, but putting d3d9.dll in TL’s folder hides it from MSI AB/something else, maybe?

**Comment by HnwT** [comment]
Ah that was the problem. I'm using MSI Afterburner with an older version of Rivatuner Statistics Server and uninstalling it fixed it without copying d3d9.dll to TL's folder. 

The v7.0.0 beta update for Rivatuner Statistics Server has fixed support for CU's updated Directx9 runtime.

**Comment by Franiac** [comment]
Thx for the info, good to know

**Comment by bananaman15** [comment]
@Franiac other thread was closed but just to let you know updating to RTSS version 7 (Beta). Beta is the only one available atm fixed the problem with it not loading. Thank you

**Comment by Xe11o** [comment]
Thanks, circumvented the issue by adding the exe to RTSS and setting detection level to none.
