### ISSUE TITLE
Shut down PC

### ISSUE THREAD

**Issue by MrClaritas** [Franiac/TwitchLeecher#121]
Hello and thank you for the best software! Could you maybe add a feature to shut down the PC once all downloads are done? Thank you again! 👍

**Comment by Franiac** [comment]
and what if some of the queued downloads did not succeed? then the log is gone and you even don't know which downloads failed. before such a feature can be implemented, others have to be refined (download manager, persistent logs and so on). low priority...

**Comment by MrClaritas** [comment]
I mean there can be for example filled logs in TwitchID.txt of that failed download before it shuts down? I don't know, it was just an idea that would help me but still it's not a big deal :)

**Comment by Franiac** [comment]
I have wrapped my head around this issue and there is a lot more involved than a simple shutdown command. Even user rights come into play in combination with UAC. This feature has such a low gain of usability for TL that it is simply not worth investing the required amount of time to design, implement and test it. The cost-benefit ratio is honestly utter crap.
