### ISSUE TITLE
Downloading only 30 mins of vods

### ISSUE THREAD

**Issue by Czechlucie** [Franiac/TwitchLeecher#122]
please can you help me.. i am trying to download vods from 2014 but it only downloads first 30 mins and after that i need to set up times to download part by part of 30 mins.. and i am getting really annoyed.. is there something i can do? i saw once one website where it will make and list parts of the vod and you have download urls to each part.. but in twitch leecher you need to make it manualy...

**Comment by Czechlucie** [comment]
i downloaded jdownloader and it works perfectly fine.. downloading full vids but its sooooo slow... so i dont know where is problem :-( please help

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher/blob/master/README.md#support--issues

**Comment by Czechlucie** [comment]
latest version of TL 1.3.7
windows 10 64
example of one vod: https://www.twitch.tv/videos/42718403
the problem is it only downloads first 30 mins and then it has nothing else but it has capacity like if you would downloaded full vod

log: 
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 42718403
Selected Quality: 960x540
Download Url: https://www.twitch.tv/videos/42718403
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\Youtube Archive\20140820_42718403_Pokémon X_Y.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\L\AppData\Local\Temp\TL_e89c97a7-bbb9-4a16-b6fd-0a8681e2d9a3

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A42718403%2C%22expires%22%3A1492113659%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: fdcfa45d6cdf0aa316270223f1b9c17afc3dc4d0
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\L\AppData\Local\Temp\TL_e89c97a7-bbb9-4a16-b6fd-0a8681e2d9a3'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/a93f9d3a1a/showvideogames_7303711104_7303711104/chunked/highlight-42718403.m3u8
https://vod.edgecast.hls.ttvnw.net/a93f9d3a1a/showvideogames_7303711104_7303711104/audio_only/highlight-42718403.m3u8

Playlist url for selected quality 960x540 is https://vod.edgecast.hls.ttvnw.net/a93f9d3a1a/showvideogames_7303711104_7303711104/chunked/highlight-42718403.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 794

Starting parallel video chunk download
Number of video chunks to download: 794
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\L\AppData\Local\Temp\TL_e89c97a7-bbb9-4a16-b6fd-0a8681e2d9a3\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\L\AppData\Local\Temp\TL_e89c97a7-bbb9-4a16-b6fd-0a8681e2d9a3\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\Youtube Archive\20140820_42718403_Pokémon X_Y.mp4"

Encoding complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\L\AppData\Local\Temp\TL_e89c97a7-bbb9-4a16-b6fd-0a8681e2d9a3'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
Nothing I can do. ffmpeg gets thousands of "non-monotonous DTS"-errors at the 30min mark. If you watch at 13:41 into the VOD you can see the stream freezing all the time. She is definitely dropping frames and/or has an unstable internet connection. ffmpeg (which is used by TL) cannot fix a broken stream without re-encoding (which TL doesn't do).

JDownloader uses ffmpeg, too and stumbles also onto those issues, see here:

https://board.jdownloader.org/showthread.php?t=69463

I highly doublt JDownloader actually can download your VOD entirely. If so, maybe a newer version of ffmpeg is used. I update it on every TL release, so it might work with 1.3.8.
