### ISSUE TITLE
Can't import VOD file to Premiere

### ISSUE THREAD

**Issue by incolas** [Franiac/TwitchLeecher#125]
Hello,

Thank you for making Twitch Leecher, I love it.

Today I encountered an issue as I wasn't able to import some .mp4 files downloaded from Twitch Leecher to Adore Premiere Pro CC 2017.

I already imported quite a few files coming from your program but here I have [this one](https://www.twitch.tv/videos/133761959) and [that one](https://www.twitch.tv/videos/133960826) that I can't get to work for Premiere.

These 2 videos are from the [Starladder CS EN](https://www.twitch.tv/starladder_cs_en) channel. Other VOD's from the same channel, about the same length, work fine on Premiere.

I picked max quality: 1920x1080, 60 fps.

I can play the files in VLC and Media Player without a problem.

It sounds like it could be a codec issue maybe?

Looking for help here,

Cheers

**Comment by entdark** [comment]
It's definitely codec issue. Could you show media info of working and non-working files?

**Comment by Franiac** [comment]
TL does not do anything with codecs. TL only merges files. If the codecs of the stream does not work in Premiere, TL cannot change that. TL does not re-encode the video. It is knows that Premiere has a lot of issues with downloaded Tiwtch VODs but that is Adobes' problem :)
You VODs work perfectly in Vegas Pro and Davinci Resolve for example. You could rather open an issue on the Adobe forums...
