### ISSUE TITLE
VOD from 09/27/2014 not correctly saved

### ISSUE THREAD

**Issue by sanamirei** [Franiac/TwitchLeecher#126]
**note:** might be related to https://github.com/Franiac/TwitchLeecher/issues/122

Trying to download https://www.twitch.tv/videos/30176058 results in 28:54 long video with the size of ~10.7gb. The video plays like normal until 28:31 where it starts frame skipping and advancing while audio is unaffected. I haven't been able to find this issue from any of the more recent vods.

Twitch Leecher processes the video up to 6%, stays there and then suddenly becomes complete (100%).

I've watched the stream from a little bit from the beginning and from 25min to 45min without any real perceived frame dropping.

Using Windows 10 64-bit Version 1607 OS Build 14393.1066
Here's the [log](https://pastebin.com/qaiyFdKL) file.

**Comment by Franiac** [comment]
See #122
