### ISSUE TITLE
Downloading 1080p VODs make them unwatchable

### ISSUE THREAD

**Issue by BaconEggCheese777** [Franiac/TwitchLeecher#127]
VODs downloaded in 1080p are constantly freezing.
VODs downloaded in 720p or less don't have this problem though.

**Comment by BaconEggCheese777** [comment]
TwitchLeecher version 1.3.8
https://www.twitch.tv/nalcs1
Windows 8.1 64-bit

**Comment by Franiac** [comment]
Absolutely smooth here. Tried 4 different VODs of this Twitch user. Maybe your CPU is topping out to 100% or something?

**Comment by BaconEggCheese777** [comment]
Alright, it seems like VLC is having problems playing 1080p VODs
I tried watching the VOD with another player, and it was smooth.
Can you think of a possible reason why this is happening?

**Comment by BaconEggCheese777** [comment]
I found out that problem stems from the VLC player itself and not the VOD.
Sorry for the false alarm.
I tried a different player and the VOD played smoothly.

**Comment by Franiac** [comment]
No problem mate
