### ISSUE TITLE
Option to download all new recordings

### ISSUE THREAD

**Issue by rvgate** [Franiac/TwitchLeecher#128]
Have an option to select all recordings that you have not previously downloaded before.

**Comment by Franiac** [comment]
Duplicate of #76

**Comment by rvgate** [comment]
@Franiac, i don't agree that this is a duplicate. The other ticket states that you can download between or from a certain date... This request is based on if you have downloaded the VOD before (aka, skip if you already have it)

**Comment by Franiac** [comment]
Please read the comments of #76
