### ISSUE TITLE
Can't download any vods.

### ISSUE THREAD

**Issue by aCardboardTube** [Franiac/TwitchLeecher#129]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 137967239
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/137967239
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Creating Movies\Downloads\20170425_137967239_Kingdom_ New Lands.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Creating Movies\AppData\Local\Temp\TL_a465c680-832e-4067-a06e-7b38b2ce8c7b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3A21966240%2C%22vod_id%22%3A137967239%2C%22expires%22%3A1493379081%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 7ce21b4e13a6d6e54a978616ed0cb9c3d1609493
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Creating Movies\AppData\Local\Temp\TL_a465c680-832e-4067-a06e-7b38b2ce8c7b'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/chunked/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/audio_only/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/high/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/low/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/medium/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/mobile/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps is https://vod.edgecast.hls.ttvnw.net/ee7226bebe_danznewz_25133423840_639509485/chunked/index-dvr.m3u8

Retrieving playlist...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Creating Movies\AppData\Local\Temp\TL_a465c680-832e-4067-a06e-7b38b2ce8c7b'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Makes sense because you cannot even watch it on Twitch.tv :)
