### ISSUE TITLE
Error Authorize Twitch Account 

### ISSUE THREAD

**Issue by Kerozen17** [Franiac/TwitchLeecher#136]
I get this https://imgur.com/a/kbCqK
(sorry for my English :(

**Comment by Kerozen17** [comment]
An unexpected error occured:
Valeur hexadecimale 0x00, est un caractère non valide. Ligne 1, position 1
All details were written to log file
C:\User\user\AppData\Roaming\Twitch Leecher\logs\05012017_023428_675_error.log

**Comment by Franiac** [comment]
There's mo image on imgur. And please provide the log file.

**Comment by Franiac** [comment]
Stale -> closed
