### ISSUE TITLE
Twitch Leecher does not open me

### ISSUE THREAD

**Issue by IIorenzo** [Franiac/TwitchLeecher#137]
I try to open it anyway and it will not let me

**Comment by bananaman15** [comment]
Hi I am having the same problem. Last time I used it was pre Windows 10 CU. I had version 1.3.7 installed and when clicking on the icon to open the programme it simply did nothing. I then upgraded to  version 1.3.8 and it does the same.

**Comment by Franiac** [comment]
See #119

**Comment by bananaman15** [comment]
@Franiac thanks, checking that thread out now.
