### ISSUE TITLE
Two-second video glitch when using timestamps

### ISSUE THREAD

**Issue by DamageESP** [Franiac/TwitchLeecher#139]
When I use timestamps to trim the video (start+end), the first two seconds of the resulting clip are corrupted -there is no video, but there is audio. I've only used this software two times, both with trimming at the beginning and the end of the clip. I link both clips.

Sample 1: https://www.youtube.com/watch?v=gbi_sN77u7I
Sample 2: https://www.youtube.com/watch?v=WN1GNUmW4Jc

**Comment by Franiac** [comment]
I know about this. ffmpeg's seeking mechanism works with keyframes. keyframes are frames in the video that tells the decoder how it should decode the video. Usually Twitch streams have keyframes every 2s. If you now crop the video and the start is somewhere between keyframes, the decoder does not know how to decode the video until it finds the first keyframe. this results in the described behavior and is considered "normal". there might be a solution by putting the -ss argument for ffmpeg before the -i. I have read this switches the seeking algorithm somehow but I don't know if it actually works. the latter should make ffmpeg only cut at keyframes. that again means if you crop a 20s part, it might be 19s or 22s long. Like I said, this has to be tested but I don't consider this a bug.

**Comment by DamageESP** [comment]
Oh, I get it. So basically you can't crop inbetween those keyframes in any way, right? Then, if there's no way to get the desired start time, at least, find the nearest keyframe (backwards or forwards), and then start the clip there. 

Also, if they are "predictable" -you know where they're gonna be beforehand, every two seconds?-, you could tell the user in the UI before downloading.

Thanks for your response!

**Comment by Franiac** [comment]
It is not that easy. I can only do, what ffmpeg can do. The keyframes interval is set by the encoder. So every streamer sets up his encoder for streaming in OBS or XSplit. Twitch has a setup guide and recommends 2s. Some streamers follow it, others don't, no guarantee.

**Comment by DamageESP** [comment]
Okay, then I guess I will set my keyframe interval to the minimum, and that will do for me.

Thanks!

**Comment by Franiac** [comment]
I opened up issue #140 for this in order to have something to refer to if questions about the video length come up in the future. So closing this...
