### ISSUE TITLE
Status: Error

### ISSUE THREAD

**Issue by MathiaTV** [Franiac/TwitchLeecher#141]
When I download a VOD from my channel I get an error when the download is finished.
Status: Error. I can't use the file in Adobe Premiere Pro or watch it (I tried VLC).

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 141728496
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/141728496
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Tom\Downloads\20170511_141728496_IRL.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Tom\AppData\Local\Temp\TL_e5d8187d-b0db-4ab3-aa51-179dcbaba606

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3A59392726%2C%22vod_id%22%3A141728496%2C%22expires%22%3A1494656158%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 769ca5eb92f2d1bcfcadaf775a88944dc5cf9579
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Tom\AppData\Local\Temp\TL_e5d8187d-b0db-4ab3-aa51-179dcbaba606'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/chunked/index-muted-LSTCOKVFQT.m3u8
https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/audio_only/index-muted-LSTCOKVFQT.m3u8
https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/720p30/index-muted-LSTCOKVFQT.m3u8
https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/480p30/index-muted-LSTCOKVFQT.m3u8
https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/360p30/index-muted-LSTCOKVFQT.m3u8
https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/160p30/index-muted-LSTCOKVFQT.m3u8

Playlist url for selected quality 1280x720@30fps is https://vod010-ttvnw.akamaized.net/v1/AUTH_system/vods_15c6/mathia_25253119168_646990441/chunked/index-muted-LSTCOKVFQT.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 16098

Starting parallel video chunk download
Number of video chunks to download: 16098
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\Tom\AppData\Local\Temp\TL_e5d8187d-b0db-4ab3-aa51-179dcbaba606\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\Tom\AppData\Local\Temp\TL_e5d8187d-b0db-4ab3-aa51-179dcbaba606\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\Tom\Downloads\20170511_141728496_IRL.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Tom\AppData\Local\Temp\TL_e5d8187d-b0db-4ab3-aa51-179dcbaba606'... done!

Download task ended with an error!

System.AggregateException: Er zijn één of meer fouten opgetreden. ---> System.ApplicationException: An error occured while encoding the video!
   bij TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   bij TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   bij System.Threading.Tasks.Task.Execute()
   --- Einde van intern uitzonderingsstackpad ---
---> (Interne uitzondering #0) System.ApplicationException: An error occured while encoding the video!
   bij TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   bij TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   bij System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
ffmpeg was updated in TL 1.3.8 and I had no problems downloading it. try the new version please

**Comment by Franiac** [comment]
Let me know if it works with 1.3.8 btw.

**Comment by MathiaTV** [comment]
Thank you, that worked!
