### ISSUE TITLE
An error occured while encoding the video

### ISSUE THREAD

**Issue by AHuxley** [Franiac/TwitchLeecher#143]
Hello, Franiac

Thank you for the great software!

But I have a problem with one video:
at the end of downloading a video I get this error: "An error occured while encoding the video".
There is no problem with other videos, only for this: https://www.twitch.tv/videos/140214533

Here is log:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 140214533
Selected Quality: 640x360@25fps
Download Url: https://www.twitch.tv/videos/140214533
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\ВИДЕО\Speedruns\New folder (5)\Sonic Adventure DX_ Director's Cut_SADX Knuckles Story in 10_36.98.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\ВИДЕО\Speedruns\TEMP\TL_1321548f-5041-4d0f-b4b2-a18083f9e123

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A140214533%2C%22expires%22%3A1494735141%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 335e5ce7ee4a621675054bc61934060c8a23846c
Sub-Only: No
Privileged: No

Creating directory 'D:\ВИДЕО\Speedruns\TEMP\TL_1321548f-5041-4d0f-b4b2-a18083f9e123'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/c2132d70e9_dage4_25205160064_643992999/chunked/highlight-140214533.m3u8
https://vod.edgecast.hls.ttvnw.net/c2132d70e9_dage4_25205160064_643992999/audio_only/highlight-140214533.m3u8

Playlist url for selected quality 640x360@25fps is https://vod.edgecast.hls.ttvnw.net/c2132d70e9_dage4_25205160064_643992999/chunked/highlight-140214533.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 217

Starting parallel video chunk download
Number of video chunks to download: 217
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'D:\ВИДЕО\Speedruns\TEMP\TL_1321548f-5041-4d0f-b4b2-a18083f9e123\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "D:\ВИДЕО\Speedruns\TEMP\TL_1321548f-5041-4d0f-b4b2-a18083f9e123\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\ВИДЕО\Speedruns\New folder (5)\Sonic Adventure DX_ Director's Cut_SADX Knuckles Story in 10_36.98.mp4"

Starting temporary download folder cleanup!
Deleting directory 'D:\ВИДЕО\Speedruns\TEMP\TL_1321548f-5041-4d0f-b4b2-a18083f9e123'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by AHuxley** [comment]
Version 1.3.8 - same error.
Log:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 140214533
Selected Quality: 640x360@25fps
Download Url: https://www.twitch.tv/videos/140214533
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\ВИДЕО\Speedruns\New folder (5)\Sonic Adventure DX_ Director's Cut_SADX Knuckles Story in 10_36.98.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\ВИДЕО\Speedruns\TEMP\TL_10512f5b-3379-4284-adce-47a2bff2b992

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A140214533%2C%22expires%22%3A1494745796%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 13156c5d1f4b3fddcb3e1fc1bcb8ea3009c256a9
Sub-Only: No
Privileged: No

Creating directory 'D:\ВИДЕО\Speedruns\TEMP\TL_10512f5b-3379-4284-adce-47a2bff2b992'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod033-ttvnw.akamaized.net/c2132d70e9_dage4_25205160064_643992999/chunked/highlight-140214533.m3u8
https://vod033-ttvnw.akamaized.net/c2132d70e9_dage4_25205160064_643992999/audio_only/highlight-140214533.m3u8

Playlist url for selected quality 640x360@25fps is https://vod033-ttvnw.akamaized.net/c2132d70e9_dage4_25205160064_643992999/chunked/highlight-140214533.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 217

Starting parallel video chunk download
Number of video chunks to download: 217
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'D:\ВИДЕО\Speedruns\TEMP\TL_10512f5b-3379-4284-adce-47a2bff2b992\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "D:\ВИДЕО\Speedruns\TEMP\TL_10512f5b-3379-4284-adce-47a2bff2b992\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\ВИДЕО\Speedruns\New folder (5)\Sonic Adventure DX_ Director's Cut_SADX Knuckles Story in 10_36.98.mp4"


Starting temporary download folder cleanup!
Deleting directory 'D:\ВИДЕО\Speedruns\TEMP\TL_10512f5b-3379-4284-adce-47a2bff2b992'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
This is a common issue. FFMPEG sometimes has problems merging Twitch VODs. This often happens when the streamer dropped frames or has a bad internet connection in general.
There is nothing TL can do about this. TL only uses FFMPEG to merge the downloaded VOD parts. If this fails, well... then it fails. I am sorry, but there is nothing I can do.

**Comment by Woland77** [comment]
How can I self-diagnose this problem so that I can know whether a specific VOD is going to work or not? it happens on some VODS but not others. 
I'm not a programmer so I don't know what to look for in the notes. Thanks.
