### ISSUE TITLE
Audio and Video Desync Since version 1.3.4 - 1.3.8

### ISSUE THREAD

**Issue by Tekniikxd** [Franiac/TwitchLeecher#146]
Ever since update 1.3.4 whenever I download a VOD audio and video aren't synced up. Even in the newest 1.3.8 version that issue still exists. And it's not only my PC because my friend tried it as well and it existed for him as well.

**Comment by Franiac** [comment]
Provide examples please

**Comment by Tekniikxd** [comment]
Ok never mind. For some reason when I download the VOD and look at it with Windows Media Player the audio is desynced. But as soon as I upload to youtube its not desynced.

**Comment by Franiac** [comment]
Don't use Windows Media Player. That piece of crap software has a lot of problems with various codecs and I know about a lot of problems especially related to Twitch VODs. I recommend using VLC.
