### ISSUE TITLE
can´t download any voids...

### ISSUE THREAD

**Issue by Makebeesandeagles** [Franiac/TwitchLeecher#148]
Hello,

I was using TwitchLeecher 1.2.2 in my windows vista and updated to the most recent(1.3.9) and now when im downloading a void it goes 100% completed and give me 2 error afther:

-ffmpeg_x86exe - point of input not found (and stop working)

was not possible to find the point of input of procedure GetNumaNodeProcessorMaskEx in the library of hyperlink dynamics KERNEL32.DLL

- when opening it appear a tiny error that can´t be read for being to small and not showing,twitchleecher only appear wen closing the error.

Logs:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.9

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 150928602
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/150928602
Crop Start: Yes (00:00:00)
Crop End: Yes (00:01:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Administrador.luso\Downloads\20170610_150928602_IRL.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x86.exe
Temporary Download Folder: C:\Users\Administrador.luso\AppData\Local\Temp\TL_7a61d24a-9e3d-4c69-ac16-8f1b0050de10

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A150928602%2C%22expires%22%3A1497306953%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 6764a106ef762130a3999fe50ca07fe4952353b6
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Administrador.luso\AppData\Local\Temp\TL_7a61d24a-9e3d-4c69-ac16-8f1b0050de10'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/chunked/index-muted-LXSMWXPI0Y.m3u8
https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/720p30/index-muted-LXSMWXPI0Y.m3u8
https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/480p30/index-muted-LXSMWXPI0Y.m3u8
https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/audio_only/index-muted-LXSMWXPI0Y.m3u8
https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/360p30/index-muted-LXSMWXPI0Y.m3u8
https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/160p30/index-muted-LXSMWXPI0Y.m3u8

Playlist url for selected quality 1280x720@30fps is https://vod.edgecast.hls.ttvnw.net/2c4118aa1d84c91967ab_jasminemilktea_25479934480_661166397/720p30/index-muted-LXSMWXPI0Y.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 818

Starting parallel video chunk download
Number of video chunks to download: 6
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\Administrador.luso\AppData\Local\Temp\TL_7a61d24a-9e3d-4c69-ac16-8f1b0050de10\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x86.exe' on local playlist...
Command line arguments: -y -ss 0 -i "C:\Users\Administrador.luso\AppData\Local\Temp\TL_7a61d24a-9e3d-4c69-ac16-8f1b0050de10\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc -t 60 "C:\Users\Administrador.luso\Downloads\20170610_150928602_IRL.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Administrador.luso\AppData\Local\Temp\TL_7a61d24a-9e3d-4c69-ac16-8f1b0050de10'... done!

Download task ended with an error!

System.AggregateException: Ocorreram um ou mais erros. ---> System.ApplicationException: An error occured while processing the video!
   em TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   em TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
   --- Fim do rastreio da pilha de excepção interna ---
---> (Excepção Interna #0) System.ApplicationException: An error occured while processing the video!
   em TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   em TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()<---

 

waiting for your answer on how to fix it..
cya

**Comment by Franiac** [comment]
Sure it doesn't work. Windows Vista is neither supported by ffmpeg nor by TL. Why are you using such an ancient operation system that's out of support?

**Comment by Makebeesandeagles** [comment]
i don´t have a job to upgrade the system. so if this 1.3.9 is not for my pc, can i get old version that i was using and it was working?

**Comment by Franiac** [comment]
nope, nothing lower than 1.3.7 will work because Twitch change their API over time and old versions of TL won't work anymore. I can't help you with this one, I'm sorry.

**Comment by Makebeesandeagles** [comment]
does tl work on tablets 4.2+?

**Comment by Franiac** [comment]
only windows PC
