### ISSUE TITLE
Audio Only Quality

### ISSUE THREAD

**Issue by cheeseman1** [Franiac/TwitchLeecher#149]
Thanks for great utility!

Audio only quality downloads are only available for streams that are presently live since 1.3.9. Perhaps this is due to the change in Twitch API? The Audio only quality is great for listening to Podcast style streams.

**Comment by Franiac** [comment]
Yep, Twitch does not support audio only streams anymore.

**Comment by tezJR** [comment]
I didn't notice that! For info, the last vods with the audio only option appear to be May 30. I use a freeware program to batch extract audio. May I name it?

**Comment by Franiac** [comment]
Sure
