### ISSUE TITLE
Downloads using 1080p60 quality result in 30 fps videos

### ISSUE THREAD

**Issue by ErrorFlynn** [Franiac/TwitchLeecher#150]
For example, I just downloaded this [URL](https://www.twitch.tv/videos/131944033) cropping the start at 00:14:00, and the resulting video has 29.970 fps instead of 60. What's going on, is this a bug? I'm using Twitch Leecher 1.3.9 on Windows 8.1.

**Comment by Franiac** [comment]
If you watch the video online on Twitch you encounter the exact same issue. You can set it to 1080p@60fps and the video player shows 30fps. Twitch lies :) nothing I can do here.

**Comment by ErrorFlynn** [comment]
I see, thank you for the clarification.
