### ISSUE TITLE
Support for multi-selection and -downloading in the search result view

### ISSUE THREAD

**Issue by Franiac** [Franiac/TwitchLeecher#153]
VODs need to be downloaded one by one. multi-selection in the search result view would be nice. Needs implementation of an advanced download dialog where all VODs can be reviewed before downloading.

**Comment by aselwyn1** [comment]
What about also adding pausing to the download queue?

**Comment by Franiac** [comment]
Scrapping this feature due to the current workload and implementation of other systems. Could be reopened in the future.
