### ISSUE TITLE
Future Request: Do not delete 

### ISSUE THREAD

**Issue by gokturksm** [Franiac/TwitchLeecher#154]
> Starting temporary download folder cleanup!
> Deleting directory 'C:\Users\...\AppData\Local\Temp\TL_2d5c0dec-ae4f-4967-8d5b-93056dfde405'... done!

Here's what I'd like to see as an enhancement. Do not delete directory if my internet connection is failed for a moment. It has happened to me three times today. And say, I got to the 73% downloaded but deleting directory after a failed connection... It's hard to take :(

I can make it work after a disconnection. I can find where it stopped from the downloaded stream(time stamp etc.) and then again I would start downloading it from where it stopped. If it wouldn't delete all files, that'd be great.

I'd like to see an option which is "Do not delete directory if connection lost". That's it.

Thanks for the great application ^^

**Comment by Franiac** [comment]
Twitch does not allow to reconnect to a server with the same token as soon as the download failed. TL already retries failed parts 3 times over the same connection before deciding to end the download with an error.

What do you want to do with all these VOD chunks? The temporary download folder is nothing the user should get involved in. It is only the source material that ffmpeg uses to merge the single video file again. I don't understand how you want to go on from a failed state. What do you want to do with the downloaded files?

**Comment by gokturksm** [comment]
I want to keep them and continue download from the disconnected point. So I would not lose all the progression. I can work with ffmpeg, so that'd a nice little addition, I thought.

**Comment by Franiac** [comment]
If you work with ffmpeg on your own, why do you need TL then? My goal with TL is to make things easy for the users that do not know anything about video processing and downloading VODs via APIs. Users want to click on stuff and TL should download what they clicked on. That's the spirit.

Keeping the downloaded chunks and processing them is "advanced stuff" that TL tries to hide from the user. I don't like the idea of opening up TL to be some kind of "support-tool" for ffmpeg users.

There's Issue #46 that will make TL more error-proof in the future. I am not a fan of adding workaround features to software that only 3 of 100000 people actually take advantage of. I hope you understand this.

**Comment by gokturksm** [comment]
I get your philosophy. Sorry for me being one sided on the subject. Because of the disconnections, I have learned to use ffmpeg recently. Thanks for the explanation.

**Comment by Franiac** [comment]
No problem, it's definitely valid to bring this up here. But you must see that overreacting to specific problems of a single user (sorry that you are one of these persons) is not the best solution in order to make software better. I made this mistake a lot of times in the past... and I have learned from it 😄
