### ISSUE TITLE
TL Can't resolve Remotename: 'api.twitch.tv' [BUG]

### ISSUE THREAD

**Issue by D3m3rion** [Franiac/TwitchLeecher#155]
For a week or two I am not able to download any VODs. Everytime I'm searching a channel name, url, or ID, it throws the mentioned error at me.
I'll add a log file.
Might be a problem caused by Twitch, because I tried an online VOD Downloader (not expecting it to work) but it gave me the same error. 
So I guess Twitch changed something?
Have't seen this reported yet.

[06282017_074911_416_AM_error.txt](https://github.com/Franiac/TwitchLeecher/files/1107955/06282017_074911_416_AM_error.txt)

**Comment by Franiac** [comment]
The question is what version of TL are you using? If 1.3.9 it definitely must be a connection issue on your end. TL has over 50000 users and I don't think noone would have reported such a massive error in the last 2 weeks. I cannot reproduce your problem. TL 1.3.9 is running just fine.
