### ISSUE TITLE
Don't know what error this is

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#156]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.9

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 155048746
Selected Quality: 960x540@30fps (Source)
Download Url: https://www.twitch.tv/videos/155048746
Crop Start: Yes (00:03:00)
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Downloaded1\WhatCD5\AllisArcadia_20170628_155048746 so540 3 .__ Cutie on Duty! __. MOAR Memory lane and murderrr_Fable Anniversary.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\K\AppData\Local\Temp\1TwLch\TL_59a412c8-c9b2-4762-a36e-c2f1bec6563d

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A155048746%2C%22expires%22%3A1498808040%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 812e8056a4ab270853eee09052e02d8090f32788
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_59a412c8-c9b2-4762-a36e-c2f1bec6563d'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/4804f4b66300acd9e095_allisarcadia_25617307360_669752202/chunked/index-muted-P66ZMMUVNV.m3u8
https://vod.edgecast.hls.ttvnw.net/4804f4b66300acd9e095_allisarcadia_25617307360_669752202/480p30/index-muted-P66ZMMUVNV.m3u8
https://vod.edgecast.hls.ttvnw.net/4804f4b66300acd9e095_allisarcadia_25617307360_669752202/audio_only/index-muted-P66ZMMUVNV.m3u8
https://vod.edgecast.hls.ttvnw.net/4804f4b66300acd9e095_allisarcadia_25617307360_669752202/360p30/index-muted-P66ZMMUVNV.m3u8
https://vod.edgecast.hls.ttvnw.net/4804f4b66300acd9e095_allisarcadia_25617307360_669752202/160p30/index-muted-P66ZMMUVNV.m3u8

Playlist url for selected quality 960x540@30fps (Source) is https://vod.edgecast.hls.ttvnw.net/4804f4b66300acd9e095_allisarcadia_25617307360_669752202/chunked/index-muted-P66ZMMUVNV.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1455

Starting parallel video chunk download
Number of video chunks to download: 1438
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_59a412c8-c9b2-4762-a36e-c2f1bec6563d\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -ss 10 -i "C:\Users\K\AppData\Local\Temp\1TwLch\TL_59a412c8-c9b2-4762-a36e-c2f1bec6563d\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Downloaded1\WhatCD5\AllisArcadia_20170628_155048746 so540 3 .__ Cutie on Duty! __. MOAR Memory lane and murderrr_Fable Anniversary.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_59a412c8-c9b2-4762-a36e-c2f1bec6563d'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
This always happens when FFMPEG is not able to merge the VOD parts together. This can happen when there are encoding errors in the source material that ffmpeg cannot skip. Maybe the streamer dropped too many frames, maybe Twitch fails at transcoding. The possibilities are endless. I am not an ffmpeg specialist but I don't see how I could fix those issues. If I print out the error mesage of ffmpeg, I usually get 10000 lines of gibberish that I don't understand.

**Comment by tezJR** [comment]
Understood. Yeah, it output a file, but it wouldn't play in VLC.
