### ISSUE TITLE
CLI Params

### ISSUE THREAD

**Issue by dbkynd** [Franiac/TwitchLeecher#157]
Hello, avid TL user here. I was interested to see if you might support CLI arguments in the future.

I'm looking to kick off a TL download with default settings, by providing the VOD ID as a CLI argument, or a comma delimited list for multiples.

Any thoughts?

My goal is to download all future vods from a particular Twitch channel back from Twitch, daily, with a CRON job that can use your software. Local recording is not an option.

**Comment by Franiac** [comment]
So many good feature requests and so little time...

**Comment by dbkynd** [comment]
Haha, no worries, I saw you mention you're building a house. Congrats!

**Comment by Franiac** [comment]
Closing this issue. Due to the current workload I don't see any possibility to implement this in the near future. Created the "maybe later" label so I can find closed issues with features worth looking into. I just don't want to look at a full list of issues that I know won't happen anytime soon.
