### ISSUE TITLE
Exe crashes instantly

### ISSUE THREAD

**Issue by Xe11o** [Franiac/TwitchLeecher#158]
Windows 10 x64, installed latest version

Following from app logs:

Source - .NET Runtime

Application: TwitchLeecher.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFB8DD4FD0C

Source - Application Error

Faulting application name: TwitchLeecher.exe, version: 1.3.9.0, time stamp: 0x593c49b8
Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
Exception code: 0xc0000005
Fault offset: 0x000000000000fd0c
Faulting process ID: 0x4a48c
Faulting application start time: 0x01d2f1d43eecffbc
Faulting application path: C:\Program Files\Twitch Leecher\TwitchLeecher.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report ID: 90e51c04-8cd3-4b2d-8d60-9fb07f7405cc
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Franiac** [comment]
See last 3 comments of #119
