### ISSUE TITLE
Audio only not appearing for new videos

### ISSUE THREAD

**Issue by yohanosullivan** [Franiac/TwitchLeecher#160]
Hello , huge fan of the program , thank you so much for it. Its made my commute much better! 

Recently the Audio only option stopped showing for the channel i watch -(Geekansundry) its a subscription only, not sure if that is relevant. Video download works fine and audio download works for old videos( a month or so back) but not new ones. 

kind regards, 

Mike

**Comment by Franiac** [comment]
Duplicate of #149
