### ISSUE TITLE
Since update can't write to network share

### ISSUE THREAD

**Issue by JohnMcLear** [Franiac/TwitchLeecher#166]
Claims don't have permissions but can create/delete folders and files fine in "Explorer"

**Comment by Franiac** [comment]
What path do you try to save to VODs in? Explorer elevates to admin permission depending what UAC setup you have. TL does not run elevated. So you don't have write permission in "Program Files" and a lot of other folders on the system drive for example.

**Comment by JohnMcLear** [comment]
A samba share.  I will try run as admin and let you know

**Comment by JohnMcLear** [comment]
Same error when running as administrator

**Comment by Franiac** [comment]
Wait... I removed the permission check for network shares in 1.3.9... what version are you using???

**Comment by JohnMcLear** [comment]
1.3.9.....

**Comment by JohnMcLear** [comment]
Want me to check 1.3.8?  You might have made default "fail" and then "pass" when write and by removing check you made all network shares fail.. ?

**Comment by Franiac** [comment]
```C#
// Only check local drives
if (driveInfo.DriveType != DriveType.Fixed)
{
    return true;
}`

this is pretty clear... how is that SMB drive mounted??

**Comment by JohnMcLear** [comment]
On windows desktop so just usual one time auth to it..  It's not mounted as a drive letter..  It's a network share...

**Comment by Franiac** [comment]
That's the problem... for .NET a folder is a folder. If you just linked a folder to a SMB share, that folder does not have windows permissions. There is no way to determine if a folder of a shortcut is a SMB share or not. If you mount that share a a drive letter it will work.

**Comment by JohnMcLear** [comment]
Weird, it wasn't mounted as a share before and it's been working..

**Comment by Franiac** [comment]
I don't know... I only stripped the permission check for network shares, that's all. There were no changes to the check itself.

**Comment by JohnMcLear** [comment]
I mounted as a symbolic link and it's working like that so I guess I can live with that :)  Thanks!
