### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by SirJorb** [Franiac/TwitchLeecher#169]
When I try to install from the x64 downloader, even when running the installer as administrator, it's stuck at 0% on Status: Installing.

**Comment by Franiac** [comment]
I am pretty bad at remote guessing. Please provide useful information. Windows version? Insider Build or not? How long does it show 0% before you ended the task? Are there errors in the event viewer of windows (category "Application")?

Give it 10 minutes and see if something happens. Depending on your system, the installer process can take quite some time.

**Comment by Franiac** [comment]
Closed because stale
