### ISSUE TITLE
I can't figure out what the error is

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#171]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.9

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 165283164
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/165283164
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Downloaded1\WhatCD5\KatFTWynn_20170807_165283164 h Mother & Daughter Play_ The Wolf Among Us ENDING! ~Episode 4 & 5~ (Telltale Game)_The Wolf Among Us (I forgot to save spethFeels).mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\K\AppData\Local\Temp\1TwLch\TL_43268841-0abe-48b5-b524-121a4533195c

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A165283164%2C%22expires%22%3A1503265121%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 0596c47674ff8fa7f0079d8091711301a4333377
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_43268841-0abe-48b5-b524-121a4533195c'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/chunked/highlight-165283164.m3u8
https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/720p60/highlight-165283164.m3u8
https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/480p30/highlight-165283164.m3u8
https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/audio_only/highlight-165283164.m3u8
https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/360p30/highlight-165283164.m3u8
https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/160p30/highlight-165283164.m3u8

Playlist url for selected quality 1280x720@60fps is https://vod.edgecast.hls.ttvnw.net/088a80fc0965b165c2bd_katftwynn_25934845968_689598064/720p60/highlight-165283164.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1927

Starting parallel video chunk download
Number of video chunks to download: 1927
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_43268841-0abe-48b5-b524-121a4533195c\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\K\AppData\Local\Temp\1TwLch\TL_43268841-0abe-48b5-b524-121a4533195c\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Downloaded1\WhatCD5\KatFTWynn_20170807_165283164 h Mother & Daughter Play_ The Wolf Among Us ENDING! ~Episode 4 & 5~ (Telltale Game)_The Wolf Among Us (I forgot to save spethFeels).mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\K\AppData\Local\Temp\1TwLch\TL_43268841-0abe-48b5-b524-121a4533195c'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
See #156 and #143

**Comment by tezJR** [comment]
Understood. May I request adding that error explanation to a future release, as others might ask (or I if I forget)?

**Comment by Franiac** [comment]
Oh, you opened #156... just saw that ;)

Yea, it's probably a good idea to get that info to the user. I'll put it on my list.
