### ISSUE TITLE
Convert VOD from 60fps to 30fps pitches voices

### ISSUE THREAD

**Issue by Muchtin** [Franiac/TwitchLeecher#173]
Hi,

since version 1.3.9 the audio will be pitched in VODs when the are processed. Tested with these VODs

https://www.twitch.tv/videos/168915243
https://www.twitch.tv/videos/168963781

Audio is always fine if source is selected even if its 28fps.

**Comment by Franiac** [comment]
I don't understand the problem. I have downloaded each of the VODs in different qualities and everything is fine. No pitched audio whatsoever. Would be quite magical if TL pitched the audio since it copies the source stream 1:1 to the target file without re-encoding.

**Comment by Muchtin** [comment]
Hi Franiac,
first thank you for looking into my problem.

I did today a lot of testing with TL and on all maschines i get the same result.

Here is what i do:
Downlaod TL here from github on the release page
Install TL 1.3.9
Open TL and click on the search tab
Click on the Urls tab and add this VOD Url https://www.twitch.tv/videos/168915243 - than i click on the search button
TL finds the VOD and i click on Download
On the Download site i select the Quality 1280x720@29fps (Source) and also name the filename to source.mp4 - than i click download
Download runs and after its finished i go back to the search result and say again download
This time i select Quality 1280x720@30fps and name the file 30fps.mp4 and click download again
Now both downloads are finished and i compare them in VLC
the 30fps.mp4 is pitched in audio and also have audio drops - the source.mp4 is fine

I tested on 2 Windows 7 and 1 Windows 10 PCs and all get me the same results. Maybe i can create a debug.log if its possible so that you can see whats going on. Also i can upload the result mp4 files if you cant reproduce the problem.

**Comment by Muchtin** [comment]
Hi,
i did now a lot of more testing. The pitching also appears in the offical ios and android app if i replay the VOD in 30fps.
So sorry for open an issue here but it has nothing to do with TwtichLeecher.

Thanks for your time

**Comment by Franiac** [comment]
Thx for the input and the solution. I suppose Twitch messes up the transcoding because 28 or 29fps is an "unsupported" framerate. So basically it's the streamers fault if you will...
