### ISSUE TITLE
Program won't launch, invisible then process ends

### ISSUE THREAD

**Issue by Pewpiepie** [Franiac/TwitchLeecher#177]
This was working fine, then one day it just failed to open. It looks like it's opening but nothing happens. On the processes, it shows it's there for about 30 seconds, then it disappears. I've tried installing different releases and each one does the same thing. Any idea what's going on?

**Comment by Franiac** [comment]
Check the event viewer -> category "Application" anything there?
Make sure not to run on Windows Insider Build, I don't support these.

**Comment by Pewpiepie** [comment]
Never mind! I found the fix on another thread here. Just close MSI afterburner and Twitch Leecher opens and works. Thanks for the guidance... googling my error led me to the appropriate solution.

**Comment by Franiac** [comment]
Ah that one... interesting how that tool messes up so much.
