### ISSUE TITLE
Cannot connect to Twitch with accounts

### ISSUE THREAD

**Issue by abcd198** [Franiac/TwitchLeecher#178]
After I type in the accounts, it goes to a http 403 page and therefore I cannot download subscription video.

**Comment by Franiac** [comment]
Is it the first time you are trying to authenticate or did it work in the past? What TL version are you using?

**Comment by abcd198** [comment]
Actually it worked well for old version and I managed to sign in with TL previously.
And yesterday it reminded that my accounts were not authorized (but I did subscribe that one) and thus I revoked my accounts.
Then I failed to sign in afterwards....
I'm using 1.3.9 and when I sign in twitch on the website, I need to pass the test (whether I'm human or computer), then I guess it's the reason? (maybe...)
Thank you~

**Comment by Franiac** [comment]
At times Twitch servers do not authorize via the API properly in different regions of the world. It is actually quite unstable. I can authorize normally here in Germany. Give it a few days and check again. TL uses a web browser control to show the login and if necessary the robot thing will appear there, too.

You can try to delete browser data of Internet Explorer and Edge and try again. The integrated browser of TL uses the Microsoft engines as a backend. Maybe that helps, maybe not. Just be a little patient. If it does not work in 3 or 4 day, you can re-open this issue.

**Comment by abcd198** [comment]
I've solve the problem and it's due to the old version of IE.......

Your mention of its IE control just reminds me. I'm always using Chrome and my IE is not the latest version. Previously old version of IE is allowed, but now twitch only accepts IE 11.0. There was no information in embedded web in TL. I did't find the cause until I tried to sign in on IE browser...

It worked properly after I updated IE. Really Very grateful to you.

**Comment by Franiac** [comment]
Well, IE less than version 11 were discontinued and ditched into the trash years ago :) Nobody nowadays takes something like that into account when developing software (and I think, that's a good thing). Nice that you could resolve your problm.

**Comment by ClefAria** [comment]
I've had Internet Explorer disabled in my Windows 7 as long as I can remember (See "Internet Explorer 9" unchecked here: https://i.imgur.com/BITaokj.png ), so I guess that's why. I ended up getting it to work by following some other user's tip that I found, that involved me getting the token and manually inserting it into the runtime.xml file, lol...

Are you able to have the program run a standalone Chromium or something for this, so that users like me don't run into problems?
