### ISSUE TITLE
Sub Only VODs not working in TL 1.4

### ISSUE THREAD

**Issue by JamMonsters** [Franiac/TwitchLeecher#181]
I tried to download a sub only VOD, but the app says im not subbed to the channel even tho i just  subscribed

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher#support--issues

**Comment by Franiac** [comment]
Oh shite... I see where that comes from... I fucked something up in 1.4

Can you please confirm that it still works in 1.3.9? That would be very kind. I personally am not subbed to any channel with sub-only VODs, so I cannot test it.

**Comment by Franiac** [comment]
I cancelled the TL 1.4 release. I will put up 1.4.1 if I get confirmation that 1.3.9 works.

**Comment by ifusayso** [comment]
I am able to download sub-only VODs with 1.3.9 without any problems.
