### ISSUE TITLE
Choppy audio and wrong pitch for entire video in 720p 30fps vods with muted audio sections

### ISSUE THREAD

**Issue by randomname42** [Franiac/TwitchLeecher#186]
First of all I'd like to say TL is a great downloader, and it's impressive how you can actually choose a time range. I don't think there's anything else which can do that.

Example vod: https://www.twitch.tv/videos/165176728

I first noticed this 7-30 or 7-31. All of a sudden choosing 30fps when there's two options for 720p (60 or 30) would result in wrong audio throughout. 60fps would work fine (but that's larger enough to be harder to get on slow internet). 

This seemed to happen for all streamers I tried. Yet none of their vods from before that date would have the 30fps problem.

Now, I did see a closed topic similar to this. But I believe that the conclusion there may be incorrect. 

For one, it started happening with too many streamers all of a sudden for it to be likely that it's due to streamer's fault (starting about 7-31 this issue simultaneously showed up for many streamers that never even once had any kind of issue like this before). No vods from before that date had the problem. It seems like Twitch itself must have changed something at that date.

Second, I asked about this problem at a different downloader which can do Twitch. (I hope it's not rude to mention that. I kind of have to because what they responded with was very informative.) They found that all the streams I posted had muted audio sections, and the fact the audio no longer existed for those sections was causing timing & sync problems when merging all the parts to a single file in 30fps.

Apparently muting happens differently in chunked/source than it does in re-encodes, which is why the 60fps source downloads aren't affected. I hope that all made sense.

**Comment by Franiac** [comment]
That makes a lot of sense indeed. If a stream results in muted audio it definitely IS the streamers fault in the end because he is the one playing back copyright protected music or other stuff.

The point about the re-encoding on Twitch makes also sense. The source version works because it is the only original stream. Therefore even Twitch seems to have difficulties with their video processing.

@randomname42 since closed topics are tracked on this site, you don't need to open a new one. Just comment on the closed issue :)

**Comment by randomname42** [comment]
Oh, I thought closed also meant the topic couldn't be posted in anymore, like a closed thread on a forum can't. Now I understand how that works on github.

Since the first post I've seen 30fps steams which I know have no muting having the same audio problem. After that date I mentioned before, I don't think I've even seen one single stream have audio be right when getting it from 30fps re-encode. It seems that unilaterally, regardless of anything the streamer has done or settings used, this happens with every 30fps stream since that date.

If Twitch is going to be that atrociously bad with their re-encoding, I don't know why they even offer a 30fps re-encode option anymore. I don't suppose you know what an effective way is to try to contact Twitch about the fact their 30fps option is so absolutely screwed up now?

**Comment by Franiac** [comment]
I do not have a communication channel to Twitch other than the developer forum. Beeing able to download other streamers' VODs is against the TOS and therefore TL is on the edge of legality. I do not want to make a big buzz about it because since that first release I am basically waiting that they shut TL down :P

**Comment by randomname42** [comment]
Actually I was ask if you knew what a good way was for an average Twitch user to contact them, because I was thinking about contacting them myself about the 30fps issue (and not about TL in the slightest). But don't really know where would be a good place that they actually might listen. I've always gotten the impression that they're so big that comments directed at them about an issue like that don't even get paid attention to.

I can completely see now however how my wording could make it sound like I was asking if you could contact them, so sorry for being confusing on that. That wasn't my intention at all.

**Comment by Franiac** [comment]
Oh... I don't know. They surely have a forum. Usually those big platforms do not have any form of direct communication other than that. Never looked for anything regarding this so I cannot help you on this one.
