### ISSUE TITLE
Receiving ERROR every time I download a vod, error occurs upon processing

### ISSUE THREAD

**Issue by aqlno** [Franiac/TwitchLeecher#187]
For the last week every time I try to download a VOD from a specific channel I get an error while processing the VOD. 

Here's the log for my most recent attempt on 1.4.2

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 178898023
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/178898023
Crop Start: Yes (03:17:00)
Crop End: Yes (03:33:20)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: E:\10-03-17-QuestMage-v-Rogue.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Ryan\AppData\Local\Temp\TL_aaf2b2ff-c3d6-47cf-9b3d-945186ff0972

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A178898023%2C%22expires%22%3A1506977741%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 01eb44be2eba4561c6ef7bd0bbbdc688ab2841ad
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Ryan\AppData\Local\Temp\TL_aaf2b2ff-c3d6-47cf-9b3d-945186ff0972'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/chunked/index-muted-W95N3RHKE5.m3u8
https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/720p60/index-muted-W95N3RHKE5.m3u8
https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/480p30/index-muted-W95N3RHKE5.m3u8
https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/audio_only/index-muted-W95N3RHKE5.m3u8
https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/360p30/index-muted-W95N3RHKE5.m3u8
https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/160p30/index-muted-W95N3RHKE5.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://fastly.vod.hls.ttvnw.net/84b1eacf747d962f2e1f_hotform_26382985968_717606814/chunked/index-muted-W95N3RHKE5.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 3022

Starting parallel video chunk download
Number of video chunks to download: 99
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\Ryan\AppData\Local\Temp\TL_aaf2b2ff-c3d6-47cf-9b3d-945186ff0972\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -ss 10 -i "C:\Users\Ryan\AppData\Local\Temp\TL_aaf2b2ff-c3d6-47cf-9b3d-945186ff0972\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc -t 980 "E:\10-03-17-QuestMage-v-Rogue.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Ryan\AppData\Local\Temp\TL_aaf2b2ff-c3d6-47cf-9b3d-945186ff0972'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
See #156 and #143 

I guess it is only that channel, right?
