### ISSUE TITLE
Automatic download of Past Broadcasts [Feature Request]

### ISSUE THREAD

**Issue by AshleyJackson** [Franiac/TwitchLeecher#189]
Could it be possible to automatically download past broadcasts?

Obviously there would be the issues of polling the API too constantly and getting TL banned.

**Comment by Franiac** [comment]
Exactly that. Too many requests get you banned. And a single search is not a single request but 5-10 requests to the API depending on the content and the amount of different games (2 per second are allowed). I like the idea and it is definitely not the first time I receive this reqeust but I do not see a possibility with the current API to implement that.
