### ISSUE TITLE
There is a problem with the video frame when using the download function.

### ISSUE THREAD

**Issue by KOR-Yeoul** [Franiac/TwitchLeecher#191]
There is no problem watching the video.
However, when a video frame is selected (ex: 60F to 30F)
The actual download frame is not 60 ~ 30.
60 frames selected: 59.999F
30 frames selected: 30.25F

Watching a video is fine, but editing a video is a fatal error.

I attached an image for reference. Please confirm.

![2017-10-08 22 58 57](https://user-images.githubusercontent.com/32615006/31317465-7ba6899c-ac7c-11e7-94b7-8b79ab0d1bb5.PNG)
![2017-10-08 22 55 38](https://user-images.githubusercontent.com/32615006/31317466-7dbb3ed0-ac7c-11e7-874a-1b3ae5698d30.PNG)

**Comment by Franiac** [comment]
that is not a problem but how Twitch stores their VODs. The displayed FPS in the download menu are shipped by twitch (and very inaccurate) and so are the video files. TL only merges them. TL does not do any kind of encoding so the video stream stays the same compared to the source. If Twitch ships 59.999 FPS then the downloaded video has that FPS, too.
