### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by lazyboygaming01** [Franiac/TwitchLeecher#192]
I have had this issue for the last 3 version my audio is out of syns with my voice but on the vod on twitch everything is fine. IDK if it is your program of what but things are not working out I am losing clips/boardcasts and cant down them

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher#support--issues

**Comment by Franiac** [comment]
Closed because stale

**Comment by Franiac** [comment]
More info on the matter: See #194
