### ISSUE TITLE
Video and Audio asynchronous when you select a custom start and/or stoptime

### ISSUE THREAD

**Issue by Exorc1st** [Franiac/TwitchLeecher#193]
You get an asynchronous video (Audio does not fit to the video) when you select a custom start and stoptime.

If you just download it, everything is nice with the audio.

Please fix it

**Comment by Franiac** [comment]
Twitch Leecher does not re-encode anything. It takes what it gets from Twitch and merges everything with ffmpeg. If that does not work, I cannot do anything about it. TL has NOTHING to do with how video or audio is processed.

If you want me to look at anything, read this:

https://github.com/Franiac/TwitchLeecher#support--issues

**Comment by Franiac** [comment]
Closed because stale

**Comment by Franiac** [comment]
More info on the matter: See #194
