### ISSUE TITLE
compiled wrong length?

### ISSUE THREAD

**Issue by Z-brah** [Franiac/TwitchLeecher#195]
Hello! My system is: old netbook, win 10 x32, TL 1.4.2
I asked your program to download Dansgaming marathons (4 vods 30+ hours each) in 360p. I tested that 1 hour of 360p is ~250Mb. What i get in result is 4 files appropriate size but each 26 hours and 30 minutes long (+- 10 second). What i mean by appropriate size is 46 hours vod weight 11.5Gb but media player sees 26:30:00 long  video

**Comment by Franiac** [comment]
FFMPEG (that TL uses to merge videos) seems to have issues with very large files and very long input streams. Downloading a 40+ hour video in one go is simply not recommended. Use the cropping feature of TL and download multiple smaller parts (8 hours for example).
