### ISSUE TITLE
All chunks download, but merge process stops prematurely

### ISSUE THREAD

**Issue by jeffraven** [Franiac/TwitchLeecher#196]
Trying to download specific section of 8+ hour video using the crop tool in TL.
TL will download all the chunks (I watched it fill up in the Temp folder) and when it goes to merge all the files, I get a video that is only a fraction of the original video length, usually cutting out randomly before finishing the merge.  The log reports the file was successfully ported, then deletes all the files in cleanup.

**Comment by Franiac** [comment]
See my comments on #156 and #143
