### ISSUE TITLE
Installation failed "Your System Has not Been Modified"

### ISSUE THREAD

**Issue by artkez** [Franiac/TwitchLeecher#197]
how fix it? Windows 7, 32-bit
![image](https://user-images.githubusercontent.com/33177434/32134231-71d13b36-bbf1-11e7-8f5b-3319225e4833.png)

**Comment by Franiac** [comment]
You can make the installer write a log file:

1. open up command line in windows
2. change to directory the TL installer is in
3. type "TwitchLeecher_1.4.2_x64.exe -l log.txt" (without quotes) and hit enter
4. step through the installer and let it fail
5. close installer

-> Now a log.txt file should exist in the same directory of the installer. That's the file I need.

**Comment by artkez** [comment]
I do all the points but file log.txt no in the folder there.

**Comment by Franiac** [comment]
Sure it works, just tried it with the installer from GitHub here. the -l is a lowercase L not an i (just saying because it is not obvious depending on the font)

**Comment by Franiac** [comment]
And surely enough you have to run the 32 bit installer.... so the x86 version for you...

**Comment by Franiac** [comment]
Closed because stale
