### ISSUE TITLE
Search function not working on some Streamers

### ISSUE THREAD

**Issue by tester2019** [Franiac/TwitchLeecher#198]
hi

I tried your Search function but sometimes they are not working for some streamers like haumph.
I tried the load limit using date range and Last X VODs option but not even 1 VOD appear.
However, the streamer has lots of VOD on the website.
do you know why?

**Comment by Franiac** [comment]
Some streamers save their VODs as Highlights... if you browse past broadcasts of this streamer there are actually none. Make sure you have selected "Highlight" in the search dialog in TL, not "Broadcast"
