### ISSUE TITLE
Searches with non-letter characters result in an error

### ISSUE THREAD

**Issue by ihabunek** [Franiac/TwitchLeecher#200]
Searching for "foo bar", "foo/bar" or "foo:bar" results in an error window.

![image](https://user-images.githubusercontent.com/482138/32594982-5f598c9c-c52e-11e7-8c09-02d3c779c812.png)

Logs say:
```
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.GetChannelIdByName(String channel)
   at TwitchLeecher.Services.Services.TwitchService.ChannelExists(String channel)
   at TwitchLeecher.Gui.ViewModels.SearchViewVM.Validate(String propertyName)
   at TwitchLeecher.Gui.ViewModels.SearchViewVM.Search()
```

I'm guessing the search isn't urlencoded.

**Comment by Franiac** [comment]
Hmm, normally I use the .NET classes to build the query string... I'll check that, thx

**Comment by yqq8418** [comment]
How should we solve this problem?

**Comment by yqq8418** [comment]
I have the same problem, and I don't know how to solve it

**Comment by Franiac** [comment]
@yqq8418 what do you mean? I have to look into it and fix the bug... that hasn't happend so far because I don't have time at the moment... normally Tiwtch names do not have whitespaces in it so this should not be a general issue.

**Comment by yqq8418** [comment]
@Franiac ystem.AggregateException: 发生一个或多个错误。 ---> System.Net.WebException: 基础连接已经关闭: 无法连接到远程服务器。 ---> System.Net.Sockets.SocketException: 无法加载或初始化请求的服务提供程序。
在 System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
--- 内部异常堆栈跟踪的结尾 ---
在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
在 System.Net.WebClient.DownloadString(Uri address)
在 TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
在 TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
在 TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
在 System.Threading.Tasks.Task.Execute()
--- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) System.Net.WebException: 基础连接已经关闭: 无法连接到远程服务器。 ---> System.Net.Sockets.SocketException: 无法加载或初始化请求的服务提供程序。
在 System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
--- 内部异常堆栈跟踪的结尾 ---
在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
在 System.Net.WebClient.DownloadString(Uri address)
在 TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
在 TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
在 TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
在 System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
@yqq8418 you posted this exact message on #206 .
Please don't spam issues with it that have nothing to do with it...
