### ISSUE TITLE
Add command line interface

### ISSUE THREAD

**Issue by WeaponsGradeAutism** [Franiac/TwitchLeecher#202]
This is an enhancement request. I have done several Google searches and searched the issue repo about this and have found no results so if this is a duplicate, I apologize.

It would be incredibly convenient if one could download a VOD by supplying the link, file destination, and relevant options to a command line interface instead of going through the UI. Sometimes I have a batch of different VODs I'd like to pull and if I could write a shell script to do it, it would save a lot of time.

Thank you for your consideration.

**Comment by Franiac** [comment]
See #157
