### ISSUE TITLE
help please, error when processing

### ISSUE THREAD

**Issue by tylahevans** [Franiac/TwitchLeecher#205]
Please see below, downloaded fine, but ~27% in to the processing, it gave me an error. I tried another video and it did the same thing. 

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 204208547
Selected Quality: 1280x720@0fps (Source)
Download Url: https://www.twitch.tv/videos/204208547
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\CDN 1.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\TylahEvans\AppData\Local\Temp\TL_79479ec0-00f1-4b58-b105-28f59672f538

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A204208547%2C%22expires%22%3A1511724115%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 6b0b3fa36bd794fa7dc8927c6714f4f76192ce3a
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\TylahEvans\AppData\Local\Temp\TL_79479ec0-00f1-4b58-b105-28f59672f538'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/chunked/index-dvr.m3u8
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/720p60/index-dvr.m3u8
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/720p30/index-dvr.m3u8
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/480p30/index-dvr.m3u8
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/audio_only/index-dvr.m3u8
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/360p30/index-dvr.m3u8
https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@0fps (Source) is https://vod134-ttvnw.akamaized.net/95d5e66f34b7430f7293_cdnthe3rd_26818651680_744835903/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2689

Starting parallel video chunk download
Number of video chunks to download: 2689
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\TylahEvans\AppData\Local\Temp\TL_79479ec0-00f1-4b58-b105-28f59672f538\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\TylahEvans\AppData\Local\Temp\TL_79479ec0-00f1-4b58-b105-28f59672f538\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\CDN 1.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\TylahEvans\AppData\Local\Temp\TL_79479ec0-00f1-4b58-b105-28f59672f538'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while processing the video!
   at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
See #156 and #143
