### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by yqq8418** [Franiac/TwitchLeecher#206]
![cgq0vc c 0n0 t32u73i43](https://user-images.githubusercontent.com/33508454/33797372-9dd06cfe-dd41-11e7-8581-6bb2d9715d25.png)

**Comment by Franiac** [comment]
Well, I don't speak chinese or whatever that is. You could send me the log file...

**Comment by yqq8418** [comment]
System.AggregateException: 发生一个或多个错误。 ---> System.Net.WebException: 基础连接已经关闭: 无法连接到远程服务器。 ---> System.Net.Sockets.SocketException: 无法加载或初始化请求的服务提供程序。
   在 System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   在 TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   在 TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   在 System.Threading.Tasks.Task.Execute()
   --- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) System.Net.WebException: 基础连接已经关闭: 无法连接到远程服务器。 ---> System.Net.Sockets.SocketException: 无法加载或初始化请求的服务提供程序。
   在 System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   在 TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   在 TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   在 System.Threading.Tasks.Task.Execute()<---

**Comment by yqq8418** [comment]
Your software is particularly useful, and it used to be good, and that's the problem

**Comment by yqq8418** [comment]
@Franiac ystem.AggregateException: 发生一个或多个错误。 ---> System.Net.WebException: 基础连接已经关闭: 无法连接到远程服务器。 ---> System.Net.Sockets.SocketException: 无法加载或初始化请求的服务提供程序。
   在 System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   在 TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   在 TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   在 System.Threading.Tasks.Task.Execute()
   --- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) System.Net.WebException: 基础连接已经关闭: 无法连接到远程服务器。 ---> System.Net.Sockets.SocketException: 无法加载或初始化请求的服务提供程序。
   在 System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadString(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.GetTwitchVideoFromId(Int32 id)
   在 TwitchLeecher.Services.Services.TwitchService.SearchIds(String ids)
   在 TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   在 System.Threading.Tasks.Task.Execute()<---

**Comment by yqq8418** [comment]
@Franiac Yes, I use it in China. Download video is especially useful. It's been a problem the day before yesterday and I don't know how to solve it

**Comment by yqq8418** [comment]
![5j5klso1 9cefp9 qy q o](https://user-images.githubusercontent.com/33508454/33802954-da2b10b4-ddbe-11e7-9a18-8006b1d21f7c.png)
@Franiac

**Comment by Franiac** [comment]
This is not the same issue as #200

**Comment by Franiac** [comment]
It tells that the remote server could not be reached. This usually happens when Twitch does some maintanance to the servers. There is nothing wrong with TL. It just says that TL could not reach out to Twitch. Just be patient and try again in a few hours if that happens. Even Twitch cannot guarantee that there servers are completely available 100% of the time. Especially when you are connected to a single server for downloading a VOD.

**Comment by yqq8418** [comment]
@Franiac Does that mean you can use it for some time?

**Comment by yqq8418** [comment]
@Franiac Thank you, it means a period of time can be automatically using?Is not the reason why my computer or software

**Comment by yqq8418** [comment]
@Franiac I won't be able to connect to the server side?A few days are all like this
