### ISSUE TITLE
retry Download if connection lost

### ISSUE THREAD

**Issue by ph0enixph0enix** [Franiac/TwitchLeecher#21]
ex: when auto-reconnecting (mandatoy and automatically done by ISP in some countries), optimal would be configurable amout of retries in preferences with a wait time (ex: 10 seconds, not neccesarily configurable)

**Comment by Franiac** [comment]
Good point. Complicated to implement due to the massively parallel download mechanism. Have to look into it.

**Comment by Franiac** [comment]
See Issue #46
