### ISSUE TITLE
i cant install Twitch Leecher

### ISSUE THREAD

**Issue by wpinflamess** [Franiac/TwitchLeecher#211]
[logfile.txt](https://github.com/Franiac/TwitchLeecher/files/1590158/logfile.txt)
heres the logfile pls HELP
64 bits version

**Comment by Franiac** [comment]
2 logfiles get created. One for the installer app and one for the actual install process. I need both. Look for logfile_001.txt or something like that

**Comment by inokuda** [comment]
Hello,
I'm having the same issue : i generated 1 logfile and the message is the same.
It stops on "Pausing automatic updates."

On the window : the "Status : installing" remains at 0%

I've tried launching as administrator, and the problem remains.

Thank you

**Comment by Franiac** [comment]
If no 2nd logfile gets generated, the Windows MSI installer Engine does not start. That is something I cannot control and points to an error outside of the TL installer application. I only tell MSI to install the program, if it does not do that, there's something wrong on the system pretty sure.

But first things first: Give me more info about your systems. What Windows version are you running and what service pack/creators update?

And have you tried to completely uninstall TL including user data? That might be an option, too.

**Comment by Franiac** [comment]
Closed because stale
