### ISSUE TITLE
i can't download

### ISSUE THREAD

**Issue by iyalniz** [Franiac/TwitchLeecher#214]
Hi every time i try to download a vod taking error issues (sorry for my english)

Download Log

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 215721288
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/215721288
Crop Start: Yes (04:28:20)
Crop End: Yes (05:35:18)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\i_yalniz06\Downloads\20180105_215721288_PLAYERUNKNOWN'S BATTLEGROUNDS.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\i_yalniz06\AppData\Local\Temp\TL_7433de86-0c6d-49db-a2d0-6bad1b15f49b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A215721288%2C%22expires%22%3A1515306994%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 5780c444129340bf02268fd19d2d6829c75f0718
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\i_yalniz06\AppData\Local\Temp\TL_7433de86-0c6d-49db-a2d0-6bad1b15f49b'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/chunked/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/720p60/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/720p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/480p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/audio_only/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/360p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod.edgecast.hls.ttvnw.net/88b0cdb014ea5a419049_shroud_27180919552_767477642/chunked/index-dvr.m3u8

Retrieving playlist...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\i_yalniz06\AppData\Local\Temp\TL_7433de86-0c6d-49db-a2d0-6bad1b15f49b'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Cannot reproduce that. Downloads perfectly on my end. The error occured when TL tried to download the VOD playlist. Have you authenticated TL? If so, try revoking authentication and download again. Maybe it is just a server hickup on Twitch.

**Comment by iyalniz** [comment]
i revoked auth. and try but same error, re installed tl but same error again i don't understand what is the problem

**Comment by Franiac** [comment]
Is this the only VOD that throws an error? Problem is, I really cannot reproduce this. The 403 error means that you don't have permission to download the VOD playlist from the Twitch server. Why I have permission and you don't... I have no clue. TL is not the problem here, Twitch does not allow you to download the playlist. Unfortunately I don't have a solution for that :(

**Comment by iyalniz** [comment]
other vods getting error too but thanks. i hope i will fix this problem.
