### ISSUE TITLE
launcher issues

### ISSUE THREAD

**Issue by oBOLTo** [Franiac/TwitchLeecher#216]
this is probably something so simple to fix but im having trouble installing the twitch leecher every time i try to install it, it finished but there is no actual launcher i am sure its just me but can someone help pls.

thanks in advance

**Comment by Franiac** [comment]
What do you mean by "launcher"? After installation there's a start menu entry. Or you can start the exe directly (C:\Program Files\Twitch Leecher\TwitchLeecher.exe is the standard location)

**Comment by oBOLTo** [comment]
ok i found it sorry for being such a noob im just stepping my foot into video editing for streamers and i didnt know how to download this thanks a bunch
