### ISSUE TITLE
Linux CLI release?

### ISSUE THREAD

**Issue by TheSneakySniper** [Franiac/TwitchLeecher#221]
Will there ever be a linux compliant CLI release of this program?

**Comment by Franiac** [comment]
TL is a WPF Windows application at the moment. There are thoughts about a re-write to a HTML frontend that would have the possibility of running on every platform (including mobile devices). Problem is FFMPEG... that is platform dependent and not easy to implement for each and every OS.

On the other hand Twitch is for gamers. Gamers usually are on Windows. The effort for creating a Linux version is simply not worth it. It is kinda stupid to invest 3+ month for a linux re-write when 10 people use it in the end. Mobile devices like Android have higher priority if I decide to re-write anything.

**Comment by TheSneakySniper** [comment]
Why would ffmpeg be platform dependent? I understand if it would be hard to reprogram the other code, but surely not ffmpeg.

**Comment by TheSneakySniper** [comment]
As a matter of fact, it would be as easy as getting the range of the VOD chunks and then recompiling it with ffmpeg.

**Comment by Franiac** [comment]
Err... ffmpeg IS platform dependent. You need to compile it for every platform separately. You cannot use a C++ library compiled for Linux on an Android device and so on. You need to compile it and additionally write a wrapper in the platform dependent program language to integrate it seemlessly into the UI and the UI hosting technology (Cordova, Electron, Browser).

The UI would be HTML/Typescript/SCSS for all platforms but hosted differently. Cordova for the mobile platforms (Android, iOS, UWP) with Chromium in the background, Electron on the desktop systems (Windows, Linux, MacOS) and pure transpiled JavaScript (Angular 5) for the browser.

**Comment by teocci** [comment]
https://github.com/teocci/TwitchLeecher I created this project for the people that uses mac or linux.
