### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Yukka123** [Franiac/TwitchLeecher#222]
Can you help me ? When I tryied to download vod after 100% it gives me error

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 223310985
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/223310985
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\David\Desktop\EDIT PACK\klipy\20180128_223310985_Counter-Strike_ Global Offensive.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\David\AppData\Local\Temp\TL_aa7c058f-58ae-4065-9d48-01b2d44e363b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A223310985%2C%22expires%22%3A1517305676%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 475e545f621c5aacc9c5830c1d110671b380058f
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\David\AppData\Local\Temp\TL_aa7c058f-58ae-4065-9d48-01b2d44e363b'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/chunked/index-muted-NHUOBCTA9Y.m3u8
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/720p60/index-muted-NHUOBCTA9Y.m3u8
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/720p30/index-muted-NHUOBCTA9Y.m3u8
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/480p30/index-muted-NHUOBCTA9Y.m3u8
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/audio_only/index-muted-NHUOBCTA9Y.m3u8
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/360p30/index-muted-NHUOBCTA9Y.m3u8
https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/160p30/index-muted-NHUOBCTA9Y.m3u8

Playlist url for selected quality 1280x720@60fps is https://fastly.vod.hls.ttvnw.net/e7f1bd47fe65517f0bb4_eleaguetv_27423136736_782616215/720p60/index-muted-NHUOBCTA9Y.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 4519

Starting parallel video chunk download
Number of video chunks to download: 4519
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\David\AppData\Local\Temp\TL_aa7c058f-58ae-4065-9d48-01b2d44e363b'... done!

Download task ended with an error!

System.AggregateException: Došlo k jedné nebo více chybám. ---> System.AggregateException: Došlo k jedné nebo více chybám. ---> System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- Konec trasování zásobníku pro vnitřní výjimku ---
   v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   v System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   v TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   v System.Threading.Tasks.Task.Execute()
   --- Konec trasování zásobníku pro vnitřní výjimku ---
---> (Inner Exception #0) System.AggregateException: Došlo k jedné nebo více chybám. ---> System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- Konec trasování zásobníku pro vnitřní výjimku ---
   v System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   v System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   v System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   v System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   v TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
   v System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #3) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #4) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #5) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #6) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #7) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #8) System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   v System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   v TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass65_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
   v System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   v System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   v System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by XoRDLC** [comment]
I'm not author, but it looks like you have not enough disk space. Clean your hdd.

**Comment by Franiac** [comment]
@XoRDLC That's right, your HDD is full.

You need double the size of the VOD: One time for the actual download and a second time for the merged VOD before the source files get deleted.

**Comment by Yukka123** [comment]
ahhh, thank you guys.
