### ISSUE TITLE
support for downloading full collections at once.

### ISSUE THREAD

**Issue by nzall** [Franiac/TwitchLeecher#225]
I am using version 1.4.2, and I would love it if I could enter a Twitch collection url (example: https://www.twitch.tv/collections/sIU92mT36hQMqw, Preach MGS2 playthrough) after which TL would automatically queue and download every video in the collection, instead of having to search for a date period during which these highlights were recorded.

**Comment by Franiac** [comment]
Up until now I have not even known about collections... requires #46

**Comment by ngocquy719** [comment]
Hi, can i download twitch videos without copyrighted sounds?
When i watch some videos on Twitch, some part being muted, but when i download, my video have full sound (even copyright sound). I want to post it on my Youtube channel but i need to do 1 more step: mute it.

**Comment by Kaszanas** [comment]
@Franiac I have similar request to create yet another quality of life upgrade.
Batch downloading all the videos with basic configuration settings.

**Comment by Franiac** [comment]
#803
