### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by v0cker** [Franiac/TwitchLeecher#229]
TwitchLeecher_1.4.2_x64.exe 
After starting a installation im getting "an error  during the installation"
Windows 8.1 Pro 9600 build
here is logfile
[logfile.txt](https://github.com/Franiac/TwitchLeecher/files/1743769/logfile.txt)

**Comment by Franiac** [comment]
That logfile does not help. This is the logfile of the installer application. It indicates that the MSI installer failed (meaning it faild during the process after you clicked "Install"). There should be another logfile next to this one (like with _1 at the end or something). That's the one we need.

**Comment by v0cker** [comment]
Sorry, that was actually my PC trouble with temporary folder. I fixed it, and now programm works totally fine.
So anyway thanks for answer.

**Comment by Franiac** [comment]
Would you be so kind to explain what happened? What went wrong? I just want to know in case others have similar troubles.
