### ISSUE TITLE
Implement a notification system for saving/enqueue actions

### ISSUE THREAD

**Issue by ph0enixph0enix** [Franiac/TwitchLeecher#23]
prevent the vidoes list scrolling to the top after adding a download so you could quickly add, let's say the 5 videos directly over the one you just marked as download. Perhaps it's even worth a thought not to switch to the download list ater adding a video to it but to fade in a android toast like message notifiying the user that the download has been added or something like that. In any case, I would not advise something with a ok button for each added download as it could get on the nerves of the user to click it away everytime.

**Comment by Franiac** [comment]
I thought about notifications, too. would be also suitable for saving operations like the preferences to get rid of the "successfully saved" message box. but for this i need to implement a notification control first.

**Comment by Franiac** [comment]
:tada:
