### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by AFK05afk** [Franiac/TwitchLeecher#230]
There is a problem with installing Twitch Leecher 1.4.2x86. During the Setup, the sentence saying that 'your system has not been modified' has been kept appeared on the screen, so if you can help me out, it would be good. (by the way, my window is 7 and 32bits with NET framework of 4.5)

![set up error](https://user-images.githubusercontent.com/36799232/36633855-81e7af86-19df-11e8-8867-31b504f3dd10.png)

**Comment by Franiac** [comment]
Are you familiar with console commands?

You can start the installer in the console with

`C:\dir\to\installer\TwitchLeecher_1.4.2_x86.exe -l "log.txt"`

The try to install as you normally would. This should create 2 logfiles, one named log.txt and another one named log_1.txt or something. We need both.

**Comment by sschnug** [comment]
After experiencing the same error, the cmd-call surprisingly works. Did not check any potential reasoning behind.

In my case: ```TwitchLeecher_1.4.2_x64.exe```

**Comment by Franiac** [comment]
@sschnug that does not make sense (technically). A cmd call is not different from clicking on the exe file unless the cmd is opened as admin or something. I suppose in your case it would now also work normally. What can be an issue though is when you start the installer from a network drive. .NET does not like running code on network drives and throws a lot of permission errors.

**Comment by sschnug** [comment]
As a CS-guy i get your point. It is like i described and i know it's of limited use for debugging.

I don't know anything about the installer and can't reason about potential side-effects and consequences (5 sec inet-loss; HDD-response time, ...).

**Comment by Franiac** [comment]
The installer is "WiX Toolset", a natively compiled C++ application that wraps a WPF GUI. It is near impossible calling a native exe from cmd or explorer makes any difference (otherwise many people would lose a lot of faith in their job 😈).

But anyway, cool that you're up and running, but there's no word from the OP... so I am closing this one for now.
