### ISSUE TITLE
Download not complete

### ISSUE THREAD

**Issue by SirNoob1991** [Franiac/TwitchLeecher#231]
Hi Franiac,

I noticed that it is not possible for me to download certain VOD from a streamer in the period 2014-2015.
That's to say: The download is successful, but only 20-30 minutes are downloaded.

I tried the program JDownlaoder for testing purposes and it works fine (but it takes ages)

e. g.:  https://www.twitch.tv/videos/42669121

I'am currently using version 1.4.2 of the Twitch leecher.

Here's the log file.

`Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 42669121
Selected Quality: 1280x720 (Source)
Download Url: https://www.twitch.tv/videos/42669121
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: I:\TwitchStreams\42669121_Silent Hills - E0X P.T. - Silent Hills Playable Teaser (20140825).mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: I:\TwitchStreams\TL_136517ed-4564-4903-b82f-40dc801f63d0

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A42669121%2C%22expires%22%3A1520162932%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 7fdc6e2b61b7bd11ce409c1d05dbb5bc01c293fd
Sub-Only: No
Privileged: No

Creating directory 'I:\TwitchStreams\TL_136517ed-4564-4903-b82f-40dc801f63d0'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/d95c184b97/herrdekay_10776440368_10776440368/chunked/highlight-42669121.m3u8
https://vod-secure.twitch.tv/d95c184b97/herrdekay_10776440368_10776440368/audio_only/highlight-42669121.m3u8

Playlist url for selected quality 1280x720 (Source) is https://vod-secure.twitch.tv/d95c184b97/herrdekay_10776440368_10776440368/chunked/highlight-42669121.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1033

Starting parallel video chunk download
Number of video chunks to download: 1033
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'I:\TwitchStreams\TL_136517ed-4564-4903-b82f-40dc801f63d0\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "I:\TwitchStreams\TL_136517ed-4564-4903-b82f-40dc801f63d0\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "I:\TwitchStreams\42669121_Silent Hills - E0X P.T. - Silent Hills Playable Teaser (20140825).mp4"

Processing complete!

Starting temporary download folder cleanup!
Deleting directory 'I:\TwitchStreams\TL_136517ed-4564-4903-b82f-40dc801f63d0'... done!

Download task ended successfully!`

**Comment by Franiac** [comment]
Common issue on very old VODs (<2015). ffmpeg is not error-prone towards dropped or general bugged frames. If there is a single bugged frame within the VOD, ffmpeg messed it all up.
If JDownloader manages to process it completely, I have to look into their command line arguments, because as far as I know they use ffmpeg, too. This is a very old topic where I invested days in and could not come up with a solution (I am a Software Architect not a video encoding specialist, unfortunately).

I am closing this one, because I have is on several todo-lists... If solved, it will 100% show up in the release notes of an upcoming version.
