### ISSUE TITLE
Please build for Mac

### ISSUE THREAD

**Issue by nguyenducphu** [Franiac/TwitchLeecher#237]
Hi Franiac.

I'm Mac user.
I am very interesting with your tool but hard to use on my Mac without Parallels.

Can you build a version for Mac?

Thank so much.

Ricky.

**Comment by saro1992** [comment]
Hi Franiac.
I'm linux  user.
I am very interesting with your tool but hard to use on my linux  .
Can you build a version for linux? 
C# is easy to cross platform by mono.
Thank so much.

**Comment by Franiac** [comment]
@nguyenducphu I do not own any Apple products and I would need an Apple Developer Account (100$/year). I am not keen on puchasing a 2000$ Mac just to release a hobby open source project on that platform. Remember that TL does not make any money.

@saro1992 As far as I know Mono does not support WPF, is that correct?

I get these questions a lot even for mobile devices (Android/iOS). The only "good way" of implementing a multi-platform TL would be the transition to HTML/TypeScript in terms of GUI. I am indeed an Angular 5 developer but so far had not the time to work on TL this way.

**Comment by nguyenducphu** [comment]
@Franiac It's OK. Thank you :)
