### ISSUE TITLE
Support for new Twitch Helix API (February, 18th)

### ISSUE THREAD

**Issue by Franiac** [Franiac/TwitchLeecher#238]
Twitch will shut down API V5 on 12/31/2018. Until then TL has to switch to the new Helix API.

Difficulties:

The new API does not contain any information about the video quality or framerate. The quality selection would be gone. TL would only be capable of downloading source quality. It is how it is, unfortunately.

I got in contact with Twitch here:

https://discuss.dev.twitch.tv/t/get-qualities-of-videos/14633

But there is no guarantee this will happen anytime soon.

**Comment by Z-brah** [comment]
And how am I supposed to watch 1080p 60fps source quality on my little netbook from 2010 (2 cores 1 GHz each). Damn twitch...

**Comment by Franiac** [comment]
@Z-brah If you want to wait like 20 hours until your 2010 toaster has re-encoded the video. Depending on the VOD length your machine will simply die 😄
TL does not re-encode anything at the moment, that's why the processing stage is very fast. And as cool as your made up screenshot is, that's not gonna happen because nobody would use it (including you if you tried it a single time...)

**Comment by ihabunek** [comment]
Well, they must implement it somehow for their own frontend. Looking at the API calls from twitch.tv now, and they're fetching from both the new and old API. For example [this page](https://www.twitch.tv/videos/277382046) fetches both of these:
https://api.twitch.tv/kraken/videos/v277382046
https://api.twitch.tv/api/videos/v277382046

**Comment by Franiac** [comment]
@ihabunek Both of your urls point to the old API.

The new API is

`https://api.twitch.tv/helix/........`

and is queried with query parameters like

`https://api.twitch.tv/helix/videos?id=277382046`

The result is

```json
{
    "data": [
        {
            "id": "277382046",
            "user_id": "25150991",
            "title": "Pokémon, then Darkest Dungeon! - @SleepCycles",
            "description": "",
            "created_at": "2018-06-25T13:06:13Z",
            "published_at": "2018-06-25T13:06:13Z",
            "url": "https://www.twitch.tv/videos/277382046",
            "thumbnail_url": "https://static-cdn.jtvnw.net/s3_vods/b53e3fb705f1175d79dc_sleepcycles_29228374208_895443551/thumb/thumb0-%{width}x%{height}.jpg",
            "viewable": "public",
            "view_count": 96,
            "language": "en",
            "type": "archive",
            "duration": "5h6m30s"
        }
    ],
    "pagination": {}
}
```

No sign of quality or framerate data...

**Comment by ihabunek** [comment]
My mistake, but my point stands. Currently twitch.tv itself is using the old API to get the available resolutions. They will need to either keep the old API endpoint alive, or add resolution data to the new API in order for their own web to work.

**Comment by Franiac** [comment]
Sure, that's why I am waiting. The thing is, they could be using a private API in the end. We'll see how they are going to solve that. I think v5 will be supported longer than 2018. Helix is far from complete and there are many complaints about it. Somewhere I even found a forum post recommending longer support for v5.

So everybody can chill right now 😄

**Comment by TheSneakySniper** [comment]
I see that when @Franiac contacted the twitch staff he did not link to this project, nor did they mention their true intentions.

I wonder if this was deliberate...

**Comment by Franiac** [comment]
@TheSneakySniper How does this recognition contribute to this GitHub issue?

**Comment by Franiac** [comment]
@xzion Ha! That's what I expected.

**Comment by MrDummyNL** [comment]
To re-encode video, there are free tools available. I use Avidemux tool because it's nice and easy editor. You can cut very fast videos and remove unwanted parts. And with filters, you can adjust video and resize it. 
You can even make it with command line: http://www.avidemux.org/admWiki/doku.php?id=using:command_line_usage
So it's no need to make another encoder again and just get free tools for converting videos.

**Comment by Codereaders** [comment]
@MrDummyNL
1. "free to use" does not nessessarily mean "free to distribute".
2. There are many people out there that do not have avidemux and don't want it to be installed in addition to Twitch Leecher. (TL uses ffmpeg)

**Comment by GreenLightning** [comment]
FYI: The new shutdown date is February 28, 2022.

https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/?utm_referrer=https://dev.twitch.tv/

**Comment by Franiac** [comment]
I prepared myself a little bit for the Helix API swap. Apparently TL will need user login to work with Helix. The API requires either an user access token or an app access token. The latter is only designed to work with server-to-server communication since the creation of an app access token needs the client secret (not to be confused with the client id) and that is actually... yeah... secret, so I cannot put it into the TL source code.

So TL will ask for user login every time there is no valid user token available. Once logged in, TL will remember the token and try to validate it on the next start. If it is still valid, everything's cool, if not, the user needs to renew their login.

Also in order to retreive the available VOD resolutions TL needs to download the playlist summary file. So the resolution cannot be displayed in the search result view anymore. In the download view it will be available still, though.

**Comment by Franiac** [comment]
Also the newly introduced rate limits on the API are designed "per user per client id" or "per app (client id)". So the login is actually beneficial because if we used an app access token, all TL users on the planet would share a single API rate bucket. That would end in amazingly long wait times between requests.

**Comment by Franiac** [comment]
This is now completely implemented in the "helix" branch. I will merge it as soon as it is necessary.

Things that will not work anymore:

- Show resultion in search results (now needs the playlist, but I cannot download it for every video in the results)
- Show game icon in search results (the game is not part of the video anymore in helix)
