### ISSUE TITLE
Feature requests: Set default download options | Multi check-box download | History

### ISSUE THREAD

**Issue by Rudolpher** [Franiac/TwitchLeecher#242]
Hello!
First off thank you for making this program, and have it freely available. Its proven to be a great tool to have in my archiving arsenal!

I am a datahoarder in the process of archiving certain channels and continually updating that archive with new VODs. In that process I've noticed a few quality-of-life features that would be very helpful, hopefully not just for my usage:  

1) The ability to set default download options(Checkbox in options, or at the bottom on Search screen?), so that when you hit "Download" in search screen, it immediately goes to queue with those default options. As opposed to current action which is when you hit "Download" in search screen, it goes to "Download video" where you have to hit "Download" again.

2) Either a "Download all"(In conjunction with the third suggestion, so previous downloads are skipped), or an extra check-box to select multiple clips/VODs for download.

3) TwitchLeecher remembering what has been downloaded in the past, and clearly showing this on the search screen(Tinted/slightly grayed out, or a green check-mark next to the download button are my suggestions). It can become difficult to keep track of things when there's hundreds of highlights or 50+ VODs.

Thanks for your time!
Rudolpher

**Comment by Franiac** [comment]
All this has been requested pretty much from the beginning. It's on my private list of features. Problem is I need #46 first, otherwise it would be a pain in the butt to implement. I close this one since I have enough reminders laying around myself 😄

**Comment by Rudolpher** [comment]
Apologizes, I checked but obviously did a bad job at it.
