### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by cdn-crz** [Franiac/TwitchLeecher#248]
[logfile.txt](https://github.com/Franiac/TwitchLeecher/files/1998006/logfile.txt)
[logfile_000_TL.txt](https://github.com/Franiac/TwitchLeecher/files/1998007/logfile_000_TL.txt)
here the logs

**Comment by Franiac** [comment]
MSI (c) (FC:E8) [02:04:34:214]: Failed to connect to server.

Strong sign that your anti virus software is blocking it. It is very unlikely that your MSI service is not running... so there's the 99% chance your anti virus software does not like TL for whatever reason.

**Comment by cdn-crz** [comment]
lol i tried to check if my windows guard is on and remembered that i disabled its service. now i toggled it back and everything is ok ty
