### ISSUE TITLE
Error While Processing Video

### ISSUE THREAD

**Issue by capslockwizard** [Franiac/TwitchLeecher#250]
Twitch Leecher version: 1.4.3

URL of VOD: https://www.twitch.tv/videos/262574304 - Subscribers only

OS: Windows 10 64 bit

Problem: Was able to download the video but I get the "Error" status while processing the video.

Log:

> Download task has been started!
> 
> TWITCH LEECHER INFO
> --------------------------------------------------------------------------------------------
> Version: 1.4.3
> 
> VOD INFO
> --------------------------------------------------------------------------------------------
> VOD ID: 262574304
> Selected Quality: 1920x1080@30fps (Source)
> Download Url: https://www.twitch.tv/videos/262574304
> Crop Start: No
> Crop End: No
> 
> OUTPUT INFO
> --------------------------------------------------------------------------------------------
> Output File: D:\Temp\20180518_262574304_Dungeons & Dragons.mp4
> FFMPEG Path: D:\Program Files\Twitch Leecher\ffmpeg_x64.exe
> Temporary Download Folder: D:\Temp\Tmp\TL_a5fa7244-e318-4f95-b63a-a3e08e9cca9c
> 
> ACCESS INFO
> --------------------------------------------------------------------------------------------
> Token: --Redacted--
> Sub-Only: Yes
> Privileged: Yes
> 
> Creating directory 'D:\Temp\Tmp\TL_a5fa7244-e318-4f95-b63a-a3e08e9cca9c'... done!
> 
> Retrieving m3u8 playlist urls for all VOD qualities... done!
> https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/chunked/index-dvr.m3u8
> https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/720p30/index-dvr.m3u8
> https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/480p30/index-dvr.m3u8
> https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/audio_only/index-dvr.m3u8
> https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/360p30/index-dvr.m3u8
> https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/160p30/index-dvr.m3u8
> 
> Playlist url for selected quality 1920x1080@30fps (Source) is https://vod049-ttvnw.akamaized.net/3dddfedad9d26b00a97d_geekandsundry_28735978496_864668820/chunked/index-dvr.m3u8
> 
> Retrieving playlist... done!
> Parsing playlist... done!
> Number of video chunks: 1493
> 
> Starting parallel video chunk download
> Number of video chunks to download: 1493
> Maximum connection count: 10
> 
> Parallel video chunk download is running...
> 
> Download of all video chunks complete!
> 
> Creating local m3u8 playlist for FFMPEG... done!
> Writing playlist to 'D:\Temp\Tmp\TL_a5fa7244-e318-4f95-b63a-a3e08e9cca9c\vod.m3u8'... done!
> 
> Executing 'D:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
> Command line arguments: -y -i "D:\Temp\Tmp\TL_a5fa7244-e318-4f95-b63a-a3e08e9cca9c\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\Temp\20180518_262574304_Dungeons & Dragons.mp4"
> 
> 
> Starting temporary download folder cleanup!
> Deleting directory 'D:\Temp\Tmp\TL_a5fa7244-e318-4f95-b63a-a3e08e9cca9c'... done!
> 
> Download task ended with an error!
> 
> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while processing the video!
>    at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.ApplicationException: An error occured while processing the video!
>    at TwitchLeecher.Services.Services.TwitchService.ProcessVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsProcessing, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<StartQueuedDownloadIfExists>b__2()
>    at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
See #156 and #143
