### ISSUE TITLE
Can not save files to NAS

### ISSUE THREAD

**Issue by austinjaymes121** [Franiac/TwitchLeecher#251]
I can not save my files to my raspberry pi NAS, using Open Media Vault. It keeps give me a error "You do not have write permissions on specified folder! Please choose a different one!" But I do have permissions, as seen in attached screenshot. Is there something I can do to fix this?

![image](https://user-images.githubusercontent.com/39657161/40579744-c7316122-60fc-11e8-9f50-8bcb6aee646e.png)

**Comment by austinjaymes121** [comment]
I have it mapped as a network drive. Yes I am on TL 1.4.3.

**Comment by Franiac** [comment]
```C#
// Only check local drives
if (driveInfo.DriveType != DriveType.Fixed)
{
    return true;
}
```

Just copied that out of the source... I am confused.
When do you actually get that message?

**Comment by austinjaymes121** [comment]
When I click download and I change the path. I go to click download it will tell me and turn the box red

**Comment by austinjaymes121** [comment]
![image](https://user-images.githubusercontent.com/39657161/40588630-80de41ec-61ae-11e8-9722-26cdb321cf02.png)

**Comment by Franiac** [comment]
But in order to get past the given code the drive must be mounted as "fixed" in your case. How your Windows comes to that conclusion is ariddle for me. What is the path you mounted the drive with? Did you use an UNC path like "\\server\folder\subfolder" or do you use some sort of protocol like "smb://ip/folder". Since I see it is a Raspberry PI i assume it is the latter...

**Comment by austinjaymes121** [comment]
Server/folder/subfolder

**Comment by Franiac** [comment]
how did you map that drive... like litteraly how, step by step. When I go into my explorer and right click the network thingy and choose "Map network drive" and I specify a UNC path, TL always detects it as NOT "Fixed"... so I wonder how you are able to map a network drive so it shows up as "Fixed". I am not able to do that, so why are you? 😈 I want to be as cool as you 😡

**Comment by austinjaymes121** [comment]
Okay. So my Rpi is running Open Media Vault, which is the software for my nas, All i do is go
This PC -> Map Network Drive -> Browse -> Click on my device (RASPBERRYPI) -> Click on the folder I want to map (In my case it is Files) -> now it looks like the first pic -> Then i just click finish and it shows like the second pic. Hope that was easy enough to follow.


![image](https://user-images.githubusercontent.com/39657161/40589744-f708f5b2-61c0-11e8-8605-96c315579eb9.png)

![image](https://user-images.githubusercontent.com/39657161/40589748-185db48c-61c1-11e8-9f4b-74776e75c200.png)

**Comment by FSDRE** [comment]
I just realized something in your screenshot (with the red textbox).

You are trying to download directly to the server with "\\RASPBERRYPI\Files\......"
Well... that's not gonna work... TL does not support direct UNC paths. That's not as trivial as you might think it is.

BUT: You mapped the UNC to drive A:\
Now you can setup the default path in TL to "A:\Twitch VOD" then TL recognizes A:\ as a network drive, skips the permission check and you're good to go.

**Comment by FSDRE** [comment]
And another hint: If you download directly to a network drive, be aware that ffmpeg.exe runs locally and processes the files on the network drive. In case of a VOD with 11000 parts for example, all those parts travel over the LAN and the result mp4 back again.
I my opinion downloading and processing locally and then copying the result to the NAS is the better and faster way. I mean, you decide but think about the netowork load especially if it is only Gigabit LAN.

**Comment by austinjaymes121** [comment]
I tired mapping directly to Z: (Which is what the letter is not A:) and it wont let me click, see screenshots. The only place I can find the Z: is in Quick Access or in Network, which is what I was trying before. 

![image](https://user-images.githubusercontent.com/39657161/40623587-a1884d08-6275-11e8-824f-f911ea325b67.png)


![image](https://user-images.githubusercontent.com/39657161/40623594-ac9cbd6e-6275-11e8-9829-48116c6b4a0f.png)

**Comment by Franiac** [comment]
That maybe explains why it does not work from the beginning. If you map \\raspberrypi\files to Z: it should normally show up in the explorer as a network drive with the drive letter. If that does not work you have to find out why that is.

**Comment by austinjaymes121** [comment]
Thats what I assumed. I will try to figure it out.

**Comment by Franiac** [comment]
Closing this because not a TL problem
