### ISSUE TITLE
your system has not been modified

### ISSUE THREAD

**Issue by itz4d4m** [Franiac/TwitchLeecher#252]
when i try to install twitch leecher i got a message "your system has not been modified" and i tried all the solutions provided but always the same issue.
i need help as soon as possible

**Comment by Franiac** [comment]
When you create an issue there is the following hint:

"Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!"

So do that please...

**Comment by Franiac** [comment]
Closed because stale
