### ISSUE TITLE
I cant link my twitch acc due to an error 

### ISSUE THREAD

**Issue by garyyuen522** [Franiac/TwitchLeecher#253]
trying to download a sub only vod but when i try to link my twitch acc it shows this msg: 
An unexpected error occured:
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1. 
All details were written to log file
C:\Users\Gary Yuen\AppData\Roaming\Twitch Leecher\logs\05312018_083026_967_AM_error.log

**Comment by Franiac** [comment]
Please provide the logfile

**Comment by Franiac** [comment]
Closed because stale
