### ISSUE TITLE
V/A Lag (1 Sec Delay)

### ISSUE THREAD

**Issue by LGIreland** [Franiac/TwitchLeecher#254]
Hi,

I know you've had some issues with this last year and I read a lot of the posts about it but couldn't find an actual solution or whether it was an on-going issue (wasn't shown in issues).

As the title states whenever I download a VOD (whether it be 1 or 2 hours, 30fps or 60fps) I get a V/A delay of around 1 second from the MP4 file produced by your software. Haven't had this issue before yesterday but now I always have the delay. Provided the log below. Any help would be grateful.

Download Log:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 267733324
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/267733324
Crop Start: Yes (00:00:00)
Crop End: Yes (02:06:06)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\nmp\20180531_267733324_Fortnite.mp4
FFMPEG Path: D:\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\lewis\AppData\Local\Temp\TL_004c61c0-bb48-4071-a6b2-962ef37cb281

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1527913049%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A267733324%7D
Signature: 5395fae8427a138302dd2eaae6b38e9e05217d69
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\lewis\AppData\Local\Temp\TL_004c61c0-bb48-4071-a6b2-962ef37cb281'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/chunked/index-dvr.m3u8
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/720p60/index-dvr.m3u8
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/720p30/index-dvr.m3u8
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/480p30/index-dvr.m3u8
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/audio_only/index-dvr.m3u8
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/360p30/index-dvr.m3u8
https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-pop-secure.twitch.tv/b5829e318561eb53ce82_nmplol_28907184336_875369185/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1262

Starting parallel video chunk download
Number of video chunks to download: 1262
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\lewis\AppData\Local\Temp\TL_004c61c0-bb48-4071-a6b2-962ef37cb281\vod.m3u8'... done!

Executing 'D:\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -ss 0 -i "C:\Users\lewis\AppData\Local\Temp\TL_004c61c0-bb48-4071-a6b2-962ef37cb281\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc -t 7566 "D:\nmp\20180531_267733324_Fortnite.mp4"

Processing complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\lewis\AppData\Local\Temp\TL_004c61c0-bb48-4071-a6b2-962ef37cb281'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
As indicated in other issues TL is not capable of adding A/V desync since it does not re-encode the video but only merges the source streams. The mp4 is a direct result of the data from Twitch without any processing. I have tried downloading a part of your given video and everything is exactly the same as the source stream in the Twitch web player.

You say you haven't had this issue before yesterday... how is it possible that TL has something to do with it? TL does not decide to function differently from one day to another ;)

There are 2 options:

1. Your video player messes up the A/V sync on playback (happens with Media Player for example). Use VLC to verify.
2. You import it into a video software and re-encode it. Adobe Premiere is one of the miserable tools that cannot handle Twitch streams the way they are.

Like I said often times before: TL does not do anything with the source material except of merging files together so it is not even capable of adding or removing A/V desync.

**Comment by LGIreland** [comment]
Yup, I think it's the video player. Didn't mean to blame your software if it came across that way, thought it was a genuine issue.

Sorry for any wasted time.
