### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Mallumo422** [Franiac/TwitchLeecher#257]
[log.txt](https://github.com/Franiac/TwitchLeecher/files/2077086/log.txt)
Windows 10 64-bit
Setup always noted with "Your system has not been modified. Please click 'Close' to exit the Setup Wizard."
and I can see it on the applications.

**Comment by Franiac** [comment]
This is your anti virus tool.... it denies the installer of writing install keys to the registry. Not a problem of TL.

**Comment by B1tchTale** [comment]
Not work

**Comment by lennrau** [comment]
how to fix it then ?
