### ISSUE TITLE
Merging: Progress bar not working

### ISSUE THREAD

**Issue by Doublespin** [Franiac/TwitchLeecher#260]
I updated to v1.5 (Win10 64)
After downloading there is the merging stage. During that time the progress bar doesn't seem to work. Its showing 0.0 until the next stage is started (processing).

Everything else is working. No errors and videos are working, too.

**Comment by Franiac** [comment]
WTF,

**Comment by Franiac** [comment]
I am an idiot... 1.5.1 incoming... I actually don't use the Processing Service at all. I forgot to delete ConcatParts and ConvertVideo from TwitchService....
