### ISSUE TITLE
Saving settings in 1.5.1

### ISSUE THREAD

**Issue by BechGameplay** [Franiac/TwitchLeecher#263]
Just downloaded the newest version of Twitch Leecher and when i try to save settings it gives me a "null" error as one of the inputs haven't been filled out - but the only thing i changed was the Download folder.

**About my installation:**
- Installed on E: drive, whitch is not the drive windows is located on. (E: is For files, programs and games)
- Running Windows 7 64-bit.

Tried changing the download folder to: "E:\Videoer\EllahDK Redigering\VODS".

**This is the log:**
`System.ArgumentNullException: En værdi må ikke være null.
Parameternavn: value
   ved System.Xml.Linq.XElement.SetValue(Object value)
   ved TwitchLeecher.Services.Services.PreferencesService.Save(Preferences preferences)
   ved TwitchLeecher.Gui.ViewModels.PreferencesViewVM.Save()`

**My settings look like this:**
![image](https://user-images.githubusercontent.com/1050050/41376206-d1c03126-6f58-11e8-88e4-42fb112eaf35.png)

Thanks.

**Comment by Franiac** [comment]
I am an idiot... preparing 1.5.2
