### ISSUE TITLE
External video player not working with ongoing streams

### ISSUE THREAD

**Issue by Doublespin** [Franiac/TwitchLeecher#264]
I tested the new option to use vlc palyer to watch twitch videos. I noticed that if you try to watch a video of an ongoing stream then there is no video but only audio streaming. Other videos are working fine.

TL: 1.5.2 x64
OS: Win10 64bit
External palyer: Vlc 3.0.3

I'm not sure if this is caused by TL. If you can't fix it then it would be nice to inform the user about that. I was quite confused why it wasn't working for some of the videos.

**Comment by Franiac** [comment]
TL only starts VLC and provides the video url to it, everything else is VLC's business.
I guess VLC simply can't handle the dynamically growing playlist.

I don't even know how TL reacts if you try to download a running stream to be honest. In the current API v5 there is a flag if I recall correctly. So I could use that as an indicator but that flag is missing in Helix API at the moment. I'll have to investigate and see if there is a solution.

Goes to my private list -> Closed

**Comment by Doublespin** [comment]
> I don't even know how TL reacts if you try to download a running stream to be honest.

I do and it works totally fine :)

**Comment by Franiac** [comment]
What happens if TL downloads faster than the streamer provides new material? Does it just stop downloading and you get a valid piece?

**Comment by Franiac** [comment]
Well what am I asking.... TL gets the current snapshot of the playlist and downloads all the currently available parts at the point of time when you click the downlaod button....
