### ISSUE TITLE
Allow for editing of filename template

### ISSUE THREAD

**Issue by BPrystnk** [Franiac/TwitchLeecher#265]
Hi,
before the 1.5 update I used to download a video of a series every week and found it very easy to name the files as I had it setup as NameofseriesSxxExx.mp4 so whenever i downloaded a new episode i'd just delete the relevant part and not have to rename the whole thing
now if I leave the filename template, it's either the one i've pre-written in the settings(which I can only change in the settings) or if i select the custom filename it erases the filename and i have to rewrite it every time
would it be possible to make it so that whenever you select use custom filename it leaves the filename field with the template filename but it allows you to edit it instead of rewriting it?

Other than that i've found the program fantastic and easy to use

**Comment by Franiac** [comment]
Funnily enough that's how it worked in the first place and I though it was bad and changed it. But I understand the usecase here. I think the case where you edit the text based on your filename template is the most common thing to do. Was not sure at first but your example maes sense.

I'll change it in the next version...

**Comment by BPrystnk** [comment]
Thank you, it's not a major issue but i do find it very useful
and again, congrats on the wonderful program
