### ISSUE TITLE
1.5.2 (x64) Video fails part way through, audio correct

### ISSUE THREAD

**Issue by MOVr8r8** [Franiac/TwitchLeecher#269]
I've noticed a replicable issue (tried three times) with 1.5.2 (x64) which breaks this VOD: 

www.twitch.tv/videos/276896601
VOD ID: 276896601
from channel www.twitch.tv/babyhsu888
quality 1280x720@29fps (Source)
under Win 10 Pro 64-bit (v1803, build 17134.112)
with playback in Zoom Player Steam Edition v13.7.1 (MS DTV-DVD decoder into EVR renderer, LAV splitter & decoder into default DirectSound)

Compared with the same VOD downloaded with 1.4.3 the file comes up 4650KiB short and reports an average frame rate 2.36 times higher in Windows filer properties. When acquired by 1.4.3 the VOD plays correctly to the end.

The practical consequence under 1.5.2 is that although the audio is always correct, the video is only correct for around the first two hours after which it proceeds for a short while with much increased frame rate after which it stalls at a single frame. The audio is always correct for any playhead value through to the end of the stream, although Zoom Player sometimes fails to play after changing play position and there is always a short mute running section until the audio is picked up again.

Yep - the VOD does not open at all for me in Windows Media Player.

Regarding audio, be aware that there are three short sections in the VOD that have been copyright-muted by Twitch.

I have included Download Logs for both 1.5.2 (shown first) and also 1.4.3. Only the part-merge sections appear to be different.

Thank you for your excellent application!

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 276896601
Selected Quality: 1280x720@29fps (Source)
Download Url: https://www.twitch.tv/videos/276896601
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\VODs\Downloads\20180624_276896601_IRL.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\VODs\Downloads\Cache\TL_0ca0abd6-ebb5-4389-afe1-900fee9926b4

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1530005761%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A104861666%2C%22version%22%3A2%2C%22vod_id%22%3A276896601%7D
Signature: 8641434d6801fbe21a3fa8d76d858bb3de66afde
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\VODs\Downloads\Cache\TL_0ca0abd6-ebb5-4389-afe1-900fee9926b4'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/chunked/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/720p30/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/480p30/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/audio_only/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/360p30/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/160p30/index-muted-H6K1W9V4Y3.m3u8

Playlist url for selected quality 1280x720@29fps (Source) is https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/chunked/index-muted-H6K1W9V4Y3.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2740

Starting parallel video chunk download
Number of video chunks to download: 2740
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'D:\VODs\Downloads\Cache\TL_0ca0abd6-ebb5-4389-afe1-900fee9926b4\20180624_276896601_IRL.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'D:\VODs\Downloads\Cache\TL_0ca0abd6-ebb5-4389-afe1-900fee9926b4\20180624_276896601_IRL.ts'...
Command line arguments: -y -i "D:\VODs\Downloads\Cache\TL_0ca0abd6-ebb5-4389-afe1-900fee9926b4\20180624_276896601_IRL.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\VODs\Downloads\20180624_276896601_IRL.mp4"

Video conversion complete!

Starting temporary download folder cleanup!
Deleting directory 'D:\VODs\Downloads\Cache\TL_0ca0abd6-ebb5-4389-afe1-900fee9926b4'... done!

Download task ended successfully!

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.4.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 276896601
Selected Quality: 1280x720@29fps (Source)
Download Url: https://www.twitch.tv/videos/276896601
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\VODs\Downloads\20180624_276896601_IRL.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: D:\VODs\Downloads\Cache\TL_d3ef2d93-2318-4ec8-86a8-fdf79d44e350

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1530009206%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A104861666%2C%22version%22%3A2%2C%22vod_id%22%3A276896601%7D
Signature: 0e86a11e3ca571e168d39503e9d18cb6f80fb3a0
Sub-Only: No
Privileged: No

Creating directory 'D:\VODs\Downloads\Cache\TL_d3ef2d93-2318-4ec8-86a8-fdf79d44e350'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/chunked/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/720p30/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/480p30/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/audio_only/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/360p30/index-muted-H6K1W9V4Y3.m3u8
https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/160p30/index-muted-H6K1W9V4Y3.m3u8

Playlist url for selected quality 1280x720@29fps (Source) is https://vod-metro.twitch.tv/152893424f7ff036da31_babyhsu888_29211762592_894405325/chunked/index-muted-H6K1W9V4Y3.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2740

Starting parallel video chunk download
Number of video chunks to download: 2740
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'D:\VODs\Downloads\Cache\TL_d3ef2d93-2318-4ec8-86a8-fdf79d44e350\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "D:\VODs\Downloads\Cache\TL_d3ef2d93-2318-4ec8-86a8-fdf79d44e350\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\VODs\Downloads\20180624_276896601_IRL.mp4"

Processing complete!

Starting temporary download folder cleanup!
Deleting directory 'D:\VODs\Downloads\Cache\TL_d3ef2d93-2318-4ec8-86a8-fdf79d44e350'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
I don't want to be mean here but the only thing I care about is: How does VLC handle it? Because it is the only video player that consistently handles Twitch streams correctly.

There are so many video software pieces that cannot handle Twitch VOD's including Media Player, Adobe Premiere and some PowerDVD products where you might think "that is proper software".

So the first thing you should test is: How does VLC 3 play back the VOD downloaded with 1.4.3 and how does it handle the VOD downloaded with 1.5.2.

The obvious argument is "Zoom Player does not play back the video correctly, TL must have an issue with the download process" when it is most of the time the exact opposite: TL downloads the VOD correctly and the video player cannot handle it.

I have never heard of Zoom Player and the Steam reviews are "Mixed", so I don't trust this software piece from the getgo.

**Comment by MOVr8r8** [comment]
Thank you, installed VLC 3.0.3 with same results: 1.4.3 VOD works no problems but 1.5.2 A/V sync and framerate falls apart about 1h45m, turns audio-only soon after. VOD also works correctly served to a browser from Twitch.

My easy work around is to revert for now. While waiting to see if there are further bug reports, please ask if there are more conditions I could try out for you.

Meanwhile I totally get that doing nothing for a while is a good thing, I get that Twitch VODs are Transport Streams, that Transport Streams are broadcaster extensible and that the Twitch platform is a live product under competitive pressure to change (the move to AWS, changing API, chasing Mixer's low latency) so consequently some problems solve themselves as Twitch introduce then subsequently fix them.

You mentioned Premiere, NLEs expect cam footage - TS is at the wrong place in the workflow to expect it to import with proper conformity and with VODs from casts such as this, originating over 4G from a cell phone, it will be more challenging due to IP packet loss to the ingestion server and consequently more dropped frames. I often see you having to correct people over this: (missing) feature not bug, it's not something TL/FFmpeg causes but equally the converse is true: even badly broken mobile IRL streams should not cause a problem for TL.

As for Zoom Player, like VLC it is mostly a front end for other people's decoders. I listed the filter graph components including Window's in-built 'Microsoft DTV-DVD Video Decoder', the 'DTV' part should reassure you it's somewhat aware of TS! :)

Again: thank you! Awesome application and please ask if you need anything further.

**Comment by Franiac** [comment]
The only thing 1.5.2 does differently is merging the thousands of .ts parts together into a single file before processing it by ffmpeg. Everything else is the same. This fixed 2 major bugs (see release notes 1.5.0 - 1.5.2) TL had since 1.0. Even if it actually IS a bug, chances that I revert it are minimal. There where at least 3 e-mails a week because of those 2 bugs. Since 1.5.2 not a single e-mail was sent. So even if you encountered a new problem I call this a success.

I see you digged into the closed issues a bit before posting (which I appreciate very much). You understand the fact that TL does nothing to the streams from Twitch except changing the container to .mp4. So broken streams keep being broken streams with TL. Most users don't get that and blame TL for it. ffmpeg is not error-prone like a web player which can just throw away a faulted frame and go on like nothing happened.

I close this one now because I will not take any action until there are more issues like this. Again, not because I don't want to solve your problem but because of the fact that this new issue competes against 200 solved ones at least. You may post further information or VODs related to the issue.
