### ISSUE TITLE
Select multiple vods and download them and bandwidth limiter

### ISSUE THREAD

**Issue by Saltystew** [Franiac/TwitchLeecher#271]
It would be really nice if I could select multiple vods on the search screen and them set to download.

Or make it so I don't have to set the download preferences after every time I click the download button.

Also a setting to limit the amount of download bandwidth the program uses would be a nice feature if that's doable.

**Comment by Franiac** [comment]
#46

**Comment by Franiac** [comment]
This is automatically implied in #46 
The current donwload manager can't do that.
