### ISSUE TITLE
object reference not set to instance of object

### ISSUE THREAD

**Issue by vailedbroom** [Franiac/TwitchLeecher#273]
Starting from 08/07 whenever i try to download a vod i get the below error when i click on the download button.

"An unexpected error occurred:
Object reference not set to instance of object. "

Twitch Leecher Version: 1.5.2
Os: windows 64 bit version 1083 (build 17134.112)

Sample vod: https://www.twitch.tv/videos/281923811
channel: flikstrr

Additional info:
I have tried uninstalling twitch leecher and reinstalling but error persists.  When the download button is selected nothing is added to the download queue.  I have tried clicking on a previously downloaded vod and that now generates the same error message. 

log
System.NullReferenceException: Object reference not set to an instance of an object.
   at TwitchLeecher.Services.Services.PreferencesService.IsChannelInFavourites(String channel)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Franiac** [comment]
Little bug. You can get around it by specifying a channel name in the "Favourite Channels" field and save.
