### ISSUE TITLE
Entry Point not found

### ISSUE THREAD

**Issue by unknown10295** [Franiac/TwitchLeecher#275]
"The procedure entry point nextafterf could not be located in the dynamic link library MSVCR120_CLR0400.dll."
I've tried all download links and each one gives me this prompt
![twitch](https://user-images.githubusercontent.com/40966063/42423485-ef9c3bce-82f2-11e8-8cbc-06a2d4fd1939.JPG)

Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by Franiac** [comment]
This is not an error message from the Twitch Leecher installer or any MSI subsystem. This is a problem with Miscrosoft Visual C++ Runtime on your system. Nothing I can do here, sorry.
