### ISSUE TITLE
Fatal UI Error when using Arabic language

### ISSUE THREAD

**Issue by Hadi10000** [Franiac/TwitchLeecher#278]
![screenshot_7](https://user-images.githubusercontent.com/35529403/42922701-87e5f278-8b2a-11e8-892d-07773171117d.png)

i need help

**Comment by Franiac** [comment]
And I need the log file...

**Comment by Hadi10000** [comment]
System.Windows.Markup.XamlParseException: Set property 'System.Windows.FrameworkElement.Style' threw an exception. ---> System.ArgumentException: 'd' is not a valid value for the 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' property on a Setter.
   عند System.Windows.Setter.Seal()
   عند System.Windows.SetterBaseCollection.Seal()
   عند System.Windows.Style.Seal()
   عند System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   عند System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   عند System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   عند System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   عند System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   عند System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   عند System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   عند System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   عند MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- نهاية تتبع بنية تخزين عناصر الاستثناء الداخلي ---
   عند System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   عند System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   عند System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   عند System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   عند System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   عند System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   عند System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   عند System.Windows.FrameworkElement.ApplyTemplate()
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   عند System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   عند System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Control.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Control.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   عند System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   عند System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   عند System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Controls.Border.MeasureOverride(Size constraint)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.Window.MeasureOverrideHelper(Size constraint)
   عند System.Windows.Window.MeasureOverride(Size availableSize)
   عند System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   عند System.Windows.UIElement.Measure(Size availableSize)
   عند System.Windows.ContextLayoutManager.UpdateLayout()
   عند System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   عند System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   عند System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   عند System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   عند System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   عند System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Franiac** [comment]
What is your Windows language?

**Comment by Hadi10000** [comment]
Arabic

**Comment by Franiac** [comment]
Ok, seems like the Xceed UI library I partly use in TL does not support Arabic. I have to implement a fallback to en_US in case anything with ar_XX comes along.
