### ISSUE TITLE
Problem downloading Twitch videos

### ISSUE THREAD

**Issue by gl205** [Franiac/TwitchLeecher#280]
Hi, 

I keep getting this error message after trying to download Twitch videos, any tips on how to fix would be great :)

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 276064107
Selected Quality: 1920x1080@30fps (Source)
Download Url: https://www.twitch.tv/videos/276064107
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\glove_000\Dropbox\20180621_276064107_Dungeons & Dragons.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\glove_000\AppData\Local\Temp39241206l\TL_efb222dd-a7c6-47eb-a2e8-6436dc9d2c68

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1532365879%2C%22https_required%22%3Afalse%2C%22privileged%22%3Atrue%2C%22user_id%22%3A176801966%2C%22version%22%3A2%2C%22vod_id%22%3A276064107%7D
Signature: 465c4f5f6b161cf634d6935f4c72a324446af0fa
Sub-Only: Yes
Privileged: Yes

Creating temporary download directory 'C:\Users\glove_000\AppData\Local\Temp39241206l\TL_efb222dd-a7c6-47eb-a2e8-6436dc9d2c68'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/chunked/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/720p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/480p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/audio_only/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/360p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@30fps (Source) is https://vod.edgecast.hls.ttvnw.net/410d8c494a9db86e9c76_geekandsundry_29183669376_892649499/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1522

Starting parallel video chunk download
Number of video chunks to download: 1522
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\glove_000\AppData\Local\Temp39241206l\TL_efb222dd-a7c6-47eb-a2e8-6436dc9d2c68\20180621_276064107_Dungeons & Dragons.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\glove_000\AppData\Local\Temp39241206l\TL_efb222dd-a7c6-47eb-a2e8-6436dc9d2c68\20180621_276064107_Dungeons & Dragons.ts'...
Command line arguments: -y -i "C:\Users\glove_000\AppData\Local\Temp39241206l\TL_efb222dd-a7c6-47eb-a2e8-6436dc9d2c68\20180621_276064107_Dungeons & Dragons.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\glove_000\Dropbox\20180621_276064107_Dungeons & Dragons.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\glove_000\AppData\Local\Temp39241206l\TL_efb222dd-a7c6-47eb-a2e8-6436dc9d2c68'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
See #156 and #143 

Additional note: If there is not enough space on disk, you will get this error, too. FFMPEG needs the same amount of space like the downloaded files from TL.

TL downloads a 6GB .ts file for example. FFMPEG uses this file, creates another 6GB file out of it (.mp4) and at the end deletes the .ts file. So you need 12GB free space on your HDD.

I will implement a more detailed error message for the processing stage in the near future.
