### ISSUE TITLE
won't install on windows seven x64 

### ISSUE THREAD

**Issue by RoyalC** [Franiac/TwitchLeecher#281]
hello i have try the 3 versions but none want to install on windows seven x64, i have try by admin but it say an error occur when installing and nothing else !!
is there any portable version can i test ?
thanks

**Comment by Franiac** [comment]
Most of the issues here with the installer are related to anti virus software. disabling anti virus for the installation helped most people. TL is open source, so don't be afraid anything fishy is going on. I don'T know why AV tools dislike TL sometimes.

If that does not help try running the installer from command line:

`TwitchLeecher_1.5.2_x64.exe -l log.txt`

Then click through the installer, let it throw the error, close the installer and send me the logfiles that were created in the same folder your installer is located.

**Comment by RoyalC** [comment]
ok give a try and send the log file

**Comment by RoyalC** [comment]
here is my log file:
[log.txt](https://github.com/Franiac/TwitchLeecher/files/2222805/log.txt)

**Comment by Franiac** [comment]
From the log:

```
MSI (s) (1C:B8) [10:57:26:029]: Product: Twitch Leecher 1.5.2 -- This product is only supported on Windows Vista SP2, Windows 7 SP1, Windows Server 2008 SP2, Windows Server 2008 R2 SP1, or higher.
```

You need at least the Service Pack 1 installed for Windows 7. There are 2 Service Packs, 1 and 2. You can install the 2nd one that includes the 1st. This is not only for TL but for your own security. Running Windows 7 without any service packs is kinda "meh". I strongly recommend you to install it and update your Windows via Windows Updates to receive the latest security patches.

**Comment by RoyalC** [comment]
ha ok i'll do that and come back for feedback :dagger:
