### ISSUE TITLE
Download task ended on error. Please help! :)

### ISSUE THREAD

**Issue by rsoueidan** [Franiac/TwitchLeecher#286]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 284613928
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/284613928
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Raed Soueidan\Videos\20180715_284613928_Overwatch.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1532922412%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A284613928%7D
Signature: 34dd8d2ceb4716a8bfdd8a90a7ab41c631ff7659
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/chunked/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/720p60/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/720p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/480p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/audio_only/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/360p30/index-dvr.m3u8
https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod.edgecast.hls.ttvnw.net/88684dc9705044e2385c_xqcow_29475342960_910879098/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 7829

Starting parallel video chunk download
Number of video chunks to download: 7829
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0\20180715_284613928_Overwatch.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0\20180715_284613928_Overwatch.ts'...
Command line arguments: -y -i "C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0\20180715_284613928_Overwatch.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\Raed Soueidan\Videos\20180715_284613928_Overwatch.mp4"

ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.1 (GCC) 20180710
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
Input #0, mpegts, from 'C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0\20180715_284613928_Overwatch.ts':
Duration: 13:02:50.14, start: 66.012989, bitrate: 7816 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 164 kb/s
Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 90k tbn, 120 tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'C:\Users\Raed Soueidan\Videos\20180715_284613928_Overwatch.mp4':
Metadata:
encoder         : Lavf58.12.100
Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt470bg/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 90k tbn, 90k tbc
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 164 kb/s
Stream mapping:
Stream #0:1 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1084 fps=0.0 q=-1.0 size=   14848kB time=00:00:18.06 bitrate=6733.2kbits/s speed=  36x
frame= 2005 fps=2001 q=-1.0 size=   27136kB time=00:00:33.43 bitrate=6648.3kbits/s speed=33.4x
frame= 3145 fps=2085 q=-1.0 size=   43008kB time=00:00:52.40 bitrate=6722.7kbits/s speed=34.7x
frame= 5536 fps=2746 q=-1.0 size=   76032kB time=00:01:32.27 bitrate=6749.9kbits/s speed=45.8x
frame= 7747 fps=3077 q=-1.0 size=  107264kB time=00:02:09.12 bitrate=6805.0kbits/s speed=51.3x
frame= 9982 fps=3307 q=-1.0 size=  139776kB time=00:02:46.37 bitrate=6882.5kbits/s speed=55.1x
frame=12937 fps=3676 q=-1.0 size=  186112kB time=00:03:35.62 bitrate=7070.9kbits/s speed=61.3x
frame=15031 fps=3730 q=-1.0 size=  218880kB time=00:04:10.52 bitrate=7157.4kbits/s speed=62.2x
frame=15840 fps=3496 q=-1.0 size=  231168kB time=00:04:24.01 bitrate=7172.9kbits/s speed=58.3x
frame=19819 fps=3938 q=-1.0 size=  293376kB time=00:05:30.30 bitrate=7276.1kbits/s speed=65.6x
frame=22864 fps=4102 q=-1.0 size=  340992kB time=00:06:21.06 bitrate=7330.6kbits/s speed=68.4x
frame=25234 fps=4154 q=-1.0 size=  377600kB time=00:07:00.58 bitrate=7354.8kbits/s speed=69.2x
frame=30200 fps=4594 q=-1.0 size=  455424kB time=00:08:23.33 bitrate=7412.2kbits/s speed=76.6x
frame=33414 fps=4723 q=-1.0 size=  505088kB time=00:09:16.90 bitrate=7429.7kbits/s speed=78.7x
frame=35162 fps=4641 q=-1.0 size=  532736kB time=00:09:46.04 bitrate=7446.8kbits/s speed=77.3x
frame=38198 fps=4729 q=-1.0 size=  580096kB time=00:10:36.62 bitrate=7464.6kbits/s speed=78.8x
frame=42006 fps=4897 q=-1.0 size=  636416kB time=00:11:40.10 bitrate=7446.8kbits/s speed=81.6x
frame=47258 fps=5206 q=-1.0 size=  718336kB time=00:13:07.64 bitrate=7471.2kbits/s speed=86.8x
frame=51568 fps=5384 q=-1.0 size=  785408kB time=00:14:19.46 bitrate=7486.1kbits/s speed=89.7x
frame=53458 fps=5304 q=-1.0 size=  814848kB time=00:14:50.97 bitrate=7492.1kbits/s speed=88.4x
frame=54306 fps=5132 q=-1.0 size=  828416kB time=00:15:05.09 bitrate=7498.0kbits/s speed=85.5x
frame=54957 fps=4959 q=-1.0 size=  838656kB time=00:15:15.93 bitrate=7500.8kbits/s speed=82.7x
frame=58213 fps=5026 q=-1.0 size=  889088kB time=00:16:10.22 bitrate=7506.9kbits/s speed=83.8x
frame=61517 fps=5091 q=-1.0 size=  940800kB time=00:17:05.30 bitrate=7516.9kbits/s speed=84.9x
frame=63151 fps=5019 q=-1.0 size=  966144kB time=00:17:32.51 bitrate=7519.8kbits/s speed=83.6x
frame=67600 fps=5167 q=-1.0 size= 1035264kB time=00:18:46.65 bitrate=7527.5kbits/s speed=86.1x
frame=72996 fps=5374 q=-1.0 size= 1119744kB time=00:20:16.58 bitrate=7539.9kbits/s speed=89.6x
frame=74212 fps=5267 q=-1.0 size= 1138432kB time=00:20:36.85 bitrate=7540.1kbits/s speed=87.8x
frame=75055 fps=5143 q=-1.0 size= 1151744kB time=00:20:50.90 bitrate=7542.6kbits/s speed=85.7x
frame=75933 fps=5030 q=-1.0 size= 1165312kB time=00:21:05.55 bitrate=7543.1kbits/s speed=83.8x
frame=79285 fps=5084 q=-1.0 size= 1217536kB time=00:22:01.42 bitrate=7548.0kbits/s speed=84.7x
frame=82522 fps=5127 q=-1.0 size= 1266176kB time=00:22:55.36 bitrate=7541.6kbits/s speed=85.4x
frame=84462 fps=5087 q=-1.0 size= 1293056kB time=00:23:27.70 bitrate=7524.8kbits/s speed=84.8x
frame=87831 fps=5135 q=-1.0 size= 1339904kB time=00:24:23.83 bitrate=7498.5kbits/s speed=85.6x
frame=90684 fps=5151 q=-1.0 size= 1380352kB time=00:25:11.38 bitrate=7481.8kbits/s speed=85.9x
frame=91743 fps=5067 q=-1.0 size= 1394944kB time=00:25:29.03 bitrate=7473.6kbits/s speed=84.5x
frame=95289 fps=5121 q=-1.0 size= 1446400kB time=00:26:28.15 bitrate=7460.8kbits/s speed=85.4x
frame=98144 fps=5136 q=-1.0 size= 1490688kB time=00:27:15.72 bitrate=7465.6kbits/s speed=85.6x
frame=99013 fps=5048 q=-1.0 size= 1504512kB time=00:27:30.21 bitrate=7468.7kbits/s speed=84.1x
frame=104516 fps=5195 q=-1.0 size= 1590272kB time=00:29:01.93 bitrate=7478.7kbits/s speed=86.6x
frame=109513 fps=5310 q=-1.0 size= 1667840kB time=00:30:25.20 bitrate=7485.7kbits/s speed=88.5x
frame=110380 fps=5225 q=-1.0 size= 1681408kB time=00:30:39.67 bitrate=7487.3kbits/s speed=87.1x
frame=111798 fps=5170 q=-1.0 size= 1703936kB time=00:31:03.28 bitrate=7491.4kbits/s speed=86.2x
frame=113918 fps=5148 q=-1.0 size= 1736960kB time=00:31:38.62 bitrate=7494.5kbits/s speed=85.8x
frame=118509 fps=5237 q=-1.0 size= 1808384kB time=00:32:55.13 bitrate=7500.4kbits/s speed=87.3x
frame=124981 fps=5404 q=-1.0 size= 1909248kB time=00:34:43.01 bitrate=7508.6kbits/s speed=90.1x
frame=126262 fps=5343 q=-1.0 size= 1929472kB time=00:35:04.35 bitrate=7511.2kbits/s speed=89.1x
frame=126898 fps=5258 q=-1.0 size= 1939200kB time=00:35:14.96 bitrate=7511.2kbits/s speed=87.6x
frame=128520 fps=5217 q=-1.0 size= 1964544kB time=00:35:42.01 bitrate=7513.3kbits/s speed=  87x
frame=132088 fps=5255 q=-1.0 size= 2020096kB time=00:36:41.46 bitrate=7517.1kbits/s speed=87.6x
frame=134872 fps=5261 q=-1.0 size= 2063616kB time=00:37:27.85 bitrate=7520.6kbits/s speed=87.7x
frame=136763 fps=5233 q=-1.0 size= 2093056kB time=00:37:59.38 bitrate=7522.3kbits/s speed=87.2x
frame=139752 fps=5247 q=-1.0 size= 2139904kB time=00:38:49.19 bitrate=7526.3kbits/s speed=87.4x
frame=142489 fps=5251 q=-1.0 size= 2182400kB time=00:39:34.82 bitrate=7528.2kbits/s speed=87.5x
frame=143676 fps=5198 q=-1.0 size= 2200832kB time=00:39:54.60 bitrate=7529.1kbits/s speed=86.6x
frame=147240 fps=5232 q=-1.0 size= 2253568kB time=00:40:54.02 bitrate=7522.8kbits/s speed=87.2x
frame=149779 fps=5229 q=-1.0 size= 2289408kB time=00:41:36.33 bitrate=7513.0kbits/s speed=87.2x
frame=151393 fps=5195 q=-1.0 size= 2312448kB time=00:42:03.21 bitrate=7507.7kbits/s speed=86.6x
frame=155110 fps=5233 q=-1.0 size= 2366464kB time=00:43:05.17 bitrate=7499.0kbits/s speed=87.2x
frame=156805 fps=5201 q=-1.0 size= 2392064kB time=00:43:33.40 bitrate=7498.2kbits/s speed=86.7x
frame=157680 fps=5144 q=-1.0 size= 2405376kB time=00:43:48.01 bitrate=7498.0kbits/s speed=85.7x
frame=161399 fps=5181 q=-1.0 size= 2463744kB time=00:44:49.98 bitrate=7503.0kbits/s speed=86.3x
frame=162958 fps=5148 q=-1.0 size= 2487808kB time=00:45:15.96 bitrate=7503.8kbits/s speed=85.8x
frame=165997 fps=5162 q=-1.0 size= 2535424kB time=00:46:06.61 bitrate=7507.4kbits/s speed=  86x
frame=169855 fps=5201 q=-1.0 size= 2595328kB time=00:47:10.90 bitrate=7510.3kbits/s speed=86.7x
frame=170715 fps=5148 q=-1.0 size= 2608896kB time=00:47:25.25 bitrate=7511.5kbits/s speed=85.8x
frame=172197 fps=5116 q=-1.0 size= 2631936kB time=00:47:49.93 bitrate=7512.6kbits/s speed=85.3x
frame=174978 fps=5122 q=-1.0 size= 2675200kB time=00:48:36.31 bitrate=7514.7kbits/s speed=85.4x
frame=177478 fps=5120 q=-1.0 size= 2714112kB time=00:49:17.96 bitrate=7516.7kbits/s speed=85.3x
frame=180481 fps=5132 q=-1.0 size= 2761216kB time=00:50:08.02 bitrate=7519.8kbits/s speed=85.5x
frame=182470 fps=5116 q=-1.0 size= 2791936kB time=00:50:41.16 bitrate=7520.7kbits/s speed=85.3x
frame=183319 fps=5069 q=-1.0 size= 2805248kB time=00:50:55.30 bitrate=7521.5kbits/s speed=84.5x
frame=186169 fps=5077 q=-1.0 size= 2849536kB time=00:51:42.81 bitrate=7523.3kbits/s speed=84.6x
frame=190802 fps=5133 q=-1.0 size= 2921984kB time=00:53:00.01 bitrate=7527.3kbits/s speed=85.6x
frame=199705 fps=5301 q=-1.0 size= 3060736kB time=00:55:28.41 bitrate=7533.2kbits/s speed=88.4x
frame=200773 fps=5260 q=-1.0 size= 3077632kB time=00:55:46.20 bitrate=7534.5kbits/s speed=87.7x
frame=201583 fps=5213 q=-1.0 size= 3090176kB time=00:55:59.71 bitrate=7534.8kbits/s speed=86.9x
frame=202441 fps=5168 q=-1.0 size= 3103744kB time=00:56:14.02 bitrate=7535.8kbits/s speed=86.1x
frame=203364 fps=5126 q=-1.0 size= 3118080kB time=00:56:29.39 bitrate=7536.2kbits/s speed=85.4x
frame=205681 fps=5120 q=-1.0 size= 3153920kB time=00:57:08.03 bitrate=7537.0kbits/s speed=85.3x
frame=208729 fps=5131 q=-1.0 size= 3201536kB time=00:57:58.81 bitrate=7539.1kbits/s speed=85.5x
frame=211593 fps=5139 q=-1.0 size= 3246336kB time=00:58:46.55 bitrate=7541.1kbits/s speed=85.6x
frame=215113 fps=5161 q=-1.0 size= 3301120kB time=00:59:45.20 bitrate=7542.9kbits/s speed=  86x
frame=218277 fps=5175 q=-1.0 size= 3350272kB time=01:00:37.93 bitrate=7544.2kbits/s speed=86.3x
frame=219313 fps=5138 q=-1.0 size= 3366400kB time=01:00:55.21 bitrate=7544.7kbits/s speed=85.6x
frame=221821 fps=5137 q=-1.0 size= 3405568kB time=01:01:37.01 bitrate=7546.2kbits/s speed=85.6x
frame=223989 fps=5127 q=-1.0 size= 3439872kB time=01:02:13.14 bitrate=7548.4kbits/s speed=85.5x
frame=227783 fps=5155 q=-1.0 size= 3494656kB time=01:03:16.36 bitrate=7540.9kbits/s speed=85.9x
frame=231316 fps=5176 q=-1.0 size= 3549696kB time=01:04:15.25 bitrate=7542.7kbits/s speed=86.3x
frame=233092 fps=5158 q=-1.0 size= 3577344kB time=01:04:44.86 bitrate=7543.5kbits/s speed=  86x
frame=234007 fps=5121 q=-1.0 size= 3591680kB time=01:05:00.11 bitrate=7544.1kbits/s speed=85.4x
frame=236495 fps=5120 q=-1.0 size= 3630592kB time=01:05:41.58 bitrate=7545.6kbits/s speed=85.3x
frame=238397 fps=5106 q=-1.0 size= 3660288kB time=01:06:13.28 bitrate=7546.7kbits/s speed=85.1x
frame=241946 fps=5127 q=-1.0 size= 3715840kB time=01:07:12.44 bitrate=7548.8kbits/s speed=85.4x
frame=245248 fps=5141 q=-1.0 size= 3767040kB time=01:08:07.45 bitrate=7549.8kbits/s speed=85.7x
frame=246120 fps=5105 q=-1.0 size= 3780608kB time=01:08:22.01 bitrate=7550.1kbits/s speed=85.1x
frame=247486 fps=5081 q=-1.0 size= 3801856kB time=01:08:44.76 bitrate=7550.7kbits/s speed=84.7x
frame=250020 fps=5081 q=-1.0 size= 3841536kB time=01:09:27.00 bitrate=7552.2kbits/s speed=84.7x
frame=252820 fps=5086 q=-1.0 size= 3885312kB time=01:10:13.65 bitrate=7553.6kbits/s speed=84.8x
frame=256903 fps=5116 q=-1.0 size= 3949056kB time=01:11:21.71 bitrate=7555.5kbits/s speed=85.3x
frame=258839 fps=5104 q=-1.0 size= 3979008kB time=01:11:53.98 bitrate=7555.9kbits/s speed=85.1x
frame=259516 fps=5067 q=-1.0 size= 3989504kB time=01:12:05.27 bitrate=7556.1kbits/s speed=84.5x
frame=262237 fps=5071 q=-1.0 size= 4032000kB time=01:12:50.62 bitrate=7557.3kbits/s speed=84.5x
frame=264601 fps=5067 q=-1.0 size= 4068864kB time=01:13:30.00 bitrate=7558.3kbits/s speed=84.5x
frame=266518 fps=5056 q=-1.0 size= 4098560kB time=01:14:01.95 bitrate=7558.7kbits/s speed=84.3x
frame=269768 fps=5069 q=-1.0 size= 4149760kB time=01:14:56.12 bitrate=7560.9kbits/s speed=84.5x
frame=270776 fps=5041 q=-1.0 size= 4165120kB time=01:15:12.91 bitrate=7560.7kbits/s speed=  84x
frame=273094 fps=5037 q=-1.0 size= 4201472kB time=01:15:51.57 bitrate=7561.9kbits/s speed=83.9x
frame=275363 fps=5032 q=-1.0 size= 4237056kB time=01:16:29.37 bitrate=7563.1kbits/s speed=83.9x
frame=278512 fps=5043 q=-1.0 size= 4285440kB time=01:17:21.85 bitrate=7563.0kbits/s speed=84.1x
frame=281032 fps=5043 q=-1.0 size= 4324608kB time=01:18:03.85 bitrate=7563.7kbits/s speed=84.1x
frame=282469 fps=5024 q=-1.0 size= 4347136kB time=01:18:27.82 bitrate=7564.4kbits/s speed=83.7x
frame=283561 fps=4999 q=-1.0 size= 4364288kB time=01:18:46.00 bitrate=7565.0kbits/s speed=83.3x
frame=285820 fps=4994 q=-1.0 size= 4399616kB time=01:19:23.66 bitrate=7565.9kbits/s speed=83.2x
frame=288172 fps=4992 q=-1.0 size= 4435712kB time=01:20:02.86 bitrate=7565.8kbits/s speed=83.2x
frame=291190 fps=5001 q=-1.0 size= 4483072kB time=01:20:53.15 bitrate=7567.3kbits/s speed=83.3x
frame=292684 fps=4983 q=-1.0 size= 4506368kB time=01:21:18.07 bitrate=7567.8kbits/s speed=83.1x
frame=293662 fps=4958 q=-1.0 size= 4521472kB time=01:21:34.37 bitrate=7567.9kbits/s speed=82.6x
frame=297240 fps=4973 q=-1.0 size= 4575744kB time=01:22:34.02 bitrate=7566.5kbits/s speed=82.9x
frame=298540 fps=4953 q=-1.0 size= 4594688kB time=01:22:55.66 bitrate=7564.8kbits/s speed=82.6x
frame=300543 fps=4946 q=-1.0 size= 4621824kB time=01:23:29.03 bitrate=7558.7kbits/s speed=82.4x
frame=303360 fps=4951 q=-1.0 size= 4665088kB time=01:24:16.00 bitrate=7558.6kbits/s speed=82.5x
frame=304616 fps=4931 q=-1.0 size= 4684800kB time=01:24:36.95 bitrate=7559.2kbits/s speed=82.2x
frame=307620 fps=4940 q=-1.0 size= 4731648kB time=01:25:27.01 bitrate=7560.3kbits/s speed=82.3x
frame=310540 fps=4947 q=-1.0 size= 4777472kB time=01:26:15.65 bitrate=7561.8kbits/s speed=82.4x
frame=311421 fps=4922 q=-1.0 size= 4791040kB time=01:26:30.35 bitrate=7561.8kbits/s speed=  82x
frame=312448 fps=4899 q=-1.0 size= 4806912kB time=01:26:47.46 bitrate=7561.9kbits/s speed=81.6x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\Raed Soueidan\Videos\20180715_284613928_Overwatch.mp4: No space left on device
frame=312704 fps=4889 q=-1.0 Lsize= 4810752kB time=01:26:51.71 bitrate=7561.7kbits/s speed=81.5x
video:4706666kB audio:104028kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001204%
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Raed Soueidan\AppData\Local\Temp\TL_49957507-41b9-412f-89e1-c42eecca4dc0'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
`No space left on device`

Go get a bigger HDD 😄

**Comment by rsoueidan** [comment]
LOL oh my god I didn't even notice that! This is really embarrassing. Thank you for marking my issue, I'm going to go hide in a corner now... But not before I delete some garbage off of my laptop.
