### ISSUE TITLE
[Feature request] Audio only

### ISSUE THREAD

**Issue by mr-flibble** [Franiac/TwitchLeecher#290]
Hello, this is only idea of possible feature.

Twitch Android and iOS app now support "Audio only" playback for live broadcast, but also for recorded VODs. 

It would be useful to have this feature in Twitch Leecher quality selection 

![image](https://user-images.githubusercontent.com/5197625/43796839-a5052b16-9a85-11e8-9da9-6dd78a704585.png)

**Comment by Franiac** [comment]
This is implemented since TL 1.2.2 (2016). The thing is that Twitch does not always include the audio only option for selection in the API. I rarely see new videos where the API actually provides this option. Nothing wrong on my end 😄
