### ISSUE TITLE
TL won't install

### ISSUE THREAD

**Issue by StillTryingToLearn1** [Franiac/TwitchLeecher#292]
The setup freezes after clicking install button, more specifically, the window shows the progress bar but it never starts installing the software. The only way I can close the .exe is by task manager.

OS: Windows 8.1 (64 Bit)
.Net Framework: 4.7.02558
TL version: 1.5.3 (64 Bit)
Logfile: [logfile.txt](https://github.com/Franiac/TwitchLeecher/files/2294283/logfile.txt)

On other people threads you mention we should get two logfiles, I'm only getting this one. Also, I tried deactivating my antivirus and/or running the setup as administrator.

**Comment by Franiac** [comment]
That's a weird one. Absolutely no error in the log. How long did you wait after clicking install? I recommend waiting at least 3 minutes. Windows Installer can act super awkward sometimes.

Another option would be to check the windows event log (category "Application") for errors related to the windows installer or TL.

The last entry in the log is

`Pausing automatic updates`

Maybe windows was installing updates at the same time and the installer wanted to wait for their completion? Could be, but I don't really know.

**Comment by StillTryingToLearn1** [comment]
I appreciate your fast assistance.

Your answer inspired me to redownload the executable and it worked at the first try. I don't know how this didn't occur to me before, I sincerelly apologise for this.

Thank you Franiac, have a nice day.
