### ISSUE TITLE
Unable to download with a subcribed account

### ISSUE THREAD

**Issue by gioba84** [Franiac/TwitchLeecher#294]
when i try to download some videos from a subbed account, twitch leecher says me "this video is sub-only!Please authorize your twitch account by clicking the twitch button in the menu". dont know if its a twitch leecher missing feature or if i have to check something. and I'm a subscriber of that channel of course

thank you

**Comment by Franiac** [comment]
Yea, and did you do what TL said you should? 😄

`Please authorize your twitch account by clicking the twitch button in the menu`

Have you authorized your Twitch account? Or in other words clicked the button and logged in to your account? If you are not logged in TL cannot check if you are subscribed to the channel or not, that is obvious.

Hint: If you are logged in, the Twitch button turns into a check mark and becomes green.

**Comment by gioba84** [comment]
yes of course man im logged in haha... i found another way to download it but its a bit more tricky

**Comment by Franiac** [comment]
Then attach the download log please.

**Comment by gioba84** [comment]
i've made it with another software, m3u8x. with twitch leecher i can download from free acount but not from subscribed account or at least i cant with the one i'm subscribed.

**Comment by Franiac** [comment]
If you give me the download log I can look into it. Without it, I cannot help you. Maybe other users have the same issue so I recommend posting the log so I can see what's going wrong. It does not help Twitch Leecher if you use another software.

**Comment by gioba84** [comment]
oh ok sorry but how do i send you the download long..what is this. thanks for you helping me btw

**Comment by gioba84** [comment]
i will send you an email with a screen

**Comment by Franiac** [comment]
I think you don't understand correctly. You are NOT logged in in Twitch Leecher. You have to click the Twitch button in the menu bar and sign in to your account WITHIN Twitch Leecher, not the browser. If you do that the Twitch button will turn green and change to a check mark as I stated before. Your button is yellow with the Twitch icon... this way it obviously doesn't work.

**Comment by gioba84** [comment]
ahhhh noway so sorry man...now i understand. thanks a lot
