### ISSUE TITLE
Specific VOD won't download.

### ISSUE THREAD

**Issue by YumNom** [Franiac/TwitchLeecher#295]
https://www.twitch.tv/videos/284389718

Im using the latest version 1.5.3
Every other VOD on the channel seems to work fine. The download gets to about 80 percent and then gives me the red error. I've tried changing the quality, no difference. Thank you in advance if you can fix it.. thanks regardless for the application, i use it alot.

**Comment by Franiac** [comment]
Read [THIS](https://github.com/Franiac/TwitchLeecher#support--issues)

There is a hint that you should always include the download log when posting a new issue 😄

**Comment by Franiac** [comment]
Closed because stale
