### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by Romano338** [Franiac/TwitchLeecher#299]
Hi

I think the software is really cool and I don't encounter any issue. I just think it would be cool to have the ability to limit how much it takes from your internet, because it tends to takes as much as possible, and when I'm not in a hurry to download the VOD, I could need the internet to do something else at the same time ;) So being able to say "ok, Twitch Leecher you get 400kb/s, and I have the rest of my internet to do something else" would be cool.

**Comment by Franiac** [comment]
See #46
