### ISSUE TITLE
cannot authorize account

### ISSUE THREAD

**Issue by chertovhmel** [Franiac/TwitchLeecher#301]
Upon trying to authorize account for sub only VODS the following window shows after entering login info.

The website declined to show this webpage
--
HTTP  403
  | Most likely causes:  This website requires you to log in.
  | What you can try:
  | Go  back to the previous page. |   | Go  back to the previous page.
  | Go  back to the previous page.
  | More  information  This error (HTTP 403 Forbidden) means that this program  was able to connect to the website, but it does not have permission to view the  webpage. |   | More  information
  | More  information

**Comment by Franiac** [comment]
Has this been resolved? TL shows the Twitch website, there is not really anything I can do if that does not work properly.

**Comment by chertovhmel** [comment]
Unfortunately, no

**Comment by Franiac** [comment]
@chertovhmel Ahhh.... see #270
