### ISSUE TITLE
cant download this video

### ISSUE THREAD

**Issue by Timolol2012** [Franiac/TwitchLeecher#304]
https://www.twitch.tv/videos/333394627

cant download this video

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 333394627
Selected Quality: 1920x1080 (Source)
Download Url: https://www.twitch.tv/videos/333394627
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\SALAD BAKERS - Fastest Naxxramas clear in the history of Vanilla WoW - Fury_Tank4 PoV.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: F:\TL_ed22e736-4208-4c87-b1c3-585e9d39c2f8

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1542177140%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A333394627%7D
Signature: 5dd1730753a4969f156d36dfb4d498960a81d5ff
Sub-Only: No
Privileged: No

Creating temporary download directory 'F:\TL_ed22e736-4208-4c87-b1c3-585e9d39c2f8'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/highlight-333394627.m3u8
https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/720p30/highlight-333394627.m3u8
https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/480p30/highlight-333394627.m3u8
https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/audio_only/highlight-333394627.m3u8
https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/360p30/highlight-333394627.m3u8
https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/160p30/highlight-333394627.m3u8

Playlist url for selected quality 1920x1080 (Source) is https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/highlight-333394627.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 679

Starting parallel video chunk download
Number of video chunks to download: 679
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' failed! Trying again in 20s
System.Net.WebException: 远程服务器返回错误: (403) 已禁止。
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' failed! Trying again in 20s
System.Net.WebException: 远程服务器返回错误: (403) 已禁止。
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' failed! Trying again in 20s
System.Net.WebException: 远程服务器返回错误: (403) 已禁止。
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'F:\TL_ed22e736-4208-4c87-b1c3-585e9d39c2f8'... done!

Download task ended with an error!

System.AggregateException: 发生一个或多个错误。 ---> System.AggregateException: 发生一个或多个错误。 ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' after 3 retries!
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   在 TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   在 System.Threading.Tasks.Task.Execute()
   --- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) System.AggregateException: 发生一个或多个错误。 ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' after 3 retries!
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   在 TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   在 System.Threading.Tasks.Task.Execute()
---> (内部异常 #0) System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' after 3 retries!
   在 TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by Franiac** [comment]
Well...

`Downloading file 'https://vod-secure.twitch.tv/7a4a05efa7ff3aec372b_cadet_15_31154602640_1015788096/chunked/324.ts' failed! Trying again in 20s`

This can have multiple reasons:

1. Your internet died
2. The file in the playlist is actually not available (Twitch messed up)
3. The playlist is wrong (Twich messed up)
4. The 403 error code indicated permission issues -> Maybe the video is sub-only?

Eiter way, nothing I can change 😞
