### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by Daisenki** [Franiac/TwitchLeecher#305]
Everytime I start the program (TwitchLeecher_1.5.3_x64) I get a error message. The program works, but I can't fix the error message, I remove all data and reinstall it, same error, running as admin or normal doesn't change nothing too.

```
System.ArgumentException: "3,04666666666667E+16" ist kein gültiger Wert für diese Eigenschaft. Gültige Werte reichen von "Int32.MinValue" bis "Int32.MaxValue".
   bei System.Windows.Window.ValidateTopLeft(Double length)
   bei System.Windows.Window.CoerceTop(DependencyObject d, Object value)
   bei System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.Window.set_Top(Double value)
   bei TwitchLeecher.Gui.Views.MainWindow.LoadWindowState()
```

**Comment by si442** [comment]
I get very similar to this upon launching the program - 2 back to back error messages when I launch the app (been using it for 1 year or so with no problems). It's generating 2 logs each time, all the same errors.

`System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at TwitchLeecher.Services.Services.RuntimeDataService.Load()
   at TwitchLeecher.Services.Services.RuntimeDataService.get_RuntimeData()
   at TwitchLeecher.Gui.Views.MainWindow.LoadWindowState()`

**Comment by Franiac** [comment]
@Daisenki I can see what the issue is in your case. The window position gets saved on close to a xml configuration file.

`3,04666666666667E+16`

is in fact 3,0466666666666666666666666666666666666666666666666666666....... and the serializer just formats the value in exponential format. Now when this value is read again, TL runs into the problem that is cannot interpret what it has written before, d'oh. Easy fix for me, needs a new release of TL (1.5.4 in this case). I'll look into it.

Workaround for you: Delete the runtime config file at

`%appdata%\Twitch Leecher\runtime.xml`

TL will start with the default window size again. But it will run into the same problem if a periodic number occurs again.

@si442 Can you please post the contents of your

`%appdata%\Twitch Leecher\runtime.xml` configuration file?

It is not the same issue like @Daisenki has, but it could be something similar.

**Comment by Daisenki** [comment]
I delete the runtime.xml and start the program. The first run was without the error message (it makes a new runtime.xml), I close the software and run the program a second time and the error message appears again. I did not touch the window size or position on the desktop.

runtime.xml has the following information inside:

```
<?xml version="1.0" encoding="utf-8"?>
<RuntimeData Version="1.5.3">
  <Application>
    <MainWindow>
      <Width>840</Width>
      <Height>800</Height>
      <Top>304.66666666666663</Top>
      <Left>860</Left>
      <IsMaximized>false</IsMaximized>
    </MainWindow>
  </Application>
</RuntimeData>
```

**Comment by Franiac** [comment]
That's interesting, I am going to try the value from the "Top" property myself. Must be something with the amount of decimal places.

What is your screen resolution?

**Comment by Daisenki** [comment]
> 
> 
> @Daisenki That's interesting, I am going to try the value from the "Top" property myself. Must be something with the amount of decimal places.
> 
> What is your screen resolution?

I'm using 4k Display 3840x2160 with a 150% Windows scaling

**Comment by Franiac** [comment]
@Daisenki That makes sense... with the 150% scaling it is much more possible to hit those half pixels resulting in odd periodic numbers. Like I said, I look into it. A possible fix is to just round the numbers to integers. You cannot position a window on half a pixel anyway, so.....

**Comment by Franiac** [comment]
@si442 The problem is that after the error TL could not read the file and therefor did not write any new info to it. I guess we'll never know what happend in your case. But maybe the fix I am going to implement solves your problems, too. It is very likely.
