### ISSUE TITLE
FFMPEG not using all cores when merging

### ISSUE THREAD

**Issue by EpicLPer** [Franiac/TwitchLeecher#307]
I noticed that FFMPEG is not using all cores when merging the video files afterwards but only using one, yet even just half of it. FFMPEG is capable of using multi-core processing as far as I'm aware.

If you need a log anyways just tell me :)

![image](https://user-images.githubusercontent.com/8442196/48970864-0512dd00-f012-11e8-88c8-34cbf867be88.png)

**Comment by Franiac** [comment]
As you can see your CPU is at 3% and not a single core is used by nearly anything. I doubt that enabling more cores would speed up anything in this case.
Don't be mistaken here. There is no encoding/transcoding or stream manipulation going on. TL just copies the source streams of the .ts file into a mp4 container. So the limiting factor here is your HDD/SSD. Copying things does not need CPU power.
It would be a total different thing if TL actually transcoded the x264 stream to maybe divX or something. That would run on the CPU and last hours. That's when multi-core processing would make sense. But again, TL does not come up with that scenario.
