### ISSUE TITLE
Twitch Authorization Not Sending

### ISSUE THREAD

**Issue by xpknightx** [Franiac/TwitchLeecher#309]
Twitch Authorization Not Sending
Twitch Leecher Version: 1.5.3 (Tried in 1.5.4 as well, identical results)
OS: Microsoft Windows 10 Pro
Default Browser: Firefox
Other Installed Browsers: Edge, Chrome
Twitch Video ID: 101350146 (Subscriber Only)

After installing the program, and clicking Authorize Twitch Account, then clicking Connect with Twitch, the Twitch Login page is displayed (Username removed).
![login](https://user-images.githubusercontent.com/45929274/50066432-86bcdd00-0170-11e9-85f3-ab84c947f5c1.png)

After entering credentials, and clicking the "Log In" button, the "Log In" button briefly flashes to display a "Sending..." button before returning to a "Log In" button, but the program does not successfully log in.
![sending](https://user-images.githubusercontent.com/45929274/50066433-86bcdd00-0170-11e9-884b-f3f3bac1dbe8.png)

There is no issue, error, or any other indication of login success/failure.

The closest Closed Issue I was able to find related to this issue was [#84](https://github.com/Franiac/TwitchLeecher/issues/84), which seemed to have a work-around of juggling the auth token from an external browser into the runtime.xml, but this does no longer appear to work.

Thank you for your time. Please let me know if I can provide any additional information or assistance.

EDIT 1: Please note, by using the workaround method in [#84](https://github.com/Franiac/TwitchLeecher/issues/84), Twitch Leecher is successfully Connected to my Twitch Account, yet still unable to successfully Authorize via the application.
![connected](https://user-images.githubusercontent.com/45929274/50066632-ca641680-0171-11e9-9260-8901c7ae6f68.png)

**Comment by Franiac** [comment]
I cannot reproduce the issue in 1.5.3 or 1.5.4 on my end. So it could be an issue with the potentially different server you get connected to.

Try the following:

1. Open up Microsoft Edge and copy the following url into the addressbar and hit enter

`https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=37v97169hnj8kaoq8fs3hzz8v6jezdj&redirect_uri=http://www.tl.com&scope=user_subscriptions&force_verify=true`

That is the exact address TL navigates to when you see the Twitch login page.

2. Hit F12 in Edge and select the "CONSOLE" tab.
3. Enter your credentials and click "Log In"
4. See if there occures any error whatsoever in the console window

**Comment by Franiac** [comment]
Closing because stale
