### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by rrcdr** [Franiac/TwitchLeecher#314]
I get the below error when doing a channel search for `cryptotraderstv` with video type = highlight. Searching for video type = broadcast seems to work fine.

It was working totally fine until today. Could this error be caused by a new highlight video thats causing the problem. The only new video that was uploaded between yesterday when it worked and today when I got the error is this one https://www.twitch.tv/videos/364449037 however changing the date range to not include today still results in the same error. Nothing else on my end has changed. Was previously using 1.5.3 until I got this error today. Updated to latest and still getting the error.

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at TwitchLeecher.Services.Services.TwitchService.ParseVideo(JObject videoJson)
   at TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at TwitchLeecher.Services.Services.TwitchService.ParseVideo(JObject videoJson)
   at TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   at TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   at System.Threading.Tasks.Task.Execute()<--
```-

**Comment by Kalbintion** [comment]
I'm able to get the above error as well.

**TL Ver:** 1.5.8 (1.3.x previously)
**OS:** Win 7 x64 Enterprise
**Reproduction Steps:** 
_By Channel_
Search for channel name millbee, video type highlight, other options default. Upon search the error appears and is written to log.

_By Urls_
Search for URLs using the following list, and upon the search the error appears and is written to log
`https://www.twitch.tv/videos/364525421
https://www.twitch.tv/videos/364527017
https://www.twitch.tv/videos/364527463
https://www.twitch.tv/videos/365016505
https://www.twitch.tv/videos/365018013
https://www.twitch.tv/videos/365019330
https://www.twitch.tv/videos/365020036
https://www.twitch.tv/videos/365022337
https://www.twitch.tv/videos/365024541
https://www.twitch.tv/videos/365024542
https://www.twitch.tv/videos/365025567
https://www.twitch.tv/videos/365027707
https://www.twitch.tv/videos/365028777`

_By IDs_
Similar to above, however replacing the URLs with only their IDs
`364525421
364527017
364527463
365016505
365018013
365019330
365020036
365022337
365024541
365024542
365025567
365027707
365028777`

**Additional Comments**: If I ignore the final URL in that list (VOD ID 365028777) the error goes away. Unsure why exactly it goes away with that single one. Even shifting that particular URL/ID in the list around does not resolve the problem, nor does it cause the last one in the list to be the new problem. It appears to just be that single URL/ID.

**Comment by Franiac** [comment]
The last VOD has some missing values in the API response. Normally every VOD has a "published_at" value caontaining the date and time the video went online. That value is empty on the last VOD. Twitch done fucked up. I will implement a fallback so TL can still show the VOD in the result view.

**Comment by rrcdr** [comment]
How can I implement this change? Or do I have to wait for the next release?

**Comment by Franiac** [comment]
As you can see with the above commit I have already done that. Sure you need to wait for the next release. Microsoft don't send you personal bugfixes either, do they 😄 ?

**Comment by rrcdr** [comment]
Just checking. Thanks for the work on this great tool!
