### ISSUE TITLE
Error when finishing download.

### ISSUE THREAD

**Issue by twitchingaround** [Franiac/TwitchLeecher#317]
So I have tried to download this video at least 10 times. It ends the same. I have enough storage space so i know thats not the reason its failing. Help please.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 364961066
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/364961066
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Plante Laptop\Videos\Twitch videos\The Forest Session 03.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1548177025%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A364961066%7D
Signature: 48d15732171c27abc5b8e8cf0cacbb48496b3f2d
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/720p30/index-dvr.m3u8
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps (Source) is https://vod-metro.twitch.tv/6defac6046a42ca25eff_aplfisher_32214572416_1082036209/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1668

Starting parallel video chunk download
Number of video chunks to download: 1668
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171\The Forest Session 03.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171\The Forest Session 03.ts'...
Command line arguments: -y -i "C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171\The Forest Session 03.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\Plante Laptop\Videos\Twitch videos\The Forest Session 03.mp4"

ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.1 (GCC) 20180710
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
Input #0, mpegts, from 'C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171\The Forest Session 03.ts':
Duration: 05:38:45.17, start: 72.502000, bitrate: 4852 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 155 kb/s
Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720, 60 fps, 60 tbr, 90k tbn, 120 tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
C:\Users\Plante Laptop\Videos\Twitch videos\The Forest Session 03.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Plante Laptop\AppData\Local\Temp\TL_b1519848-b6fe-4b25-bffc-972db126b171'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
That's right, it's not the space:

`C:\Users\Plante Laptop\Videos\Twitch videos\The Forest Session 03.mp4: Permission denied`
