### ISSUE TITLE
Error after downloading

### ISSUE THREAD

**Issue by Lukilele** [Franiac/TwitchLeecher#318]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 369206066
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/369206066
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\Videos\20190124_369206066_World of Warcraft.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1548450967%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A369206066%7D
Signature: 0b5d76ca5c42cb85ec49c201f865a8684ebaad5b
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/2d082413d6c806954567_legendenbalu_32355551168_1090847381/chunked/highlight-369206066.m3u8
https://vod-metro.twitch.tv/2d082413d6c806954567_legendenbalu_32355551168_1090847381/audio_only/highlight-369206066.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-metro.twitch.tv/2d082413d6c806954567_legendenbalu_32355551168_1090847381/chunked/highlight-369206066.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 64

Starting parallel video chunk download
Number of video chunks to download: 64
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e\20190124_369206066_World of Warcraft.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e\20190124_369206066_World of Warcraft.ts'...
Command line arguments: -y -i "C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e\20190124_369206066_World of Warcraft.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\Videos\20190124_369206066_World of Warcraft.mp4"

ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.1 (GCC) 20180710
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
Input #0, mpegts, from 'C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e\20190124_369206066_World of Warcraft.ts':
Duration: 00:12:33.00, start: 7515.984000, bitrate: 6334 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 137 kb/s
Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, unknown/bt709/unknown, progressive), 1920x1080, 59.94 fps, 59.94 tbr, 90k tbn, 2k tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
D:\Videos\20190124_369206066_World of Warcraft.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Lukilele\AppData\Local\Temp\TL_86661290-b60d-4014-8343-54d85b54101e'... done!

Download task ended with an error!

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ApplicationException: An error occured while converting the video!
   bei TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.ApplicationException: An error occured while converting the video!
   bei TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
As the log says:

`D:\Videos\20190124_369206066_World of Warcraft.mp4: Permission denied`
