### ISSUE TITLE
Permission Denied?

### ISSUE THREAD

**Issue by twitchingaround** [Franiac/TwitchLeecher#319]
"C:\Users\Plante Laptop\Videos\Twitch videos\The Forest Session 03.mp4: Permission denied"
Does this mean my firewall is preventing videos being downloaded?

**Comment by Franiac** [comment]
No, Tl downloads the video as a .ts file into the temporary download folder (see preferences)... then it hands this file over to ffmpeg that tries to create a mp4 in the download folder....

It seems that you simply don't have write permissions on "C:\Users\Plante Laptop\Videos\Twitch videos\"
