### ISSUE TITLE
Feature Suggestion: Start download of next video while previous one is processing

### ISSUE THREAD

**Issue by EpicLPer** [Franiac/TwitchLeecher#324]
As title says. It's kinda annoying to wait for a 5 hour livestream to finish processing before a new one starts downloading, this could save quite a lot of time when downloading streams :)

**Comment by EpicLPer** [comment]
nvm I saw that apparently this is discussed about in #46 already... Sorry.

**Comment by Franiac** [comment]
So you understand that one video is actually multiple files downloaded in parallel? You wouldn't gain download speed... it is already over 9000 ;)

**Comment by EpicLPer** [comment]
> So you understand that one video is actually multiple files downloaded in parallel? You wouldn't gain download speed... it is already over 9000 ;)

No, I meant that while one video is being merged together that it should start downloading the next one.

**Comment by Franiac** [comment]
ah ok, yea.... that's something for the new DL manager for sure 😄
