### ISSUE TITLE
Feature request: Use Custom File Name Default

### ISSUE THREAD

**Issue by devnumber4** [Franiac/TwitchLeecher#325]
![screenshot 18](https://user-images.githubusercontent.com/18508845/53714528-c95f8e80-3e1c-11e9-92be-4c380c446ace.jpg)
 Is it possible to include a setting where this use custom file name checkbox is checked by default?

**Comment by devnumber4** [comment]
When I download some streams I have to rename them due to the limits of my file system I end up renaming them frequently an option to have it enabled to default would save some time for me.

**Comment by devnumber4** [comment]
Also, no I don't a blank text field I would like to have the option to change the text field enabled by default.

**Comment by Franiac** [comment]
First off, you seem to be one of a few users who use this more often. Most users don't edit the filename and go with the filename templating system.

I dislike the checkbox anyway and would prefer the textbox to be editable by default and add a simple button to reset the text to the filename template. So no checkbox anymore.

This goes onto my private todo list. I don't want to add settings for every single checkbox in the UI, that's just overkill.
