### ISSUE TITLE
Feature request: downloading chat replay too.

### ISSUE THREAD

**Issue by borouj-rashid-UOIT** [Franiac/TwitchLeecher#329]
Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by garoto** [comment]
and how is rechat supposed to be merged into the resulting video file?

**Comment by Franiac** [comment]
As @garoto says.... not possible without some really fancy next level text to video rendering engine. Since I am not Google and your PC is not a cloud server cluster for complicated rendering tasks.... won't happen

**Comment by Franiac** [comment]
And in case you mean downloading chat only as a text file..... that's not what TL was built for.

**Comment by borouj-rashid-UOIT** [comment]
as a subtitle file perhaps. since they are possibly already timestamped.
