### ISSUE TITLE
[FYI]Video downloaded broken

### ISSUE THREAD

**Issue by AlexOuO** [Franiac/TwitchLeecher#331]
OS:Windows10 64bit Home
TL version : 1.5.5 / 1.5.6
Twitch video link: https://www.twitch.tv/videos/407504081
Timestamps : 02:12:45
Video broken after that time.
However,downloading using 1.4.3 is fine.
This time it is not **connection** problem.
She was using S10+ and it's android so she can use other apps while streaming.
I guess she was trying to use google map to search the place she wanted to go.
You can tell it via watching it on twitch. The video is fine.
This time. Not **shit** in , shit out. It was normal.
If this problem can be solved , it would be great, cuz there're chances that outdoor stream got muted some part due to store playing copyrighted music and I have to download it ASAP but I can't use the newest version of TL.

BTW, I test downloading video 'that I downloaded using 1.4.3 and it's not sync on Pr CC2018' using 1.5.6 but it's still not sync in Pr. ( It's Pr problem too . Even Pr CC2019 can't handle VFR video well but Powerdirector can)
Besides, I don't know what it means " Greatly decreased the probability of getting out of sync audio in a downloaded VOD"
Videos are sync on VLC or MPC player all the time no matter which TL version I used.(Actually I only used 1.4.3 and 1.5.5)
For your information. Thanks for the great software.

**Comment by Franiac** [comment]
You are addressing 2 problems at the same time:

1. I cannot change that. And it's not the first time I told you that. I cannot repair streams ffmpeg cannot convert.

2. "it's not sync on Pr CC2018"

Premiere cannot handle Twitch streams. That is documented everywhere in the Adobe forums. People using Premiere are running the videos through Handbrake first to make it compatible. Just google "Premiere and Twitch streams". Adobe doesn't care about the problem as far as I can tell.

"Videos are sync on VLC or MPC player" <--- there you go... so the videos are actually ok, only Premiere messes it up.
