### ISSUE TITLE
Checkboxes and ctrl+click to download with default settings

### ISSUE THREAD

**Issue by Gallion** [Franiac/TwitchLeecher#332]
It would be useful to have a way to quickly download videos using default download settings without having to confirm the settings for every video. I am currently downloading a couple hundred of highlights from a channel and it's becoming very tedious to have to confirm the settings for every video. I'm thinking that using ctrl + click on the download button of a single video and using checkboxes to batch download would be a good way to achieve this.

**Comment by Franiac** [comment]
that's included in #46 automatically... but that needs time.
