### ISSUE TITLE
Feature Request - Download limiter

### ISSUE THREAD

**Issue by Daisenki** [Franiac/TwitchLeecher#338]
Hi,

please add in the next version a setting to limit the download speed. Every download runs with full speed and it's not really possible to do anything like watch a stream, load websites or play online games. I really need a setting to limit the download speed.

Thanks!

**Comment by Codereaders** [comment]
As long as this feature is being missed, you could use for example netlimiter (https://www.netlimiter.com/)
It's quite easy to use and works system wide. It's able to limit each applications inbound and outbound traffic rate.

**Comment by Franiac** [comment]
See #46
