### ISSUE TITLE
Disable autotab switching

### ISSUE THREAD

**Issue by shadeslain** [Franiac/TwitchLeecher#34]
Whenever you download a video/add it to the queue the app switches tabs to the download queue. Can we have an option to disable this? It's incredibly annoying to be downloading 5 or so broadcasts which are about halfway through a 100 vod list and have to scroll and find the next video every time(when you switch tabs it doesn't remember your position).

Either that or a way to multi-select vods and click the download button once for all of them.

Thanks,

**Comment by Franiac** [comment]
This is related to issue #23. I want to introduce an notification system. So if you add a download, a panel becomes visible for like 5 seconds telling you "Download has been added...".
The tab switiching is a relic of the initial release when I developed the tool for myself in the first place and when there was no download queue at all :)

**Comment by Franiac** [comment]
I now show the current download count in the download button text. No more automatic view switching.

**Comment by shadeslain** [comment]
Awesome, thanks. Best VOD downloader I've used next to livestreamer(this one is much easier for filenaming though).

**Comment by Franiac** [comment]
Any suggestions on how to improve filenaming in TL? I don't know livestreamer. What are you missing?

**Comment by shadeslain** [comment]
Sorry I meant TL is easier for filenaming, Some infor on livestreamer "Livestreamer is a command-line utility that pipes video streams from various services into a video player" (it can also be used to just download).

The only template wildcard that I wold use that isn't currently there is "streamer username",it would make it easier to organize if you are downloading multiple vods from separate users into the same download folder.

**Comment by Franiac** [comment]
See #40
