### ISSUE TITLE
Audio and Video Desync and a possible reason as to why

### ISSUE THREAD

**Issue by bramnet** [Franiac/TwitchLeecher#341]
Version 1.5.6
VOD url: https://www.twitch.tv/videos/421233927
Windows 10 64-bit
When downloading this 13 hour long vod, there is an audio delay that became noticeable to me around 6 and a half hours in. I've downloaded this vod 3 times to verify it isn't just an issue with the first download and I've watched the vod back on twitch to confirm it's only an issue with the downloaded copies. My best guess as to a possible cause was that there was a disconnect within that first 6 hours and said channel was using the new Disconnect Protection setting on twitch which shows a temporary "disconnected" image for 90 seconds when an unexpected disconnect occurs to allow for a smoother reload when they get back online.
Log:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 421233927
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/421233927
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: G:\TRG Colosseum\20190506_421233927_Super Smash Bros. Ultimate.mp4
FFMPEG Path: E:\Programs\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Bram\AppData\Local\Temp\TL_9c8d313d-c2c9-4737-a7cb-3f850c4da09f

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1558282178%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A421233927%7D
Signature: 1a4469dc84dcbf628efe6dfe47ac702e91f827e0
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Bram\AppData\Local\Temp\TL_9c8d313d-c2c9-4737-a7cb-3f850c4da09f'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/720p30/index-dvr.m3u8
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-metro.twitch.tv/1dd58a122eb2d9ec7a76_protonjon_34012187680_1194419233/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 4709

Starting parallel video chunk download
Number of video chunks to download: 4709
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Bram\AppData\Local\Temp\TL_9c8d313d-c2c9-4737-a7cb-3f850c4da09f\20190506_421233927_Super Smash Bros. Ultimate.ts'...

Executing 'E:\Programs\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\Bram\AppData\Local\Temp\TL_9c8d313d-c2c9-4737-a7cb-3f850c4da09f\20190506_421233927_Super Smash Bros. Ultimate.ts'...
Command line arguments: -y -i "C:\Users\Bram\AppData\Local\Temp\TL_9c8d313d-c2c9-4737-a7cb-3f850c4da09f\20190506_421233927_Super Smash Bros. Ultimate.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc "G:\TRG Colosseum\20190506_421233927_Super Smash Bros. Ultimate.mp4"

Video conversion complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Bram\AppData\Local\Temp\TL_9c8d313d-c2c9-4737-a7cb-3f850c4da09f'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
I cannot fix disconnects or A/V Desync caused by an unstable stream or bad internet connection of the streamer. I have to deal with the sources I get from Twitch. If those sources are not compatible to FFMPEG due to frame drops and such, it is how it is.

My advice is: Don't download 13 hour long VODs. Crop it to several parts, leaving out the "bad parts" and see if that fixes something. A function to auto-split a VOD in a given number of chunks will be there soon.
