### ISSUE TITLE
support for download of incomplete vods

### ISSUE THREAD

**Issue by AbIntra** [Franiac/TwitchLeecher#342]
Currently when I try to download a vod that is not yet complete (streamer is still live) the download stops when it catches up with the stream. It looks like #46 could potentially be a partial solution if it allows me to rate limit the download so that it doesn't overtake the live broadcast. However I'm hoping for a more elegant solution, like automatic detection or a checkbox in the video download options menu.

**Comment by Franiac** [comment]
TL is not meant to download ongoing streams and probably never will.
