### ISSUE TITLE
Errror After Downloading; Tried Different Resolutions & FPS

### ISSUE THREAD

**Issue by Bananasaurus** [Franiac/TwitchLeecher#343]
I downloaded a 3 hour video and a 3.5 hour video just fine, but when tried to download an 8 hour stream (I have plenty of room, I have an SSD) it didn't work. I tried downloading it in smaller parts - also didn't work.
So I tried re-downloading the other streams as both their source resolution/FPS, and a lower resolution/FPS because I thought maybe the download time was causing a timeout. Here's the 8 hour stream that was originally 1920 x 1080@60 FPS. I tried it at half resolution and 60 FPS, and now this, half resolution and half FPS.

Please don't just quote "here is the line that is causing the issue," please tell me how to fix it. I'm basically code/computer-illiterate

`Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 432580276
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/432580276
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1559531366%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A432580276%7D
Signature: c122056961aea5f9d15ce04ea302806497136b48
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p30/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@30fps is https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p30/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2936

Starting parallel video chunk download
Number of video chunks to download: 2936
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts'...
Command line arguments: -y -i "C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc "C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4"

ffmpeg version N-93529-g8e3b01e20e Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20190212
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 26.100 / 56. 26.100
libavcodec     58. 48.101 / 58. 48.101
libavformat    58. 26.101 / 58. 26.101
libavdevice    58.  7.100 / 58.  7.100
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
Input #0, mpegts, from 'C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts':
Duration: 08:09:12.58, start: 66.006000, bitrate: 2206 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 4 kb/s
Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720, 30 fps, 30 tbr, 90k tbn, 2k tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\AFedo\AppData\Local\Temp\TL_32b0edc9-4c5f-4389-ab71-c40475bb0ffb'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
`

**Comment by Bananasaurus** [comment]
I tried to download the entire 8 hour stream again in full resolution and it downloaded just fine, was combining files just fine, then abruptly ran into this issue again:

`Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 432580276
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/432580276
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1559533937%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A432580276%7D
Signature: 8a1734dbd7207ae5a6a30ea0f8b87cb72943f20d
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p30/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-metro.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2936

Starting parallel video chunk download
Number of video chunks to download: 2936
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts'...
Command line arguments: -y -i "C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc "C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4"

ffmpeg version N-93529-g8e3b01e20e Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20190212
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 26.100 / 56. 26.100
libavcodec     58. 48.101 / 58. 48.101
libavformat    58. 26.101 / 58. 26.101
libavdevice    58.  7.100 / 58.  7.100
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
Input #0, mpegts, from 'C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.ts':
Duration: 08:09:13.02, start: 66.006000, bitrate: 6373 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 4 kb/s
Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080, 60 fps, 60 tbr, 90k tbn, 120 tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\AFedo\AppData\Local\Temp\TL_0ce8522c-8b20-4009-b1f4-4a7c98ddf800'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
`

**Comment by Bananasaurus** [comment]
And neither did partial download of half-resolution and half-FPS didn't work:
`Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 432580276
Selected Quality: 1280x720@30fps
Download Url: https://www.twitch.tv/videos/432580276
Crop Start: Yes (00:00:00)
Crop End: Yes (02:00:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1559538828%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A432580276%7D
Signature: c823c010ee68d000eea3d2ef2f254f881b231d0d
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p60/index-dvr.m3u8
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p30/index-dvr.m3u8
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/480p30/index-dvr.m3u8
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/audio_only/index-dvr.m3u8
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/360p30/index-dvr.m3u8
https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@30fps is https://vod-secure.twitch.tv/a80807b2dadab6c03f9e_minion777_34350464496_1215567393/720p30/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2936

Starting parallel video chunk download
Number of video chunks to download: 720
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.ts'...
Command line arguments: -y -ss 0 -i "C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc -t 7200 "C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.mp4"

ffmpeg version N-93529-g8e3b01e20e Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20190212
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 26.100 / 56. 26.100
libavcodec     58. 48.101 / 58. 48.101
libavformat    58. 26.101 / 58. 26.101
libavdevice    58.  7.100 / 58.  7.100
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
Input #0, mpegts, from 'C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.ts':
Duration: 02:00:00.03, start: 66.006000, bitrate: 2204 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 4 kb/s
Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720, 30 fps, 30 tbr, 90k tbn, 2k tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1.1 with Uno, Sorry, and More HALF RESOLUTION AND FPS.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\AFedo\AppData\Local\Temp\TL_0180922f-655e-4a15-8219-66f38da749ea'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
`

**Comment by Bananasaurus** [comment]
accidentally closed issue

**Comment by Franiac** [comment]
The only thing that is reocurring in every attemp you do is the following line:
```
C:\Users\AFedo\Videos\Wade Lordminion777 May 31st Stream Part 1 with Uno, Sorry, and More.mp4: Permission denied
```
This is a pretty clear error message. Why you don't have permission... I don't know since I don't know your computer. This is nothing Twitch Leecher decides. Windows tells ffmpeg that it cannot convert the video with the given output directory.
