### ISSUE TITLE
Feature Request: Download progress speed

### ISSUE THREAD

**Issue by atward** [Franiac/TwitchLeecher#344]
As part of the download progress view when status is "Downloading" provide additional information about speed of download (bytes/s).

Information could be presented as part of the progress bar. Inspiration can be taken from common web browsers 'downloads' page about what information users typically desire.

**Comment by atward** [comment]
I'm not good enough with C#, but should be achievable using callback on WebClient if the DownloadData is changed to DownloadDataAsync. This should give fine grained updates, but would require refactor of parallel logic

```
downloadClient.DownloadProgressChanged += new DownloadProgressChangedEventHandler(setProgressCallback);
```

Otherwise summary could be course grained and done at the part level, aggregated at bytes.Length / duration and updated after each part completes

**Comment by Franiac** [comment]
I will not enhance the current (shitty) download manager with features that #46 will solve anyway. Just be a little more patient and we get all the good stuff a state of the art download manager provides.
