### ISSUE TITLE
Keep getting download errors

### ISSUE THREAD

**Issue by uaxiii** [Franiac/TwitchLeecher#346]
Every time I try to download a VOD I get an immediate error.
This is the download log:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 439693760
Selected Quality: 1920x1080@30fps (Source)
Download Url: https://www.twitch.tv/videos/439693760
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\epstein_2\Downloads\20190615_439693760_Path of Exile.mp4
FFMPEG Path: C:\Users\epstein_2\Downloads\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\epstein_2\Downloads\1Twitch\TL_d3c420dd-cab0-4a2d-b4ab-d81a4a9099c0

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561710293%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A439693760%7D
Signature: eede54fc2f9f3ca7dadc4d0f927c19072d70443b
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\epstein_2\Downloads\1Twitch\TL_d3c420dd-cab0-4a2d-b4ab-d81a4a9099c0'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\epstein_2\Downloads\1Twitch\TL_d3c420dd-cab0-4a2d-b4ab-d81a4a9099c0'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

Is there any way for me to fix it? I get this with every vod.

**Comment by garoto** [comment]
Working for me:
```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 439693760
Selected Quality: 1920x1080@30fps (Source)
Download Url: https://www.twitch.tv/videos/439693760
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: F:\Videos\downloading\LSC - Getting caught up_20190615_rbFrosty-v439693760.mp4
FFMPEG Path: C:\Apps\Diversos\TwitchLeecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\redacted\AppData\Local\Temp\TL_0bf108e7-6f08-4e65-8d91-f35b8b81eafd

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561727778%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A439693760%7D
Signature: 146ff5ef308daf67f07d892b5fff2a72cd45c5e4
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\redacted\AppData\Local\Temp\TL_0bf108e7-6f08-4e65-8d91-f35b8b81eafd'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/chunked/index-muted-KNGSGERAW0.m3u8
https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/720p30/index-muted-KNGSGERAW0.m3u8
https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/480p30/index-muted-KNGSGERAW0.m3u8
https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/audio_only/index-muted-KNGSGERAW0.m3u8
https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/360p30/index-muted-KNGSGERAW0.m3u8
https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/160p30/index-muted-KNGSGERAW0.m3u8

Playlist url for selected quality 1920x1080@30fps (Source) is https://vod-secure.twitch.tv/951fd62dacca6de48863_rbfrosty_34548082976_1227920152/chunked/index-muted-KNGSGERAW0.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1417

Starting parallel video chunk download
Number of video chunks to download: 1417
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\redacted\AppData\Local\Temp\TL_0bf108e7-6f08-4e65-8d91-f35b8b81eafd'... done!

Download task was canceled!
```

**Comment by uaxiii** [comment]
Do you probably know why I'm getting an error?

**Comment by garoto** [comment]
No idea really. All I know is twitch uses a global CDN network to deliver its contents, for both livestreams and VODs, and which CDN one gets to use is determined by a geolocation aware DNS resolver, so switching DNSs around might be a solution perhaps? I guess? Or it might be an OS thing involving the whole .NET ecosystem? (I'm on Windows 8.1 and not up-to-date).

Very hard for me to troubleshoot. Hopefully @Franiac can offer some more valuable insight in to this.

**Comment by uaxiii** [comment]
I un- and reinstalled it and it was working again for while, but now its doing the same thing again. I tried doing the same thing, but now it just keeps giving the error. So I don't know what it is, maybe it's just something I have to wait out?
