### ISSUE TITLE
Download subscriber-only VODs

### ISSUE THREAD

**Issue by SDraconis** [Franiac/TwitchLeecher#35]
This is a request to re-open #8 . This is currently my only use-case for a Twitch downloader (i.e. the only VODs I wish to download are subscriber-only on channels for which I am a subscriber).

**Comment by Franiac** [comment]
I'd like to support this, but first I want to get rid of some relics in the code and implement a few other features that are more important. But since this is the 2nd request I'll leave this issue open.

**Comment by Franiac** [comment]
Duplicate of #8
