### ISSUE TITLE
Audio not downloading with some VOD

### ISSUE THREAD

**Issue by jasonzuzio** [Franiac/TwitchLeecher#358]
attempted to Download https://www.twitch.tv/videos/445727682 (and others by the same uploader) and result when finished is a file with no audio stream. Log from the download:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 445727682
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/445727682
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\20190629_445727682_The Legend of Zelda_ Breath of the Wild.mp4
FFMPEG Path: C:\TwitchLeecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Temp\AppData\Local\Temp\TL_cf893fe6-adca-4a23-8da5-a4cf29700d34

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562535051%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A445727682%7D
Signature: 5d18b0d1859e06d5763b6a69946a0134baf3c406
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Temp\AppData\Local\Temp\TL_cf893fe6-adca-4a23-8da5-a4cf29700d34'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/720p30/index-dvr.m3u8
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-metro.twitch.tv/2309b5999da0b2214acf_gamesdonequick_34711101184_1238111029/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 9423

Starting parallel video chunk download
Number of video chunks to download: 9423
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Temp\AppData\Local\Temp\TL_cf893fe6-adca-4a23-8da5-a4cf29700d34\20190629_445727682_The Legend of Zelda_ Breath of the Wild.ts'...

Executing 'C:\TwitchLeecher\ffmpeg_x64.exe' on 'C:\Users\Temp\AppData\Local\Temp\TL_cf893fe6-adca-4a23-8da5-a4cf29700d34\20190629_445727682_The Legend of Zelda_ Breath of the Wild.ts'...
Command line arguments: -y -i "C:\Users\Temp\AppData\Local\Temp\TL_cf893fe6-adca-4a23-8da5-a4cf29700d34\20190629_445727682_The Legend of Zelda_ Breath of the Wild.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc "D:\20190629_445727682_The Legend of Zelda_ Breath of the Wild.mp4"

Video conversion complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Temp\AppData\Local\Temp\TL_cf893fe6-adca-4a23-8da5-a4cf29700d34'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
Try cropping a very long video into several parts. downloading a 26 hour VOD in one piece is a very bad idea. I tried 4 hour pieces and audio is always fine.

**Comment by jasonzuzio** [comment]
Is there a way to batch-break a download if this is necessary to do? Is there any specific max size/length that would be OK to download?

Thanks

**Comment by Franiac** [comment]
There is a pull request open that is able to cut a VOD into a given amount of pieces.

There is no specific max length in order to grab this issue. But the 10 hour mark is a good indicator.
