### ISSUE TITLE
VODs encounter error after downloading.

### ISSUE THREAD

**Issue by GourdWhisperer** [Franiac/TwitchLeecher#359]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 442536273
Selected Quality: 1920x1080@30fps (Source)
Download Url: https://www.twitch.tv/videos/442536273
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: D:\LA by Night\S03E04 - Swimming with the Sharks.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\ME\AppData\Local\Temp\TL_2a5fd7cc-548d-4f3c-825a-3ae5152c0bfd

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562568378%2C%22https_required%22%3Afalse%2C%22privileged%22%3Atrue%2C%22user_id%22%3A159432531%2C%22version%22%3A2%2C%22vod_id%22%3A442536273%7D
Signature: 8e755653fb0661249c8144d3afaf36258e05a886
Sub-Only: Yes
Privileged: Yes

Creating temporary download directory 'C:\Users\ME\AppData\Local\Temp\TL_2a5fd7cc-548d-4f3c-825a-3ae5152c0bfd'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/chunked/highlight-442536273.m3u8
https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/720p30/highlight-442536273.m3u8
https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/480p30/highlight-442536273.m3u8
https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/audio_only/highlight-442536273.m3u8
https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/360p30/highlight-442536273.m3u8
https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/160p30/highlight-442536273.m3u8

Playlist url for selected quality 1920x1080@30fps (Source) is https://vod-secure.twitch.tv/6002e217093b77620428_geekandsundry_57127635930_5950756591/chunked/highlight-442536273.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1072

Starting parallel video chunk download
Number of video chunks to download: 1072
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\ME\AppData\Local\Temp\TL_2a5fd7cc-548d-4f3c-825a-3ae5152c0bfd\S03E04 - Swimming with the Sharks.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\ME\AppData\Local\Temp\TL_2a5fd7cc-548d-4f3c-825a-3ae5152c0bfd\S03E04 - Swimming with the Sharks.ts'...
Command line arguments: -y -i "C:\Users\ME\AppData\Local\Temp\TL_2a5fd7cc-548d-4f3c-825a-3ae5152c0bfd\S03E04 - Swimming with the Sharks.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc "D:\LA by Night\S03E04 - Swimming with the Sharks.mp4"

frame=142237 fps=1014 q=-1.0 size= 2393600kB time=01:19:05.98 bitrate=4131.6kbits/s speed=33.8x
frame=142839 fps=1015 q=-1.0 size= 2403840kB time=01:19:26.05 bitrate=4131.8kbits/s speed=33.9x
frame=143426 fps=1015 q=-1.0 size= 2413568kB time=01:19:45.60 bitrate=4131.6kbits/s speed=33.9x
frame=144004 fps=1016 q=-1.0 size= 2423296kB time=01:20:04.92 bitrate=4131.5kbits/s speed=33.9x
frame=144594 fps=1016 q=-1.0 size= 2433280kB time=01:20:24.57 bitrate=4131.6kbits/s speed=33.9x
frame=145152 fps=1017 q=-1.0 size= 2442496kB time=01:20:43.20 bitrate=4131.3kbits/s speed=33.9x
frame=145654 fps=1017 q=-1.0 size= 2450944kB time=01:20:59.98 bitrate=4131.3kbits/s speed=33.9x
frame=146135 fps=1016 q=-1.0 size= 2459136kB time=01:21:16.09 bitrate=4131.4kbits/s speed=33.9x
frame=146684 fps=1017 q=-1.0 size= 2468352kB time=01:21:34.35 bitrate=4131.4kbits/s speed=33.9x
frame=147119 fps=1016 q=-1.0 size= 2475776kB time=01:21:48.82 bitrate=4131.7kbits/s speed=33.9x
frame=147611 fps=1016 q=-1.0 size= 2483968kB time=01:22:05.29 bitrate=4131.5kbits/s speed=33.9x
frame=148138 fps=1016 q=-1.0 size= 2492672kB time=01:22:22.82 bitrate=4131.2kbits/s speed=33.9x
frame=148605 fps=1016 q=-1.0 size= 2500864kB time=01:22:38.42 bitrate=4131.8kbits/s speed=33.9x
frame=148984 fps=1015 q=-1.0 size= 2507008kB time=01:22:51.05 bitrate=4131.4kbits/s speed=33.9x
frame=149542 fps=1015 q=-1.0 size= 2516480kB time=01:23:09.67 bitrate=4131.5kbits/s speed=33.9x
frame=150097 fps=1016 q=-1.0 size= 2525696kB time=01:23:28.25 bitrate=4131.3kbits/s speed=33.9x
frame=150684 fps=1016 q=-1.0 size= 2535680kB time=01:23:47.81 bitrate=4131.5kbits/s speed=33.9x
frame=151260 fps=1017 q=-1.0 size= 2545408kB time=01:24:07.04 bitrate=4131.5kbits/s speed=33.9x
frame=151831 fps=1017 q=-1.0 size= 2554880kB time=01:24:26.09 bitrate=4131.3kbits/s speed=33.9x
frame=152414 fps=1018 q=-1.0 size= 2564608kB time=01:24:45.50 bitrate=4131.2kbits/s speed=  34x
frame=152988 fps=1018 q=-1.0 size= 2574592kB time=01:25:04.66 bitrate=4131.7kbits/s speed=  34x
frame=153561 fps=1018 q=-1.0 size= 2584064kB time=01:25:23.81 bitrate=4131.4kbits/s speed=  34x
frame=154121 fps=1019 q=-1.0 size= 2593536kB time=01:25:42.50 bitrate=4131.5kbits/s speed=  34x
frame=154597 fps=1018 q=-1.0 size= 2601472kB time=01:25:58.40 bitrate=4131.4kbits/s speed=  34x
frame=155045 fps=1018 q=-1.0 size= 2608896kB time=01:26:13.33 bitrate=4131.2kbits/s speed=  34x
frame=155483 fps=1018 q=-1.0 size= 2616320kB time=01:26:27.94 bitrate=4131.3kbits/s speed=  34x
frame=155910 fps=1017 q=-1.0 size= 2623488kB time=01:26:42.15 bitrate=4131.3kbits/s speed=33.9x
frame=156426 fps=1017 q=-1.0 size= 2632192kB time=01:26:59.41 bitrate=4131.3kbits/s speed=33.9x
frame=156931 fps=1017 q=-1.0 size= 2640640kB time=01:27:16.26 bitrate=4131.2kbits/s speed=33.9x
frame=157490 fps=1017 q=-1.0 size= 2650112kB time=01:27:34.91 bitrate=4131.3kbits/s speed=33.9x
frame=158032 fps=1018 q=-1.0 size= 2659328kB time=01:27:53.00 bitrate=4131.5kbits/s speed=  34x
frame=158569 fps=1018 q=-1.0 size= 2668288kB time=01:28:10.92 bitrate=4131.3kbits/s speed=  34x
frame=159146 fps=1018 q=-1.0 size= 2678016kB time=01:28:30.12 bitrate=4131.4kbits/s speed=  34x
frame=159706 fps=1018 q=-1.0 size= 2687488kB time=01:28:48.81 bitrate=4131.5kbits/s speed=  34x
frame=160294 fps=1019 q=-1.0 size= 2697216kB time=01:29:08.43 bitrate=4131.2kbits/s speed=  34x
frame=160842 fps=1019 q=-1.0 size= 2706688kB time=01:29:26.76 bitrate=4131.6kbits/s speed=  34x
frame=161416 fps=1020 q=-1.0 size= 2716160kB time=01:29:45.87 bitrate=4131.3kbits/s speed=  34x
frame=161984 fps=1020 q=-1.0 size= 2725888kB time=01:30:04.82 bitrate=4131.6kbits/s speed=  34x
frame=162533 fps=1020 q=-1.0 size= 2735104kB time=01:30:23.14 bitrate=4131.5kbits/s speed=  34x
frame=163073 fps=1020 q=-1.0 size= 2744064kB time=01:30:41.15 bitrate=4131.4kbits/s speed=  34x
frame=163656 fps=1021 q=-1.0 size= 2753792kB time=01:31:00.67 bitrate=4131.2kbits/s speed=34.1x
frame=164220 fps=1021 q=-1.0 size= 2763520kB time=01:31:19.42 bitrate=4131.6kbits/s speed=34.1x
frame=164716 fps=1021 q=-1.0 size= 2771712kB time=01:31:36.02 bitrate=4131.3kbits/s speed=34.1x
frame=165264 fps=1021 q=-1.0 size= 2780928kB time=01:31:54.26 bitrate=4131.4kbits/s speed=34.1x
frame=165843 fps=1022 q=-1.0 size= 2790656kB time=01:32:13.58 bitrate=4131.3kbits/s speed=34.1x
frame=166361 fps=1022 q=-1.0 size= 2799616kB time=01:32:30.91 bitrate=4131.7kbits/s speed=34.1x
frame=166939 fps=1022 q=-1.0 size= 2809088kB time=01:32:50.15 bitrate=4131.3kbits/s speed=34.1x
frame=167513 fps=1023 q=-1.0 size= 2818816kB time=01:33:09.33 bitrate=4131.4kbits/s speed=34.1x
frame=168097 fps=1023 q=-1.0 size= 2828544kB time=01:33:28.85 bitrate=4131.2kbits/s speed=34.1x
frame=168599 fps=1023 q=-1.0 size= 2836992kB time=01:33:45.55 bitrate=4131.3kbits/s speed=34.1x
frame=169093 fps=1023 q=-1.0 size= 2845184kB time=01:34:02.02 bitrate=4131.1kbits/s speed=34.1x
frame=169621 fps=1023 q=-1.0 size= 2854144kB time=01:34:19.64 bitrate=4131.2kbits/s speed=34.1x
frame=170159 fps=1023 q=-1.0 size= 2863360kB time=01:34:37.63 bitrate=4131.4kbits/s speed=34.1x
frame=170737 fps=1023 q=-1.0 size= 2872832kB time=01:34:56.93 bitrate=4131.0kbits/s speed=34.1x
frame=171298 fps=1024 q=-1.0 size= 2882560kB time=01:35:15.64 bitrate=4131.5kbits/s speed=34.2x
frame=171875 fps=1024 q=-1.0 size= 2892032kB time=01:35:34.84 bitrate=4131.2kbits/s speed=34.2x
frame=172443 fps=1024 q=-1.0 size= 2901760kB time=01:35:53.81 bitrate=4131.4kbits/s speed=34.2x
frame=173006 fps=1025 q=-1.0 size= 2911232kB time=01:36:12.58 bitrate=4131.4kbits/s speed=34.2x
frame=173559 fps=1025 q=-1.0 size= 2920704kB time=01:36:31.04 bitrate=4131.6kbits/s speed=34.2x
frame=174119 fps=1025 q=-1.0 size= 2929920kB time=01:36:49.72 bitrate=4131.3kbits/s speed=34.2x
frame=174688 fps=1025 q=-1.0 size= 2939392kB time=01:37:08.71 bitrate=4131.2kbits/s speed=34.2x
frame=175271 fps=1026 q=-1.0 size= 2949120kB time=01:37:28.21 bitrate=4131.0kbits/s speed=34.2x
frame=175841 fps=1026 q=-1.0 size= 2958848kB time=01:37:47.22 bitrate=4131.2kbits/s speed=34.2x
frame=176398 fps=1026 q=-1.0 size= 2968320kB time=01:38:05.78 bitrate=4131.4kbits/s speed=34.2x
frame=176965 fps=1027 q=-1.0 size= 2977792kB time=01:38:24.70 bitrate=4131.3kbits/s speed=34.3x
frame=177542 fps=1027 q=-1.0 size= 2987520kB time=01:38:43.94 bitrate=4131.3kbits/s speed=34.3x
frame=178114 fps=1027 q=-1.0 size= 2996992kB time=01:39:03.04 bitrate=4131.1kbits/s speed=34.3x
frame=178684 fps=1028 q=-1.0 size= 3006720kB time=01:39:22.04 bitrate=4131.3kbits/s speed=34.3x
frame=179236 fps=1028 q=-1.0 size= 3015936kB time=01:39:40.45 bitrate=4131.2kbits/s speed=34.3x
frame=179814 fps=1028 q=-1.0 size= 3025664kB time=01:39:59.78 bitrate=4131.2kbits/s speed=34.3x
frame=180393 fps=1029 q=-1.0 size= 3035392kB time=01:40:19.11 bitrate=4131.2kbits/s speed=34.3x
frame=180957 fps=1029 q=-1.0 size= 3044864kB time=01:40:37.93 bitrate=4131.1kbits/s speed=34.3x
frame=181535 fps=1029 q=-1.0 size= 3054592kB time=01:40:57.19 bitrate=4131.2kbits/s speed=34.3x
frame=182111 fps=1030 q=-1.0 size= 3064320kB time=01:41:16.43 bitrate=4131.2kbits/s speed=34.4x
frame=182710 fps=1030 q=-1.0 size= 3074304kB time=01:41:36.42 bitrate=4131.1kbits/s speed=34.4x
frame=183288 fps=1030 q=-1.0 size= 3084288kB time=01:41:55.71 bitrate=4131.4kbits/s speed=34.4x
frame=183868 fps=1031 q=-1.0 size= 3093760kB time=01:42:15.06 bitrate=4131.0kbits/s speed=34.4x
frame=184452 fps=1031 q=-1.0 size= 3103744kB time=01:42:34.51 bitrate=4131.3kbits/s speed=34.4x
frame=185045 fps=1032 q=-1.0 size= 3113728kB time=01:42:54.33 bitrate=4131.2kbits/s speed=34.4x
frame=185643 fps=1032 q=-1.0 size= 3123712kB time=01:43:14.24 bitrate=4131.2kbits/s speed=34.4x
frame=186146 fps=1032 q=-1.0 size= 3132160kB time=01:43:31.02 bitrate=4131.1kbits/s speed=34.4x
frame=186628 fps=1032 q=-1.0 size= 3140352kB time=01:43:47.15 bitrate=4131.2kbits/s speed=34.4x
frame=187164 fps=1032 q=-1.0 size= 3149312kB time=01:44:05.03 bitrate=4131.1kbits/s speed=34.4x
frame=187703 fps=1032 q=-1.0 size= 3158272kB time=01:44:23.01 bitrate=4131.0kbits/s speed=34.4x
frame=188271 fps=1032 q=-1.0 size= 3168000kB time=01:44:41.94 bitrate=4131.2kbits/s speed=34.4x
frame=188841 fps=1033 q=-1.0 size= 3177472kB time=01:45:00.97 bitrate=4131.1kbits/s speed=34.5x
frame=189422 fps=1033 q=-1.0 size= 3187200kB time=01:45:20.34 bitrate=4131.0kbits/s speed=34.5x
frame=189968 fps=1033 q=-1.0 size= 3196416kB time=01:45:38.60 bitrate=4131.0kbits/s speed=34.5x
frame=190502 fps=1033 q=-1.0 size= 3205376kB time=01:45:56.41 bitrate=4131.0kbits/s speed=34.5x
frame=191057 fps=1033 q=-1.0 size= 3214848kB time=01:46:14.93 bitrate=4131.2kbits/s speed=34.5x
frame=191624 fps=1034 q=-1.0 size= 3224576kB time=01:46:33.81 bitrate=4131.5kbits/s speed=34.5x
frame=192187 fps=1034 q=-1.0 size= 3233792kB time=01:46:52.60 bitrate=4131.1kbits/s speed=34.5x
frame=192761 fps=1034 q=-1.0 size= 3243776kB time=01:47:11.74 bitrate=4131.5kbits/s speed=34.5x
frame=193337 fps=1035 q=-1.0 size= 3253248kB time=01:47:31.00 bitrate=4131.2kbits/s speed=34.5x
frame=193903 fps=1035 q=-1.0 size= 3262976kB time=01:47:49.86 bitrate=4131.5kbits/s speed=34.5x
frame=194475 fps=1035 q=-1.0 size= 3272192kB time=01:48:08.93 bitrate=4131.0kbits/s speed=34.5x
frame=195044 fps=1035 q=-1.0 size= 3282176kB time=01:48:27.96 bitrate=4131.5kbits/s speed=34.5x
frame=195615 fps=1036 q=-1.0 size= 3291392kB time=01:48:47.01 bitrate=4131.0kbits/s speed=34.6x
frame=196186 fps=1036 q=-1.0 size= 3301376kB time=01:49:06.02 bitrate=4131.5kbits/s speed=34.6x
frame=196763 fps=1036 q=-1.0 size= 3310848kB time=01:49:25.29 bitrate=4131.2kbits/s speed=34.6x
frame=197336 fps=1036 q=-1.0 size= 3320576kB time=01:49:44.40 bitrate=4131.3kbits/s speed=34.6x
frame=197921 fps=1037 q=-1.0 size= 3330560kB time=01:50:03.92 bitrate=4131.5kbits/s speed=34.6x
frame=198514 fps=1037 q=-1.0 size= 3340288kB time=01:50:23.70 bitrate=4131.2kbits/s speed=34.6x
frame=199083 fps=1037 q=-1.0 size= 3349760kB time=01:50:42.73 bitrate=4131.0kbits/s speed=34.6x
frame=199673 fps=1038 q=-1.0 size= 3359744kB time=01:51:02.42 bitrate=4131.1kbits/s speed=34.6x
frame=200190 fps=1038 q=-1.0 size= 3368448kB time=01:51:19.63 bitrate=4131.1kbits/s speed=34.6x
frame=200773 fps=1038 q=-1.0 size= 3378176kB time=01:51:39.09 bitrate=4131.0kbits/s speed=34.6x
frame=201343 fps=1038 q=-1.0 size= 3387904kB time=01:51:58.10 bitrate=4131.2kbits/s speed=34.6x
frame=201925 fps=1039 q=-1.0 size= 3397632kB time=01:52:17.55 bitrate=4131.1kbits/s speed=34.7x
frame=202477 fps=1039 q=-1.0 size= 3406848kB time=01:52:35.98 bitrate=4131.0kbits/s speed=34.7x
frame=203056 fps=1039 q=-1.0 size= 3416576kB time=01:52:55.25 bitrate=4131.0kbits/s speed=34.7x
frame=203638 fps=1039 q=-1.0 size= 3426560kB time=01:53:14.68 bitrate=4131.2kbits/s speed=34.7x
frame=204191 fps=1040 q=-1.0 size= 3435776kB time=01:53:33.14 bitrate=4131.1kbits/s speed=34.7x
frame=204760 fps=1040 q=-1.0 size= 3445504kB time=01:53:52.12 bitrate=4131.3kbits/s speed=34.7x
frame=205328 fps=1040 q=-1.0 size= 3454976kB time=01:54:11.11 bitrate=4131.2kbits/s speed=34.7x
frame=205889 fps=1040 q=-1.0 size= 3464192kB time=01:54:29.78 bitrate=4130.9kbits/s speed=34.7x
frame=206468 fps=1041 q=-1.0 size= 3474176kB time=01:54:49.15 bitrate=4131.2kbits/s speed=34.7x
frame=207037 fps=1041 q=-1.0 size= 3483648kB time=01:55:08.16 bitrate=4131.1kbits/s speed=34.7x
frame=207507 fps=1041 q=-1.0 size= 3491584kB time=01:55:23.81 bitrate=4131.1kbits/s speed=34.7x
frame=207968 fps=1040 q=-1.0 size= 3499264kB time=01:55:39.15 bitrate=4131.0kbits/s speed=34.7x
frame=208560 fps=1041 q=-1.0 size= 3509248kB time=01:55:58.91 bitrate=4131.1kbits/s speed=34.7x
frame=209149 fps=1041 q=-1.0 size= 3519232kB time=01:56:18.60 bitrate=4131.1kbits/s speed=34.7x
frame=209725 fps=1041 q=-1.0 size= 3528960kB time=01:56:37.82 bitrate=4131.2kbits/s speed=34.7x
frame=210298 fps=1042 q=-1.0 size= 3538432kB time=01:56:56.93 bitrate=4131.0kbits/s speed=34.8x
frame=210877 fps=1042 q=-1.0 size= 3548160kB time=01:57:16.28 bitrate=4130.9kbits/s speed=34.8x
frame=211459 fps=1042 q=-1.0 size= 3557888kB time=01:57:35.63 bitrate=4130.9kbits/s speed=34.8x
frame=212013 fps=1042 q=-1.0 size= 3567360kB time=01:57:54.13 bitrate=4131.1kbits/s speed=34.8x
frame=212595 fps=1043 q=-1.0 size= 3577088kB time=01:58:13.58 bitrate=4131.0kbits/s speed=34.8x
frame=213179 fps=1043 q=-1.0 size= 3587072kB time=01:58:33.06 bitrate=4131.2kbits/s speed=34.8x
frame=213763 fps=1043 q=-1.0 size= 3597056kB time=01:58:52.52 bitrate=4131.4kbits/s speed=34.8x
frame=214279 fps=1043 q=-1.0 size= 3605504kB time=01:59:09.73 bitrate=4131.1kbits/s speed=34.8x
frame=214773 fps=1043 q=-1.0 size= 3613696kB time=01:59:26.22 bitrate=4131.0kbits/s speed=34.8x
frame=215143 fps=1042 q=-1.0 size= 3620096kB time=01:59:38.56 bitrate=4131.2kbits/s speed=34.8x
frame=215673 fps=1042 q=-1.0 size= 3628800kB time=01:59:56.28 bitrate=4130.9kbits/s speed=34.8x
frame=216169 fps=1042 q=-1.0 size= 3637504kB time=02:00:12.84 bitrate=4131.3kbits/s speed=34.8x
frame=216589 fps=1042 q=-1.0 size= 3644416kB time=02:00:26.85 bitrate=4131.1kbits/s speed=34.8x
frame=217075 fps=1041 q=-1.0 size= 3652608kB time=02:00:43.07 bitrate=4131.1kbits/s speed=34.8x
frame=217472 fps=1041 q=-1.0 size= 3659264kB time=02:00:56.32 bitrate=4131.1kbits/s speed=34.7x
frame=218010 fps=1041 q=-1.0 size= 3668224kB time=02:01:14.24 bitrate=4131.0kbits/s speed=34.7x
frame=218519 fps=1041 q=-1.0 size= 3676928kB time=02:01:31.22 bitrate=4131.2kbits/s speed=34.7x
frame=219106 fps=1041 q=-1.0 size= 3686912kB time=02:01:50.80 bitrate=4131.3kbits/s speed=34.7x
frame=219677 fps=1041 q=-1.0 size= 3696384kB time=02:02:09.85 bitrate=4131.2kbits/s speed=34.7x
frame=220259 fps=1042 q=-1.0 size= 3706112kB time=02:02:29.31 bitrate=4131.1kbits/s speed=34.8x
frame=220827 fps=1042 q=-1.0 size= 3715584kB time=02:02:48.21 bitrate=4131.0kbits/s speed=34.8x
frame=221422 fps=1042 q=-1.0 size= 3725568kB time=02:03:08.11 bitrate=4130.9kbits/s speed=34.8x
frame=222009 fps=1043 q=-1.0 size= 3735552kB time=02:03:27.65 bitrate=4131.1kbits/s speed=34.8x
frame=222601 fps=1043 q=-1.0 size= 3745536kB time=02:03:47.41 bitrate=4131.1kbits/s speed=34.8x
frame=223145 fps=1043 q=-1.0 size= 3754496kB time=02:04:05.61 bitrate=4130.9kbits/s speed=34.8x
frame=223734 fps=1043 q=-1.0 size= 3764480kB time=02:04:25.21 bitrate=4131.0kbits/s speed=34.8x
frame=224318 fps=1044 q=-1.0 size= 3774464kB time=02:04:44.73 bitrate=4131.1kbits/s speed=34.8x
frame=224912 fps=1044 q=-1.0 size= 3784448kB time=02:05:04.53 bitrate=4131.1kbits/s speed=34.8x
frame=225492 fps=1044 q=-1.0 size= 3794176kB time=02:05:23.88 bitrate=4131.1kbits/s speed=34.8x
frame=226070 fps=1044 q=-1.0 size= 3803904kB time=02:05:43.16 bitrate=4131.1kbits/s speed=34.8x
frame=226636 fps=1045 q=-1.0 size= 3813376kB time=02:06:02.04 bitrate=4131.0kbits/s speed=34.9x
frame=227216 fps=1045 q=-1.0 size= 3823104kB time=02:06:21.39 bitrate=4131.0kbits/s speed=34.9x
frame=227815 fps=1045 q=-1.0 size= 3833344kB time=02:06:41.40 bitrate=4131.2kbits/s speed=34.9x
frame=228370 fps=1045 q=-1.0 size= 3842560kB time=02:06:59.90 bitrate=4131.1kbits/s speed=34.9x
frame=228967 fps=1046 q=-1.0 size= 3852544kB time=02:07:19.87 bitrate=4131.0kbits/s speed=34.9x
frame=229551 fps=1046 q=-1.0 size= 3862528kB time=02:07:39.30 bitrate=4131.2kbits/s speed=34.9x
frame=230125 fps=1046 q=-1.0 size= 3872000kB time=02:07:58.48 bitrate=4130.9kbits/s speed=34.9x
frame=230703 fps=1046 q=-1.0 size= 3881728kB time=02:08:17.74 bitrate=4131.0kbits/s speed=34.9x
frame=231286 fps=1047 q=-1.0 size= 3891712kB time=02:08:37.24 bitrate=4131.1kbits/s speed=34.9x
frame=231875 fps=1047 q=-1.0 size= 3901440kB time=02:08:56.91 bitrate=4130.9kbits/s speed=34.9x
frame=232469 fps=1047 q=-1.0 size= 3911424kB time=02:09:16.67 bitrate=4130.9kbits/s speed=34.9x
frame=233058 fps=1048 q=-1.0 size= 3921408kB time=02:09:36.34 bitrate=4131.0kbits/s speed=  35x
frame=233617 fps=1048 q=-1.0 size= 3930880kB time=02:09:55.00 bitrate=4131.1kbits/s speed=  35x
frame=234191 fps=1048 q=-1.0 size= 3940352kB time=02:10:14.14 bitrate=4130.9kbits/s speed=  35x
frame=234786 fps=1048 q=-1.0 size= 3950336kB time=02:10:34.02 bitrate=4130.8kbits/s speed=  35x
frame=235341 fps=1048 q=-1.0 size= 3959808kB time=02:10:52.54 bitrate=4131.0kbits/s speed=  35x
frame=235703 fps=1048 q=-1.0 size= 3965952kB time=02:11:04.57 bitrate=4131.1kbits/s speed=  35x
frame=236051 fps=1047 q=-1.0 size= 3971840kB time=02:11:16.20 bitrate=4131.1kbits/s speed=34.9x
frame=236444 fps=1046 q=-1.0 size= 3978496kB time=02:11:29.30 bitrate=4131.1kbits/s speed=34.9x
frame=236991 fps=1046 q=-1.0 size= 3987712kB time=02:11:47.56 bitrate=4131.2kbits/s speed=34.9x
frame=237562 fps=1047 q=-1.0 size= 3997184kB time=02:12:06.65 bitrate=4131.0kbits/s speed=34.9x
frame=238154 fps=1047 q=-1.0 size= 4007168kB time=02:12:26.36 bitrate=4131.0kbits/s speed=34.9x
frame=238729 fps=1047 q=-1.0 size= 4016896kB time=02:12:45.58 bitrate=4131.1kbits/s speed=34.9x
frame=239319 fps=1047 q=-1.0 size= 4026880kB time=02:13:05.25 bitrate=4131.1kbits/s speed=34.9x
frame=239899 fps=1048 q=-1.0 size= 4036352kB time=02:13:24.58 bitrate=4130.9kbits/s speed=  35x
frame=240491 fps=1048 q=-1.0 size= 4046336kB time=02:13:44.34 bitrate=4130.9kbits/s speed=  35x
frame=241081 fps=1048 q=-1.0 size= 4056320kB time=02:14:04.03 bitrate=4130.9kbits/s speed=  35x
frame=241672 fps=1048 q=-1.0 size= 4066304kB time=02:14:23.78 bitrate=4131.0kbits/s speed=  35x
frame=242257 fps=1049 q=-1.0 size= 4076032kB time=02:14:43.32 bitrate=4130.8kbits/s speed=  35x
frame=242835 fps=1049 q=-1.0 size= 4085760kB time=02:15:02.54 bitrate=4130.9kbits/s speed=  35x
frame=243406 fps=1049 q=-1.0 size= 4095488kB time=02:15:21.60 bitrate=4131.0kbits/s speed=  35x
frame=243984 fps=1049 q=-1.0 size= 4105216kB time=02:15:40.92 bitrate=4131.0kbits/s speed=  35x
frame=244558 fps=1050 q=-1.0 size= 4114944kB time=02:16:00.08 bitrate=4131.0kbits/s speed=  35x
frame=245137 fps=1050 q=-1.0 size= 4124672kB time=02:16:19.41 bitrate=4131.0kbits/s speed=  35x
frame=245723 fps=1050 q=-1.0 size= 4134400kB time=02:16:38.91 bitrate=4130.9kbits/s speed=  35x
frame=246298 fps=1050 q=-1.0 size= 4144128kB time=02:16:58.11 bitrate=4131.0kbits/s speed=  35x
frame=246883 fps=1050 q=-1.0 size= 4154112kB time=02:17:17.63 bitrate=4131.1kbits/s speed=35.1x
frame=247456 fps=1051 q=-1.0 size= 4163584kB time=02:17:36.74 bitrate=4130.9kbits/s speed=35.1x
frame=248015 fps=1051 q=-1.0 size= 4173056kB time=02:17:55.49 bitrate=4131.0kbits/s speed=35.1x
frame=248591 fps=1051 q=-1.0 size= 4182784kB time=02:18:14.61 bitrate=4131.0kbits/s speed=35.1x
frame=249142 fps=1051 q=-1.0 size= 4192000kB time=02:18:33.02 bitrate=4131.0kbits/s speed=35.1x
av_interleaved_write_frame(): No space left on device
Error writing trailer of D:\LA by Night\S03E04 - Swimming with the Sharks.mp4: No space left on device
frame=249275 fps=1051 q=-1.0 Lsize= 4194048kB time=02:18:37.48 bitrate=4130.8kbits/s speed=35.1x
video:4063614kB audio:130381kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001264%
[aac @ 000002cade9e9840] Qavg: 309.443
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\ME\AppData\Local\Temp\TL_2a5fd7cc-548d-4f3c-825a-3ae5152c0bfd'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
`No space left on device`

Maybe you should free up some space on your HDD ;)
