### ISSUE TITLE
Download Fails at conversion

### ISSUE THREAD

**Issue by OrangeBeatle123** [Franiac/TwitchLeecher#362]
Hey 
I love twitch leecher but when downloading videos it fails at 100% on the conversion stage. (See Image below)
![Capture](https://user-images.githubusercontent.com/52868669/61176862-179d4f00-a5c0-11e9-91a0-4ef52d33bec0.PNG)

I'll attach the download log and would appreciate if you could suggest a fix.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 426475511
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/426475511
Crop Start: No
Crop End: Yes (04:55:52)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\orang\Downloads\Deadpine2.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\orang\AppData\Local\Temp\TL_7585167e-ceb7-4cd4-ba13-80e35f78e6f3

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1563124758%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A426475511%7D
Signature: 7ba4c889cebc675c041ea4c03cf95e07d401033c
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\orang\AppData\Local\Temp\TL_7585167e-ceb7-4cd4-ba13-80e35f78e6f3'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/720p60/index-dvr.m3u8
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/720p30/index-dvr.m3u8
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/480p30/index-dvr.m3u8
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/audio_only/index-dvr.m3u8
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/360p30/index-dvr.m3u8
https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps is https://vod-secure.twitch.tv/2ba47032df2c9dfe6e20_deadpine_34165317712_1203993908/720p60/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2940

Starting parallel video chunk download
Number of video chunks to download: 1776
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\orang\AppData\Local\Temp\TL_7585167e-ceb7-4cd4-ba13-80e35f78e6f3\Deadpine2.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on 'C:\Users\orang\AppData\Local\Temp\TL_7585167e-ceb7-4cd4-ba13-80e35f78e6f3\Deadpine2.ts'...
Command line arguments: -y -i "C:\Users\orang\AppData\Local\Temp\TL_7585167e-ceb7-4cd4-ba13-80e35f78e6f3\Deadpine2.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -bsf:a aac_adtstoasc -t 17752 "C:\Users\orang\Downloads\Deadpine2.mp4"

frame=358007 fps=1860 q=-1.0 size= 2170368kB time=01:39:26.74 bitrate=2979.8kbits/s speed=  31x
frame=358231 fps=1856 q=-1.0 size= 2171648kB time=01:39:30.47 bitrate=2979.7kbits/s speed=30.9x
frame=359361 fps=1857 q=-1.0 size= 2178560kB time=01:39:49.31 bitrate=2979.8kbits/s speed=  31x
frame=360415 fps=1858 q=-1.0 size= 2184960kB time=01:40:06.88 bitrate=2979.8kbits/s speed=  31x
frame=360921 fps=1855 q=-1.0 size= 2187776kB time=01:40:15.31 bitrate=2979.4kbits/s speed=30.9x
frame=362172 fps=1857 q=-1.0 size= 2195456kB time=01:40:36.16 bitrate=2979.6kbits/s speed=  31x
frame=362870 fps=1854 q=-1.0 size= 2199808kB time=01:40:47.79 bitrate=2979.7kbits/s speed=30.9x
frame=364167 fps=1856 q=-1.0 size= 2207488kB time=01:41:09.41 bitrate=2979.5kbits/s speed=30.9x
frame=365204 fps=1856 q=-1.0 size= 2213632kB time=01:41:26.69 bitrate=2979.3kbits/s speed=30.9x
frame=365696 fps=1854 q=-1.0 size= 2216448kB time=01:41:34.89 bitrate=2979.1kbits/s speed=30.9x
frame=366830 fps=1855 q=-1.0 size= 2223360kB time=01:41:53.79 bitrate=2979.1kbits/s speed=30.9x
frame=367639 fps=1855 q=-1.0 size= 2228224kB time=01:42:07.28 bitrate=2979.1kbits/s speed=30.9x
frame=368369 fps=1854 q=-1.0 size= 2232832kB time=01:42:19.44 bitrate=2979.3kbits/s speed=30.9x
frame=369631 fps=1855 q=-1.0 size= 2240768kB time=01:42:40.48 bitrate=2979.7kbits/s speed=30.9x
frame=370701 fps=1856 q=-1.0 size= 2247424kB time=01:42:58.31 bitrate=2979.9kbits/s speed=30.9x
frame=372007 fps=1858 q=-1.0 size= 2255360kB time=01:43:20.07 bitrate=2979.9kbits/s speed=  31x
frame=373218 fps=1859 q=-1.0 size= 2263040kB time=01:43:40.26 bitrate=2980.4kbits/s speed=  31x
frame=374254 fps=1860 q=-1.0 size= 2269440kB time=01:43:57.52 bitrate=2980.5kbits/s speed=  31x
frame=375506 fps=1861 q=-1.0 size= 2277376kB time=01:44:18.40 bitrate=2981.0kbits/s speed=  31x
frame=376737 fps=1863 q=-1.0 size= 2285312kB time=01:44:38.91 bitrate=2981.6kbits/s speed=  31x
frame=377858 fps=1864 q=-1.0 size= 2291712kB time=01:44:57.60 bitrate=2981.1kbits/s speed=31.1x
frame=379173 fps=1866 q=-1.0 size= 2299904kB time=01:45:19.51 bitrate=2981.4kbits/s speed=31.1x
frame=380342 fps=1867 q=-1.0 size= 2306560kB time=01:45:39.00 bitrate=2980.8kbits/s speed=31.1x
frame=381451 fps=1868 q=-1.0 size= 2313216kB time=01:45:57.48 bitrate=2980.7kbits/s speed=31.1x
frame=382686 fps=1869 q=-1.0 size= 2321152kB time=01:46:18.06 bitrate=2981.3kbits/s speed=31.2x
frame=383972 fps=1871 q=-1.0 size= 2329088kB time=01:46:39.51 bitrate=2981.5kbits/s speed=31.2x
frame=385079 fps=1872 q=-1.0 size= 2336000kB time=01:46:57.97 bitrate=2981.7kbits/s speed=31.2x
frame=386280 fps=1873 q=-1.0 size= 2343680kB time=01:47:17.98 bitrate=2982.2kbits/s speed=31.2x
frame=387588 fps=1875 q=-1.0 size= 2351104kB time=01:47:39.76 bitrate=2981.6kbits/s speed=31.2x
frame=388931 fps=1877 q=-1.0 size= 2359808kB time=01:48:02.15 bitrate=2982.3kbits/s speed=31.3x
frame=389762 fps=1876 q=-1.0 size= 2365184kB time=01:48:15.99 bitrate=2982.7kbits/s speed=31.3x
frame=390949 fps=1877 q=-1.0 size= 2372864kB time=01:48:35.77 bitrate=2983.3kbits/s speed=31.3x
frame=392200 fps=1879 q=-1.0 size= 2380544kB time=01:48:56.62 bitrate=2983.4kbits/s speed=31.3x
frame=392699 fps=1877 q=-1.0 size= 2383872kB time=01:49:04.94 bitrate=2983.8kbits/s speed=31.3x
frame=393539 fps=1876 q=-1.0 size= 2389248kB time=01:49:18.94 bitrate=2984.1kbits/s speed=31.3x
frame=394799 fps=1878 q=-1.0 size= 2397440kB time=01:49:39.97 bitrate=2984.8kbits/s speed=31.3x
frame=395016 fps=1874 q=-1.0 size= 2398976kB time=01:49:43.56 bitrate=2985.1kbits/s speed=31.2x
frame=396197 fps=1875 q=-1.0 size= 2406144kB time=01:50:03.24 bitrate=2985.1kbits/s speed=31.3x
frame=396963 fps=1874 q=-1.0 size= 2411264kB time=01:50:16.01 bitrate=2985.6kbits/s speed=31.2x
frame=397507 fps=1872 q=-1.0 size= 2414592kB time=01:50:25.07 bitrate=2985.7kbits/s speed=31.2x
frame=398766 fps=1874 q=-1.0 size= 2422272kB time=01:50:46.06 bitrate=2985.7kbits/s speed=31.2x
frame=399223 fps=1871 q=-1.0 size= 2425088kB time=01:50:53.67 bitrate=2985.8kbits/s speed=31.2x
frame=400129 fps=1871 q=-1.0 size= 2430976kB time=01:51:08.77 bitrate=2986.2kbits/s speed=31.2x
frame=401328 fps=1872 q=-1.0 size= 2438400kB time=01:51:28.76 bitrate=2986.4kbits/s speed=31.2x
frame=401523 fps=1869 q=-1.0 size= 2439680kB time=01:51:32.01 bitrate=2986.5kbits/s speed=31.1x
frame=402741 fps=1870 q=-1.0 size= 2446848kB time=01:51:52.31 bitrate=2986.2kbits/s speed=31.2x
frame=403724 fps=1870 q=-1.0 size= 2452992kB time=01:52:08.70 bitrate=2986.4kbits/s speed=31.2x
frame=404311 fps=1868 q=-1.0 size= 2456576kB time=01:52:18.50 bitrate=2986.5kbits/s speed=31.1x
frame=405533 fps=1870 q=-1.0 size= 2464000kB time=01:52:38.84 bitrate=2986.5kbits/s speed=31.2x
frame=406016 fps=1867 q=-1.0 size= 2467072kB time=01:52:46.89 bitrate=2986.6kbits/s speed=31.1x
frame=406940 fps=1867 q=-1.0 size= 2472704kB time=01:53:02.29 bitrate=2986.7kbits/s speed=31.1x
frame=408291 fps=1869 q=-1.0 size= 2480896kB time=01:53:24.81 bitrate=2986.6kbits/s speed=31.2x
frame=408493 fps=1866 q=-1.0 size= 2482176kB time=01:53:28.18 bitrate=2986.7kbits/s speed=31.1x
frame=409757 fps=1867 q=-1.0 size= 2489344kB time=01:53:49.24 bitrate=2986.1kbits/s speed=31.1x
frame=410412 fps=1866 q=-1.0 size= 2493440kB time=01:54:00.16 bitrate=2986.2kbits/s speed=31.1x
frame=410594 fps=1863 q=-1.0 size= 2494208kB time=01:54:03.19 bitrate=2985.8kbits/s speed=  31x
frame=410849 fps=1860 q=-1.0 size= 2495488kB time=01:54:07.44 bitrate=2985.5kbits/s speed=  31x
frame=411069 fps=1856 q=-1.0 size= 2496768kB time=01:54:11.11 bitrate=2985.4kbits/s speed=30.9x
frame=411618 fps=1855 q=-1.0 size= 2500352kB time=01:54:20.26 bitrate=2985.7kbits/s speed=30.9x
frame=412840 fps=1856 q=-1.0 size= 2507776kB time=01:54:40.62 bitrate=2985.7kbits/s speed=30.9x
frame=413212 fps=1853 q=-1.0 size= 2509824kB time=01:54:46.82 bitrate=2985.5kbits/s speed=30.9x
frame=414467 fps=1855 q=-1.0 size= 2516992kB time=01:55:07.75 bitrate=2984.9kbits/s speed=30.9x
frame=415672 fps=1856 q=-1.0 size= 2523904kB time=01:55:27.83 bitrate=2984.5kbits/s speed=30.9x
frame=416256 fps=1854 q=-1.0 size= 2527232kB time=01:55:37.56 bitrate=2984.2kbits/s speed=30.9x
frame=417564 fps=1856 q=-1.0 size= 2534656kB time=01:55:59.36 bitrate=2983.6kbits/s speed=30.9x
frame=418300 fps=1855 q=-1.0 size= 2539008kB time=01:56:11.62 bitrate=2983.5kbits/s speed=30.9x
frame=419091 fps=1854 q=-1.0 size= 2543616kB time=01:56:24.81 bitrate=2983.2kbits/s speed=30.9x
frame=420351 fps=1856 q=-1.0 size= 2551040kB time=01:56:45.81 bitrate=2983.0kbits/s speed=30.9x
frame=420969 fps=1855 q=-1.0 size= 2554880kB time=01:56:56.11 bitrate=2983.1kbits/s speed=30.9x
frame=422255 fps=1856 q=-1.0 size= 2562304kB time=01:57:17.55 bitrate=2982.6kbits/s speed=30.9x
frame=423394 fps=1857 q=-1.0 size= 2569216kB time=01:57:36.52 bitrate=2982.6kbits/s speed=  31x
frame=424383 fps=1857 q=-1.0 size= 2575616kB time=01:57:53.01 bitrate=2983.1kbits/s speed=  31x
frame=425685 fps=1859 q=-1.0 size= 2583552kB time=01:58:14.71 bitrate=2983.1kbits/s speed=  31x
frame=426950 fps=1860 q=-1.0 size= 2590720kB time=01:58:35.80 bitrate=2982.5kbits/s speed=  31x
frame=428086 fps=1861 q=-1.0 size= 2597632kB time=01:58:54.72 bitrate=2982.6kbits/s speed=  31x
frame=429287 fps=1862 q=-1.0 size= 2604544kB time=01:59:14.74 bitrate=2982.1kbits/s speed=  31x
frame=430422 fps=1863 q=-1.0 size= 2611200kB time=01:59:33.66 bitrate=2981.9kbits/s speed=31.1x
frame=431554 fps=1864 q=-1.0 size= 2617600kB time=01:59:52.52 bitrate=2981.3kbits/s speed=31.1x
frame=432874 fps=1866 q=-1.0 size= 2626048kB time=02:00:14.53 bitrate=2981.8kbits/s speed=31.1x
frame=434035 fps=1867 q=-1.0 size= 2632704kB time=02:00:33.89 bitrate=2981.4kbits/s speed=31.1x
frame=435300 fps=1868 q=-1.0 size= 2640128kB time=02:00:54.96 bitrate=2981.1kbits/s speed=31.1x
frame=436559 fps=1870 q=-1.0 size= 2647552kB time=02:01:15.97 bitrate=2980.9kbits/s speed=31.2x
frame=437915 fps=1871 q=-1.0 size= 2655744kB time=02:01:38.54 bitrate=2980.8kbits/s speed=31.2x
frame=439266 fps=1873 q=-1.0 size= 2664192kB time=02:02:01.06 bitrate=2981.1kbits/s speed=31.2x
frame=440521 fps=1875 q=-1.0 size= 2671872kB time=02:02:21.98 bitrate=2981.2kbits/s speed=31.2x
frame=441725 fps=1876 q=-1.0 size= 2679552kB time=02:02:42.04 bitrate=2981.6kbits/s speed=31.3x
frame=442905 fps=1877 q=-1.0 size= 2686720kB time=02:03:01.71 bitrate=2981.6kbits/s speed=31.3x
frame=443737 fps=1876 q=-1.0 size= 2691840kB time=02:03:15.57 bitrate=2981.7kbits/s speed=31.3x
frame=445010 fps=1878 q=-1.0 size= 2699776kB time=02:03:36.80 bitrate=2982.0kbits/s speed=31.3x
frame=446275 fps=1879 q=-1.0 size= 2707456kB time=02:03:57.88 bitrate=2982.0kbits/s speed=31.3x
frame=446500 fps=1875 q=-1.0 size= 2708992kB time=02:04:01.62 bitrate=2982.2kbits/s speed=31.3x
frame=447802 fps=1877 q=-1.0 size= 2716928kB time=02:04:23.33 bitrate=2982.2kbits/s speed=31.3x
frame=448580 fps=1876 q=-1.0 size= 2722048kB time=02:04:36.29 bitrate=2982.6kbits/s speed=31.3x
frame=449134 fps=1875 q=-1.0 size= 2725376kB time=02:04:45.53 bitrate=2982.6kbits/s speed=31.2x
frame=450339 fps=1876 q=-1.0 size= 2732544kB time=02:05:05.61 bitrate=2982.4kbits/s speed=31.3x
frame=450827 fps=1873 q=-1.0 size= 2735616kB time=02:05:13.74 bitrate=2982.6kbits/s speed=31.2x
frame=451880 fps=1873 q=-1.0 size= 2742016kB time=02:05:31.29 bitrate=2982.6kbits/s speed=31.2x
frame=452928 fps=1874 q=-1.0 size= 2748672kB time=02:05:48.76 bitrate=2982.9kbits/s speed=31.2x
frame=453193 fps=1871 q=-1.0 size= 2750208kB time=02:05:53.17 bitrate=2982.8kbits/s speed=31.2x
frame=454455 fps=1872 q=-1.0 size= 2757888kB time=02:06:14.21 bitrate=2982.8kbits/s speed=31.2x
frame=455263 fps=1872 q=-1.0 size= 2762752kB time=02:06:27.67 bitrate=2982.8kbits/s speed=31.2x
frame=455990 fps=1871 q=-1.0 size= 2767360kB time=02:06:39.79 bitrate=2983.0kbits/s speed=31.2x
frame=457298 fps=1873 q=-1.0 size= 2775296kB time=02:07:01.60 bitrate=2983.0kbits/s speed=31.2x
frame=457751 fps=1870 q=-1.0 size= 2778368kB time=02:07:09.14 bitrate=2983.3kbits/s speed=31.2x
frame=458935 fps=1871 q=-1.0 size= 2785536kB time=02:07:28.88 bitrate=2983.3kbits/s speed=31.2x
frame=460042 fps=1872 q=-1.0 size= 2792704kB time=02:07:47.32 bitrate=2983.8kbits/s speed=31.2x
frame=460464 fps=1869 q=-1.0 size= 2795264kB time=02:07:54.36 bitrate=2983.8kbits/s speed=31.2x
frame=461801 fps=1871 q=-1.0 size= 2803456kB time=02:08:16.64 bitrate=2983.9kbits/s speed=31.2x
frame=462466 fps=1869 q=-1.0 size= 2807808kB time=02:08:27.72 bitrate=2984.2kbits/s speed=31.2x
frame=463199 fps=1869 q=-1.0 size= 2812416kB time=02:08:39.98 bitrate=2984.4kbits/s speed=31.1x
frame=464515 fps=1870 q=-1.0 size= 2820352kB time=02:09:01.88 bitrate=2984.3kbits/s speed=31.2x
frame=464778 fps=1867 q=-1.0 size= 2822144kB time=02:09:06.26 bitrate=2984.5kbits/s speed=31.1x
frame=466099 fps=1869 q=-1.0 size= 2830080kB time=02:09:28.28 bitrate=2984.4kbits/s speed=31.1x
frame=467083 fps=1868 q=-1.0 size= 2836480kB time=02:09:44.67 bitrate=2984.9kbits/s speed=31.1x
frame=467762 fps=1867 q=-1.0 size= 2840832kB time=02:09:56.00 bitrate=2985.1kbits/s speed=31.1x
frame=468969 fps=1868 q=-1.0 size= 2848512kB time=02:10:16.11 bitrate=2985.5kbits/s speed=31.1x
frame=469426 fps=1866 q=-1.0 size= 2851072kB time=02:10:23.73 bitrate=2985.3kbits/s speed=31.1x
frame=470620 fps=1867 q=-1.0 size= 2858496kB time=02:10:43.63 bitrate=2985.5kbits/s speed=31.1x
frame=471602 fps=1867 q=-1.0 size= 2864896kB time=02:11:00.00 bitrate=2985.9kbits/s speed=31.1x
frame=472093 fps=1865 q=-1.0 size= 2867968kB time=02:11:08.17 bitrate=2986.0kbits/s speed=31.1x
frame=473354 fps=1866 q=-1.0 size= 2875648kB time=02:11:29.19 bitrate=2986.0kbits/s speed=31.1x
frame=474018 fps=1865 q=-1.0 size= 2880000kB time=02:11:40.26 bitrate=2986.4kbits/s speed=31.1x
frame=475086 fps=1865 q=-1.0 size= 2886656kB time=02:11:58.06 bitrate=2986.5kbits/s speed=31.1x
frame=476488 fps=1867 q=-1.0 size= 2894848kB time=02:12:21.43 bitrate=2986.2kbits/s speed=31.1x
frame=476858 fps=1865 q=-1.0 size= 2896896kB time=02:12:27.60 bitrate=2986.0kbits/s speed=31.1x
frame=477955 fps=1866 q=-1.0 size= 2903552kB time=02:12:45.88 bitrate=2986.0kbits/s speed=31.1x
frame=479206 fps=1867 q=-1.0 size= 2911488kB time=02:13:06.73 bitrate=2986.3kbits/s speed=31.1x
frame=480289 fps=1867 q=-1.0 size= 2917888kB time=02:13:24.77 bitrate=2986.1kbits/s speed=31.1x
frame=481554 fps=1869 q=-1.0 size= 2926080kB time=02:13:45.86 bitrate=2986.7kbits/s speed=31.1x
frame=482701 fps=1869 q=-1.0 size= 2933248kB time=02:14:04.97 bitrate=2986.9kbits/s speed=31.2x
frame=483931 fps=1871 q=-1.0 size= 2940672kB time=02:14:25.47 bitrate=2986.8kbits/s speed=31.2x
frame=485119 fps=1872 q=-1.0 size= 2948096kB time=02:14:45.28 bitrate=2987.0kbits/s speed=31.2x
frame=486308 fps=1873 q=-1.0 size= 2956032kB time=02:15:05.09 bitrate=2987.7kbits/s speed=31.2x
frame=487518 fps=1874 q=-1.0 size= 2963968kB time=02:15:25.26 bitrate=2988.3kbits/s speed=31.2x
frame=488776 fps=1875 q=-1.0 size= 2971648kB time=02:15:46.23 bitrate=2988.3kbits/s speed=31.2x
frame=489720 fps=1875 q=-1.0 size= 2977792kB time=02:16:01.99 bitrate=2988.7kbits/s speed=31.2x
frame=490957 fps=1876 q=-1.0 size= 2984960kB time=02:16:22.57 bitrate=2988.4kbits/s speed=31.3x
frame=492117 fps=1877 q=-1.0 size= 2992384kB time=02:16:41.91 bitrate=2988.8kbits/s speed=31.3x
frame=493425 fps=1878 q=-1.0 size= 3000576kB time=02:17:03.71 bitrate=2989.0kbits/s speed=31.3x
frame=494686 fps=1879 q=-1.0 size= 3008256kB time=02:17:24.73 bitrate=2989.0kbits/s speed=31.3x
frame=495919 fps=1880 q=-1.0 size= 3016192kB time=02:17:45.28 bitrate=2989.4kbits/s speed=31.3x
frame=497251 fps=1882 q=-1.0 size= 3024640kB time=02:18:07.48 bitrate=2989.8kbits/s speed=31.4x
frame=498564 fps=1883 q=-1.0 size= 3032320kB time=02:18:29.36 bitrate=2989.5kbits/s speed=31.4x
frame=499822 fps=1884 q=-1.0 size= 3039744kB time=02:18:50.32 bitrate=2989.3kbits/s speed=31.4x
frame=501057 fps=1885 q=-1.0 size= 3047424kB time=02:19:10.91 bitrate=2989.4kbits/s speed=31.4x
frame=502120 fps=1886 q=-1.0 size= 3053824kB time=02:19:28.63 bitrate=2989.4kbits/s speed=31.4x
frame=502558 fps=1884 q=-1.0 size= 3056384kB time=02:19:35.97 bitrate=2989.3kbits/s speed=31.4x
frame=503848 fps=1885 q=-1.0 size= 3064320kB time=02:19:57.42 bitrate=2989.4kbits/s speed=31.4x
frame=504536 fps=1884 q=-1.0 size= 3068416kB time=02:20:08.89 bitrate=2989.3kbits/s speed=31.4x
frame=505445 fps=1884 q=-1.0 size= 3073792kB time=02:20:24.04 bitrate=2989.1kbits/s speed=31.4x
frame=506593 fps=1884 q=-1.0 size= 3080448kB time=02:20:43.17 bitrate=2988.8kbits/s speed=31.4x
frame=507735 fps=1885 q=-1.0 size= 3087104kB time=02:21:02.21 bitrate=2988.5kbits/s speed=31.4x
frame=508912 fps=1886 q=-1.0 size= 3094016kB time=02:21:21.83 bitrate=2988.3kbits/s speed=31.4x
frame=510142 fps=1887 q=-1.0 size= 3101696kB time=02:21:42.33 bitrate=2988.5kbits/s speed=31.4x
frame=511197 fps=1887 q=-1.0 size= 3107840kB time=02:21:59.91 bitrate=2988.2kbits/s speed=31.5x
frame=512476 fps=1889 q=-1.0 size= 3114752kB time=02:22:21.22 bitrate=2987.4kbits/s speed=31.5x
frame=513188 fps=1888 q=-1.0 size= 3118848kB time=02:22:33.09 bitrate=2987.2kbits/s speed=31.5x
frame=514028 fps=1887 q=-1.0 size= 3123712kB time=02:22:47.09 bitrate=2986.9kbits/s speed=31.5x
frame=515308 fps=1889 q=-1.0 size= 3131648kB time=02:23:08.43 bitrate=2987.1kbits/s speed=31.5x
frame=515722 fps=1886 q=-1.0 size= 3134464kB time=02:23:15.33 bitrate=2987.4kbits/s speed=31.4x
frame=516860 fps=1887 q=-1.0 size= 3141632kB time=02:23:34.30 bitrate=2987.6kbits/s speed=31.4x
frame=517872 fps=1887 q=-1.0 size= 3147776kB time=02:23:51.16 bitrate=2987.6kbits/s speed=31.5x
frame=518282 fps=1885 q=-1.0 size= 3150080kB time=02:23:57.99 bitrate=2987.4kbits/s speed=31.4x
frame=519505 fps=1886 q=-1.0 size= 3157760kB time=02:24:18.37 bitrate=2987.7kbits/s speed=31.4x
frame=520212 fps=1885 q=-1.0 size= 3162624kB time=02:24:30.16 bitrate=2988.2kbits/s speed=31.4x
frame=521158 fps=1885 q=-1.0 size= 3168256kB time=02:24:45.98 bitrate=2988.1kbits/s speed=31.4x
frame=522338 fps=1886 q=-1.0 size= 3175680kB time=02:25:05.60 bitrate=2988.3kbits/s speed=31.4x
frame=522531 fps=1883 q=-1.0 size= 3176960kB time=02:25:08.81 bitrate=2988.4kbits/s speed=31.4x
frame=523705 fps=1884 q=-1.0 size= 3183872kB time=02:25:28.38 bitrate=2988.2kbits/s speed=31.4x
frame=524817 fps=1884 q=-1.0 size= 3190784kB time=02:25:46.91 bitrate=2988.4kbits/s speed=31.4x
frame=525254 fps=1883 q=-1.0 size= 3193344kB time=02:25:54.20 bitrate=2988.3kbits/s speed=31.4x
frame=526510 fps=1884 q=-1.0 size= 3201024kB time=02:26:15.12 bitrate=2988.3kbits/s speed=31.4x
frame=527278 fps=1883 q=-1.0 size= 3205632kB time=02:26:27.96 bitrate=2988.2kbits/s speed=31.4x
frame=528142 fps=1882 q=-1.0 size= 3211008kB time=02:26:42.33 bitrate=2988.4kbits/s speed=31.4x
frame=529420 fps=1883 q=-1.0 size= 3218944kB time=02:27:03.62 bitrate=2988.5kbits/s speed=31.4x
frame=529695 fps=1881 q=-1.0 size= 3220736kB time=02:27:08.21 bitrate=2988.6kbits/s speed=31.3x
frame=530991 fps=1882 q=-1.0 size= 3228416kB time=02:27:29.82 bitrate=2988.4kbits/s speed=31.4x
frame=531965 fps=1882 q=-1.0 size= 3234560kB time=02:27:46.05 bitrate=2988.6kbits/s speed=31.4x
frame=532421 fps=1880 q=-1.0 size= 3237376kB time=02:27:53.64 bitrate=2988.7kbits/s speed=31.3x
frame=533669 fps=1881 q=-1.0 size= 3245056kB time=02:28:14.45 bitrate=2988.8kbits/s speed=31.3x
frame=534093 fps=1879 q=-1.0 size= 3247616kB time=02:28:21.51 bitrate=2988.8kbits/s speed=31.3x
frame=535264 fps=1879 q=-1.0 size= 3254784kB time=02:28:41.02 bitrate=2988.8kbits/s speed=31.3x
frame=536339 fps=1880 q=-1.0 size= 3261696kB time=02:28:58.94 bitrate=2989.1kbits/s speed=31.3x
frame=536779 fps=1878 q=-1.0 size= 3264256kB time=02:29:06.27 bitrate=2989.0kbits/s speed=31.3x
frame=538013 fps=1879 q=-1.0 size= 3271680kB time=02:29:26.84 bitrate=2989.0kbits/s speed=31.3x
frame=538764 fps=1878 q=-1.0 size= 3276544kB time=02:29:39.36 bitrate=2989.2kbits/s speed=31.3x
frame=539387 fps=1877 q=-1.0 size= 3280384kB time=02:29:49.74 bitrate=2989.3kbits/s speed=31.3x
frame=540699 fps=1879 q=-1.0 size= 3288320kB time=02:30:11.61 bitrate=2989.2kbits/s speed=31.3x
frame=541131 fps=1876 q=-1.0 size= 3291136kB time=02:30:18.81 bitrate=2989.4kbits/s speed=31.3x
frame=542420 fps=1877 q=-1.0 size= 3299072kB time=02:30:40.29 bitrate=2989.5kbits/s speed=31.3x
frame=543300 fps=1876 q=-1.0 size= 3304704kB time=02:30:54.96 bitrate=2989.8kbits/s speed=31.3x
frame=544085 fps=1876 q=-1.0 size= 3309568kB time=02:31:08.04 bitrate=2989.8kbits/s speed=31.3x
frame=545287 fps=1877 q=-1.0 size= 3317248kB time=02:31:28.08 bitrate=2990.2kbits/s speed=31.3x
frame=545803 fps=1875 q=-1.0 size= 3320576kB time=02:31:36.67 bitrate=2990.3kbits/s speed=31.2x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\orang\Downloads\Deadpine2.mp4: No space left on device
frame=546842 fps=1875 q=-1.0 Lsize= 3326464kB time=02:31:54.01 bitrate=2989.9kbits/s speed=31.2x
video:3183281kB audio:143037kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.004417%
[aac @ 000002643ee10900] Qavg: 304.285
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\orang\AppData\Local\Temp\TL_7585167e-ceb7-4cd4-ba13-80e35f78e6f3'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by garoto** [comment]
```
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\orang\Downloads\Deadpine2.mp4: No space left on device
```
