### ISSUE TITLE
System.IO.IOException: The device is not ready

### ISSUE THREAD

**Issue by KrimsonAer** [Franiac/TwitchLeecher#363]
I have the following error for all attempts to download VODs - Have tried multiple directories and different disc drives etc. but no luck

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 454042790
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/454042790
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: L:\Recordings\PUBG\PEL\PEL Promos\20190717_454042790_PLAYERUNKNOWN'S BATTLEGROUNDS.mp4
FFMPEG Path: K:\Programs\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: J:\Temp\TL_73c5fe26-a732-4dec-9c26-5c351aa57357

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1563472978%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A454042790%7D
Signature: 6b157b5f3e01256b2e79cb4a1f84dadd44cb3827
Sub-Only: No
Privileged: No

Creating temporary download directory 'J:\Temp\TL_73c5fe26-a732-4dec-9c26-5c351aa57357'...

Starting temporary download folder cleanup!
Deleting directory 'J:\Temp\TL_73c5fe26-a732-4dec-9c26-5c351aa57357'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   at TwitchLeecher.Services.Services.TwitchService.CheckTempDirectory(Action`1 log, String tempDir)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: The device is not ready.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   at TwitchLeecher.Services.Services.TwitchService.CheckTempDirectory(Action`1 log, String tempDir)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by KrimsonAer** [comment]
Nevermind - My default temp. folder was set to a HDD that wasn't plugged in! Closing and leaving in case anyone makes my mistake

**Comment by LukasKnuth** [comment]
I have the same issue with the Download directory being set to a HDD which had recently been assigned a new drive-letter.

I feel like it's probably worth to invest some time into throw up a textbox on-screen for these more common errors (the "no space left" one as well) @Franiac 

You could also check that both directories are accessible and writable before starting the download.

**Comment by LukasKnuth** [comment]
Let me re-phrase: I think the error messages should be output on-screen (_maybe_ as a popup) so users don't have to go through the log to find out what the problem is.

This would give you the opportunity to make the messages a little "nicer" as in:

* "The device is not ready." -> "The target device E:\ is not available. If it's a HDD/SSD, make sure the driver letter is correct. If it's a network mount, make sure the network is available"
* "There is not enough space on the disk." -> "The target folder at D:\twitch doesn't have enough storage space (200MB free). Aborting..."

I agree that most people will probably never see these errors. However, I also belief that you can't create quality software if you only look at the "happy execution path". Which is not to say I don't appreciate the (free) work you've done here.
