### ISSUE TITLE
This website requires you to log in.

### ISSUE THREAD

**Issue by VGDCM** [Franiac/TwitchLeecher#365]
Trying to connect through https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=37v97169hnj8kaoq8fs3hzz8v6jezdj&redirect_uri=http://www.tl.com&scope=user_subscriptions&force_verify=true
Internet Explorer gives me a 403 Error after logging in, stating "This website requires you to log in."
Firefox and Chrome give me a "connection was reset" error after authorizing, but TwitchLeecher is shown in the Connections tab on Twitch
So I guess all I need to do is to log in to the Leecher, but the Internet Explorer glitch will still happen.

**Comment by Codereaders** [comment]
You should check out the Twitch api documentation.
The article about Authentication should answer your question:
https://dev.twitch.tv/docs/authentication/

**Comment by Franiac** [comment]
I don't get what you want to achieve. Are you trying to connect Twitch Leecher like with the button within the application or are you trying to do something else?
