### ISSUE TITLE
Audio not syncing

### ISSUE THREAD

**Issue by Antolio** [Franiac/TwitchLeecher#368]
I know that some of these have been answered and I hate to drag it up again. However, I would love for this to work and would happily make a donation.

When I export a clip through a web service, it's fine. When I export a trimmed section through leecher the audio never syncs and the video freezes up etc. I am not sure if it's just me. When I open that file in VLC it is fine, so it feels file type or encoder related. However, if I open it in premier pro I cannot even safe it as something else. Any idea on what I could do to fix this my end?

**Comment by Franiac** [comment]
If you checked the other issues you might have come accross the fact that Premiere is a shit video tool that cannot handle Twitch streams. As you state yourself the file is ok in VLC, so it actually IS ok. Premiere messes the file up, not TL. If you import the file in Vegas Pro or Resolve you don't get those issues. Maybe post an issue in the Adobe forums?

**Comment by Antolio** [comment]
It's not okay, because when I upload that clip to google drive then it is frozen. I tried using premiere purely to re save it to see if it fixed the issue. Any standalone player used and it is broken. Why does it work in VLC and not drive? Do I need to resave it in Vegas Pro? I have no issue doing that, just not sure on the solution. Thank you again for a great tool, appreciate the help.

**Comment by Franiac** [comment]
No all players and tools handle videos the same way. There are multiple players out there that cannot play back Twitch streams properly. And waht can be played back and not is not depending on TL but on the streamers encoding settings. Maybe you could try the new 1.6 feature to skip writing a mp4 file. TL can download the raw .ts file now. I cannot fix broken streams. TL does not re-encode anything. It just copies files from the internet to your harddrive.
