### ISSUE TITLE
Application not authorizing

### ISSUE THREAD

**Issue by TenseiDragon** [Franiac/TwitchLeecher#369]
Using v1.6, Win10 64-bit.

I am attempting to use TwitchLeecher for the first time.  I can log into Twitch successfully from in the app, but when I go to authorize it, nothing happens.  Upon clicking the button, nothing appears to change.  No error message.  No loading screens.  Nothing.  I'm almost positive this is something on Twitch's end, but any workaround would be appreciated.  It also does not appear in the Connections tab of my Twitch settings.

I had seen thread #84 that you could manually input the authorization token into the runtime.xml file, but every time I do, reopening the app deletes those new lines, so I am at a bit of a loss.

If any additional information is needed, please let me know and I will deliver.

**Comment by Franiac** [comment]
Please check other issues befor posting duplicates... #367
