### ISSUE TITLE
Can't authorize my twitch account

### ISSUE THREAD

**Issue by yztuar** [Franiac/TwitchLeecher#371]
Hi. Does anyone know why when I try verifying my twitch account, it doesn’t even let me press the authorize button? It does nothing, it's just stuck.

**Comment by kaizen95** [comment]
I have the same problem. Problems occur in versions 1.5.6 and 1.6.
I think the problem is that we do not have access to tl.com
tl server is down?

**Comment by yztuar** [comment]
Yeah that could be the reason. Anyway, please let me know if you find a way to fix this.

**Comment by yztuar** [comment]
Yeah that could be the reason. Anyway, please let me know if you find a way to fix that.

**Comment by Franiac** [comment]
Just check the closed issues befor posting, please!

#367
