### ISSUE TITLE
Update message links to non-existent release

### ISSUE THREAD

**Issue by ArcanErasmus** [Franiac/TwitchLeecher#372]
Both the 1.6 and 1.7 releases have had bad links from inside the client:
[https://github.com/Franiac/TwitchLeecher/releases/tag/v1.7](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.7)
This link is dead, the correct link goes to 1.7.0:
[https://github.com/Franiac/TwitchLeecher/releases/tag/v1.7.0](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.7.0)

**Comment by Franiac** [comment]
This bug is fixed in 1.7.0 (see release notes)

How can you even tell 1.7.0 has it when you never saw the update dialog?

**Comment by ArcanErasmus** [comment]
Whoops, my bad! I saw the "1.7" link dead (which was obv a problem with 1.5 and 1.6), and assumed that it had to do with the new update, as opposed to the previous one.
