### ISSUE TITLE
Some bugginess

### ISSUE THREAD

**Issue by tpunt** [Franiac/TwitchLeecher#375]
For the past couple of months, I have observed some issues with TwitchLeecher. When opening the app, I get the following error twice:
<img width="687" alt="Screen Shot 2019-08-10 at 11 42 29" src="https://user-images.githubusercontent.com/1403064/62820963-4a594980-bb64-11e9-8fa8-b0c6d07cdfa0.png">

The first error log:
<img width="689" alt="Screen Shot 2019-08-10 at 11 46 48" src="https://user-images.githubusercontent.com/1403064/62820977-94dac600-bb64-11e9-9074-bf9860fba913.png">

And the second error log:
<img width="688" alt="Screen Shot 2019-08-10 at 11 47 30" src="https://user-images.githubusercontent.com/1403064/62820982-ad4ae080-bb64-11e9-911b-02826310f281.png">
(With the only difference being the root stack frame, it seems.)

Clicking ok to both errors, the app then doesn't load correctly (the top menu just appears off the screen):
<img width="974" alt="Screen Shot 2019-08-10 at 11 43 04" src="https://user-images.githubusercontent.com/1403064/62820984-c6539180-bb64-11e9-99cc-255c3390695a.png">

Resizing the app, of course, resolves this:
<img width="944" alt="Screen Shot 2019-08-10 at 11 43 18" src="https://user-images.githubusercontent.com/1403064/62820985-cc497280-bb64-11e9-9957-06e20f98077a.png">

When I try to authorise the app to use my Twitch account, I get the same error above:
<img width="831" alt="Screen Shot 2019-08-10 at 11 44 26" src="https://user-images.githubusercontent.com/1403064/62820987-d2d7ea00-bb64-11e9-978c-bb9e88123966.png">

The error log for this is as follows:
<img width="690" alt="Screen Shot 2019-08-10 at 11 49 20" src="https://user-images.githubusercontent.com/1403064/62820994-f00cb880-bb64-11e9-93ae-802d0fc53871.png">

The authorisation is still successful, however:
<img width="832" alt="Screen Shot 2019-08-10 at 11 44 41" src="https://user-images.githubusercontent.com/1403064/62820998-fb5fe400-bb64-11e9-8f61-b7c3a2b2f281.png">

I can still use the TwitchLeecher app even with these issues (downloading new videos works fine), but it just makes it more of a pain.

I am using the latest TwitchLeecher 1.7 version on a Windows 2012, 64bit VM. It has the following `Vagrantfile`:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

Please let me know if I can provide any further information. Thanks!

**Comment by Franiac** [comment]
Go to:

`C:\Users\vagrant\AppData\Roaming\Twitch Leecher`

and send me the runtime.xml to contact@franiac.com

**Comment by Franiac** [comment]
Your runtime.xml show contents TL is not even able to write. The file contains binary info only. The file must have been corrupted outside of TL. TL cannot write such contents without throwing errors. The errors you posted occured when TL tried to read the corrupted file, so that's logical.

Deleting the file and letting TL re-create it helps.
