### ISSUE TITLE
 Prevent system from going to sleep when downloading...

### ISSUE THREAD

**Issue by Keagel** [Franiac/TwitchLeecher#377]

**Comment by Franiac** [comment]
Not gonna happen. Applications should never overwrite the system power settings. Like if you have 3 installed applications and each one of them tell the system to behave differently. That cannot work. Disable sleep mode in your power settings if you don't want your PC to enter sleep mode, that is how it is designed.

**Comment by Keagel** [comment]
I'm pretty sure you're wrong. If you download a file on Firefox and it takes 4 hours to download and your system is set to sleep after 1 hour, it won't go to sleep until the download is over: that's logical. It is absolutely not logical to let the system sleep when it is doing work that shouldn't be interrupted, ESPECIALLY if it can't be resumed.
This is definitely not about cancelling the sleep in the power plan or whatever, only to keep the system awake while it's doing work. Your system isn't going to sleep when you're watching a movie for 2 hours and it's set to sleep after 1 hour. I've had a download going on for over 5 hours in JDownloader and my system hasn't gone to sleep. This is the right way to do things.
