### ISSUE TITLE
Quality string when downloading

### ISSUE THREAD

**Issue by dstftw** [Franiac/TwitchLeecher#38]
Regardless of which quality has been selected in `Download Video` window (see first screenshot):
![image](https://cloud.githubusercontent.com/assets/1908898/15871113/25f3c486-2d1d-11e6-8bef-42296f471d1a.png)
The quality shown while downloading is always best available (`1280x720@60fps` in this case) rather than selected one (`Mobile (400x226@30fps)`). Though in fact it correctly downloads selected quality:
![image](https://cloud.githubusercontent.com/assets/1908898/15871145/42988cac-2d1d-11e6-93c0-44b473a1e4c8.png)

This behavior seems misleading or is it expected?

**Comment by Franiac** [comment]
No, this is not how it should work actually. Thelength should be the length specified via time selection and the video quality should show the actual download quality.

I'll investigate!

**Comment by Franiac** [comment]
Fixed!

**Comment by dstftw** [comment]
Thanks.
