### ISSUE TITLE
Audio out of sync playback on PS3 fix

### ISSUE THREAD

**Issue by nailz420** [Franiac/TwitchLeecher#380]
Audio sync issue with network streaming playback on PS3 from Windows 10 64bit machine
https://www.twitch.tv/smoke

Fixed it by re-coding the downloaded mp4 with avidemux 2.7 with audio set to "AAC(lav)" and no other changes (audio sample rate didn't matter)

Suggestion: allow customizing ffmpeg encoding options.

**Comment by Franiac** [comment]
TL is not planned to be a fully featured re-encoding platform. Actually the plan is to eliminate ffmpeg entirely. Therefor I will not add more features depending on it.
