### ISSUE TITLE
Unable to crop while downloading raw VODs.

### ISSUE THREAD

**Issue by ScottQB4** [Franiac/TwitchLeecher#382]
Why not tell Twitch Leecher to move the .ts file from the temp folder to the destination?

**Comment by Franiac** [comment]
RTFM. The tooltip in the preferences explains exactly that. cropping is not available when downloading ts files. ffmpeg is used to crop. when downloading raw... no ffmpeg... no cropping.

**Comment by ScottQB4** [comment]
FFMpeg isn't even open until converting the combined .ts files. I even deleted FFMpeg and it _still_ merges when "cropped" (which only tells it _which_ .ts files to download, barring cut bookends, if any.) though deletes the merged file right after. If you can go through the trouble of programming a fake hurdle, then the least you can do is be honest, you pompous fuck. BTW, it has trouble with a streamer's dropped frames. Might want to check that out.

**Comment by Franiac** [comment]
LUL... you smartass really understood how TL works... NOT. Internet smartasses are welcomed to the blocked users list... so.... WELCOME 😄
