### ISSUE TITLE
End-User License Agreement not reedable

### ISSUE THREAD

**Issue by CheGad** [Franiac/TwitchLeecher#383]
Hello,

when installing TL, the License Agreement is not fully readable. The right side of the text is hidden and can not be scrolled left-right, only up-down. The window size also can not be modified.

![TL End-User License agreement](https://user-images.githubusercontent.com/56118546/66125790-353eeb00-e5e8-11e9-8e01-69d9b5d5de3b.PNG)

Kind regards,
Brad

**Comment by CheGad** [comment]
So i downloaded the new 1.7 version, because 1.5 stopped working for me. Now that I've installed it, i run into the same problem again. The download fails before starting. Here is a screenshot and the log:

![TL error](https://user-images.githubusercontent.com/56118546/66126691-5a345d80-e5ea-11e9-9ade-1e3694912dcf.PNG)

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 489293560
Selected Quality: 1152x720@30fps (Source)
Download Url: https://www.twitch.tv/videos/489293560
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: Y:\Downloads\Twitch Leecher Downloads\Китай в Раннее Средневековье.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\AN3\AppData\Local\Temp\TL_1a773c1f-3abb-4311-a79e-27e40613255b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1570177317%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A489293560%7D
Signature: c00d979ba005b2a13555f2712a4b665654080374
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\AN3\AppData\Local\Temp\TL_1a773c1f-3abb-4311-a79e-27e40613255b'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\AN3\AppData\Local\Temp\TL_1a773c1f-3abb-4311-a79e-27e40613255b'... done!

Download task ended with an error!

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\AN3\AppData\Local\Temp\TL_1a773c1f-3abb-4311-a79e-27e40613255b" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bei TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   bei TwitchLeecher.Services.Services.TwitchService.CheckTempDirectory(Action`1 log, String tempDir)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\AN3\AppData\Local\Temp\TL_1a773c1f-3abb-4311-a79e-27e40613255b" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bei TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   bei TwitchLeecher.Services.Services.TwitchService.CheckTempDirectory(Action`1 log, String tempDir)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()<---




Any ideas? A couple of weeks ago it worked perfectly fine for me.
Brad

**Comment by Franiac** [comment]
Please do not post two different issues in one 😄 

1. I'll look into the cut off text.... but we got to be honest.. who reads it? :P

As for the error:

`Der Zugriff auf den Pfad "C:\Users\AN3\AppData\Local\Temp\TL_1a773c1f-3abb-4311-a79e-27e40613255b" wurde verweigert.`

That's a permission issue. I cannot tell why you don't have the rights to write in that folder. As a sanity check you could start TL as administrator and see if that works and go from there.

**Comment by Franiac** [comment]
Fixed in 1.7.2
