### ISSUE TITLE
error with downloading

### ISSUE THREAD

**Issue by llccae** [Franiac/TwitchLeecher#384]
This is my download task. I'm Korean so theirs some Korean. sorry i rerecommend you using translator.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 467990415
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/467990415
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: A:\Twich\20190816_467990415_Just Chatting.mp4
FFMPEG Path: A:\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: A:\Twich\TL_49d65eaf-da49-4a5d-b360-06cb3b2fb332

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1570320555%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A467990415%7D
Signature: f5fe67903f7bd51e2942260f0853656ba5199b19
Sub-Only: No
Privileged: No

Creating temporary download directory 'A:\Twich\TL_49d65eaf-da49-4a5d-b360-06cb3b2fb332'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/index-muted-0GKXP50YWL.m3u8
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/720p60/index-muted-0GKXP50YWL.m3u8
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/720p30/index-muted-0GKXP50YWL.m3u8
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/480p30/index-muted-0GKXP50YWL.m3u8
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/audio_only/index-muted-0GKXP50YWL.m3u8
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/360p30/index-muted-0GKXP50YWL.m3u8
https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/160p30/index-muted-0GKXP50YWL.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/index-muted-0GKXP50YWL.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 4360

Starting parallel video chunk download
Number of video chunks to download: 4360
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/1993.ts' failed! Trying again in 20s
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadData(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/1993.ts' failed! Trying again in 20s
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadData(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/1993.ts' failed! Trying again in 20s
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadData(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'A:\Twich\TL_49d65eaf-da49-4a5d-b360-06cb3b2fb332'... done!

Download task ended with an error!

System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/1993.ts' after 3 retries!
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   위치: TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   위치: System.Threading.Tasks.Task.Execute()
   --- 내부 예외 스택 추적의 끝 ---
---> (내부 예외 #0) System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/1993.ts' after 3 retries!
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   위치: TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   위치: System.Threading.Tasks.Task.Execute()
---> (내부 예외 #0) System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/91b32eb151a80a2e298c_saddummy_35316990032_1275985681/chunked/1993.ts' after 3 retries!
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
That looks like a common corrupt VOD playlist. Twitch sometimes messes up their files. The playlist includes files that are not available on the server. There is nothing I can do about that. It's messed up on Twitches' end, sorry.
