### ISSUE TITLE
error with downloading 2

### ISSUE THREAD

**Issue by llccae** [Franiac/TwitchLeecher#385]
I'm again. i dont think so that you told me.
because this video is lately video
just same errors in every video download

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 488369191
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/488369191
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: A:\Twich\20190930_488369191_Just Chatting.mp4
FFMPEG Path: A:\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: A:\Twich\TL_30c761b1-3d4d-40c2-9440-f45617bcaf01

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1570403842%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A488369191%7D
Signature: 2f97d1eafc9455c6e7df6511ecbbc12b7c7ef1ee
Sub-Only: No
Privileged: No

Creating temporary download directory 'A:\Twich\TL_30c761b1-3d4d-40c2-9440-f45617bcaf01'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/index-muted-ANJ9N818ZT.m3u8
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/720p60/index-muted-ANJ9N818ZT.m3u8
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/720p30/index-muted-ANJ9N818ZT.m3u8
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/480p30/index-muted-ANJ9N818ZT.m3u8
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/audio_only/index-muted-ANJ9N818ZT.m3u8
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/360p30/index-muted-ANJ9N818ZT.m3u8
https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/160p30/index-muted-ANJ9N818ZT.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/index-muted-ANJ9N818ZT.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 4276

Starting parallel video chunk download
Number of video chunks to download: 4276
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts' failed! Trying again in 20s
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadData(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts' failed! Trying again in 20s
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadData(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts' failed! Trying again in 20s
System.Net.WebException: 원격 서버에서 (500) 내부 서버 오류 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadData(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Starting temporary download folder cleanup!
Deleting directory 'A:\Twich\TL_30c761b1-3d4d-40c2-9440-f45617bcaf01'... done!

Download task ended with an error!

System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts' after 3 retries!
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   위치: TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   위치: System.Threading.Tasks.Task.Execute()
   --- 내부 예외 스택 추적의 끝 ---
---> (내부 예외 #0) System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts' after 3 retries!
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   위치: TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   위치: System.Threading.Tasks.Task.Execute()
---> (내부 예외 #0) System.ApplicationException: Could not download file 'https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts' after 3 retries!
   위치: TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass63_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
I can download the given VOD without any problems. Like the log says, TL is unable to download some files. That is not the problem of TL. To check that you can click on the URLs in the log file of the failed parts:

What happens if you click on the following link?

[https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts](https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts)

Can you download this file or not?

I can download it. If you cannot there must be an issue that I am not able to reproduce or fix. Twitch has some weird region-locking going on. There were multiple errors in the past where people of different countries could not download a certain VOD whereas other people could. I am not aware what Twitch is doing.

As I states before, I cannot do anything about this. TL only tries to download files Twitch tells it to download. There is nothing to fix.

**Comment by llccae** [comment]
> I can download the given VOD without any problems. Like the log says, TL is unable to download some files. That is not the problem of TL. To check that you can click on the URLs in the log file of the failed parts:
> 
> What happens if you click on the following link?
> 
> https://vod-secure.twitch.tv/3955ae8056a45dcab3ae_saddummy_35827849552_1307923309/chunked/1135.ts
> 
> Can you download this file or not?
> 
> I can download it. If you cannot there must be an issue that I am not able to reproduce or fix. Twitch has some weird region-locking going on. There were multiple errors in the past where people of different countries could not download a certain VOD whereas other people could. I am not aware what Twitch is doing.
> 
> As I states before, I cannot do anything about this. TL only tries to download files Twitch tells it to download. There is nothing to fix.

i can download you given to me.

**Comment by Franiac** [comment]
So try again downloading the VOD...

**Comment by llccae** [comment]
> So try again downloading the VOD...

um.. i tried download again
this time i can download up to 70% of the same video.
but same error came up again..

i cant understand 'internal exception'
