### ISSUE TITLE
Feature Request: Downloading videos

### ISSUE THREAD

**Issue by EugW** [Franiac/TwitchLeecher#388]
Start downloading next video in queue right after previous one finished download.
Now we wait for first video to be finished to start downloading second
But it can be faster
If we start downloading next video when first download is finished (when comes  merging, conversion etc) it will be way faster
conversion, merging does not use the Internet, so why stand idle if you can immediately start downloading the next video

**Comment by Franiac** [comment]
This is the 10th time it gets requested. I know the deal, just wait for #46 please.
