### ISSUE TITLE
Exception not enough space

### ISSUE THREAD

**Issue by Micke3rd** [Franiac/TwitchLeecher#390]
Hi,
the app tries to use a temp folder in %user%\..\temp before copying the result to the configured download folder.
Usually the target folder has more space than the drive of %temp%. I suggest to use the target folder also for temp stuff.

**Comment by Franiac** [comment]
I strongly recommend to take a look at the preferences and read the little yellow questionmark tooltips ;)

**Comment by Micke3rd** [comment]
omg, you are right :-), thank you !  But give me a second to verify this exception, because my %temp% drive has enough space
