### ISSUE TITLE
Download while stream is still "Live"

### ISSUE THREAD

**Issue by MatthewBraun** [Franiac/TwitchLeecher#395]
It would be great to download a stream while they are live.
I would search for twitch.tv/kitboga
The leecher would see he is live
and it would download the previous segments along with real time segments. 

This might need some stitching when stream is finished with ffmpeg or something. 
I know youtube-dl can download live streams if that helps.

**Comment by Franiac** [comment]
There is a PR open for this but I need to review and maybe re-code. Patience pls 😄
