### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by Preuse** [Franiac/TwitchLeecher#398]
System.Net.WebException: The remote server returned an error: (410) Gone.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by kleanins** [comment]
same here. I hope it dissolves soon.

**Comment by Adam022695** [comment]
having the same issue

**Comment by C44RL** [comment]
same

**Comment by Physikbuddha** [comment]
Same issue here

**Comment by Ownee** [comment]
It was not only me...

**Comment by kleanins** [comment]
its just fixed

**Comment by KurtBuhagiar** [comment]
wow, thanks to whoever just fixed it.

**Comment by Codereaders** [comment]
Seems to be one of Twitches API endpoints that was temporarily down for some reason.

```
https://api.twitch.tv/api/vods/<VIDEO_ID>/access_token
```

**Comment by Preuse** [comment]
How can i solve this problem?

**Comment by Franiac** [comment]
So it's back up again? Well... not every problem is a TL problem, HA! 😄
