### ISSUE TITLE
TL 1.4

### ISSUE THREAD

**Issue by aria90** [Franiac/TwitchLeecher#399]
I updated my TL from version 1.4 to 1.7 and now I get mostly a A / V desync. It is still desync when I import the file to Sony Vegas Pro for edits.
Would you please offer a download for the old 1.4.2 or 1.4.3 version of TL (I forgot which one it was). I don't know why but it worked perfectly for me (Windows 7). Unfortunately I don't have this version on my PC anymore and I also can't find it in the internet anymore. 
Mabye someone can give me a download link.

Thank you

**Comment by KurtBuhagiar** [comment]
By desync you mean like the video is before the audio right? It's happening to me as from like an hour ago. It was working fine earlier today.

**Comment by Franiac** [comment]
A/V desync has been discussed in nearly 30 issues. There are no changes I could apply.
