### ISSUE TITLE
Incorrect link to release tag in app

### ISSUE THREAD

**Issue by greenham** [Franiac/TwitchLeecher#400]
Links to https://github.com/Franiac/TwitchLeecher/releases/tag/v1.7 which 404s instead of https://github.com/Franiac/TwitchLeecher/releases/tag/v1.7.0

iirc this isn't the first time it's happened, so maybe there's something systemic here?

**Comment by greenham** [comment]
> Guys, how freaking difficult is this to understand???

> It is fixed in 1.7.0.... That means whenever there is an update to 1.7.1 or 1.8 the update dialog of TL > 1.7.0 will work correctly. I KNOW that the dialog is wrong in 1.6.0 presenting you the wrong link, but the bug was discovered AFTER 1.6 was released.

Nice attitude. :+1:

**Comment by Franiac** [comment]
I want to see your attitude when you get your inbox shat by 200 mails of a fixed and documented bug.

**Comment by greenham** [comment]
Okay. :)
