### ISSUE TITLE
410 error?

### ISSUE THREAD

**Issue by naoup** [Franiac/TwitchLeecher#402]
System.Net.WebException: 원격 서버에서 (410) 없음 오류를 반환했습니다.
   위치: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   위치: System.Net.WebClient.DownloadString(Uri address)
   위치: TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   위치: TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

Download error
![캡처](https://user-images.githubusercontent.com/57543318/68506656-6a0c2500-02ad-11ea-9898-bc3aaa93fdd0.PNG)

**Comment by Franiac** [comment]
See #398 

That's a Twitch Fuckup 😄
