### ISSUE TITLE
Cannot install TL 1.7 - .net 4.8 install fails hash

### ISSUE THREAD

**Issue by randomname42** [Franiac/TwitchLeecher#404]
It's been a while since I've gotten any Twitch videos, and I just found that for some reason I can't seem to upgrade to 1.7.

I've tried redownloading 1.7 and running the installer as admin (I'm on Windows 10 if that matters). Same thing fails every time.

The .net setup fails after a while and pops up a box that says "0x80091007 - The hash value is not correct." The only option is to close, so I can't even start installing TL 1.7 itself.

The log file it links says this:

> [1296C:A020][2019-11-08T19:13:24]i001: Burn v3.11.1.2318, Windows v10.0 (Build 17134: Service Pack 0), path: C:\Users\User\AppData\Local\Temp\{68B23778-220C-4AA6-B135-5AE60A28D60F}\.cr\TwitchLeecher_1.7.exe
> [1296C:A020][2019-11-08T19:13:24]i000: Initializing string variable 'BUNDLE_MANUFACTURER' to value 'Franiac'
> [1296C:A020][2019-11-08T19:13:24]i000: Initializing string variable 'BUNDLE_PRODUCT_NAME' to value 'Twitch Leecher'
> [1296C:A020][2019-11-08T19:13:24]i000: Initializing string variable 'BUNDLE_PRODUCT_VERSION_PADDED' to value '1.7.0.0'
> [1296C:A020][2019-11-08T19:13:24]i000: Initializing string variable 'BUNDLE_PRODUCT_VERSION_TRIMMED' to value '1.7'
> [1296C:A020][2019-11-08T19:13:24]i009: Command Line: '"-burn.clean.room=D:\D\TwitchLeecher 1 7\TwitchLeecher_1.7.exe" -burn.filehandle.attached=668 -burn.filehandle.self=672'
> [1296C:A020][2019-11-08T19:13:24]i000: Setting string variable 'WixBundleOriginalSource' to value 'D:\D\TwitchLeecher 1 7\TwitchLeecher_1.7.exe'
> [1296C:A020][2019-11-08T19:13:24]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'D:\D\TwitchLeecher 1 7\'
> [1296C:A020][2019-11-08T19:13:25]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\User\AppData\Local\Temp\Twitch_Leecher_1.7_20191108191325.log'
> [1296C:A020][2019-11-08T19:13:25]i000: Setting string variable 'WixBundleName' to value 'Twitch Leecher 1.7'
> [1296C:A020][2019-11-08T19:13:25]i000: Setting string variable 'WixBundleManufacturer' to value 'Franiac'
> [1296C:A020][2019-11-08T19:13:25]i000: Loading prerequisite bootstrapper application because managed host could not be loaded, error: 0x80131700.
> [1296C:F39C][2019-11-08T19:13:25]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
> [1296C:F39C][2019-11-08T19:13:25]i000: Setting version variable 'WixBundleFileVersion' to value '1.7.0.0'
> [1296C:A020][2019-11-08T19:13:25]i100: Detect begin, 2 packages
> [1296C:A020][2019-11-08T19:13:25]i000: Setting string variable 'NetFxCurrent' to value '461808'
> [1296C:A020][2019-11-08T19:13:25]i102: Detected related bundle: {389fde6d-ca41-4c22-81fe-8af53375295c}, type: Upgrade, scope: PerMachine, version: 1.5.8.0, operation: MajorUpgrade
> [1296C:A020][2019-11-08T19:13:25]w120: Detected partially cached package: NetFxWeb, invalid payload: NetFxWeb, reason: 0x80070002
> [1296C:A020][2019-11-08T19:13:25]i052: Condition 'NetFxCurrent >= 528040' evaluates to false.
> [1296C:A020][2019-11-08T19:13:25]i103: Detected related package: {EF04F328-C52F-4D15-A11E-03867E017C5F}, scope: PerMachine, version: 1.5.8.0, language: 0 operation: MajorUpgrade
> [1296C:A020][2019-11-08T19:13:25]i101: Detected package: NetFxWeb, state: Absent, cached: Partial
> [1296C:A020][2019-11-08T19:13:25]i101: Detected package: TL, state: Absent, cached: None
> [1296C:A020][2019-11-08T19:13:25]i199: Detect complete, result: 0x0
> [1296C:A020][2019-11-08T19:13:26]i200: Plan begin, 2 packages, action: Install
> [1296C:A020][2019-11-08T19:13:26]i202: Planned bundle: {389fde6d-ca41-4c22-81fe-8af53375295c}, ba requested state: None over default: Absent
> [1296C:A020][2019-11-08T19:13:26]w321: Skipping dependency registration on package with no dependency providers: NetFxWeb
> [1296C:A020][2019-11-08T19:13:26]i000: Setting string variable 'NetFxFullLog' to value 'C:\Users\User\AppData\Local\Temp\Twitch_Leecher_1.7_20191108191325_000_NetFxWeb.log'
> [1296C:A020][2019-11-08T19:13:26]i201: Planned package: NetFxWeb, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
> [1296C:A020][2019-11-08T19:13:26]i201: Planned package: TL, state: Absent, default requested: Present, ba requested: None, execute: None, rollback: None, cache: No, uncache: No, dependency: None
> [1296C:A020][2019-11-08T19:13:26]i207: Planned related bundle: {389fde6d-ca41-4c22-81fe-8af53375295c}, type: Upgrade, default requested: Absent, ba requested: None, execute: None, rollback: None, dependency: None
> [1296C:A020][2019-11-08T19:13:26]i299: Plan complete, result: 0x0
> [1296C:A020][2019-11-08T19:13:26]i300: Apply begin
> [1296C:A020][2019-11-08T19:13:26]i010: Launching elevated engine process.
> [1296C:A020][2019-11-08T19:13:28]i011: Launched elevated engine process.
> [1296C:A020][2019-11-08T19:13:28]i012: Connected to elevated engine.
> [CA5C:122E4][2019-11-08T19:13:28]i358: Pausing automatic updates.
> [CA5C:122E4][2019-11-08T19:13:28]i359: Paused automatic updates.
> [CA5C:122E4][2019-11-08T19:13:28]i360: Creating a system restore point.
> [CA5C:122E4][2019-11-08T19:13:28]w363: Could not create system restore point, error: 0x80070422. Continuing...
> [CA5C:122E4][2019-11-08T19:13:28]i370: Session begin, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, options: 0x7, disable resume: No
> [CA5C:122E4][2019-11-08T19:13:28]i000: Caching bundle from: 'C:\Users\User\AppData\Local\Temp\{D0FB034C-5639-4B5B-A2D5-1AA033884F94}\.be\TwitchLeecher.exe' to: 'C:\ProgramData\Package Cache\{d1c2c779-f1ef-41e0-926a-443b289eaefd}\TwitchLeecher.exe'
> [CA5C:122E4][2019-11-08T19:13:28]i320: Registering bundle dependency provider: {d1c2c779-f1ef-41e0-926a-443b289eaefd}, version: 1.7.0.0
> [CA5C:122E4][2019-11-08T19:13:28]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: Active, restart initiated: No, disable resume: No
> [1296C:12934][2019-11-08T19:13:28]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: D:\D\TwitchLeecher 1 7\ndp48-web.exe
> [1296C:12934][2019-11-08T19:13:28]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
> [CA5C:12168][2019-11-08T19:13:36]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
> [CA5C:12168][2019-11-08T19:13:36]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
> [CA5C:12168][2019-11-08T19:13:36]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
> [CA5C:12168][2019-11-08T19:13:36]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
> [1296C:12934][2019-11-08T19:13:36]e314: Failed to cache payload: NetFxWeb from working path: C:\Users\User\AppData\Local\Temp\{D0FB034C-5639-4B5B-A2D5-1AA033884F94}\NetFxWeb, error: 0x80091007.
> [1296C:12934][2019-11-08T19:13:36]e349: Application requested retry of payload: NetFxWeb, encountered error: 0x80091007. Retrying...
> [1296C:12934][2019-11-08T19:13:36]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: D:\D\TwitchLeecher 1 7\ndp48-web.exe
> [1296C:12934][2019-11-08T19:13:39]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
> [CA5C:12168][2019-11-08T19:13:45]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
> [CA5C:12168][2019-11-08T19:13:45]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
> [CA5C:12168][2019-11-08T19:13:45]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
> [CA5C:12168][2019-11-08T19:13:45]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
> [1296C:12934][2019-11-08T19:13:45]e314: Failed to cache payload: NetFxWeb from working path: C:\Users\User\AppData\Local\Temp\{D0FB034C-5639-4B5B-A2D5-1AA033884F94}\NetFxWeb, error: 0x80091007.
> [1296C:12934][2019-11-08T19:13:45]e349: Application requested retry of payload: NetFxWeb, encountered error: 0x80091007. Retrying...
> [1296C:12934][2019-11-08T19:13:45]w343: Prompt for source of package: NetFxWeb, payload: NetFxWeb, path: D:\D\TwitchLeecher 1 7\ndp48-web.exe
> [1296C:12934][2019-11-08T19:13:48]i338: Acquiring package: NetFxWeb, payload: NetFxWeb, download from: http://go.microsoft.com/fwlink/?LinkId=2085155
> [CA5C:12168][2019-11-08T19:13:56]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, expected: 755349ECD6A478FE010E466B29911D2388F6CE94, actual: 5A84A8E612E270E27D0061D58DB6B470153BE1F9
> [CA5C:12168][2019-11-08T19:13:56]e000: Error 0x80091007: Failed to verify hash of payload: NetFxWeb
> [CA5C:12168][2019-11-08T19:13:56]e310: Failed to verify payload: NetFxWeb at path: C:\ProgramData\Package Cache\.unverified\NetFxWeb, error: 0x80091007. Deleting file.
> [CA5C:12168][2019-11-08T19:13:56]e000: Error 0x80091007: Failed to cache payload: NetFxWeb
> [1296C:12934][2019-11-08T19:13:56]e314: Failed to cache payload: NetFxWeb from working path: C:\Users\User\AppData\Local\Temp\{D0FB034C-5639-4B5B-A2D5-1AA033884F94}\NetFxWeb, error: 0x80091007.
> [1296C:A020][2019-11-08T19:13:56]e000: Error 0x80091007: Failed while caching, aborting execution.
> [CA5C:122E4][2019-11-08T19:13:56]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: None, restart: None, disable resume: No
> [CA5C:122E4][2019-11-08T19:13:56]i330: Removed bundle dependency provider: {d1c2c779-f1ef-41e0-926a-443b289eaefd}
> [CA5C:122E4][2019-11-08T19:13:56]i352: Removing cached bundle: {d1c2c779-f1ef-41e0-926a-443b289eaefd}, from path: C:\ProgramData\Package Cache\{d1c2c779-f1ef-41e0-926a-443b289eaefd}\
> [CA5C:122E4][2019-11-08T19:13:56]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{d1c2c779-f1ef-41e0-926a-443b289eaefd}, resume: None, restart initiated: No, disable resume: No
> [1296C:A020][2019-11-08T19:13:56]i399: Apply complete, result: 0x80091007, restart: None, ba requested restart:  No

**Comment by Franiac** [comment]
This is already fixed. Needs a 1.7.1 release which is not yet planned.

As a workaround you can install .NET 4.8 separately and TL 1.7 will then detect it and run the installer.
