### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by Rnadomname1234** [Franiac/TwitchLeecher#407]
So i have to download 5h+- clip but twitch leecher wont download on external hard drive because of
"There is not enough space on the disk" error. But the disk has !1.3tb! left from 1.5tb (and the video (1080p 59fps)is only like 9gb as i know from other videos that downloaded normally) . I was tkinking that theres something is wrong with the external hdd or windows but no. All the files(before merge) those 7-8 seconds clips are downloaded(Into E:\TL_572e7bb6-b1a8-4fe9-8507-1d8e309c4216). And even merged to about 90+-% as i saw. Then the error comes.

Download task has been started!

TWITCH LEECHER INFO
Version: 1.7

VOD INFO
VOD ID: 503463651
Selected Quality: 1920x1080@59fps (Source)
Download Url: https://www.twitch.tv/videos/503463651
Crop Start: No
Crop End: No

OUTPUT INFO
Disable Conversion: No
Output File: E:\Moje\twt\20191103_503463651_Grand Theft Auto V_mudrkufr.mp4
FFMPEG Path: D:\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: E:\TL_572e7bb6-b1a8-4fe9-8507-1d8e309c4216

ACCESS INFO
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1573411487%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A503463651%7D
Signature: fde6d0765e0ca96f82565d5472abd42e256015fb
Sub-Only: No
Privileged: No

Creating temporary download directory 'E:\TL_572e7bb6-b1a8-4fe9-8507-1d8e309c4216'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/chunked/index-muted-KE8FYUUTZL.m3u8
https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/720p60/index-muted-KE8FYUUTZL.m3u8
https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/480p30/index-muted-KE8FYUUTZL.m3u8
https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/audio_only/index-muted-KE8FYUUTZL.m3u8
https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/360p30/index-muted-KE8FYUUTZL.m3u8
https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/160p30/index-muted-KE8FYUUTZL.m3u8

Playlist url for selected quality 1920x1080@59fps (Source) is https://vod-secure.twitch.tv/73c6f2dc3ad5c8a2ffdb_mudrkufr_124772481_7847138/chunked/index-muted-KE8FYUUTZL.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1747

Starting parallel video chunk download
Number of video chunks to download: 1747
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'E:\TL_572e7bb6-b1a8-4fe9-8507-1d8e309c4216\20191103_503463651_Grand Theft Auto V_mudrkufr.ts'...

Starting temporary download folder cleanup!
Deleting directory 'E:\TL_572e7bb6-b1a8-4fe9-8507-1d8e309c4216'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
at System.IO.FileStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action1 log, Action1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.b__2()
at System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: There is not enough space on the disk.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
at System.IO.FileStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action1 log, Action1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.b__2()
at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Can you please confirm that your HDD is fomatted with the NTFS file system? Because if it's FAT32, the maximum size of a file is 4GB and that will definitely make trouble with a 5hr VOD.

**Comment by Rnadomname1234** [comment]
Oh so thats the problem. well... can i see somwhere how big the file will be? But thanks.

**Comment by Codereaders** [comment]
@Rnadomname1234 That depends on several parameters.
You could do some approximation.

Twitch delivers VoDs parted in multiple chunks. All chunks but the last one are roughly of the same size. So you need to know the last chunk's size (`last_chunk_size`), any other chunk's size (`any_chunk_size`) and the total number of chunks (`number_of_chunks`). The number of chunks comes almost for free, but you need to download the two chunks to get their file sizes.
Given you have those information, you can do your approximation:

```
filesize = (number_of_chunks - 1) * any_chunk_size + last_chunk_size
```

But that's only an approximation for the final file size.
As some processing steps might even double total file size for a short period of time.

**Comment by Franiac** [comment]
@Codereaders thx for the explanation.

Closed for FAT reason 😄
