### ISSUE TITLE
Small Misspelling in options screen 

### ISSUE THREAD

**Issue by poklj** [Franiac/TwitchLeecher#41]
![twitchleecher_2016-06-30_13-07-39](https://cloud.githubusercontent.com/assets/7953696/16495407/a9400194-3ec3-11e6-93a9-fb7f3a544cb0.png)

"Check fo updates" Should be replaced with "Check for updates"

**Comment by Franiac** [comment]
Heh... ops :D

**Comment by Franiac** [comment]
:tada:
