### ISSUE TITLE
Error when file is attempting to convert

### ISSUE THREAD

**Issue by fidorulz** [Franiac/TwitchLeecher#411]
So updated to 1.7.1 and attempting to download a specific VOD and after downloading and merging when attempting to convert it results in ERROR

Other VODs are ok. Im just reporting this in case this can occur with other VODs down the road.

No big deal

Here are the logs

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.7.1

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 506792668
Selected Quality: 640x360@30fps
Download Url: https://www.twitch.tv/videos/506792668
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\fidorulz\Desktop\Mega\20191110_506792668_Talk Shows & Podcasts.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1573735979%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A506792668%7D
Signature: da8e2c004b83a967b21c24ce05b9b3fefe030d7a
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/720p30/index-dvr.m3u8
https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/480p30/index-dvr.m3u8
https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/audio_only/index-dvr.m3u8
https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/360p30/index-dvr.m3u8
https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/160p30/index-dvr.m3u8

Playlist url for selected quality 640x360@30fps is https://vod-secure.twitch.tv/de8c79fac6e27fb7f229_mega64podcast_36190310640_1330589419/360p30/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 527

Starting parallel video chunk download
Number of video chunks to download: 527
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e\20191110_506792668_Talk Shows & Podcasts.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e\20191110_506792668_Talk Shows & Podcasts.ts'...
Command line arguments: -y -i "C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e\20191110_506792668_Talk Shows & Podcasts.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy "C:\Users\fidorulz\Desktop\Mega\20191110_506792668_Talk Shows & Podcasts.mp4"

ffmpeg version N-93529-g8e3b01e20e Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20190212
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 26.100 / 56. 26.100
libavcodec     58. 48.101 / 58. 48.101
libavformat    58. 26.101 / 58. 26.101
libavdevice    58.  7.100 / 58.  7.100
libavfilter     7. 48.100 /  7. 48.100
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
[h264 @ 000000d2ff58c140] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 000000d2ff58c140] decode_slice_header error
[h264 @ 000000d2ff58c140] no frame!
[h264 @ 000000d2ff58c140] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 000000d2ff58c140] decode_slice_header error
[h264 @ 000000d2ff58c140] no frame!
[h264 @ 000000d2ff58c140] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 000000d2ff58c140] decode_slice_header error
[h264 @ 000000d2ff58c140] no frame!
[h264 @ 000000d2ff58c140] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 000000d2ff58c140] decode_slice_header error
[h264 @ 000000d2ff58c140] no frame!
[h264 @ 000000d2ff58c140] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 000000d2ff58c140] decode_slice_header error
[h264 @ 000000d2ff58c140] no frame!
[mpegts @ 000000d2ff58ab40] decoding for stream 1 failed
[mpegts @ 000000d2ff58ab40] Could not find codec parameters for stream 1 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e\20191110_506792668_Talk Shows & Podcasts.ts':
Duration: 01:27:45.79, start: 73.166000, bitrate: 683 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 61 kb/s
Stream #0:1[0x101]: Video: h264 ([27][0][0][0] / 0x001B), none, 30 tbr, 90k tbn, 180k tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream mapping:
Stream #0:1 -> #0:0 (copy)
Stream #0:0 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[mp4 @ 000000d2ff5ff780] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --
[aac @ 000000d2ff606940] Qavg: nan
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\fidorulz\AppData\Local\Temp\TL_b9866c72-79fe-4d13-9256-cc4d0b535a6e'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass58_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass58_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
> Could not find codec parameters for stream 1

Very clear message from ffmpeg that the source file is corrupted. That is nothing TL can change. In the web player the video starts playing back very choppy. Maybe that's the issue.

You could try disabling mp4 conversion in the preferences and see if you can work with the raw .ts file instead. Other than that I cannot help you with this one.
