### ISSUE TITLE
"Use Costom Filename" button

### ISSUE THREAD

**Issue by JeronemoFive** [Franiac/TwitchLeecher#413]
Hello. Is it possible to make this option ("Use Costom Filename") automatically enabled when downloading a file? Now every time you have to click on it to change the file name, and this is annoying, creates useless difficulties (especially when dealing with many downloads). Can you fix it please? (there were no such formalities on older versions)
![photo](https://user-images.githubusercontent.com/57756810/68857602-8f10f580-06fc-11ea-8f63-8436b446279e.PNG)

**Comment by Franiac** [comment]
Absolutely not. The filename template in the preferences should be set so that you don't need to change it everytime by hand. Why are you making your life more difficult? 😄
Set the filemane template to the desired value and never have to change anything anymore. I think that's the best solution.

And if we think ahead we will be able to download multiple videos (selecting them in the search result view). There needs to be an automated filename system. Think about downloading 100 videos and you have to step through every single one? Nah...

I honestly don't know many user who use this switch anyway, so there is nothing to change.

**Comment by JeronemoFive** [comment]
you apparently misunderstood me. I don't say anything about the filename template. I'm talking about a "Use Costom Filename" button. Is it possible to make it automatically turned on (now you have to constantly turn it on manually to change the file names)
![sugest](https://user-images.githubusercontent.com/57756810/68887077-c352d900-0731-11ea-889f-a58e211fa8ad.png)

**Comment by Franiac** [comment]
I did not misunderstand you 😄 

I will not enable the checkbox by default, because that is not how the majority of the users use TL.

**Comment by JeronemoFive** [comment]
Thanks for answer! Is it very difficult to made a 'choice option' (“Check mark always on” or “always off”) in settings in future updates? This will not affect the "majority" in any way (some of them i'm sure will even appreciate it), but at the same time it will make working with the program for the "minority" much more convenient.

**Comment by Franiac** [comment]
@JeronemoFive I am hesitant regarding those changes. I want to keep the software as clean as possible. If I start this now we will have an option in the preferences for every single control in the entire UI. My dev-experience tells me I should not do it, honestly.

**Comment by JeronemoFive** [comment]
@Franiac thanks for reply! Honestly, I see no reason why this one added option should trigger a domino effect. In fact, most of the functions in the program are already “democratic” (if I may say so). If you don't consider it right to add such an option in the settings. Maybe it is possible to do that like this - if you manually checked the box once, then the next time you click the download button, the checkbox will already be checked, if you uncheck it after that, then the next time you press download button, there will be no checkmark there.
I hope you could understand my broken English, I made an illustration just in case :)
![omg](https://user-images.githubusercontent.com/57756810/68978533-7562d180-0814-11ea-97b1-bbc6cbbf24d9.png)
