### ISSUE TITLE
Solution of 410 Error on only login state. (BUG IN 1.7.1)

### ISSUE THREAD

**Issue by sfsepark** [Franiac/TwitchLeecher#414]
After 1.7.1 patch, 410 errors were found again.
When you log in on TL, you get 410 Error on any video download
But if you reset the user setting of TL, you won't get 410 Error.

I used the chrome developer tool to observe the network on the video replay page of the Twitch Front End.

Twitch is using a request URL such as " https://api.twitch.tv/api/vods/508093581/access_token?oauth_token=4yvywu5fvbcli4q6gg2l32cj5cijgc&need_https=true&platform=web&player_type=site&player_backend=mediaplayer " to get sig.

However, TL is sending the request URL such as "https://api.twitch.tv/api/vods/{0}/access_token " from the  'RetrieveVodAuthInfo' function of "TwitchLeecher/TwitchLeecher.Services/Services/TwitchService.cs"
regardless of the login status.

And, there is no 'Authorization' property in request header of XHR(to get sig) on Twitch frontend .

SO, Here is my solution.

1. Use ' _twitchAuthInfo.AccessToken ' as a query parameter for the Request URL in line 212 
2. Use 'CreateTwitchWebClient()' instead 'CreateAuthorizedTwitchWebClient()' on 'RetrieveVodAuthInfo' function

I'm sorry I sent you an issue without testing it.
I hope the problem will be solved soon.

**Comment by Tomijs** [comment]
@sfsepark is there a way to avoid 410 Error without waiting for update? :?

**Comment by sfsepark** [comment]
@Tomijs  No. There's no other way but to re-compile.

**Comment by Tomijs** [comment]
@sfsepark I just emptied the "C:\Users\{user}\AppData\Roaming\Twitch Leecher" and the error is gone. Not exactly what You suggested but did the same job by resetting settings as well. Anyway, now I can download videos. :)

**Comment by vyperszn** [comment]
@Tomijs what version of twitch leecher are u using? I am still having that error after i empty the folder! Please help

**Comment by Franiac** [comment]
@sfsepark You have to differentiate between the web client to the v5 Kraken API and the private Tiwtch API for retrieving the auth info and video playlist.

https://dev.twitch.tv/docs/authentication#sending-user-access-and-app-access-tokens

For the Public v5 API you MUST include the Authorization header, otherwise you won't get any info from the API when using scoped calls.

the interesting point is that the public and private API worked the same way so far. I also saw that the public API now uses the query parameter but in all the hassle and email spam I did not test the 1.7.1 update with a logged in account.

I need some testing for that.

**Comment by Franiac** [comment]
@sfsepark And just in order to confirm:

The reason why you got the 410 in 1.7.1 was because you had an auth token in the user settings (you were logged in). Cleaning the settings delets the access token and therefor works. If you login again, it fails again...

**Comment by vyperszn** [comment]
@Franiac is twitch leecher working now?

**Comment by Franiac** [comment]
@vyperszn please don't post unrealated stuff in github issues. 1.7.1 only works when you are not logged in

**Comment by w4hnsinn** [comment]
> I did not test the 1.7.1 update with a logged in account.

Not sure if that helps, but I downloaded a sub-only vod yesterday directly after updating to 1.7.1, so at least I can confirm it worked for a time before breaking again.

**Comment by Franiac** [comment]
Fixed & closed...

I will roll out 1.7.2 later.

**Comment by vyperszn** [comment]
410 Error on only login state is happening again
