### ISSUE TITLE
Can't download Subscriber-Only VODs

### ISSUE THREAD

**Issue by nullified071** [Franiac/TwitchLeecher#416]
TwitchLeecher Version:  1.7.2
Operating System: Windows 8.1 64-bit
When trying to download subscriber only  VODs I get the message "This video is sub-only but you are not subscribed"
Have tried multiple video urls, IDs and channels and all have the same result

**Comment by itsmeduhdoi** [comment]
me too

**Comment by Franiac** [comment]
the thing is... i cannot test it. i am not subscribed to anyone who makes his videos sub-only.

**Comment by Franiac** [comment]
@nullified071 If you want to help, please send me an email to contact@franiac.com. i can provide you with test builds of TL to find out if we can make it work.

**Comment by nullified071** [comment]
@Franiac Sent you an email!

**Comment by Franiac** [comment]
@nullified071 I sent you an answer with the link like 5 hours ago... check spam maybe?

**Comment by Franiac** [comment]
Here's the todo list for everyone who wants to help. Don't use this build in any productive way, only for testing the sub downloads!

https://franiac.com/TL.7z

- Unpack
- Run TwitchLeecher.exe
- Search for the video
- Click Download
- A File named "SUB_LOG.log" gets written to the same directory as TwitchLeecher.exe
- Send me that file pls

**Comment by A-Few-Asians** [comment]
{
  "token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p30\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1573854513,\"https_required\":false,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":507963168}",
  "sig": "61314fdfddb6d861d7f912b05dfc2d04a216fe2b",
  "expires_at": "2019-11-15T21:48:33Z"
}

**Comment by jkhrisjj** [comment]
{
  "token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p30\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1573856465,\"https_required\":false,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":508137612}",
  "sig": "fef07a4d2fcf3c7f691a2c652f00e25fd3946485",
  "expires_at": "2019-11-15T22:21:05Z"
}

**Comment by psyclone1982** [comment]
{
  "token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p30\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1573859534,\"https_required\":false,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":507988664}",
  "sig": "2f5538e8d498feb38aaf98e525aa0064537d1048",
  "expires_at": "2019-11-15T23:12:14Z"
}

**Comment by mouarflenoob** [comment]
I just signed in twitch in order to watch the video I am trying to download, and it works. Here is the log file : 

{
  "token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p30\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1573867219,\"https_required\":false,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":508465676}",
  "sig": "8f24c8d08745a94cbbc307e9ecb9d8b51f405849",
  "expires_at": "2019-11-16T01:20:19Z"
}
[SUB_LOG.log](https://github.com/Franiac/TwitchLeecher/files/3849918/SUB_LOG.log)

**Comment by DracoDruid** [comment]
Same here:

{
  "token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p30\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1573880097,\"https_required\":false,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":508465676}",
  "sig": "ffa192dbc2d9acdb14c0be07c138268864bc12a7",
  "expires_at": "2019-11-16T04:54:57Z"
}

@Franiac : I just wanted to take the time and tell you how grateful I am for you to take your time and create and improve this great little piece of software. Thank you very much for all your time and effort!

**Comment by gibmeseeds** [comment]
I have the exact same problem with what everyone mentioned above.

{
  "token": "{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[\"160p30\",\"360p30\",\"480p30\",\"720p30\",\"720p60\",\"audio_only\",\"chunked\"]},\"device_id\":null,\"expires\":1573879316,\"https_required\":false,\"privileged\":false,\"user_id\":null,\"version\":2,\"vod_id\":507013560}",
  "sig": "fec038cadaa35321482d1298f779b407138e9791",
  "expires_at": "2019-11-16T04:41:56Z"
}

**Comment by Franiac** [comment]
File has been deleted from the webspace... that's enough tests

**Comment by Franiac** [comment]
Ok, the "privileged" flag should be "true" if you are logged in and subscribed, so that's odd.

Now we have 3 options:

1. Please check if TL 1.7.1 works (I thought it would not, but some people seem to have it work)

2. Someone gift me a sub to the channel and post me a link to the sub-only video so I can test by myself (probably the fastest method, but involves money) 😄 

3. If you are familiar with the Chrome DevTools and checking out requests and responses, here is what you can do:
- Go to the channel that has sub-only videos
- Go to the "Videos" section and find a sub-only video in the list
- press F12 to open the DevTools
- Go to Network Tab
- Clear the request list
- Click on the video
- When the video starts to play back, stop the request recording in the network tab
- Look for calls to "https://api.twitch.tv/api/vods/[videoID]/access_token........."
- Post the COMPLETE request url, request headers and response body (JSON) here

Any help is appreciated!

**Comment by Franiac** [comment]
@Paticern Can you please confirm that you are also able to download NON sub-only videos if you are logged in (green checkmark).

**Comment by Franiac** [comment]
@Paticern I iknow that the auth header is missing because i deleted it myself :P
The token gets sent by query parameter now (which actually was the error, why it didn't work). Now I am confused whether the request needs both or not.

**Comment by Paticern** [comment]
>     3. If you are familiar with the Chrome DevTools and checking out requests and responses, here is what you can do:
> 
> 
>     * Go to the channel that has sub-only videos
> 
>     * Go to the "Videos" section and find a sub-only video in the list
> 
>     * press F12 to open the DevTools
> 
>     * Go to Network Tab
> 
>     * Clear the request list
> 
>     * Click on the video
> 
>     * When the video starts to play back, stop the request recording in the network tab
> 
>     * Look for calls to "[https://api.twitch.tv/api/vods/[videoID]/access_token](https://api.twitch.tv/api/vods/%5BvideoID%5D/access_token)........."
> 
>     * Post the COMPLETE request url, request headers and response body (JSON) here

Request (1):
```
OPTIONS /api/vods/xxxxxxxxx/access_token?need_https=true&oauth_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&platform=_&player_backend=mediaplayer&player_type=site HTTP/1.1
Host: api.twitch.tv
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,client-id,content-type,twitch-api-token,x-device-id,x-requested-with
Referer: https://www.twitch.tv/videos/xxxxxxxxx
Origin: https://www.twitch.tv
DNT: 1
Connection: keep-alive
```
Response headers (1):
```
HTTP/2.0 200 OK
access-control-allow-credentials: true
access-control-allow-headers: authorization,client-id,content-type,twitch-api-token,x-device-id,x-requested-with
access-control-allow-methods: GET
access-control-allow-origin: https://www.twitch.tv
access-control-max-age: 600
cache-control: no-cache, no-store, must-revalidate, private
expires: 0
pragma: no-cache
timing-allow-origin: https://www.twitch.tv
accept-ranges: bytes
date: Fri, 15 Nov 2019 09:39:17 GMT
via: 1.1 varnish, 1.1 varnish
age: 0
x-served-by: cache-sea4468-SEA, cache-man4127-MAN
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1573810757.246805,VS0,VS0,VE137
vary: Accept-Encoding
strict-transport-security: max-age=300
content-length: 0
X-Firefox-Spdy: h2
```
(emtpy response body)

Request:
```
GET /api/vods/xxxxxxxxx/access_token?need_https=true&oauth_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&platform=_&player_backend=mediaplayer&player_type=site HTTP/1.1
Host: api.twitch.tv
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: application/vnd.twitchtv.v5+json; charset=UTF-8
Accept-Language: en-us
Accept-Encoding: gzip, deflate, br
Referer: https://www.twitch.tv/videos/xxxxxxxxx
Client-ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
X-Device-Id: xxxxxxxxxxxxxxxx
X-Requested-With: XMLHttpRequest
Content-Type: application/json; charset=UTF-8
Authorization: OAuth xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Twitch-Api-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Origin: https://www.twitch.tv
DNT: 1
Connection: keep-alive
Cookie: unique_id=xxxxxxxxxxxxxxxx; server_session_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; twitch.lohp.countryCode=DE; api_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; spare_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D%3D; persistent=xxxxxxxx%3A%3Axxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sudo=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; bits_sudo=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; login=xxxxxxxxxxxxxx; name=xxxxxxxxxxxxxx; last_login=2019-11-15T08:58:58Z; twilight-user={%22authToken%22:%22xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%22%2C%22displayName%22:%22xxxxxxxxxxxxxx%22%2C%22id%22:%22xxxxxxxx%22%2C%22login%22:%22xxxxxxxxxxxxxx%22%2C%22roles%22:{%22isStaff%22:false}%2C%22version%22:2}; auth-token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Response headers:
```
HTTP/2.0 200 OK
content-type: application/json; charset=utf-8
access-control-allow-credentials: true
access-control-allow-origin: https://www.twitch.tv
cache-control: no-cache, no-store, must-revalidate, private
expires: 0
pragma: no-cache
timing-allow-origin: https://www.twitch.tv
accept-ranges: bytes, bytes, bytes, bytes
age: 0, 0, 0, 0
date: Fri, 15 Nov 2019 09:39:17 GMT
via: 1.1 varnish, 1.1 varnish
x-served-by: cache-sea4457-SEA, cache-man4127-MAN
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1573810757.451973,VS0,VS0,VE223
vary: Accept-Encoding
strict-transport-security: max-age=300
content-length: 353
X-Firefox-Spdy: h2
```
Response body:
```{"token":"{\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"chansub\":{\"restricted_bitrates\":[]},\"device_id\":\"xxxxxxxxxxxxxxxx\",\"expires\":1573882757,\"https_required\":true,\"privileged\":true,\"user_id\":xxxxxxxx,\"version\":2,\"vod_id\":xxxxxxxxx}","sig":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","expires_at":"2019-11-16T05:39:17Z"}```

**Comment by Paticern** [comment]
> @Paticern Can you please confirm that you are also able to download NON sub-only videos if you are logged in (green checkmark).

I just tried that and it seems to work

**Comment by DracoDruid** [comment]
@Franiac: I am willing to gift you a channel subscription for a month

**Comment by Paticern** [comment]
> @Paticern I iknow that the auth header is missing because i deleted it myself :P
> The token gets sent by query parameter now (which actually was the error, why it didn't work). Now I am confused whether the request needs both or not.

By looking at the requests from my browser the OAuth token is sent in 4 places: the query parameter, the authorization header, as authToken in the JSON string of twilight-user-cookie and in the auth-token-cookie

**Comment by w4hnsinn** [comment]
> Ok guys, some new attempts:

> Please tell me what works with what build.

8 of the 9 test downloads worked. Only fail was the sub-only video using build 3 ("this video is subscriber-only but you are not subscribed..")

**Comment by Paticern** [comment]
I got the same results as @w4hnsinn.

**Comment by Franiac** [comment]
@Paticern In the 2nd request can you please confirm that the query parameter "access_token" is the same token compared to the header "Authentication"?

Thx guys so far, I think I figured it out... will provide a "release candidate" build soon for testing.

**Comment by Paticern** [comment]
> @Paticern In the 2nd request can you please confirm that the query parameter "oauth_token" is the same token compared to the header "Authentication"?

Yes, the value of oauth_token query parameter is the same as the OAuth token in the Authorization header.

**Comment by Franiac** [comment]
Here we go again:

https://franiac.com/TL.7z

3 tests to do:

Download a NON sub-only video without being logged in (no green checkmark in the titlebar)
Download a NON sub-only video while being logged in (green checkmark in the titlebar)
Download a SUB-ONLY video while being logged in (green checkmark in the titlebar)

**Comment by DracoDruid** [comment]
All 3 work for me now!

**Comment by Paticern** [comment]
Everything works for me as well.

**Comment by Franiac** [comment]
Apparently the request must contain the query parameter **AND** the header. Who the fuck designed this API???

Thanks for the nice work guys! TL 1.7.3 is coming soon (TM) 😈

**Comment by Franiac** [comment]
As for future testing could you all please post one or more streamers who hide their videos behind teh sub wall? I just need a list of Twitch channels I could possible sub to in order to test sub-only downloads by myself.

**Comment by DracoDruid** [comment]
If you like Dungeons & Dragons / Pen-&-Paper RPGs: https://www.twitch.tv/criticalrole

**Comment by Paticern** [comment]
@DracoDruid I was about to make the same recommendation

**Comment by Paticern** [comment]
@Franiac I think there was a bit of a misunderstanding, it should be `Headers.Add(TWITCH_AUTHORIZATION_HEADER, "OAuth " + _twitchAuthInfo.AccessToken);` in https://github.com/Franiac/TwitchLeecher/commit/c5347cff127724754377328449a471e9b7f4d2ee#diff-24776de1038a3bd1a341713aa05b1ed4R211 (just as in version 1.7.1).
But if the release contained the same line, maybe both versions work?

**Comment by Franiac** [comment]
@Paticern LOL, that was not a misunderstanding, I am just plain stupid...

The whole time in 1.7.1 the query param was named "access_token" and not "oauth_token"... how did I not see this? So I think it actually can work without the "Authorization" header.

Let's try this one more time...

**Comment by Franiac** [comment]
I hope this is the last time now, Jesus:

https://franiac.com/TL.7z

I left both in now, the query param and the header because that is how the website does it.
The query param is named "oauth_token" and the header is "Authorization: OAuth XXXXXXXXXXXXXXXXX"

As always:
-Download a NON sub-only video without being logged in (no green checkmark in the titlebar)
-Download a NON sub-only video while being logged in (green checkmark in the titlebar)
-Download a SUB-ONLY video while being logged in (green checkmark in the titlebar)

This is one messed up issue, oh my god 😄

**Comment by Paticern** [comment]
Everything works with the new version.

**Comment by DracoDruid** [comment]
Gimme a hot sec...

**Comment by MrDummyNL** [comment]
I am the Twitch streamer, so i can help with the tests and can also setup some sub-only videos for testing. So you can ask me for help. :-) If you need sub, i will give it to you for testing reason.

Good to see problem is solved.

**Comment by Franiac** [comment]
@MrDummyNL what's your channel name? are you "criticalole"?

**Comment by MrDummyNL** [comment]
MrDummy_NL is my Twitch channel. Only normal videos yet, but can setup for testing purposes.

**Comment by Franiac** [comment]
TL 1.7.3 is released. I hope that's it for the 410 nightmare... Closed

**Comment by Franiac** [comment]
See #419 

Do you understand how fucking much I hate Twitch right now?
