### ISSUE TITLE
Live Broadcast Download Issue on 60fps streams

### ISSUE THREAD

**Issue by ChaoticPapaya** [Franiac/TwitchLeecher#42]
Live Broadcast download issue with 60fps streams the audio is always desynced.
Live Broadcast with 30 fps works fine with no desync

Post stream broadcast download of 60fps is fine with no desync
Post stream broadcast download of 30fps is fine with no desync

**Comment by Franiac** [comment]
Uhm, I think this is a misunderstanding. TL is no live-encoder or whatsoever. I am even surprised, that you can already download "live" broadcasts. After finishing a stream, Twitch post-processes the broadcast. If that is done, it's TL-ime not before. If you want to use harddisk recording while streaming, OBS is the tool to go, not TL.
