### ISSUE TITLE
Error at program startup appcrash

### ISSUE THREAD

**Issue by Giddrozzz** [Franiac/TwitchLeecher#420]
Hello, when installing the program, asked to download the framework, I downloaded, asked to restart the computer and automatically rebooted, now after starting and re-downloading and trying to install an error and writes Имя события проблемы:	APPCRASH   Имя приложения:	TwitchLeecher.exe   Версия приложения:	1.7.3.0   Отметка времени приложения:	5a10ad86   Имя модуля с ошибкой:	KERNELBASE.dll   Версия модуля с ошибкой:	6.1.7601.18798   Отметка времени модуля с ошибкой:	5507b485   Код исключения:	c06d007e   Смещение исключения:	0000c42d   Версия ОС:	6.1.7601.2.1.0.256.1   Код языка:	1049   Дополнительные сведения 1:	0a9e   Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789   Дополнительные сведения 3:	0a9e   Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789  if you speak Russian, answer in Russian, I am not strong in English, I use Google translator

Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by Franiac** [comment]
I have no clue what your error message says and no, I don't speak russian, sorry

**Comment by Giddrozzz** [comment]
Here is an error with the translation or you say that you do not know why such an error can be?

Problem event name: APPCRASH application Name: TwitchLeecher.exe application Version: 1.7.3.0 application Timestamp: 5a10ad86 error module Name: KERNELBASE.dll module Version with error: 6.1.7601.18798 module Timestamp with error: 5507b485 exception Code: c06d007e exception Offset: 0000c42d OS Version: 6.1.7601.2.1.0.256.1 language Code: 1049 Additional information 1: 0a9e Additional information 2: 0a9e372d3b4ad19135b953a78882e789 Additional information 3: 0a9e Additional information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by Franiac** [comment]
#421
