### ISSUE TITLE
Requires download framework when installing

### ISSUE THREAD

**Issue by Giddrozzz** [Franiac/TwitchLeecher#421]
Hello, when I want to install the program, it says that you need to install Microsoft .Net Framework, if I install it, then I have an error, please tell me what version of the framework is needed, so I installed it myself in advance and when I installed the program, there was no request for it

Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by Codereaders** [comment]
The most current version should be fine, I'd say.
Currently this should be [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework) (2019-04-18)

**Comment by Giddrozzz** [comment]
thank you, but If I install version 4.7 or 4.8, the program crashes and does not start, and if lower, it requires utsanovit 4.8, such a situation, what can I do?

**Comment by Franiac** [comment]
Please stop opening up issues without providing the requested infos:

https://github.com/Franiac/TwitchLeecher#support--issues

Please read this and answer the questions accordingly, otherwise I will close the issues. We cannot make guessing games here.

**Comment by Giddrozzz** [comment]
What information should be provided?

**Comment by Codereaders** [comment]
Read the link provided by @Franiac and the preset text in new bug report form:
> https://github.com/Franiac/TwitchLeecher#support--issues

> Provide the version of Twitch Leecher you are using
> Provide as much information about the VOD as possible (Url, Channel, ID)
> Provide information about your operating system (e.g. Windows 10 64 Bit)
> Try to describe the problem as detailed as possible, I cannot read your mind ;)
> Is there any additional information about the issue that might be interesting for me? Write it down!
> When you have a problem with a download, provide the download log created by Twitch Leecher (see screenshot below)

**Comment by Giddrozzz** [comment]
thank you

**Comment by Giddrozzz** [comment]
I'm sorry) I have version  Twitch Leecher 1.7.3 , Windows 7 64 bit, If I install .net Framework version 4.8, then when I try to install Twitch Leecher, Twitch Leecher fails: problem event Name: APPCRASH error module Name: KERNELBASE.dll program Stopped working. Additional information: If I install .net Framework 4.5, then I have sony vegas pro running, but Twitch Leecher needs .net Framework 4.8, when I install .net Framework 4.8 I also fail and sony vegas pro, yesterday I still reinstalled windows, maybe something is related to this, but before everything worked, windows is the same as it was

> Please stop opening up issues without providing the requested infos:
> 
> https://github.com/Franiac/TwitchLeecher#support--issues
> 
> Please read this and answer the questions accordingly, otherwise I will close the issues. We cannot play guessing games here.

I'm sorry) I have version  Twitch Leecher 1.7.3 , Windows 7 64 bit, If I install .net Framework version 4.8, then when I try to install Twitch Leecher, Twitch Leecher fails: problem event Name: APPCRASH error module Name: KERNELBASE.dll program Stopped working. Additional information: If I install .net Framework 4.5, then I have sony vegas pro running, but Twitch Leecher needs .net Framework 4.8, when I install .net Framework 4.8 I also fail and sony vegas pro, yesterday I still reinstalled windows, maybe something is related to this, but before everything worked, windows is the same as it was

**Comment by Giddrozzz** [comment]
> Please stop opening up issues without providing the requested infos:
> 
> https://github.com/Franiac/TwitchLeecher#support--issues
> 
> Please read this and answer the questions accordingly, otherwise I will close the issues. We cannot play guessing games here.

I'm sorry) I have version  Twitch Leecher 1.7.3 , Windows 7 64 bit, If I install .net Framework version 4.8, then when I try to install Twitch Leecher, Twitch Leecher fails: problem event Name: APPCRASH error module Name: KERNELBASE.dll program Stopped working. Additional information: If I install .net Framework 4.5, then I have sony vegas pro running, but Twitch Leecher needs .net Framework 4.8, when I install .net Framework 4.8 I also fail and sony vegas pro, yesterday I still reinstalled windows, maybe something is related to this, but before everything worked, windows is the same as it was

**Comment by Giddrozzz** [comment]
> Read the link provided by @Franiac and the preset text in new bug report form:
> 
> > https://github.com/Franiac/TwitchLeecher#support--issues
> 
> > Provide the version of Twitch Leecher you are using
> > Provide as much information about the VOD as possible (Url, Channel, ID)
> > Provide information about your operating system (e.g. Windows 10 64 Bit)
> > Try to describe the problem as detailed as possible, I cannot read your mind ;)
> > Is there any additional information about the issue that might be interesting for me? Write it down!
> > When you have a problem with a download, provide the download log created by Twitch Leecher (see screenshot below)

thank you

**Comment by Franiac** [comment]
If I get this right you even have problems installing .NET 4.8 from the Microsoft installer, right?

If this is the case I we cannot really help you since it is not a problem related to TL but the installation process of .NET Framework 4.8 in general.

**Comment by Giddrozzz** [comment]
> If I get this right you even have problems installing .NET 4.8 from the Microsoft installer, right?
> 
> If this is the case I we cannot really help you since it is not a problem related to TL but the installation process of .NET Framework 4.8 in general.

It's bad :( but thanks :)
Topic can be closed, the question is not on topic, if you may have ever faced with similar, I don't know what could be the problem?
