### ISSUE TITLE
Error 410 when trying to download sub-only vods

### ISSUE THREAD

**Issue by bhdrozgn** [Franiac/TwitchLeecher#424]
Version: 1.7.3
Channel: CanSungur ([https://www.twitch.tv/cansungur])
OS: Windows 10 64 Bit

I got this error when i try to download sub-only vods. Yes, i already connected my twitch account and subbed to that channel.
![image](https://user-images.githubusercontent.com/45441291/69009744-7ce7bf00-0969-11ea-821a-2b00dee1eeba.png)

and the log files:
`System.Net.WebException: Uzak sunucu hata döndürdü: (410) Gitti.
   konum: System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   konum: System.Net.WebClient.DownloadString(Uri address)
   konum: TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   konum: TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)`

**Comment by qfavor** [comment]
Hello! I am still encountering this error, even after updating to the latest release. Can you please look into it?

**Comment by Franiac** [comment]
@qfavor  Man, just take a look at the open issues....
