### ISSUE TITLE
Twitch Leecher only downloads audio.

### ISSUE THREAD

**Issue by Larrythemerchant** [Franiac/TwitchLeecher#427]
Hello.
Twitch leecher seems to only download audio even if i try to change amount of video it has to download.
I use 1.7.3 twitch leecher version.
WIN 10 64BIT
Thanks for help in advance.

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher#support--issues

**Comment by Larrythemerchant** [comment]
> https://github.com/Franiac/TwitchLeecher#support--issues

Well, here's the video URL https://www.twitch.tv/videos/509674612
also the video lags a bit till it gets to 8th second.
If there's anything i should tell about, if thats not a problem of course could you tell me.
Thanks.

**Comment by Franiac** [comment]
if cropping doesn't cut it you could try disabling conversion to mp4 in the preferences (which bypasses any kind of processing on the source file) and see if that works. if not, the video is already corrupted on Tiwtch.
