### ISSUE TITLE
Audio Desync after downloading VOD

### ISSUE THREAD

**Issue by aingc** [Franiac/TwitchLeecher#428]
- Twitch Leecher Version: 1.7.3
- VOD Info
  URL: [https://www.twitch.tv/videos/508824775](url)
  Channel: Battle Lounge
  Start: 06:37:55, End: 08:59:20
- OS: Windows 10 Education (64-Bit)
- Problem: When the VOD has been downloaded the audio was not in sync and the audio through watching the VOD on Twitch directly is perfectly fine
- Download Log:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.7.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 508824775
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/508824775
Crop Start: Yes (06:37:55)
Crop End: Yes (08:59:20)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\Users\Corey\Battle Lounge\SamshoKumoricon2019.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Corey\AppData\Local\Temp\TL_38936b9e-50bb-40bc-b4d9-8789a3c54023

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1574204652%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A508824775%7D
Signature: c204bcc3e4cc9e0fa6eca791d30e3fc96ff7fe14
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Corey\AppData\Local\Temp\TL_38936b9e-50bb-40bc-b4d9-8789a3c54023'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/chunked/index-dvr.m3u8
https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/720p60/index-dvr.m3u8
https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/480p30/index-dvr.m3u8
https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/audio_only/index-dvr.m3u8
https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/360p30/index-dvr.m3u8
https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps (Source) is https://vod-metro.twitch.tv/cad5467a7f59aca3152f_battlelounge_36221146080_1332518646/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 3241

Starting parallel video chunk download
Number of video chunks to download: 849
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Corey\AppData\Local\Temp\TL_38936b9e-50bb-40bc-b4d9-8789a3c54023\SamshoKumoricon2019.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\Corey\AppData\Local\Temp\TL_38936b9e-50bb-40bc-b4d9-8789a3c54023\SamshoKumoricon2019.ts'...
Command line arguments: -y -ss 5 -i "C:\Users\Corey\AppData\Local\Temp\TL_38936b9e-50bb-40bc-b4d9-8789a3c54023\SamshoKumoricon2019.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -t 8485 "D:\Users\Corey\Battle Lounge\SamshoKumoricon2019.mp4"

Video conversion complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Corey\AppData\Local\Temp\TL_38936b9e-50bb-40bc-b4d9-8789a3c54023'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
see closed issues
