### ISSUE TITLE
Autoupdate not working on 1.5.6

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#429]
I have "Check for Updates" selected and yet at no point has it asked me to update to 1.7.3 or any version before that.

I also don't see a button to manually force updating/check for updates.

**Comment by Franiac** [comment]
It checks it right after startup. check the box in preferences and restart TL... see what happens...

**Comment by dsnvwlmnt** [comment]
I'm confused.

I have "Check for Updates" selected.

**Comment by Franiac** [comment]
I installed the old 1.5.6 and the update message instantly popped up after the start. Maybe check your firewall...

**Comment by dsnvwlmnt** [comment]
If that's what the problem is Twitch Leecher could ask for a firewall exception on install rather than leave users scratching their heads.
