### ISSUE TITLE
Because of .NET Installation, 1.7.3 Install Hard-Resets your Machine Without Warning and No User Prompting

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#430]
Please put a warning on the install prompt, thanks.

**Comment by Franiac** [comment]
resets what? your PC?

**Comment by dsnvwlmnt** [comment]
Yes, hard shutdown to update Windows without warning you nor allowing you to save and close programs.

**Comment by Franiac** [comment]
first off, you should never run any open programs on any installation in Windows.

TL installs .NET with the microsoft installer from the web. it is the microsoft installer that chooses to restart, not the TL installer. I don't even know if this behaviour can be controlled. There are multiple forum posts about this on the microsoft support pages and there seems to be no solution.

i see this as a very minor issue. windows 10 already ships with .NET 4.8 so this solves itself anyways in the near future.

**Comment by dsnvwlmnt** [comment]
All I asked was for a warning on your setup. It is your setup that launches .NET install, you can't just write it off as someone else's problem.

**Comment by Franiac** [comment]
The Installer also is a .NET program and cannot run without it. If there is no .NET installed I cannot show anything since showing a warning needs .NET to be installed in the case of a WiX based installer like TL uses.

> As for not running anything while installing something... This is 2019, programs install nicely for 10-15 years now with other programs running.

If you think that is the case, I can only say, you're fundamentaly wrong.
