### ISSUE TITLE
VOD doesn't download with closed captions.

### ISSUE THREAD

**Issue by LeO-Fr** [Franiac/TwitchLeecher#432]
_Version: Twitch Leecher 1.7.3
URL of the VOD: any from here: https://www.twitch.tv/leofr49/videos but if I have to chose one: https://www.twitch.tv/videos/509208060
I'm using Win 10 Pro at latest 1903 relase_

Hello, I have no technical issue with your software, it's working perfectly fine, but there is a missing feature: download the subtiltes when available.
I'm streaming with closed captions, when you go throug my VOD, you can see the [CC] button on the Twitch player (make sure I'm talking for the button showing), it's not from an extension but from Twitch itself. Please can you add the possibility to download the subtitles? By adding a separate srt file maybe? Thank you.

**Comment by Franiac** [comment]
I honestly don't know if that is possible. I have never checked if there is an option to download subtitles. At least it never came across any data fragments I saw so far 😄

**Comment by LeO-Fr** [comment]
Maybe you can use it to help you:
https://help.twitch.tv/s/article/guide-to-closed-captions?language=en_US
Go to the "How to Use Live Closed Captions: for Broadcasters" part.
![image](https://user-images.githubusercontent.com/22010386/69655107-2f103c80-1076-11ea-828b-1a3227725772.png)

**Comment by Franiac** [comment]
Hmm, do I understand that correctly that the captions are part of the video stream and not just a separate file?

**Comment by LeO-Fr** [comment]
It's broadcasted with the video but not in the video, it's like mkv movies, the user can enable or disable it. I was just asking if I could download the vod's subtitle in a separate srt or download the video with subtitles in mkv file. Just any method you want, I just want to able to get the subtitle with my downloaded vod. Like as you saw, you have a CC button on the twitch player.

**Comment by Franiac** [comment]
I digged into this a little bit and there is no public endpoint where I could grab those captions in any way possible. Seems to be another private API from Twitch. SO this will probably not work with TL.

**Comment by Franiac** [comment]
After investing some more time I don't see how this could be implemented, therefore closed.
