### ISSUE TITLE
I NEED HELP WITH "STATUS ERROR", i have very good internet and space in the disk 

### ISSUE THREAD

**Issue by peterpink** [Franiac/TwitchLeecher#434]
Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

**Comment by Franiac** [comment]
> i have very good internet and space in the disk

I mean... good for you, but without the slightest amount of information we should start a guessing game now? 😄 

You didn't even click on the link you posted. It takes a high amount of courage to ignore so many things at the same time.

**Comment by Franiac** [comment]
no response closed..
