### ISSUE TITLE
cannot uninstall 1.7.3 version in Windows7 32bit

### ISSUE THREAD

**Issue by asdf012321** [Franiac/TwitchLeecher#435]
![adfaf](https://user-images.githubusercontent.com/58067914/69410039-85ffd400-0d4d-11ea-8663-7c0d4ecf614a.PNG)
I'm Windows7 32bit user, but I accidentally installed the 1.7.3 version. 
It cannot be uninstall. 
I also used the uninstaller like "revo uninstaller", but it was not helpful because the same error was displayed.
Please tell me how to uninstall.

**Comment by asdf012321** [comment]
It is uninstalled that used "IObit Uninstaller".

**Comment by Franiac** [comment]
One question tho:

Did the installer try to install .NET Framework 4.8 first? Because only showing the bit error screen does not trigger any installation routines. If you don't have .NET 4.8 installed, that's usually coming up first. do you remember what happened?
