### ISSUE TITLE
Feature request: Full strftime (or something similiar) support for Filename Template

### ISSUE THREAD

**Issue by CanvasWhitewolf** [Franiac/TwitchLeecher#439]
I'd like to add the abbreviated weekday name of the recording date as part of the filename for example.

**Comment by Franiac** [comment]
good feature but this would require a lot of language translation options and such which TL currently does not have. it's english only. the available wildcards are all language independent so far. i do not see this beeing top priority thinking about the time i can invest into TL right now. and if we introduce "only english" wildcards there are going to pop up issues for transaltion support instantly. so i am quite hesitant of doing that 😄

**Comment by Franiac** [comment]
putting this on the private feature list and closing this here
