### ISSUE TITLE
Can't add more than one Favorite.

### ISSUE THREAD

**Issue by HoarderofData** [Franiac/TwitchLeecher#440]
When I press the + button the box does not give me a blank line to add a new entry it still shows the channel name I last entered.

**Comment by Franiac** [comment]
Exactly. Read the helper text on the questionmark. +/- buttons add the current value to the dropdown list. The name specified in the textfield is the one predefined in the search dialog.

Let's say you start with a fresh installation of TL and nothing is specified (empty textfield):

* type in "streamer1" and press +
* type in "streamer2" and press +
* type in "streamer3" and press +
* then type "defaultstramer666"
* save preferences

If you now open up the search dialog the channel textfield will show "defaultstreamer666" and when you open the dropdown you see your streamer 1/2/3

I kinda understand the confusion, tho 😄 
I wanted to minimize the control count in the UI. I did not want to add a separate textfield for just adding streamers, or implement a poput where you can specify a new name. The current textfield acts as both, the fav streamers list AND the default value for the search dialog.

Hope that makes it clear.
