### ISSUE TITLE
wont install at all, crashes

### ISSUE THREAD

**Issue by chrise12287** [Franiac/TwitchLeecher#441]
i downloaded 1.7.3 and whenever i try to run it, as normal or as administator, it just crashes immediately, ive tried running in different compatibility modes, etc, but it wont work

im on windows 7 sp1, 64 bit

**Comment by chrise12287** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	TwitchLeecher_1.7.3.exe
  Application Version:	1.7.3.0
  Application Timestamp:	5a10ad86
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.19045
  Fault Module Timestamp:	56258f05
  Exception Code:	c06d007e
  Exception Offset:	0000c42d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

i have no idea if this information is useful

**Comment by Franiac** [comment]
A few things you can try (the above log does not really help):

**Option 1:**
Let the installer write a logfile. Run TL installer from console with `TiwtchLeecher_1.7.3.exe -l log.txt`.
See if the log gets written to the same folder as the installer. If not, it is probably a problem with the system or the .NET installation

**Option 2:**
Check if .NET Framework 4.8 is installed on your machine. If not, install .NET 4.8 from the official Microsoft installer. Then try installing 1.7.3 again and see if it works.

Your error does not seem to be something the TL installer itself causes. TL tries to install .NET 4.8 quietly if it is not present. But we had some issues with this in the past where installing .NET 4.8 manually did the trick.

**Comment by Franiac** [comment]
Closed because no response
