### ISSUE TITLE
Alternate Software to download twitch Sub Vods

### ISSUE THREAD

**Issue by vyperszn** [Franiac/TwitchLeecher#447]
Franiac Mention This:
I know there are some tools out there that still work in certain conditions and there are some workarounds that also make it possible to download sub-only content for a short period of time with older versions of Twitch Leecher.

Does anyone know what other software I can use to download sub only twitch videos?

**Comment by Franiac** [comment]
Please understand that when I say the methods such tools use are "dirty and hacky" I refrain from recommending them. I am not saying they are bad, but I don't agree with what they are doing regarding sub-only videos.

**Comment by vyperszn** [comment]
can you please let me know where I can find it? I just want to test it to see how it works

**Comment by vyperszn** [comment]
hello?

**Comment by vyperszn** [comment]
@Franiac can you please tell me the name of softtware?

**Comment by vyperszn** [comment]
@Franiac waiting for ur response
