### ISSUE TITLE
Update Download Button incorrect URL

### ISSUE THREAD

**Issue by mouarflenoob** [Franiac/TwitchLeecher#448]
Hi !

The correct URL to download the new version is 
https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8
But the button redirects to : 
https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0

And it gives a 404 page from Twitch.

If you have the time, please let me know the file in which this is written, so that I can make the change myself next time, so you can spend less time on something so trivial :)

Have a great day.

I'm running version 1.7.3

**Comment by Franiac** [comment]
LUL, that's because I am a fucking idiot and provided the wrong release tag version format. Should be good now. If you click the second link in your post you get the correct page now...
