### ISSUE TITLE
Can't search entire channel

### ISSUE THREAD

**Issue by Xyrexus** [Franiac/TwitchLeecher#450]
Using Twitch Leecher 1.8, although I can search for videos individually in the search, the channel-wide search isn't working for me.

For instance if I put https://www.twitch.tv/kazeugma (or some variation like https://www.twitch.tv/kazeugma/ or https://www.twitch.tv/kazeugma/videos etc) it won't search, the search bar will get a red line around it indicating something's wrong.

I have some channels I want to grab quite a lot of videos from, so being able to put in a channel and telling it to grab the latest 30 vods or whatever would be quite useful, rather than having to copy and paste each one in. But I just can't seem to get it to work?

**Comment by Franiac** [comment]
Sure it won't search when you put a random internet url into the field that says "channel name"...

How about "kazeugma"... and... so much wow... you get what you want 😄

**Comment by Xyrexus** [comment]
Oh I see, that could have been clearer. Because to me channel name just implies, put the twitch channel url in, thanks for the quick reply, it works now!
