### ISSUE TITLE
resume after lost connection?

### ISSUE THREAD

**Issue by nocoel** [Franiac/TwitchLeecher#452]
so i usually been here and what happens is that TL restarts the download anew.
this time around my connection crashed after 6 hours of download (98%) and then TL (error)ed the VOD.
now i know there is no feature on TL to pick up my download from where it stopped, but after checking my "C:\Users\<user>\AppData\Local\Temp" i could find this folder filled with these 9s tiny clips. so i was wondering if there is some big brain method to use these files and resume it? that would be super convenient.
thanks.

**Comment by Franiac** [comment]
Part of #46
