### ISSUE TITLE
Difficulty to download a VOD

### ISSUE THREAD

**Issue by ratcool** [Franiac/TwitchLeecher#453]
Hi, I try to download my 18 hr stream but it always failed at the end. I have enough space on my pc and i try to download the stream with 5 min cut at the end still the same thing. Help me plz.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 518488232
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/518488232
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\rat19\Downloads\20191207_518488232_Just Chatting.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\rat19\AppData\Local\Temp\TL_f1a26a22-f2cf-4077-b4a7-8ce88cd4b666

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1575948747%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A518488232%7D
Signature: 2f76bdbb539fc624f335a00d2f60190e2ed8d62d
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\rat19\AppData\Local\Temp\TL_f1a26a22-f2cf-4077-b4a7-8ce88cd4b666'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/chunked/index-muted-6L3RPTND6Z.m3u8
https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/720p60/index-muted-6L3RPTND6Z.m3u8
https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/480p30/index-muted-6L3RPTND6Z.m3u8
https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/audio_only/index-muted-6L3RPTND6Z.m3u8
https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/360p30/index-muted-6L3RPTND6Z.m3u8
https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/160p30/index-muted-6L3RPTND6Z.m3u8

Playlist url for selected quality 1280x720@60fps (Source) is https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/chunked/index-muted-6L3RPTND6Z.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 6645

Starting parallel video chunk download
Number of video chunks to download: 6645
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/chunked/2244.ts' failed! Trying again in 20s
System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.WebClient.DownloadBitsState.RetrieveBytes(Int32& bytesRetrieved)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/chunked/5213-muted.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/92a6f8adea1e13015b37_ratcool_36371029200_1341901076/chunked/2590.ts' failed! Trying again in 20s
System.Net.WebException: The operation has timed out.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

**Comment by Franiac** [comment]
I cannot change the fact that the remote (Twitch) host closed the connection. If the server kicks you out, it kicks you out 😄 
I don't know why this happens every now and then but in most cases "try tomorrow again" usually helps.
