### ISSUE TITLE
Help! Clip finder isn't working?

### ISSUE THREAD

**Issue by devilmaycats** [Franiac/TwitchLeecher#454]
Hey all!

If you could help please: Just upgraded to Twitch Leecher 1.8. Didn't have any issues finding twitch clips from my own channel using twitch leecher 1.7, but now when I search up links to find a clip, the box turns red. (indicating that it's not finding anything)

Here's a screenshot link: https://imgur.com/FUFIei0

Am I doing something wrong?
Please let me know and thank you!

**Comment by Franiac** [comment]
Clips are and have never been supported in TL. You can search for video urls but not for clips... also not in 1.7
