### ISSUE TITLE
Downloading to diffenent set harddrive

### ISSUE THREAD

**Issue by imfreestyling** [Franiac/TwitchLeecher#456]
When i download a vod, it starts to fill on the C drive, even though i set it to E: and my twtich leetcher is downloaded for E: too, thats a problem, with a small C: Harddrive. When its done downloading, its removing the data on C: and place it in E:. So if i download ex. 1 hour and it fill 10GB, and my C: has 9.9gb, then it cancel

**Comment by Franiac** [comment]
That's why there are preferences where you can tell TL exactly what to store where...
