### ISSUE TITLE
Twitch Leecher is now gated to only windows 10 users

### ISSUE THREAD

**Issue by futurecity249** [Franiac/TwitchLeecher#457]
Please read

https://github.com/Franiac/TwitchLeecher#support--issues

before posting anything!

I'm still running windows 7 and using the 1.6 Twitch Leecher.  Now since twitch updated whatever the fuck, I only get 410 errors. I cant download any of the updated leechers because this stupid program for some reason doesnt see I have the net shit downloaded on my computer so now I just cant use the program.  Fucking unreal.

**Comment by Franiac** [comment]
Douchebag lesson: Be an asshole on the internet, get treated like an asshole on the internet.

The only thing that is unreal is your behavior. I don't see any reason why I should help you.
