### ISSUE TITLE
Start downloading next video while merging/converting previous

### ISSUE THREAD

**Issue by The-Cop** [Franiac/TwitchLeecher#458]
Is it possible to start downloading chunks for next video in queue while the previous one is already downloaded and is merging/converting?

It could save lots of time if more than one video is queued.

There's a possible issue with HDD speeds while writing new chunks and reading/writing operations on simultaneous merge/converion, but it would be sweet to have this option in settings.

**Comment by Franiac** [comment]
This is already included in an open pull request. So far I did not have the time to check it out and merge it 😄

**Comment by The-Cop** [comment]
Sorry, looked briefly through issues and totally forgot about PRs! Thank you for your time and great product!
