### ISSUE TITLE
Can't download Twitch Videos with version 1.8 - Issue

### ISSUE THREAD

**Issue by Tammn** [Franiac/TwitchLeecher#459]
I  have a problem... why do i cannot download any of my own videos?

the program shows me this:

####
An unexpected error occured:
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: filename
   bei TwitchLeecher.Core.Models.DownloadParameters..ctor(TwitchVideo video, VodAuthInfo vodAuthInfo, TwitchVideoQuality quality, String folder, String filename, Boolean disableConversion)
   bei TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)
####

can anybody help?

**Comment by Franiac** [comment]
Need more info here:

1. Video ID
2. All parameters written down or a screenshot from the download page (quality, filename, cropping etc.)

**Comment by Tammn** [comment]
1. https://www.twitch.tv/videos/511016714

where do I get the parameter-infos?

**Comment by Franiac** [comment]
Well, from the download oage in TL. After clicking the download button in the search result view. like the view where you can specify the cropping and select the video quality and such.

**Comment by Tammn** [comment]
![Screenshot_49](https://user-images.githubusercontent.com/58908609/70863384-f1e9ec80-1f47-11ea-944b-3d029e6b5b45.png)

This?

**Comment by Tammn** [comment]
Okay... found the fault...
The video is more than 10 days old, so i`ve had to change the option.

**Comment by Franiac** [comment]
Err... but that error should not happen. can you post the log file pls?

Go to the path and copy the file contents and just post them here.

**Comment by Tammn** [comment]
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: filename
   bei TwitchLeecher.Core.Models.DownloadParameters..ctor(TwitchVideo video, VodAuthInfo vodAuthInfo, TwitchVideoQuality quality, String folder, String filename, Boolean disableConversion)
   bei TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Tammn** [comment]
![Screenshot_50](https://user-images.githubusercontent.com/58908609/70863515-58233f00-1f49-11ea-8817-0ab18e0f1911.png)
I just only changed the load limit from 10 up to 30 - and it worked

**Comment by Franiac** [comment]
But I don't understand how you got the error in the first place O_o

**Comment by Tammn** [comment]
I don`t know either. I just turned it back from 30 down to 10 days - thought the error would be there again... but no error showed.. it works...... strange.. :)

**Comment by Franiac** [comment]
That is some black magic shit 😈 

Ok, we just leave it there, i guess...
