### ISSUE TITLE
New Download Manager - Show Rate / Rate Limit / Pause / Resume / Reconnect

### ISSUE THREAD

**Issue by Franiac** [Franiac/TwitchLeecher#46]
This issue summarizes issues #21, #24 and #30.

At the moment, there is no real download manager that could handle the above requirements.

The idea is to create a completely separate event-driven download manager outside of the "TwitchService" class. At the moment the download process is quite "wired" to this service which is not maintainable.

**Comment by Hagnor** [comment]
Thank for you excellent software ! =D

**Comment by souravsaraf** [comment]
First of all , thanks to Franiac for his time and work on this great software.

My next question/small feature request is : Since the software already shows me a percentage of download completion, can it also display the download speed , how much data downloaded , time taken so far , time left for completion. I think you can integrate and display above info in this task (#46) itself. Thanks a lot (btw no pressure, as you are doing this in your free time :D )

**Comment by Franiac** [comment]
@souravsaraf yes, this could all be done but I do not want to invest time into it when I write a new download manager anyways. The major problem about all this is that I do not know the total download size. I know that I have to download 11000 VOD parts for example, but there ist no information about the size until I really download such a part. It will all come down to an approximation of how many parts were downloaded in what time and what was the average download size and how many parts are left. the more parts there are, the more accurate this calculation will be.
But first I need the download manager as such. I do not implement one of the above requirements into the current downloading system. That would be stupid and a waste of time.

**Comment by tezJR** [comment]
@Franiac, I understand a new download manager is a work-intensive request. Can a stopgap solution be implemented so it can optionally retry an infinite number of times? I have a data cap, so multigig errors are significant.

**Comment by aselwyn1** [comment]
any updates to the Pausing ability and some of these other features?

**Comment by Franiac** [comment]
Yes, I am building a house and have no time for it (honest answer)

**Comment by aselwyn1** [comment]
fair fair

**Comment by JoshuaaMichael** [comment]
Any updates on how this is going, specifically enabling rate limiting? I pulled from Twitch at ~400Mbps today and caused myself a miniature denial of service to other devices in my network. First world problems, amirite, haha.

Also a feature idea, being able to multi select a bunch of videos to download from the UI would be great, a classic ctrl+click style thing. That'd save me some time.

Thanks for the great software!

**Comment by Franiac** [comment]
I just want to point out the complexity of this issue since I refer to it very often. I get a lot of emails asking about the download manager and when it is done.

This "feature" is not comparable to let's say a new wildcard for the filename template or a checkbox in the preferences menu. We are talking of a project size equally big as Twitch Leecher itself.

If I ever start to implement this download manager it will probably happen in a separate repository. So I hope this makes my point clear why this issue doesn't get implemented in the next few days (apart from the reasons in my other comments). So please bear with me, I am not a coding robot 😄

**Comment by JoshuaaMichael** [comment]
@Franiac Not a worry, I'll keep an eye out for when you get around to the big rewrite. It's good to hear you're striking a healthy hobby-life balance. Best wishes for the future.

**Comment by kingcatdaan** [comment]
I personally use software like NetLimiter 4 to limit the download speed and it works great for TwitchLeecher

**Comment by Franiac** [comment]
I created a separate repository (SharpLoader) for this issue [HERE](https://github.com/Franiac/SharpLoader)

If you want to stay updated, consider following/watching the new repo. This conversation will be locked.

I will integrate new library into TL as soon as it is ready for use.

**Comment by Franiac** [comment]
#803
