### ISSUE TITLE
Extreme delay on twitch video downloads [bug]

### ISSUE THREAD

**Issue by Phaxyy** [Franiac/TwitchLeecher#463]
Hello, i have a really big problem.

If i download a vod with Twitch Leecher, and say like i just want the time stamp from 2:18:00 -
2:50:00 i have a big delay on my video, its not my fault, my friends tested it also and its with every vod on twitch if u download them with a time stamp. anyone knows wth this is? twitch leecher was working so perfect, and now the downloaded videos are just broke af with big audio delay. 
Please help fast <3

**Comment by Franiac** [comment]
Please check out the closed issues with "A/V" or "desync" in the title...
