### ISSUE TITLE
Potential of Mac version or GUI alternative?

### ISSUE THREAD

**Issue by godzfire** [Franiac/TwitchLeecher#465]
I was extremely happy to find this application as I had been looking for a program to download Twitch VODs before they would disappear, but also have the option to download selected time sections from very long VODs which the people I watch do (3-10 hours), since they switch games sometimes and the video file sizes are already insane for 1080 quality content. Finally, TwitchLeecher is a GUI, which as someone who openly admits I'm completely stupid and don't understand command line anything, makes it so I can actually use it.

Unfortunately I discovered that this program is Windows only. Is there any possibility of converting this to a Mac version, or does anyone know a Mac program that can split files and a GUI?

**Comment by Franiac** [comment]
Won't happen, sorry. In order to develop for Mac or IOS, you are forced to buy a Mac which I won't do ever in my life. I am not the "paying too much money for flawed products" kinda guy 😄
