### ISSUE TITLE
The update link doesn't work

### ISSUE THREAD

**Issue by Kenshin9977** [Franiac/TwitchLeecher#467]
When updating Twitch leecher if I click on "Download"
![TwitchLeecher_gcmTnHBlPF](https://user-images.githubusercontent.com/33557877/73136673-74d68a80-4050-11ea-9e13-0bf6cbd66f48.png)
The software redirects me to this page which gives me a 404
https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8
But the link should be 
https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0

**Comment by Franiac** [comment]
This has been fixed in 1.7.0
