### ISSUE TITLE
[1.8 issue] twitch leecher 1.8 has stopped working while attempting to install 

### ISSUE THREAD

**Issue by dragon870** [Franiac/TwitchLeecher#468]
hello Franiac, hope you're having a great day

im trying to install the latest version which is 1.8 and i made sure to install .NET Framework 4.8 [as you can see here](https://cdn.discordapp.com/attachments/623998486911909901/676008494721400832/netframe_proof.jpg)

but [this is what i get](https://cdn.discordapp.com/attachments/623998486911909901/676008492255150100/2.jpg) upon clicking the TwitchLeecher_1.8.exe setup icon 

**system info:**
- Operating system: [win7 SP1 64bit](https://cdn.discordapp.com/attachments/623998486911909901/676008493974814742/op.jpg)

**what i've tried:**
- 4 rotations of installing and uninstalling of .NET Framework 4.8 (offline version, normal version, version attached with 1.7.3)
- installing older versions of twitch leecher like 1.6 and 1.7 still provides the same prompt
- run as admin

theres one curious matter you might be interested in, upon installing version 4.5 of net framework it allows me to install compatible versions of twitch leecher like 1.6 and 1.7 and fully functional except it gives me the error that started it all 3 month ago which is 410 (gone), yet when i upgrade to 4.8 all twitch leecher versions stop working and am not allowed to install or uninstall due to the same message appearing (twitch leecher has stopped working)

apologies if its a repeated issue, i promise i've spent sometime searching for similar issues in closed tab and google/reddit. im very active and will be checking 4 times a day to make sure i can provide all info needed, thank you so much for your time and your amazing work <3

**Comment by Franiac** [comment]
these kind of errors are usually not related to the program. you can check the windows event log (application category) for more. there should be an error pointing towards TL. maybe that helps. i have the feeling that something with your machine is not right.

**Comment by dragon870** [comment]
i see, i've launched the even viewer and managed to reproduce the problem and each time it happens these two error would show up 
[first error](https://cdn.discordapp.com/attachments/623998486911909901/676099221824471070/1.jpg) 
[second error](https://cdn.discordapp.com/attachments/623998486911909901/676099226131890176/2.jpg) 

would thos be of any help to you?

**Comment by Franiac** [comment]
this is definitely a problem with either the .NET 4.8 installation or windows. also it could be antivirus. maybe check if it works when antivirus is disabled (should you have anything installed besides windows defender).
all i really can say is that it is not related to the TL installer. my installer has error handling from the first line of code. this means the installer fails even before loading up. i don't know how i could help you on this one, unfortunately 😢

**Comment by dragon870** [comment]
no problem, much appreciated for your time, have a good one <3

**Comment by Franiac** [comment]
the last thing you could check is start the installer with

`TwitchLeecher_1.8.exe -l log.txt`

and post the contents of BOTH files written. maybe there's something that helps.

**Comment by dragon870** [comment]
hello, i just did that, it sadly launched TL but [with the same problem](https://cdn.discordapp.com/attachments/623998486911909901/676498803226050569/1.jpg) , since the program didnt even get the chance to start im guessing a log file(s) did not have the chance to be created right? might they be created in a different directory? because i have the icon on desktop and no new file (text or log) has been created at all :(

**Comment by Franiac** [comment]
the second log gets written when you actually press "install" and confirm the UAC message from windows. there are absolutely no errors in this log.

mabe you could try the hard way:
* Uninstall TL 1.7.3
* Delete whatever you find in `%appdata% -> TwitchLeecher`

Try a clean install of 1.8 again...

**Comment by dragon870** [comment]
just did that, also made sure to check the registry for the correct version of .net framework 4.8 and its indeed the correct one i have install and deleted TwitchLeecher folder from appdata after uninstalling 1.7.3 but sadly same problem :( , im guessing this is the deadend right?

**Comment by Franiac** [comment]
I just doublechecked that error handling in the installer application is there from the first line of code that is run. this means the installer fails before my code runs... i cannot help 😢 
closing this one since i am really out of ideas and it does not seem to be a TL issue. we got a lot of Win7 SP1 running.
