### ISSUE TITLE
Can't download Twitch Videos

### ISSUE THREAD

**Issue by glot7891** [Franiac/TwitchLeecher#471]
![註解 2020-02-26 175759](https://user-images.githubusercontent.com/61511796/75364043-00646500-58f6-11ea-8f67-3a1b0cbcc983.jpg)

**Comment by Codereaders** [comment]
How can you be able to set up an account on github, screenshot the message and create a new issue but in the same time not just read the message shown on your screenshot?

The video is for subscribers only and Twitch removed the ability for 3rd party software - such as TwitchLeecher - to download such videos.

So: It's a known limitation and there's nothing to do about it.

**Comment by Franiac** [comment]
Sometimes I wonder.....
