### ISSUE TITLE
lost all my saves

### ISSUE THREAD

**Issue by pepehands777** [Franiac/TwitchLeecher#475]
Hey guys, my twitchleecher didnt work these days so i uninstalled it to get a newer version, but the folder with the saves is gone PepeHands, does anyone know if there could be a save of it anywhere in C maybe? (i dont understand how they got deleted, it was a separate folder from twitch leecher's one)

**Comment by Franiac** [comment]
If you somehow deleted your downloaded videos there is nothing we can do. My witchcraft is not strong enough to make your video reappear again 😢

**Comment by pepehands777** [comment]
yeah, i asked because i wanted to know if there's a savings folder in C for twitch leecher, or if twitch leecher deleted the save folders that its connected to if you uninstall it, i was wondering

**Comment by garoto** [comment]
check your "System Restore" settings for a possible C: restore point.
