### ISSUE TITLE
Completely unable to launch

### ISSUE THREAD

**Issue by Burntbreadbits** [Franiac/TwitchLeecher#477]
I'm running Windows 10 x64 Version 1903
I tried running every version between 1.5.5 and 1.8 and TwitchLeecher never once opened properly, it would briefly appear in task manager before closing again.

Only version 1.5.5 specifically was kind enough to show an error message that it "failed to start because its side-by-side configuration is incorrect".

Some google searching suggested checking Event Viewer when no error message popped up and lo and behold:

Faulting application name: TwitchLeecher.exe, version: 1.8.0.0, time stamp: 0x5dde8512
Faulting module name: d3d9.dll, version: 10.0.18362.387, time stamp: 0xc808fce5
Exception code: 0xc0000005
Fault offset: 0x00000000000ac44e
Faulting process ID: 0x2240
Faulting application start time: 0x01d5fd9152de4694
Faulting application path: C:\Program Files\Twitch Leecher\TwitchLeecher.exe
Faulting module path: C:\Windows\SYSTEM32\d3d9.dll
Report ID: 6880b74f-1f20-45ff-8546-2cc0387fa794
Faulting package full name: 
Faulting package-relative application ID:

I managed to get TL working again by copying d3d9.dll into the TL install directory and I'm more so posting this the other people I've seen with similar issues haven't found solutions.

Because TL has worked for me in past, I suspect the problem's been caused by a recent windows update but then again this ain't my piece of software so I'm not the expert.

**Comment by Franiac** [comment]
Check out #119 and #177 

You probably have this garbage MSI Afterburner running, am I correct? 😄
