### ISSUE TITLE
Not Downloading Full Hightlight/VOD?

### ISSUE THREAD

**Issue by Shtoops** [Franiac/TwitchLeecher#48]
Hello!

So I'm trying to download one of my favorite streams from a while back, however when I download it, I'm the video I get is not the whole stream. The Stream is 2:30 hours, yet the video I'm getting is only 7:28 minutes. The program says the download is 100% finished, and I don't see any errors. I've attempted it multiple times and the result is always the same.

Do you think you could help me? I'll attach the log from the download

[Twitch Leecher Log.txt](https://github.com/Franiac/TwitchLeecher/files/392173/Twitch.Leecher.Log.txt)

**Comment by Franiac** [comment]
First thing: Why do you crop the video? You selected the whole video anyway, no need to crop it.
Watch through the video from 7:20 and see what happens right before 7:46... basically his stream died. There are probably some endoding errors that the Twitch player manages to skip, but FFMPEG (the encoder in TL) cannot. I cannot do anything about that unfortunately. I only encode the material what I get from Twitch. If that is corrupted, I cannot fix it.

But... you could try to download from 00:00 to 7:45 and from lets say 7:55 to end and merge the 2 parts together in a video cuttin program...
