### ISSUE TITLE
Schedule Downloads

### ISSUE THREAD

**Issue by DeanGifford** [Franiac/TwitchLeecher#480]
Would be a nice feature to be able to queue downloads and set a start time for when they should begin downloading. I'm imagining one setting for a time, then (If TwithLeecher is open) when it's that time, it triggers all queued downloads to begin.

To take this even further there could be an end time as well, so if there is any downloads still ongoing, it would cancel / pause them when the end time is reached.

**Comment by Franiac** [comment]
So kinda like "Active Hours" for the Windows 10 Updates... good idea, but I want to finish #46 first.

**Comment by radkoolaid** [comment]
> So kinda like "Active Hours" for the Windows 10 Updates... good idea, but I want to finish #46 first.

Would love a way to setup to monitor a channel and download new videos when they are posted. I've been watching a lot of DJ Twitch streams and they are quickly processed by Twitch removing a good portion of the audio from the streams. The quicker the download could execute once the video is available the better.

**Comment by Franiac** [comment]
@radkoolaid I will not implement anything supporting quick downloads in order to work around illegal music distribution. Those DJ's are not allowed to play copyright protected music on Twitch without a license.

**Comment by EvilEtho** [comment]
It would be cool with this if you could "Subscribe" to a channel and when the program is open it will look for the "Stream has Ended" packet from twitch, and download the most recent vod.

**Comment by EvilEtho** [comment]
> @radkoolaid I will not implement anything supporting quick downloads in order to work around illegal music distribution. Those DJ's are not allowed to play copyright protected music on Twitch without a license.

I understand this, but it would be nice if we could download vods right after the stream ends. I run 4 Vod youtube channels for some creators, because i have gig internet so its faster for me to just download them and upload them, than it would be for them to save vod local and upload them selfs.

Even if it was a few mins or an hr after stream ended to start downloading the vod would be nice. A sort of "Subscribe" feature

**Comment by Franiac** [comment]
@EvilEtho It needs to be delayed quite a bit because we must wait until the VOD is transcoded completely.

**Comment by Franiac** [comment]
#803
