### ISSUE TITLE
Add '-start_at_zero' and '-copyts' commands to FFmpeg command line

### ISSUE THREAD

**Issue by EnterGin** [Franiac/TwitchLeecher#481]
Hello! 

There are some issues with VODs that have broken timestamps. After processing by FFmpeg without '-start_at_zero' and '-copyts' some part of stream can be lost.
These two commands don't affect on perfomance of processing and quality of processed stream but can help if errors occur in timestamps.

Can read more on https://github.com/streamlink/streamlink/pull/2559

**Comment by Franiac** [comment]
Please provide multiple VODs to test. Without validation and actual examples there will be no change to the ffmpeg arguments... this has broken a lot of things in the past.

**Comment by EnterGin** [comment]
I think that I have a couple.
I will send you unprocessed VODs.

**Comment by Franiac** [comment]
I need only the VOD urls.

```
When used with copyts, shift input timestamps so they start at zero.

This means that using e.g. -ss 50 will make output timestamps start at 50 seconds, regardless of what timestamp the input file started at.
```

The cropping feature uses `-ss`. I am not a ffmpeg pro and actually don't really understand the video timestamp shenanigans. Can you explain how this all will affect videos? I need to read more about the topic, but as of now I am quite hesitant to change the current ffmpeg call because we had a lot of timestamp issues in the past that caused stuttering or A/V desync.

**Comment by EnterGin** [comment]
I don't have any VOD urls, because it was long ago.

When timestamps is broken at some point, all the frames of the video occupy the same time stamp, because of this, at some point the video is interrupted.
![broken timestamps](https://user-images.githubusercontent.com/51099894/78545498-8a142600-7804-11ea-8e1f-852416dadc62.jpg)

I uploaded 3 streams with broken timestamps. 
423047243 - breaks at 00:41:40
423876485 - breaks at 00:34:35
441863440 - breaks at 00:45:52

https://drive.google.com/drive/folders/1CPRIxCSs-H6kKvO7RPStguo68jgIOHpX?usp=sharing

Also I'm using that in my script for long time and this seems fine to me.

**Comment by Franiac** [comment]
We need test for all kinds of channels, streaming/encoding settings, cropping and so on. The "it works for me" is worth nothing when 499999 other users have not confirmed it. I will do some testing and may release a preview version but this does not go straight to a new TL version.

Don't get me wrong. We had 4 of these "command line improvements" from a single user in the past and in all cases I fell flat on my face, rolling it back a hour later. So I have to apologize, but you're the first one to receive the "Press X for doubt" sign 😄

**Comment by Franiac** [comment]
I like to add that my personal problem is that I don't know shit about video processing at all and cannot judge such recommendation well... that may sound weird because I made TL but that's what happens when a program goes viral, I guess...

**Comment by EnterGin** [comment]
Yea, I fully understand that because I'm also develop some downloading and recording stuff. And I'm understand how ffmpeg works :smile:

**Comment by Franiac** [comment]
Or.... how it doesn't work... right? :P

**Comment by EnterGin** [comment]
A long way full of mistakes...

**Comment by Franiac** [comment]
@EnterGin This does not work at all...

Try downloading the following video by cropping from 00:16:00 to 00:17:00 with TL 1.8:

[https://www.twitch.tv/videos/662860708](https://www.twitch.tv/videos/662860708)

The resulting video is exactly 1min long and plays as expected in VLC.

If I add `-start_at_zero -copyts` to ffmpeg, the following happens:

* The resulting video is 50s long -> WTF?
* VLC starts playing at 10s in -> WTF?
* After reaching 50s (where the video should end), it plays another 10s  -> WTF?

What do you think about that? Enlighten me pls 😄

**Comment by Franiac** [comment]
And here's the TL log so you can see the ffmpeg call:

```
Executing 'D:\Repositories\TwitchLeecher\TwitchLeecher\TwitchLeecher\bin\ffmpeg.exe' on 'C:\Users\Franiac\AppData\Local\Temp\TL_40ddcd34-226b-4b2f-b1cf-82de94a454ce\20200627_662860708_Company of Heroes 2.ts'...
Command line arguments: -y -ss 10 -i "C:\Users\Franiac\AppData\Local\Temp\TL_40ddcd34-226b-4b2f-b1cf-82de94a454ce\20200627_662860708_Company of Heroes 2.ts" -analyzeduration 2147483647 -probesize 2147483647 -start_at_zero -copyts -c copy -t 60 "D:\20200627_662860708_Company of Heroes 2.mp4"
```

**Comment by EnterGin** [comment]
I checked this now and I can agree that this isn't working fine in this way of use. Cropping is too much trouble. 😂
It working fine with VODs without cropping but I understand that this unacceptable in this program. Issue can be closed for now I think.

**Comment by Franiac** [comment]
Alright, but thanks for the suggestion anyways!
