### ISSUE TITLE
Corrupted output file on long VOD's 

### ISSUE THREAD

**Issue by Keshenatech1** [Franiac/TwitchLeecher#482]
I was wondering if there's a maximum time or size length for a VOD to be downloaded?  The reason I ask is that the streamer I mod for, Danarachel,  just completed her 1st 48 hour 1 year anniversary sub-athon stream.  I tried downloading the vod 3 different times with the latest version of Twitch Leacher.  It took close to 8 hours to complete and didn't give any error messages, but the output mp4 file won't play and seems to be corrupted.  It is 83.1 GB long but won't even show a time length when clicking on it like others do.  I finally worked around the issue by using the built in crop feature and split it into 2 different 24 hour videos.  Is 48 hours or 83.1 GB too large to process, or should have it worked?

**Comment by Franiac** [comment]
In a 48hr stream it is very likely that there are some dropouts and chokes. FFMPEG cannot handle those kind of hickups very well and gives up pretty fast.
As you relized, cropping is the 1st workaround. Also you could disable mp4 conversion in the preferences and go with the original .ts file.
To my knowledge there is no hard size limit to anything in TL.
