### ISSUE TITLE
audio desync

### ISSUE THREAD

**Issue by nokk1g** [Franiac/TwitchLeecher#483]
Hi,

so after the downloads the audio is not syncing I tried to un install it and install it again but still the same

**Comment by nokk1g** [comment]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.7.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 600222367
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/600222367
Crop Start: Yes (30:36:00)
Crop End: Yes (31:12:33)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\owenb\Downloads\1.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\owenb\AppData\Local\Temp\TL_864576e2-1baf-4770-8401-1698192fd5df

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1587840139%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A600222367%7D
Signature: 733db1e2bebc97b8e3f9d42aa91880f89ae0b1bf
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\owenb\AppData\Local\Temp\TL_864576e2-1baf-4770-8401-1698192fd5df'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/chunked/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/720p60/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/720p30/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/480p30/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/audio_only/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/360p30/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/160p30/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps is https://d2nvs31859zcd8.cloudfront.net/c0c2cc841655ddc9b252_beyondthesummit_37695262848_1424787132/720p60/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 11819

Starting parallel video chunk download
Number of video chunks to download: 220
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\owenb\AppData\Local\Temp\TL_864576e2-1baf-4770-8401-1698192fd5df\1.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\owenb\AppData\Local\Temp\TL_864576e2-1baf-4770-8401-1698192fd5df\1.ts'...
Command line arguments: -y -ss 4.811 -i "C:\Users\owenb\AppData\Local\Temp\TL_864576e2-1baf-4770-8401-1698192fd5df\1.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -t 2193 "C:\Users\owenb\Downloads\1.mp4"

Video conversion complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\owenb\AppData\Local\Temp\TL_864576e2-1baf-4770-8401-1698192fd5df'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
There is absolutely no desync in this video when watching the downloaded part in VLC 3. What video player or video software do you use?

**Comment by Franiac** [comment]
Closed because inactive
