### ISSUE TITLE
audio desync in davinci resolve

### ISSUE THREAD

**Issue by mishasnowdon** [Franiac/TwitchLeecher#484]
hi, I have an audio desync in davinci resolve 16. I checked video with VLC video player - audio is ok, but when I importing it to davinci resolve to edit and cut - there is an audio desync, what should I do to fix it?

**Comment by Franiac** [comment]
I don't know, actually. Maybe try the Resolve forum for further info. I cannot provide reasonable fixes for every software that does not work properly. I only know that many programs have trouble with downloaded streams from a m3u8 playlist (e.g. Twitch streams).

**Comment by mishasnowdon** [comment]
> I don't know, actually. Maybe try the Resolve forum for further info. I cannot provide reasonable fixes for every software that does not work properly. I only know that many programs have trouble with downloaded streams from a m3u8 playlist (e.g. Twitch streams).


What could you recommend to solve this?

**Comment by Franiac** [comment]
Did you read my comment?

> I don't know, actually. Maybe try the Resolve forum for further info.

This issue is not a Twitch Leecher problem, but a Davinci Resolve problem. I don't know how to fix issues with Davinci Resolve, unfortunately.
