### ISSUE TITLE
non-sub videos are considered sub videos

### ISSUE THREAD

**Issue by JimmyWu1934** [Franiac/TwitchLeecher#485]
https://www.twitch.tv/videos/607730282

i can watch this on incognito just fine and im not a sub but twitchleecher says that it's a sub-only video.

the streamer has some of his vods sub-only but some not. and since i could view the free vods i wanted to see if im also able to download them

**Comment by Franiac** [comment]
Can't help here. The API call to Twitch when downloading the VOD tells TL that it is actually sub-only. I also can watch teh VOD in Firefox (not even incognito). Seems to be a mistake/bug on Twitches end.
