### ISSUE TITLE
Any ways to download sub videos now?

### ISSUE THREAD

**Issue by Marcinho2107** [Franiac/TwitchLeecher#489]
hi,
Any ways to download sub videos now?

There are some? Can anybody help me please :)

**Comment by Franiac** [comment]
Not possible since TL 1.8 because Twitch made changes to prevent exactly that.

See [https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0)
