### ISSUE TITLE
Start next download in queue earlier

### ISSUE THREAD

**Issue by Svish** [Franiac/TwitchLeecher#490]
There seems to be these 4 states for a download:

1. `Downloading`
2. `Merging files`
3. `Converting video`
4. `Done`

Currently, the next item in the queue is only started once the current one reaches `Done`. 

But neither `Merging files` nor `Converting video` uses any network bandwidth (I assume), so it would be great if the next item in the queue could start downloading as soon as the current one is done `Downloading` instead.

**Comment by Franiac** [comment]
#458
