### ISSUE TITLE
Stop/pause button

### ISSUE THREAD

**Issue by ShivamShokeen** [Franiac/TwitchLeecher#491]
Hi my name is shivam and I think you app does not have any stop/pause button.Yesterday I was downloading some video and I did not see any pause downloading button so all the downloading progress was restarted. Can you please add stop/pause button so that if I want to download it later I can download it where I left not from beginning and one more thing I just saw in the task manager that it is taking my entire or say 25mbps out of 30 mbps speed and there is nothing to set bandwidth speed and I am using latest version

**Comment by Franiac** [comment]
#46
