### ISSUE TITLE
Optimizing? 

### ISSUE THREAD

**Issue by b1n4ryk1lla** [Franiac/TwitchLeecher#492]
i have a 64 core Threadripper and TL uses about 10% max cpu and 2% if any of my GPU's  any way to make it more efficient and utilize the system its on? or have a setting to adjust encoding or something to take advantage of higher end pcs..? 

thanks for all the hard work!

**Comment by garoto** [comment]
There's no _encoding_ taking place, it's all concat/codec copy from one container to another. Invest in fast I/O.

**Comment by Franiac** [comment]
Yup, you misunderstand what TL is doing. TL only downloads and merges a lot of files together into a single file. FFMPEG is only used for cropping. No encoding whatsoever...
