### ISSUE TITLE
The update link is not correct

### ISSUE THREAD

**Issue by kdewilde** [Franiac/TwitchLeecher#493]
When I open Twitch Leecher (Didn't use it for a while, was on version 1.5.6) I got the message that an update is available.

The link that is written and the link that the download button takes me to is
https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8

this should be
https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0

**Comment by Franiac** [comment]
Already fixed in 1.6 or 1.7, don't remember exactly.
