### ISSUE TITLE
Ability to select the download folder with filename.

### ISSUE THREAD

**Issue by luvyana** [Franiac/TwitchLeecher#494]
Ability to select the download folder with filename just one click, instead of first selecting the folder, then clicking checkbox to enable renaming then entering a new name.

It would be really nice to tell the software to something like 

**"\Desktop\Highlights\streamVOD.mp4"** instead of;

**"\Desktop\Highlights\"** and **"streamVOD.mp4"**

**Comment by Franiac** [comment]
You don't answer the most important question: Why?

You set the download folder and the filename template in the preferences once and you never need to change any folder or filename again when downloading a video.

I don't see why you would need to change the folder AND the filename every time you download a video.

**Comment by luvyana** [comment]
Hey! Thank you for the answer! This is not really a huge thing anyway, but I love UI/UX design, so I'll give it a go! =)

I actually explained the "why", it is a UI/UX improvement. Having the ability of setting a template is irrelevant to my point, I'm talking about "how you & software" sets the file name & folder. They are seperate in the UI. Which would be better if they weren't. And also "Use Custom Filename" can also be gone, just let people edit, without checking a box, it is just a unnecessary extra step.

What I mean is to just getting rid of the "Filename" box. For example when you "Save as" anything in any software, It doesn't ask you twice, for picking file name & folder. It asks you both at the same time. You go in to a folder you want to save your file and write the name and it uses that path. This can still work with the name template. It would just give the templated name in to that picker. This would also get rid of use custom filename option. Example:

Save to : String {default_folder_path}/{template_name}.mp4 , Button (Change)

Also, my english isn't really great so I'm so sorry if i sound offensive or anything. Thank you for the great software!

**Comment by luvyana** [comment]
Also I do change filename for **every single video.** , that's one of the reasons why I requested it. It wouldn't break the current system.

**Comment by Franiac** [comment]
Ok, I understand your points, but there is a little bit more to consider.

The "Use Custom Filename" checkbox is necessary. If you switch it on, you have the option to rename the file manually as you already know. But we need the possibility to re-apply the template again.
Let's say you changed the filename and decide to switch back to the template from the preferences, there must be an option to do so. Either it would be a "Reset to template" button or the checkbox as it is right now. Either way it would be a single click you have to do. We discussed this like 4 times in other closed issues already and there was never really a better solution coming up.

The point that you don't use the template system and enter the filenames ever single time is a very small minority actually. Nearly all users use the template system and never touch the filenames.
What you also have to consider is the fact that multi-selection downloads will be possible in the future. You will be able to select let's say 10 videos in the search result and hit "Download All". Nobody wants to type in filenames for every single video. In that case the mechanism will exclusivly rely on the template system. With the new download manager you will be able to queue up 100 videos (and people want that actually), so manual filename operations will be gone anyways with the exception of downloading a single video.

I share your opinion that the folder and the filename COULD be a single textbox and a "Save as" option works differently. That's a rather minor change, but as I stated above, the way you use the download dialog is rather uncommon. And you have to admit that the normal Windows "Save as" functionality does not have to bother with a template system. That makes it farely easy for Windows 😄 

So even if I decide to combile the textboxes, there would still be the checkbox.

I hope that makes my points clear and explains why the dialog is implemented like it currently is.

**Comment by luvyana** [comment]
Thank you for the explanation! ^^ With how people use it, I can see the use of these. It seems it's just rather little inconvenient for people like me who names the videos based on the context of the video, which is not possible with templates, hence why the pain.

Checkbox is not a problem at all! It was just a side thing I wanted to point out, it's just kinda annoying to click it everytime :P Single textbox for folder/filename would be really nice tho!

Thank you for taking the time =)

**Comment by Franiac** [comment]
Sure thing! When there are changes to the download dialog in the future I will combine the textboxes. But my first priority right now is my 5 week old daughter 🥰

**Comment by Franiac** [comment]
I decided not to change this. Most users rely on the filename template and IF they change something in the download dialog it is mostly the quality or the download folder, but NOT the filename. So the selection option for the folder alone is a good thing I do not want to change.
