### ISSUE TITLE
Missing Connect to Twitch button

### ISSUE THREAD

**Issue by kramer67** [Franiac/TwitchLeecher#496]
At  the top right, before I updated I had the connect to twitch button so I could download subbed videos but, was getting an error when trying to download so I updated. Now the button is gone completely.

**Comment by Franiac** [comment]
Here you go:

[https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0)
