### ISSUE TITLE
Look at the Screenshot

### ISSUE THREAD

**Issue by DeadShowP** [Franiac/TwitchLeecher#497]
Look at the Screenshot
![2020-06-15 (11)](https://user-images.githubusercontent.com/66972763/84701175-296c3c80-af5d-11ea-9ee2-abffcd2d4ce6.png)

**Comment by Franiac** [comment]
Cool screenshot!

How about posting the log file instead of the screen 😄

**Comment by DeadShowP** [comment]
![2020-06-15 (13)](https://user-images.githubusercontent.com/66972763/84703031-35a5c900-af60-11ea-85a6-9d3037b80caf.png)

**Comment by puyanwei** [comment]
I got this too when I tried to search for a vod straight after streaming. After a little time the search worked.

**Comment by DeadShowP** [comment]
I think Twitch is f.. up right now. İts barely working.

**Comment by DeadShowP** [comment]
@Franiac Hey you can make a mobile app?

**Comment by Franiac** [comment]
That means the remote server (Twitch) had an internal (unspecified) error. Nothing I can do here 😄 

No mobile apps... not even time for the desktop app currently (became a dad)...
