### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by InfamousKnight** [Franiac/TwitchLeecher#498]

**Comment by Franiac** [comment]
Not possible with the current technology.
.NET 4.8 does not support Linux. Would have to switch to .NET Core or other multi-platform frameworks like Electron.
Currently not worth the struggle. I personally love Linux but TL is mainly used by gamers or people related to gaming content and that still happens 99% on WIndows.

**Comment by DracoDruid** [comment]
Just wanna leave a comment here that Linux support would be great.
Either way, great program, keep up the good work!
