### ISSUE TITLE
Bulk download for downloading a whole channel

### ISSUE THREAD

**Issue by mortenmoulder** [Franiac/TwitchLeecher#500]
Since Reckful passed away recently, I wanted to preserve his memory by grabbing all his VODs (of which there are many), and creating a torrent for them. Or at least archive them on my server, as I have plenty of storage. I've only had good experiences with Twitch Leecher so I figured it would make sense to use that, because the speed is quite a lot better than youtube-dl.

I noticed this issue, that was closed 4 years ago, asking for the same thing: https://github.com/Franiac/TwitchLeecher/issues/6

Any chance we could get this? Going through hundreds of videos (I think he has close to 800) is going to take a long, long time.

Thanks

**Comment by Franiac** [comment]
Closing this because it is part of #225 

Info: I have a new born daughter... development is on hold right now.

**Comment by EpicLPer** [comment]
> Closing this because it is part of #225
> 
> Info: I have a new born daughter... development is on hold right now.

Congrats! :)
