### ISSUE TITLE
Sound issue - harsh esses added

### ISSUE THREAD

**Issue by tightropexilo** [Franiac/TwitchLeecher#501]
I have an issue that emerged recently, when I download video using twitch leecher the audio quality is being degraded and this is most noticeable when it comes to the esses sounds,  it is making them very harsh and unusable.

Downloading a clip from the same channel (I have editor permissions) I see the audio bitrate is 160kbps whereas downloading that video with Twitch leecher it comes through as 128kbps which I believe is causing the issue.

Here is an example of the issue. Twitch leecher makes the audio stratchy and metallic.
https://www.youtube.com/watch?v=yZ_RFB76Rjk

I'm using twitch leecher 1.8, windows 10

**Comment by Franiac** [comment]
Since there is no direct comparison, nobody can actually judge. The "degrade" from 160kbps to 128kbps should be inaudible due to the fact that it is both dogshit audio quality. Though I don't actually know how ffmpeg's conversion algorithm performs. TL re-encodes the audio stream because otherwise you'll get annoying A/V desync when there are dropped frames in the Twitch video.

If you don't need cropping I recommend turning off mp4 conversion in the preferences and downloading the original (and therefor unchanged) video stream as a .ts file. From there you can do wahtever you like with it.

Personal note: I don't get why the hell Twitch limits audio streams to 160kbps when some music streaming platforms offer 96khz/24bit audio. Someone over there needs to realize it's 2020. I complained about 160kbps in 2005.

**Comment by tightropexilo** [comment]
"Since there is no direct comparison, nobody can actually judge"
I'm not sure what you mean by this. If you watch the video you can clearly hear the difference between the two.

Unfortunately cropping was what I mainly used it for, collecting clips longer than 1 minute, preferable to using the Twitch highlighter editor.

I checked using another channel that I know runs at a lower bitrate and it didn't cause an audio issue so I guess going forward I will only be able to use TL on that channel, not the higher quality ones. I don't want to sound ungrateful or anything, I do very much appreciate the software you put together.

**Comment by Franiac** [comment]
What I mean is there is no url to the original Twitch video. Downloading a video from Twitch, cutting it in a video software and re-uploading it to YouTube where the streams get compressed again is not a test. Fortunately I am an audio engineer and with the original source I could check if there is a real problem.

What happens a lot is that people don't understand digital audio and butcher it by choosing wrong sample rates for their video projects, exporting it in another sample rate and maybe lowber bitrate. That sample rate again is incompatible to YouTube, so they resample the audio again, so on and so on....

Not telling you, you did that, but I don't have confirmation that you didn't, if that makes sense. I can go after bugs in my software if I definitely know I have one. So far, I don't know and we're trying it find out. I hope that makes sense. A single conversion with a good algorithm from 160kbps to 128kbps is near impossible to hear even in a direct comparison on very good studio monitors.

Conclusion: Do you have the original Twitch video url? 😄

**Comment by tightropexilo** [comment]
I first noticed it on my video:
https://www.twitch.tv/videos/662977119
Then the same issue on this:
https://www.twitch.tv/videos/662961231
And finally no issue on this one:
https://www.twitch.tv/videos/662860708

**Comment by Franiac** [comment]
So, I have checked the .ts and .mp4 version TL 1.8 spits out. This must be something on your end. I can maybe trick my mind into hearing a difference on my monitors if I take a deep (visual) look at an extremely high resolution frequency analizer in my DAW. But there is absolutely no audible difference, let alone something you would notice in a blind test.

I would like to know how you cut that YouTube video. What software did you use, what was the processing chain? If something in the chain downsamples the audio to 16bit without applying a good dither, inter-sample aliasing can actually have a negative effect in the upper frequency band (s-noises and stuff). Also software may react differently on importing .ts files vs. .mp4. I can only speculate what's going on but fact is, TL does not mess up the audio in the extent of your YouTube video. It "degrades" it to 128kbps, that'S correct, but it does not have the mentioned effect.

**Comment by tightropexilo** [comment]
I can hear the issue when playing back the mp4 from twitch leecher with VLC or k-lite codec pack, so it is happening before it gets into the editing software. I'm using premiere pro though, the newest version.

**Comment by Franiac** [comment]
That is weird. I do not hear anything different when playing back the original files with VLC 3.x

Dunno what to do actually 😞 can't reproduce the issue...
