### ISSUE TITLE
TwitchLeecher v1.8 failure to install

### ISSUE THREAD

**Issue by jwcho0609** [Franiac/TwitchLeecher#503]
I've tried to install the version 1.8 of TwitchLeecher and every time I try to install the application, I get an error message saying "An error occured during the installation. Your system has not been modified. Please click "close" to exit the Setup Window." 
Could I get some help on this? Thanks.

Here are the 2 log files I got:
[log.txt](https://github.com/Franiac/TwitchLeecher/files/4943910/log.txt)
[log_000_TL.txt](https://github.com/Franiac/TwitchLeecher/files/4943911/log_000_TL.txt)

**Comment by Franiac** [comment]
This error is client-side. Some other windows installer executable is blocking TL from beeing installed.
You may attempt to kill all msiexec-tasks and try again.

**Comment by Franiac** [comment]
Stale
