### ISSUE TITLE
Cant download vod with gifted subscription 

### ISSUE THREAD

**Issue by mr-flibble** [Franiac/TwitchLeecher#504]
Hello
I was gifted Twitch channel subscription (so I have that on https://www.twitch.tv/subscriptions?tab=gifts )

But when I try download VOD in Twitch Leeacher 1.7.2  I get message: "This video is sub-only but you are not subscribed to ___"
I tried Channel/Urls and IDs search.

Should it work? Or it's some app/Twitch limitations ? 

Thanks

**Comment by clb92** [comment]
Pretty sure it's a Twitch limitation. In the newest version of TwitchLeecher (1.8) it says "This video is sub-only! Twitch removed the ability for 3rd party software to download such videos, sorry :(" when trying to download sub-only videos.

**Comment by Franiac** [comment]
[https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.0)
