### ISSUE TITLE
Search Urls tab rejecting valid videos with 'video' (not 'videos') in name

### ISSUE THREAD

**Issue by dporges20** [Franiac/TwitchLeecher#507]
When using Twitch's own search, at least, videos can be returned in the form

https://www.twitch.tv/causeimdanjones/video/673362657

This is rejected by the Urls search tab; looking at the code shows that it's looking for "videos/" in the string. 

Locally tested fix in TwitchLeecher.Core.Models.SearchParameters.Validate() -- added  || clause at line 296 (commit 605fce703957f6284b4649245917b7881bfd79c1)

**Comment by Franiac** [comment]
Weird that Twitch is inconsistent... I'll fix it. Thx for spotting it.
