### ISSUE TITLE
Request to add "Download All" button

### ISSUE THREAD

**Issue by Ishwood** [Franiac/TwitchLeecher#518]
Twitch has recently announced that Twitch Sings will stop its services Jan 1st 2020 - additionally it was announced that all Twich Duo VODs will be removed from the Users channels beginning Dec 1st.

The Twitch Sings community is currently trying to save their clips, because they are very valuable to them.

Many users have several hundreds of vods and it would be more easy for them to download all, if a button in the search area was added with "download all" without having the need to confirm every single vod. 

Additionally it would be nice if the title of the vod could be added to the filename automatically.

**Comment by Heistergand** [comment]
@Ishwood  You can change the default filename pattern in the settings. I am using `[{date} {time24}] ({game}) {title}` for example.

But the download all button is really needed and it's urgent.

**Comment by Franiac** [comment]
@Ishwood As I replied to you via mail, at the moment I am keeping TL running if there are breaking changes but new features are on hold due to the fact that I became a father.

**Comment by Ishwood** [comment]
Thank you @Heistergand for that - that really is helpful
@Franiac as I wrote you alreay, you have my full understanding, and I wish you the very best   ;-)

**Comment by Franiac** [comment]
#803
