### ISSUE TITLE
Rate Limit Downloads

### ISSUE THREAD

**Issue by Xirious** [Franiac/TwitchLeecher#519]
TwitchLeecher completely prevents me from using my internet at all when I download a VOD because there is no way to limit the speed at which it downloads. It takes all available bandwidth.

I realise it would be a feature part of the New Download Manager as described in https://github.com/Franiac/TwitchLeecher/issues/46... And it's been requested since 2018 so I don't think it's unreasonable to bring it up again. 

Even just being able to limit the rate would be tremendously helpful.

**Comment by Franiac** [comment]
It is not unreasonable to bring it up, but it does not give me more time to implement things, unfortunately 😃 
Like I posted in other issues, I have became a father and that's top priority right now.
I know #46 is necessary and super lame that it is not yet implemented but it's a quite big thing to do.
Also, implementing rate limit into the current system is a waste of time.

As a little workaround: There are some tools that are able to limit network bandwidth for windows processes. Don't ask me for names, but other users brought it up in a couple issues. Maybe go look for something like that, it could be the problem solver for you.

**Comment by garoto** [comment]
Maybe it's time for you to archive this repo, at least for the time being, because all you've replied to  issues for the past few months is the same boiler-plate response over and over again. It's tiresome.

**Comment by Franiac** [comment]
@garoto I keep things running here depite all the jazz around me and all I get is some "meh, if you don't work on it, just declare it dead". WTF dude, you've been around here long enough to see that we still have a working tool that is being used by thousands of people. It's not the greatest, never was and never will be, but with that kind of attitude I surely won't get motivated. It's like I have to apologize for my baby not growing faster, bleh. If you don't like what you get anymore, press the "Unwatch" button at the top right. I understand your point but there is absolutely no reason to act like I am bothering my users.
