### ISSUE TITLE
Downloading Issue

### ISSUE THREAD

**Issue by YumNom** [Franiac/TwitchLeecher#52]
Im assuming this section is for reporting bugs in the system, but i could be wrong so forgive me, im just a noob. First of all i LOVE this.. ive been using it for a while. But yesterday when trying to download a 6 hour stream it didnt work properly. It only downloaded 30 minutes and when trying to play it back, after 30 minutes it made vlc lag and freeze. I tested a shorter video to see if it was just the 6 hour vid, but i got the same issue. I just wanted to let you guys know. Either way, thanks so much for making this program, its the best! & thanks for reading :P

**Comment by Franiac** [comment]
@YumNom When reporting a bug please provide as much information as possible:

- VOD Url
- TL download settings (quality, cropping?)
- TL download log
- What goes wrong at what time
- VOD url of the working VOD
- ...

Do not get me wrong, but what do you expect me to answer to "it does not work" ;)

**Comment by YumNom** [comment]
Sorry lol, im a big dumb-face. Thanks for replying tho.

-VOD Url: https://www.twitch.tv/markiplier/v/50502626
-All settings on default (original source)
-What goes wrong: It downloads too fast for how long the video is. Says 'Complete'. But when opened in vlc player it displays run-time as 30:00 minutes (on a 6 hour vid), and when playing past the 30:00 minute mark lags and freezes vlc player.

I think its simply an issue of the VOD being years old as apposed to months or weeks. After reporting the bug, i tried a more recent video and it worked fine. It just has trouble with older highlights. Sorry if i was a bother, but i hope the info helps a little :3

But thanks again for creating the program! Its a life saver <3

**Comment by Franiac** [comment]
First thing that I found is a #EXT-X-DISCONTINUITY flag at the end of the Twitch m3u8 playlist for the VOD.

**Playlist:**

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#ID3-EQUIV-TDTG:2016-02-25T18:52:12
#EXT-X-PLAYLIST-TYPE:EVENT

#EXT-X-TWITCH-ELAPSED-SECS:0.0
#EXT-X-TWITCH-TOTAL-SECS:23162.438
#EXTINF:8.334,
transmux-0000000000-LJqO.ts?start_offset=0&end_offset=563811
#EXTINF:8.333,
transmux-0000000001-1ZZq.ts?start_offset=0&end_offset=721731
#EXTINF:8.333,
transmux-0000000002-XaNx.ts?start_offset=0&end_offset=510983
#EXTINF:8.334,
transmux-0000000003-Y6hY.ts?start_offset=0&end_offset=365659

...
...
...

#EXTINF:8.333,
transmux-0000000189-RbLD.ts?start_offset=0&end_offset=349867
#EXTINF:8.334,
transmux-0000000190-Yt3S.ts?start_offset=0&end_offset=403823
#EXTINF:8.333,
transmux-0000000191-id7B.ts?start_offset=0&end_offset=432963
#EXTINF:8.100,
transmux-0000000192-I42b.ts?start_offset=0&end_offset=533731
#EXTINF:5.708,
transmux-0000000193-lhr6.ts?start_offset=0&end_offset=377503
**#EXT-X-DISCONTINUITY**
#EXT-X-ENDLIST

**I found the following information about this in the HLS specification:**

The EXT-X-DISCONTINUITY tag indicates a discontinuity between the
Media Segment that follows it and the one that preceded it.

Its format is:

#EXT-X-DISCONTINUITY

The EXT-X-DISCONTINUITY tag MUST be present if there is a change in
any of the following characteristics:

o  file format
o  number, type and identifiers of tracks
o  timestamp sequence

The EXT-X-DISCONTINUITY tag SHOULD be present if there is a change in
any of the following characteristics:

o  encoding parameters
o  encoding sequence

Conclusion:

This tells us that the streaming settings changed. Now it would be interesting to find out how Twitch manages to keep playing a finished playlist... at 30:30 the playlist is at it's end. Where do the other 5.5hrs of video come from? Will investigate.

**Comment by Franiac** [comment]
@YumNom I have to refer to issue #49 

This is not a problem that I can fix. The stored playlist from Twitch only provides the VOD up until 30:30. I do not know, how the Twitch web player is capable of retrieving the other data after that. Sorry.

**Comment by YumNom** [comment]
Im sure your busy with more important stuff, so I hope it wasn't too much trouble. I'll be sure to check the closed issues first if i have any other problems, but thank you for trying regardless. Have a good one
