### ISSUE TITLE
Twitch Leecher not installing (An Error Occured During The Installation)

### ISSUE THREAD

**Issue by TacticalCooler** [Franiac/TwitchLeecher#520]
I'm launching the Twitch Leecher setup wizard and when I try to install it I get the error "An Error Occurred During The Installation". Ive tried to open the log file put I cant find any instructions on how to open the log file. Version 1.8.1 on Windows 10

**Comment by Franiac** [comment]
Open command line an start the installer with:

` TwitchLeecher_1.8.1.exe -l log.txt`

Try installing and let it run into the error. There should be 2 logfiles now in the same folder as the installer. Post both files here.

**Comment by TacticalCooler** [comment]
So I do believe that the bug was the "Another Installation Is In Progress" bug because I was trying to download something else today and got that error. To fix you have to go to task manager and "end task" Windows Installer. After that launch services.msc and find the Windows Installer, Start it, then stop it and it should download fine. The installer works fine now after doing those steps.

**Comment by Franiac** [comment]
yes, Windows installer can only run a single installataion at a time. If something went wrong earlier and was still stuck, TL doesn't like that 😄
