### ISSUE TITLE
I can´t download sub-only videos!

### ISSUE THREAD

**Issue by reini2121** [Franiac/TwitchLeecher#521]
If i try to download a sub-only video then comes the message "This video is sub-only! Twtich removed the ability for 3rd party software to download such videos, sorry :(".

**Comment by Franiac** [comment]
Correct... exactly what the message tells you. So why the issue?

**Comment by reini2121** [comment]
In the description of this programm stands"Subscriber-only videos can be downloaded"!!!
see this link "https://www.chip.de/downloads/Twitch-Leecher_100979217.html?utm_source=nl_chipd-dy&utm_medium=chip-newsletter&utm_campaign=18-09-2020%2B21%253A00%253A09&utm_content=nl_chipmob&utm_term="
It´s in german, but you can translate it.

**Comment by Franiac** [comment]
I am German :)

I am not responsible for the description texts Chip writes. They tested TL years ago and obviously never updated the text. Here on GitHub you eventually find the truth :P

**Comment by reini2121** [comment]
Dann kann ich ja Deutsch schreiben :)
Unter Letzte Änderungen steht "Twitch Leecher wurde zuletzt am 18.09.2020 aktualisiert und steht Ihnen hier in der Version 1.8.1 zum Download zur Verfügung.", also kann man doch eigentlich annehmen das der Text aktuell ist. Aber was solls, wenn man mit dem Programm die Subscriber-only videos nicht runterladen kann ist es für mich nicht zu gebrauchen. Die anderen Videos kann ich mir ja jederzeit anschauen, die brauche ich nicht runterzuladen, schade, eine nette Idee.

**Comment by Franiac** [comment]
Ja die scannen irgendwie die Repositories und updaten die Installer auf ihren Servern, damit die Leute immer die neueste Version bekommen, aber die Texte lassen sie über Jahre stehen, ohne sie zu überprüfen. Das ist halt dämlich.

Twitch hat erst vor kurzem den Sub-Only Downloads einen Strich durch die Rechnung gemacht. Wieso, weiß keiner, aber kann man leider nix dran ändern.
