### ISSUE TITLE
[FEATURE REQUEST] Write data as yyyy-MM-dd

### ISSUE THREAD

**Issue by Ansem93** [Franiac/TwitchLeecher#523]
As the title says, it would be possible to add a new template like {data2} that would usee yyyy-MM-dd instaead of yyyyMMdd? Or 3 different teemplates {year}, {month},{day}?
It would make it easier to read it.

**Comment by Franiac** [comment]
3 days ago I got an email asking if I can implement "Mar. 13th, 2020 at 07:59:34 PM", no joke 😄 
I hoestly don't want to play this game, it's not fun.

**Comment by Franiac** [comment]
I just checked my inbox for requests about the filename formatting feature in TL. And before people get angry at me I want to provide some insight why I am hesitant:

* 37 emails
* Sum of individual wildcards would be 87 (if I implemented every wish of every user)

So this is just that we are on the same page. I want to implement a downloader, not a brand new C# datetime framework.

I have to give you ( @Ansem93 ) credit to pick the most common and useful of them all and if a nice day comes along and I am in good mood, I may implement the single year/month/day templates in exchange for {date}, but I am sure this will start a whole shitload of requests that make no sense for the general user but only of single individuals.

**Comment by Ansem93** [comment]
I would go for the mulltile  template {year}. {month}... {hour}, maybe {minute} but I think it's already a stretch.
That way everyone will be able to write them as they please. I would stick to the ISO format, so 24 hours and no name for days (also to avoid transaltion request).

**Comment by stijndp** [comment]
If a lot of people really want it, you could make a free field and a link to https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
Then you can .ToString($"{customFormat}") the DateTime prop and be done with it. And give the user a nice error dialogue in the inevitable case they make an error.

**Comment by OleMortensen8** [comment]
I run a little archive .... and .... I'd hoped twitch leecher could be used to format dateson the downloaded like: "(stock title) MM-dd.mp4".
Because I lose valuable sleep for having to edit the date after the fact. 
now, I deal with daily updates often where I need to get em from twitch before archival.

**Comment by OleMortensen8** [comment]
implemented functionality into MY Twitch Leecher. now that I'm confident I'd be able to add the headline issueI'd ask premission to do so. One would be able to spilt a date into  {year}{month}, {day} if it's stil of intrest.

**Comment by Franiac** [comment]
@OleMortensen8 I mean, you can just add a pull request here. I am still quite busy and would appreciate every line of code I don't have to work on.

**Comment by OleMortensen8** [comment]
well but I'm not quite confident in github...  So if I had cloned your repo...  isn't that my repo? how'd I add my change in my cloned repo of yours to the @Franiac  repo or am I missing something? It'd be my first time doing a pull request to someoneelses repo.

**Comment by Franiac** [comment]
Ususally you make a separate branch in your cloned repo that contains the changes you want to request. Then in VS you can just request a new pull request and choose the target branch (my TL master).

Maybe you have to read a little bit about it, but there's plenty of info online. It's never a bad thing to know GitHub a little bit. You cannot make mistakes that affect my repo or anything.

**Comment by OleMortensen8** [comment]
got this. 

"git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream origin date-enchancement:date-enchancement
remote: **Permission to Franiac/TwitchLeecher.git denied to OleMortensen8**.
fatal: unable to access 'https://github.com/Franiac/TwitchLeecher/': The requested URL returned error: 403
Pushing to https://github.com/Franiac/TwitchLeecher
Completed with errors, see above."

**Comment by OleMortensen8** [comment]
I've read up on github and seems like I should have forked it before cloning... I got my Work cut out for me.
