### ISSUE TITLE
[Feature request] Downloading by chapter

### ISSUE THREAD

**Issue by stijndp** [Franiac/TwitchLeecher#526]
When going through the video archive of Twitch channels, they have a chapter function.
The link always goes to the same video. But by opening the video through the chapter links, you open the video directly at the timestamp of the chapter.

I wonder if these chapter timestamps are also given through the API?

**Feature 1**
Then it would be a great enhancement to have a chapter selection after clicking the download button.
A listbox in the crop video section with the from and to of each chapter databound to the from and to fields so they could be automatically filled in by selecting the chapter.

**Feature 2**
Possibly also implement the chapters in the video browser in TL.
Personally I don't use TL to browse for videos. I go to Twitch, find what I want and then track it down in TL to download. But users who do use TL to browse, might find it handy to also see the chapters in the search overview.

It's only a nice to have.
![image](https://user-images.githubusercontent.com/29801608/96441040-21712180-1209-11eb-9da3-ca045ddd713c.png)
Inspecting the panel is pretty much the easy way to find the timestamps and manually enter them in TL right now. It's a pretty cumbersome way to work.

**Comment by Franiac** [comment]
I like the idea, but there is no API support for it, unfortunately 😞
