### ISSUE TITLE
what about audio download only ?

### ISSUE THREAD

**Issue by capellavacancies** [Franiac/TwitchLeecher#535]
thanks for this app
I'm pretty sure it was possible to download audio only, is this feature now removed or was I dreaming ?

thanks

**Comment by Franiac** [comment]
The feature is there and works. The thing is, not all VOD's support it. Twitch sometimes supports it and sometimes not. I sense it has something to do with whether you are partnered/affiliate or not. But that's just a feeling. Twtich always was and will always be a mess when it comes to the question "does this support that?". So I only can tell you: If it works, it works... if not... then not 😄
