### ISSUE TITLE
[ERROR] Download Finished, but file cannot be rendered, when being played!

### ISSUE THREAD

**Issue by ScyllaHide** [Franiac/TwitchLeecher#537]
I wanted to download a twitch video with the recent version 1.8.1. Everything went fine until the download is finished and the video is put together. The resulting video cannot be rendered. TL also shows this as error, after the download job is finished.

im running win10Pro version 1903 x64! I have no idea, what could have caused this problem. Last week i download a video the last time and it went smoothly.

Here is the video im talking about:
https://www.twitch.tv/videos/810717998

Remark: the video has muted copyrighted parts, but this was never a problem before.
Here is the log file: 
https://pastebin.com/AJAWrBnv

**Comment by Franiac** [comment]
From the log:

> Error writing trailer of C:\Users\Ameyah\Downloads\20201121_810717998_Music.mp4: No space left on device

I think we found the issue 😄

**Comment by ScyllaHide** [comment]
file was 6GB, there was still enough space left, 10GB was left after download. hmm okay, then im sorry for posting here. i will try it again tmro.

thank you!

**Comment by Codereaders** [comment]
It while the download/ file conversion is in progress it takes on about twice the size of the final video.

**Comment by Franiac** [comment]
One could definitely implement this a little bit better and delete merged files "on the go" in order to minimize the "duplicate" space needed... but... you know how it is 😄
