### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Zemogiter** [Franiac/TwitchLeecher#539]
So I've taken a look at simillar, closed issues and none helped. Using 1.8.1 installer. Windows 10 20H2.
The progress bar remains empty then after about 4 seconds I get this
![Przechwytywanie](https://user-images.githubusercontent.com/24385408/100552444-8481b980-3287-11eb-8c27-6a854382e996.PNG)

[log.txt](https://github.com/Franiac/TwitchLeecher/files/5612781/log.txt)
[log_000_TL.txt](https://github.com/Franiac/TwitchLeecher/files/5612782/log_000_TL.txt)

Alse the partition I'm installing to is compressed but I dont think that's an issue.

**Comment by Franiac** [comment]
The installer engine returns error code 1632. According to [this](https://csi-windows.com/toolkit/windowsinstallererrors) either your temp folder is full or inaccessible.

Where does the Windows Explorer point to when you type %TEMP% in the address bar?

Normally it should point to

`C:\Users\[Username]\AppData\Local\Temp\`

If you changed that or the new location does not have enough access rights, you should provide them.

**Comment by Zemogiter** [comment]
It points to that location exactly. And the access rights are therefore not an issue.

**Comment by Franiac** [comment]
I can't help in this case, unfortunately. The error is not thrown by the TL installer but the Windows installation system running on your PC. Maybe clean the temp folder and try again?
