### ISSUE TITLE
Video files don't work with Sony Vegas 12

### ISSUE THREAD

**Issue by rmkomeshak** [Franiac/TwitchLeecher#54]
Tried mp4 files from both Shadowplay and Dxtory and they were working fine. But as soon as I tried to add the files from twitch leecher into my project, it would just crash SV12.

**Comment by Franiac** [comment]
If it is a VOD of yourself, recheck your streaming settings. TL only copies the stream from Twitch. TL does NOT encode anything, so there is nothing TL can do or change about the mp4 file. I tried my own streams in Vegas 13, and everything works perfectly. Maybe you should try Sony Vegas support instead. If Sony cannot handle a mp4, it is a problem of Vegas, not a problem of the mp4 file or TL.
