### ISSUE TITLE
Frame Loss

### ISSUE THREAD

**Issue by ElementNull** [Franiac/TwitchLeecher#540]
Every time I download a long vod, many frames are lost late into the video. The first hour or so is usually alright, but when I move to about 3 hours into the stream I'm only getting about 1 frame for every 5 seconds. The problem gets worse over time. I'm using a fresh install of 1.8.1.

**Comment by Franiac** [comment]
What do you mean? Losing or dropping frames is something that occurs when streaming whenever your PC is not fast enough to put togeter the next frame of the video just in time. Since TL is not encoding anything but only downloading and merging files on a binary level "losing frames" is something it actually cannot do. Please be more specific and/or provide examples or reproducable steps.

**Comment by Fezian** [comment]
Having the same issues, it seems that after the hour mark of a VOD the footage starts to skip and the skipping seems to worsen as the VOD goes on.

**Comment by Franiac** [comment]
This does not help. Please post examples/reproducable steps/logfiles as mentioned in the issue template. I am not a magician or mentalist. What are you trying to do? How? What video? Channel? Mp4 convertion or not? What video player are you using to verify?

C'mon guys... you also don't go to the car shop ant tell them "it doesn't work" and leave...

**Comment by Fezian** [comment]
My apologies, after further testing to see if it was on my end I recognized that it was probably my default video player causing issues. After switching to VLC it no longer has the frame skip. So yeah, I don't know what the other guy is on about.

**Comment by Franiac** [comment]
What was the other player? Windows Media Player cannot handle Twitch streams very well. VLC is always the best option.

**Comment by Fezian** [comment]
> What was the other player? Windows Media Player cannot handle Twitch streams very well. VLC is always the best option.

Yeah, that was the one. It did not handle it well. I decided to use VLC instead and it worked perfectly.

**Comment by Franiac** [comment]
Closed beacuse no further input from OP
