### ISSUE TITLE
Downloading Chat logs feature

### ISSUE THREAD

**Issue by Kaszanas** [Franiac/TwitchLeecher#541]
Hello,

This is technically a feature request.
What are Your thoughts on introducing chat download along with respective video?
There are existing implementations of such code available untested example would be:
https://github.com/PetterKraabol/Twitch-Chat-Downloader

Another question would be if it is possible to use TwitchLeecher as a command line tool - which would ease the pain of using 2 command line software one for downloading video another for downloading chat.

**Comment by Franiac** [comment]
For command line support see #462

**Comment by speedevil** [comment]
I'm glad someone has already raised this, saves me typing. Just donated 5.41 euros as some form of non-binding indication. :) Would save me having to work out another software. (for me at least, some text IRC style log with timestamps would be best)

**Comment by Ethan-BB** [comment]
I'm currently using TwitchDownloader for getting chat logs and manualy converting them to SRT subtitles to use on youtube ... automating that would be amazing.

**Comment by skyfox1977** [comment]
This is an old feature request by now and is is something I also very much would love to have implented in TwitchLeecher

**Comment by Franiac** [comment]
#803
