### ISSUE TITLE
Not downloading directly to remote location?

### ISSUE THREAD

**Issue by riahc3** [Franiac/TwitchLeecher#542]
Hello :)

When I am downloading a large VOD file, I store it in a remote share as it occupies a lot of space. I havent had any issues until today where I am downloading a HUGE one and Twitch Leecher each time says it cannot download it because there is not enough disk space.

I was surprised because I have enough disk space on the remote location (TBs and TBs)

The thing is that while downloading I expected a file being created on the remote share and it slowly getting bigger. 

This is NOT the case.

I suspect then that Twitch Leecher is trying to LOCALLY first download the file then it moves it to the location I specify.

This does not work well when you have HUGE VODs that you want to download and want to store them in a remote location.

I consider this a "bug" as it makes no sense to put it in a remote location and instead it first downloads it locally.

Could you please take a look at this? I doubt Im the only one that stores VODs in a remote location.

Thanks

**Comment by riahc3** [comment]
Never Mind

**Comment by Franiac** [comment]
So I guess you found the "temporary download folder" setting...
