### ISSUE TITLE
Getting "Unexpected error" after a username change

### ISSUE THREAD

**Issue by Flamaros** [Franiac/TwitchLeecher#546]
I am following a user that have change his name from nayaser88 to j_blow.

I am getting an unexpected error when launching TL as it is the default search on this user.
It took me a while to understand the issue, it will be nice if I go a better error message like "The user nayaser88 doesn't exist,...".

Thank you for this very useful application.

I wish you the best for the new year.

Here is the full log file:
`System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Net.WebException: Le serveur distant a retourné une erreur : (404) Introuvable.
   à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   à System.Net.WebClient.DownloadString(Uri address)
   à TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   à TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
---> (Exception interne #0) System.Net.WebException: Le serveur distant a retourné une erreur : (404) Introuvable.
   à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   à System.Net.WebClient.DownloadString(Uri address)
   à TwitchLeecher.Services.Services.TwitchService.SearchChannel(String channel, VideoType videoType, LoadLimitType loadLimit, DateTime loadFrom, DateTime loadTo, Int32 loadLastVods)
   à TwitchLeecher.Services.Services.TwitchService.Search(SearchParameters searchParams)
   à System.Threading.Tasks.Task.Execute()<---
`

**Comment by Franiac** [comment]
This is actually a bug. Some time ago the "channel name" ComboBox was a Textbox (without the dropdown option).

If there is an error, the textbox should get a red background (not only a red border) and a tooltip with the error message.

I'll fix that in a future update.

**Comment by Flamaros** [comment]
Ok, thank you
