### ISSUE TITLE
Allow file names that are longer than 260 characters

### ISSUE THREAD

**Issue by MPeti1** [Franiac/TwitchLeecher#547]
The only related (closed) issue I found relating to this problem is #451, but it hasn't evaluated the option of allowing longer paths than the default limit in NTFS.

<details>
<summary>Download log of TL</summary>
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.1

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 805157048
Selected Quality: 1920x1080@50fps (Source)
Download Url: https://www.twitch.tv/videos/805157048
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\masap\Downloads\VODs\20201116-175254 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Johnny Depp and Die Hard_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-020341.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_6656fbf8-e133-4f07-8754-f5b057c8417e

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1610175273%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A805157048%7D
Signature: 1fa1c47b7c5bc234bb349d30d39f1225b8f7db3b
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_6656fbf8-e133-4f07-8754-f5b057c8417e'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/chunked/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/720p60/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/480p30/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/audio_only/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/360p30/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@50fps (Source) is https://d3c27h4odz752x.cloudfront.net/1daff6da6bef06071667_fusiontv1_40010310284_1605545563/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 743

Starting parallel video chunk download
Number of video chunks to download: 743
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_6656fbf8-e133-4f07-8754-f5b057c8417e\20201116-175254 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Johnny Depp and Die Hard_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-020341.ts'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_6656fbf8-e133-4f07-8754-f5b057c8417e'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_6656fbf8-e133-4f07-8754-f5b057c8417e\20201116-175254 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Johnny Depp and Die Hard_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-020341.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_6656fbf8-e133-4f07-8754-f5b057c8417e\20201116-175254 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Johnny Depp and Die Hard_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-020341.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
</details>

TL version: 1.8.1
Video URL: https://www.twitch.tv/videos/805157048
OS: Windows 10 64 bit (NTFS length limit disabled by Group Policy, been using this feature for a few years, no problems so far)

I occasionally ran into this issue where the download fails just before conversion because the length of the final path is longer than the default NTFS limit. When this happens, I usually change the download dir to something like C:\Temp, but it's annoying when a bunch of downloads error out because of this, after the many hours have been downloaded.

I've disabled the length limit in Group Policy a few years ago, and I haven't encountered problems with it being this way, popular software like Total Commander and VLC can handle it well.

Here you can find some information about disabling the path length limit, and adding support for it to TL:
Tenforums article: https://www.tenforums.com/tutorials/51704-enable-disable-win32-long-paths-windows-10-a.html
Microsoft documentation: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

I'm not much into C# (I can read it, but I'm not familiar with the APIs it uses), but it seems the change can be as simple as including a new setting in the manifest file. If you can make a beta build with this change I would be happy to test it.

Before writing this, I remembered that I wanted to open an issue for this multiple times already, so I checked whether I actually did it, but haven't found an other one. But if I just missed it, or it was deleted, sorry for making a duplicate

**Comment by Franiac** [comment]
There are multiple things to consider here:

1. The problem that the exception gets thrown after download is a bug. The target folder gets checked before download but obviously not the temporary download folder. That should get checked, too and I will correct this in a future update.

2. You are only talking about NTFS. There are many users that use external drives or USB sticks or century old NAS systems as their download targets. Commonly those are formatted with FAT32. I have not dived into the topic, but is this potentially an issue?

3. The long path option is "opt-in" in WIndows 10 >=1607. Honestly you are the first person ever that I met dealing with this setting. I don't know anyone, not even in a partnered Ccompany having this setting enabled. I have worked with Microsoft as a partner for over 20 years and I can tell you one thing: If MS declares something "opt-in", they are not really sure about it.

Fact is: The average TL user does not care or does not know about long paths and even if he does know, a very small percentage would opt-in. A Twitch gamer does not deal with Windows group policies. This is a very very tiny edge case. Before I change something like this, I need to clarify that the change works on every supported OS, machine and file system.

**Comment by MPeti1** [comment]
2: According to [Microsoft](https://docs.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison#limits), all filesystems officially supported by Windows allow a length of 255 characters for filenames (little inconsistency with their other article..), except UDF, but I don't think users will want to download directly to optical disks.
So in their case the default limit should be ok.



Why I actually want this is that I just stumbled upon streams from a channel that I follow that has long enough stream names that they, with the default temp dir and my short username (5 chars), and I would like to archive this in their original form. Currently I do that by copying the title to notepad, changing the name to a single pattern, and renaming them after they completed. Earlier I also downloaded the chat, but something happened with my API key and twitch would only give me a new one if I give them my phone number, so fuck them, I'm not doing it since that.

> A very small percentage would opt-in

Probably there are (not much, but not that few) people who just don't know that they have opted in. There are popular software (e.g. qBittorrent, Python) that has a setting in the installer to disable the length limit, and it's is on by default.

![image](https://user-images.githubusercontent.com/9215491/104054834-1a492680-51ee-11eb-908b-e35bf7b064f3.png)

Also, an other bunch of people might not know about it, because [it turns out](https://github.com/qbittorrent/qBittorrent/issues/6645#issuecomment-509307806) that there are API methods that allow write operations even without the manifest setting (and maybe the registry one too?), but then I don't know why does the problem affect TL. Maybe that's only working for c++ APIs?

> Before I change something like this, I need to clarify that the change works on every supported OS, machine and file system.

It does not seem to me that it would break existing configurations. What it changes is that instead of checking MAX_PATH, Windows will check the lpMaximumComponentLength from [GetVolumeInformation](https://docs.microsoft.com/en-us/windows/desktop/api/FileAPI/nf-fileapi-getvolumeinformationa), and now instead of only by UNC paths, long paths can also be used normally.
[Here](https://github.com/dotnet/runtime/issues/19209) is an issue from 2016 in which they added the support for long paths. But actually, from this I only got confused, because what I understand from it is that this should work by default?

**Comment by Franiac** [comment]
I have to evaluate what the standpoint of the .NET Framework is regarding long paths. Surely you can call whatever C++ Win32 API you want, but it depends on what .NET uses in my case. Meaning: Does .NET call the API that actually checks the lpMaximumComponentLength and so on? Also I have to check if you can enable long path support in a .NET manifest file which is different from the Win32 manifest file described in your original link.

Personally I think a software that enables opt-in features of any OS as a default in its installer should be banned. It does not matter what option that might be or if it works or not. Changing an opt-in option in an random installer of a random software is an absolute nogo. What would you think if TL enabled "optional updates" for your Windows update service? Nobody wants that 😄 So these garbage pieces of software are not a guideline I support.

**Comment by Franiac** [comment]
.NET 4.6.2+ supports long paths if

```xml
<runtime>
  <AppContextSwitchOverrides value="Switch.System.IO.UseLegacyPathHandling=false;Switch.System.IO.BlockLongPaths=false" />
</runtime>
```

is set in the app.config.

I have to do some tests if it works for both worlds (long paths enabled of disabled). If it does, it could be an easy enhancement to TL.

**Comment by MPeti1** [comment]
> 
> 
> .NET 4.6.2+ supports long paths if
> 
> ```
> <runtime>
>   <AppContextSwitchOverrides value="Switch.System.IO.UseLegacyPathHandling=false;Switch.System.IO.BlockLongPaths=false" />
> </runtime>
> ```
> 
> is set in the app.config.
> 
> I have to do some tests if it works for both worlds (long paths enabled and disabled). If it does, it could be an easy enhancement to TL.

I've tried it already, but it does not seem to make a difference :/ I thought it's just not working for some reason.

<details>
<summary>Download log of TL</summary>
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.1

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 813120834
Selected Quality: 1920x1080@50fps (Source)
Download Url: https://www.twitch.tv/videos/813120834
Crop Start: No
Crop End: Yes (00:02:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\masap\Downloads\VODs\20201123-175125 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Dinos and Medical TV Shows_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-000200.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_2aa45eb1-754a-4aba-8716-57663909a920

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1610212508%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A813120834%7D
Signature: fb9296626628304a4960c9e36209cb11eaa53001
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_2aa45eb1-754a-4aba-8716-57663909a920'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/chunked/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/720p60/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/480p30/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/audio_only/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/360p30/index-dvr.m3u8
https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@50fps (Source) is https://d3c27h4odz752x.cloudfront.net/56dced3e1391e20d61e0_fusiontv1_40105142604_1606150274/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 730

Starting parallel video chunk download
Number of video chunks to download: 12
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_2aa45eb1-754a-4aba-8716-57663909a920\20201123-175125 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Dinos and Medical TV Shows_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-000200.ts'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_2aa45eb1-754a-4aba-8716-57663909a920'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_2aa45eb1-754a-4aba-8716-57663909a920\20201123-175125 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Dinos and Medical TV Shows_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-000200.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\masap\AppData\Local\Temp\TwitchLeecher\TL_2aa45eb1-754a-4aba-8716-57663909a920\20201123-175125 - WIN a Horizon_ Zero Dawn Board Game!_ Test your knowledge on Dinos and Medical TV Shows_ @fusionquiz - Talk Shows & Podcasts - 1920x1080-50 fps_till-000200.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
</details>

**Comment by mouarflenoob** [comment]
Hi ! i just wanted to say that I also had the issue of filenames being too long in the past, because a streamer was putting several sentences in the title of his stream. I'm not sure you guys are talking about this exact issue, but I this it would be amazing if TL handled such issues "gracefully", meaning, handling the length by itself, or even letting me decide the max length of each wildcard.

Am I in the correct spot to comment or should I make another change request / bug report? let me know and I'll happily do it, sorry for the inconvenience.

**Comment by Franiac** [comment]
I cannot get long filenames to work with a .NET 4.8 application. I don't know what it is. I have tried everything Microsoft has documented in their online references.

This feature seems to be broken in so many places. You cannot even create long filename dictionaries in Explorer. If a long dictionary exists, Explorer can handle it, but it cannot create it.

I have the impression that even MS is not ready for this yet. I am not going to put more time into it at the moment, it leads to nothing.
