### ISSUE TITLE
[Feature Request] Remember settings between sessions

### ISSUE THREAD

**Issue by CrazieIvan** [Franiac/TwitchLeecher#548]
Thanks for the nice app! 
I'd like to suggest the following QoL improvements:

1.  Search history.  It's strange - I can see a dropdown menu in the channel name search box, which looks like it should have a list of past searches, but mine is empty.  I don't know if I'm using it wrong somehow...
2. Remember the last saved folder location.  
3. Remember the enabled checkbox for "Use custom filename".  TBH I don't know why this is even a toggle, and why the name isn't customizable by default.  

Other than that, it's a pretty useful app.  I appreciate your continued work on it!

**Comment by Franiac** [comment]
You definitely should take a look at the preferences of TL.

1. The dropdown is not really well implemented to be honest. You can add favourite streamers in the preferences... those will show up.
2. Like I said -> preferences
3. Most users use filename templates, so they don't need to do anything for each download. The checkbox is there to toggle between the standard (template) and the custom mode.

The dropdown of point 1 could remember the last searched channels, that's right, but everything else works as intended and has been discussed multiple times.
