### ISSUE TITLE
Suggestion: Add ability to pause download

### ISSUE THREAD

**Issue by Arnz5050** [Franiac/TwitchLeecher#549]
I find it annoying personally that I can't pause the download of a vod, the only way to get some bandwidth back is to cancel it entirely
If you can find a way to get the program to pause the downloading, that would be awesome

Thanks

**Comment by Franiac** [comment]
See #46 

I know it's an issue from 2016, but life is life and time is time, a download manager is complicated and TL is the lowest priority project that I am currently running 😄
