### ISSUE TITLE
mp4 suffers audio desync when cutting in avidemux

### ISSUE THREAD

**Issue by dede5** [Franiac/TwitchLeecher#55]
Hi,

First, thank you for this beautiful program. It is very well made.

I noticed that Twitch VoD Downloader and this program both face a similar problem. The downloaded VOD played fine, but suffers desync as soon as I try to cut the video [to keep a section] inside avidemux. I hope you could fix this. I suspect it has something to do with downloading the many small chunks somehow messes up the audio sync.

**Comment by Franiac** [comment]
This is not an issue regarding TL. It is an issue of wrong project settings in the video software (maybe sample rate or bit depth I suppose). I had this already with a guy using Premiere and Vegas. Vegas has an option to match the video source file properties and use them as project properties. Everything worked fine after that. I use Vegas Pro 13 myslef without any problems when the properties are ok.

**Comment by dede5** [comment]
Ok. Thank you!
