### ISSUE TITLE
Error 404 when trying to download any VOD

### ISSUE THREAD

**Issue by DonkeyKong123321** [Franiac/TwitchLeecher#550]
- If you have a problem with a download, provide the download log created by Twitch Leecher
Error [404] an unexpected error occured... all details was written to the log

- Provide the version of Twitch Leecher you are using
-1.81
- Provide information about the video (Url, Channel, ID)
https://www.twitch.tv/videos/869004058 all of this vods... No vods on twitch works, i tried multiple channels

- Provide information about your operating system (e.g. Windows 10 64 Bit)
Windows 10

- Try to describe the problem as detailed as possible, I cannot read your mind
I copy the link of the twitch video as usual, paste it into the twitch leacher program under serach > urls 
When i press download, it shows error 404, and the download doesnt go through. Its all the same with every vod on twitch. It worked fine yesterday.

**Comment by KralOstruzin** [comment]
I have the same problem.

**Comment by TheTitoLeo** [comment]
I got this issue as well
Its says this:

An unexpected error occured:

The remote server returned an error: (404) Not Found

All details were written to log file

(then here is just some mumbo jumbo I don't understand)

**Comment by cooldude222222222** [comment]
Same issue here.

System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

Version 1.8.1

Various different Twitch videos from different channels.

Win10 64

When clicking the download button on the search tab this message appears:
The remote server returned an error: (404) Not found.

**Comment by momosugus** [comment]
It happens the same to me...
Remote server error:(404) not found
version 1.8.1
W10 64

System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   en TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by jimmyeatsquaids** [comment]
Same issue for me: Remote server error: (404) not found

**Comment by Kirdnevs** [comment]
I have the same issue when clicking on the download button of the vod after searching for the VOD.

System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   bei TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)
   
Twitch Leecher 1.8.1

WIN 10 Pro | 64-bit | Version 1909 | Build 18363.1316

I tried several channels (~5). I tries old and new VODs (1 day old and also 1 year old). None worked

**Comment by Lord-Curdin** [comment]
Same Issue 
System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
bei System.Net.WebClient.DownloadString(Uri address)
bei TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
bei TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

Twitch Leecher 1.8.1
WIN 10 Pro | 64-bit | Version 1909 | Build 18363.1256

**Comment by JoeyGameLover** [comment]
Same here. Error log:

System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Tahsin123456** [comment]
i have the same issue brothers

**Comment by TNightster** [comment]
Same issue reported:
Win10, TL 1.8.1

The remote server returned an error: (404) Not Found

Issue appeared approximately 48-96 hours ago.

**Comment by MobiusReactor** [comment]
Seems to be a change on twitch's end, twitch-dl and youtube-dl both broke too.

**Comment by Tahsin123456** [comment]
> Seems to be a change on twitch's end, twitch-dl and youtube-dl both broke too.

what does dl mean

**Comment by ChristopherI-Dev** [comment]
> > Seems to be a change on twitch's end, twitch-dl and youtube-dl both broke too.
> 
> what does dl mean

Download

**Comment by Franiac** [comment]
Please keep it clean and don't spam the same stuff over and over again...

**Comment by twitchbear** [comment]
I have the same problem for 2 days. Can anyone find a solution?

**Comment by Franiac** [comment]
The following API is currently unavailable:

`https://api.twitch.tv/api/vods/{0}/access_token`

where `{0}` is the video ID. It is used to retrieve the access token for the video in order to be able to access the playlist. Without an access token -> no download.

So far I have taken a look at the Twitch website and how they retrieve the token. They get their access token over their private GQL API. I think one cannot access it from the outside since there are SHA256 hashes in the game that probably verify API calls (not sure, though).

Scenario 1: The old API just comes back and TL starts working again.

Scenario 2: Someone finds another way to retrieve the token. Currently I don't see one.

Scenario 3: This was intentional by Twitch in order to block "shady" tools like TL and youtube-dl and so on.

At the moment I cannot help or do anything because I don't see a workaround to get the access token without the old API. Let's first wait a bit for it to come back online. If that does not happen... we either find a solution or not 😄

**Comment by Wojsan** [comment]
how is situation?

**Comment by Eastborn** [comment]
It seems to be fixed for me

**Comment by Franiac** [comment]
Can confirm

**Comment by Franiac** [comment]
So as predicted: Scenario 1 it is... closed 😄

**Comment by Codereaders** [comment]
@Franiac as for an alternative to the `api` endpoint you could use their `GraphQL` endpoint.
It's what they use on their website too and it should be more up to date.

Here's a query template for the old api and how it translates.

Let's assume the following:
xxxxx - client id
yyyyyy - corresponding oauth token (without `oauth:`)
zzzzzzz - the vod id you're interested in

The old API:

```bash
curl \
    -H 'Accept:application/vnd.twitchtv.v5+json' \
    -H 'Client-Id:xxxxx' \
    -H 'Authorization:Bearer yyyyyy' \
    -X GET \
    https://api.twitch.tv/api/vods/zzzzzzz/access_token?oauth_token=yyyyyy
```

The gql API:

```bash
curl \
    -H 'Accept: application/json' \
    -H 'Authorization: OAuth yyyyyy' \
    -H 'Client-ID: xxxxx' \
    --data-raw '....' \
    'https://gql.twitch.tv/gql'
```

That's the (raw) data:

```json
{
    "operationName": "PlaybackAccessToken_Template",
    "query": "query PlaybackAccessToken_Template($login: String!, $isLive: Boolean!, $vodID: ID!, $isVod: Boolean!, $playerType: String!) {  streamPlaybackAccessToken(channelName: $login, params: {platform: \"web\", playerBackend: \"mediaplayer\", playerType: $playerType}) @include(if: $isLive) {    value    signature    __typename  }  videoPlaybackAccessToken(id: $vodID, params: {platform: \"web\", playerBackend: \"mediaplayer\", playerType: $playerType}) @include(if: $isVod) {    value    signature    __typename  }}",
    "variables": {
        "isLive": false,
        "login": "",
        "isVod": true,
        "vodID": "zzzzzzz",
        "playerType": "site"
    }
}
```

I'm not using the gql API endpoint much. But it should be maintained and it's quite powerful from what you can query via it.

**Comment by Franiac** [comment]
@Codereaders I have digged into the GQL API a little bit but never actually called it. Is it just "open", meaning you only need the CLient-ID in order to make requests? I saw hashes and stuff in the requests and responses of the website and was not sure if it is "locked" in some way for external use.

Another question: Do you know by any chance if there is a way to retrieve the quality/resolutions of a VOD via GQL? I still have not found anything other than the old Kraken API or "regexing" the playlist links.

**Comment by Codereaders** [comment]
kranken (legacy) and helix are the only official APIs maintained for developers. 
All others (gql.twitch.tv, api.twitch.tv, usher.twitch.tv, etc) are all basically internal APIs. However as they use them on their website it's technically possible to use them in your applications too. Might cause some maintenance overhead for you as they could potentially change the internal APIs from one day to another - even if it's not very likely.

**Comment by Codereaders** [comment]
I extract the video information (resolution and framerate) from the playlist file directly not via any API.
However as twitch highly makes use of the gql API, they might have an appropriate endpoint for that too.

First you need an auth and signature tuple:
(This is the old fashioned api endpoint, but there's also a qgl-API endpoint for that.)
```
https://api.twitch.tv/api/vods/{$video_id}/access_token?oauth_token={$oauth}
```

auth is some sort of json data blob, sig is a hash

Next step is to request the playlist:
```
http://usher.twitch.tv/vod/{$video_id}?nauthsig={$sig}&nauth={$token}&allow_source=true
```

You can extract the required information with this one:
```php
function filterMetadata($haystack) {
        $pattern = "/(GROUP-ID=\"\d+p(\d+)|NAME=\"\d+p(\d+)).+\n.+(?=RESOLUTION)RESOLUTION=(\d+x\d+)/m";
        $matches = [];
        preg_match_all($pattern, $haystack, $matches, PREG_SET_ORDER);

        try {
            // filter matches and normalize rows
            foreach($matches as $key => $match) {
                $l = count($match);
                $matches[$key]   = [];
                // Resolution
                $matches[$key][] = $match[$l-1];
                // FPS, either found in GROUP-ID or in NAME
                if(!empty($match[$l-2])) {
                    $matches[$key][] = $match[$l-2]; // FPS
                }else if(!empty($match[$l-3])) {
                    $matches[$key][] = $match[$l-3]; // FPS
                }else {
                    $matches[$key][] = null; // FPS
                }
            }
            return $matches;
        }catch(\Exception $e) { /* deal with any exception */ }
}

// raw data returned from usher
$haystack = ""; 
```

**Comment by Franiac** [comment]
@Codereaders That's what I meant with "regexing" the playlist links. A lot of projects do it this way. In TL I get the resolutions and framerates from Kraken, still since I don't use Helix yet (and won't until it is really necessary).

Nevertheless I am really curious how Tiwtch are doing it, since I have not found any GQL request regarding resolutions/framerates when opening a VOD.

**Comment by Franiac** [comment]
@Codereaders  taking a look at youtube-dl, they actually store the hashes for each GQL operation in an array

```python
_OPERATION_HASHES = {
        'CollectionSideBar': '27111f1b382effad0b6def325caef1909c733fe6a4fbabf54f8d491ef2cf2f14',
        'FilterableVideoTower_Videos': 'a937f1d22e269e39a03b509f65a7490f9fc247d7f83d6ac1421523e3b68042cb',
        'ClipsCards__User': 'b73ad2bfaecfd30a9e6c28fada15bd97032c83ec77a0440766a56fe0bd632777',
        'ChannelCollectionsContent': '07e3691a1bad77a36aba590c351180439a40baefc1c275356f40fc7082419a84',
        'StreamMetadata': '1c719a40e481453e5c48d9bb585d971b8b372f8ebb105b17076722264dfa5b3e',
        'ComscoreStreamingQuery': 'e1edae8122517d013405f237ffcc124515dc6ded82480a88daef69c83b53ac01',
        'VideoPreviewOverlay': '3006e77e51b128d838fa4e835723ca4dc9a05c5efd4466c1085215c6e437e65c',
    }
`

That is some code that might break super easily if Twitch implements something like a weekly hash roundtrip or something 😄 
But it confirms at least ,the GQL API is "usable".

**Comment by Wojsan** [comment]
System.Net.WebException: Serwer zdalny zwrócił błąd: (404) Nie znaleziono.
   w System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   w System.Net.WebClient.DownloadString(Uri address)
   w TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   w TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by IzaGz** [comment]
same problem here, cant download, any issues ? will it be fixed ? the video will expire, i need to download it please help!!!!

**Comment by sinanpalloks** [comment]
I still have the same problem. I am trying youtube-dl now but it's really inconvenient in comparison I could get it running until now. Is there a paid program that still works? I just now realized how much I depended on TL for my work

**Comment by Franiac** [comment]
Twitch Leecher 1.82. is released! should be working again 😄

**Comment by Codereaders** [comment]
@Franiac I think I know what the sha-hash stands for:
GQL allows you to describe how the response's data structure should look like. As an alternative to scripting the response, you can also send the corresponding hash.

**Comment by Franiac** [comment]
@Codereaders Nope, you're wrong 😄 

[https://dgraph.io/docs/master/graphql/queries/persistent-queries/](https://dgraph.io/docs/master/graphql/queries/persistent-queries/)
