### ISSUE TITLE
Able to find the video but returns a 404 when trying to download

### ISSUE THREAD

**Issue by Chutler** [Franiac/TwitchLeecher#558]
- _If you have a problem with a download, provide the download log created by Twitch Leecher:_
 `System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrieveVodAuthInfo(String id)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)`
- _Version of Twitch Leecher:_ 1.8.1
- _Provide information about the video:_ https://www.twitch.tv/videos/878155810
- _Provide information about your operating system:_ Windows 10 64 Bit
- _Try to describe the problem as detailed as possible, I cannot read your mind:_ TL is able to find the video in a search but when I click download it is returning a 404. See log above.

**Comment by holysnipz** [comment]
> Version of Twitch Leecher: 1.8.1

[1.8.2 fixed this already](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.2)

![image](https://user-images.githubusercontent.com/9103583/104879036-a9450400-598f-11eb-9b96-c92ea4d6e356.png)

*more info (if you interested) : #550 #551*

**Comment by Chutler** [comment]
Excellent. Odd that it didn't prompt me about a new version when I launched 1.8.1. Anyhow, thank you!

**Comment by Franiac** [comment]
@Chutler Maybe check if you have "Check for updates" enabled in the preferences...
