### ISSUE TITLE
versions after 1.8 won't launch

### ISSUE THREAD

**Issue by zweek** [Franiac/TwitchLeecher#561]
Running Windows 10 64bit
Installation works fine, but trying to launch the program on version 1.8.1 or 1.8.2 seemingly does nothing. (I'm able to launch 1.8 without problems)
Checking in the task manager, the process shows up as many times as I try to open the program, but I'm unable to close the process (Unable to terminate process, Access is denied). This also disallows me from uninstalling until I restart my PC

**Comment by Franiac** [comment]
The only thing I can think of is that you don't have .NET Framework 4.8 installed as it's required by TL 1.8+
Other than that I don't see what could be wrong with your PC.

**Comment by zweek** [comment]
I do already have .NET framework 4.8, tried installing it again manually to be sure and the setup told me that I already have it, so this doesn't seem to be the issue for me

**Comment by Franiac** [comment]
Do you have anti-virus installed by any chance? Since TL is an open unsigned application, some anti-virus tools block it.
