### ISSUE TITLE
Small bug. Download folder is wrong.

### ISSUE THREAD

**Issue by DitNavn** [Franiac/TwitchLeecher#562]
It is a small problem but i just thought i would let you know.
When a video is done with the download then the button at the bottom of the screen that says "Open Download Folder" doesn't go to the acutal folder you selected at the start of the download, it just goes to the deafult "Downloads" folder.
I don't know if this is intentional but it's kinda weird.

I am using:
Twitch Leecher version 1.8.2.

Sorry for my bad English.

![Screenshot](https://user-images.githubusercontent.com/78153629/106143948-c76ee900-6173-11eb-9c1a-5ff1fd79fc0b.PNG)

**Comment by Franiac** [comment]
Jup, that's just wrong. Each download should get it's own button for opening the folder...
