### ISSUE TITLE
Error Downloading Video

### ISSUE THREAD

**Issue by idkbruhlol** [Franiac/TwitchLeecher#565]
Hello! I'm very new to Twitch Leecher and I'm currently using 1.8.2. I have downloaded 2 vods from Twitch before this problem occurred. They came out fine until I downloaded my third vod and it kept giving me an error. I'm so sorry if this has already been talked about, I am not good with knowing how this works so I would appreciate if anyone could help me. I've tried multiple times to try to redownload the video but it keeps saying the same thing, Error. Down below is the log that I copied from the download:

> Download task has been started!
> 
> TWITCH LEECHER INFO
> --------------------------------------------------------------------------------------------
> Version: 1.8.2
> 
> VOD INFO
> --------------------------------------------------------------------------------------------
> VOD ID: 884218550
> Selected Quality: 1920x1080@60fps (Source)
> Download Url: https://www.twitch.tv/videos/884218550
> Crop Start: No
> Crop End: No
> 
> OUTPUT INFO
> --------------------------------------------------------------------------------------------
> Disable Conversion: No
> Output File: C:\Users\Karen\Downloads\20210122_884218550_Dead By Daylight.mp4
> FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
> Temporary Download Folder: C:\Users\Karen\AppData\Local\Temp\TL_1393a6bc-0596-49b1-b3ba-218f01e5e5ba
> 
> ACCESS INFO
> --------------------------------------------------------------------------------------------
> Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1613098528%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A884218550%7D
> Signature: f1f2b517e3ad5990aa4bedff7c39fa0fad043029
> Sub-Only: No
> Privileged: No
> 
> Creating temporary download directory 'C:\Users\Karen\AppData\Local\Temp\TL_1393a6bc-0596-49b1-b3ba-218f01e5e5ba'... done!
> 
> Retrieving m3u8 playlist urls for all VOD qualities... done!
> https://dqrpb9wgowsf5.cloudfront.net/fa76f50fe93dc75ce401_pensivexd_41417833774_1611361729/chunked/index-dvr.m3u8
> https://dqrpb9wgowsf5.cloudfront.net/fa76f50fe93dc75ce401_pensivexd_41417833774_1611361729/audio_only/index-dvr.m3u8
> 
> Playlist url for selected quality 1920x1080@60fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/fa76f50fe93dc75ce401_pensivexd_41417833774_1611361729/chunked/index-dvr.m3u8
> 
> Retrieving playlist... done!
> Parsing playlist... done!
> Number of video chunks: 1672
> 
> Starting parallel video chunk download
> Number of video chunks to download: 1672
> Maximum connection count: 10
> 
> Parallel video chunk download is running...
> 
> Starting temporary download folder cleanup!
> Deleting directory 'C:\Users\Karen\AppData\Local\Temp\TL_1393a6bc-0596-49b1-b3ba-218f01e5e5ba'... done!
> 
> Download task ended with an error!
> 
> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
>    at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
>    at TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
>    at System.Threading.Tasks.Task.Execute()
> ---> (Inner Exception #0) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #1) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #2) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #3) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #4) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #5) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #6) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #7) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> 
> ---> (Inner Exception #8) System.IO.IOException: There is not enough space on the disk.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> <---
>

**Comment by Franiac** [comment]
`There is not enough space on the disk`

Pretty clear message 😄 

You have to check the paths in the preferences. Check the temporary download folder and the output download folder. Per default the temporary folder is on C:\, so this could be your issue?

**Comment by JoniFresh** [comment]
I have the same issue, but even if I reset the Preferences or set the temporary folder to another, the issue is still there.

**Comment by Franiac** [comment]
@JoniFresh We need valuable information. "It doesn't work" does not help. What folders? What drives? What TL version? What video? My magical mind reading device is currently offline 😄

**Comment by JoniFresh** [comment]
I am on Version 1.8.2. In the beginning, i wanted to download it to a folder on my desktop which is on my D: drive. I tried to use my Download folder(also on D:) and I tried to use a folder on my C: drive. It worked on one 15 sec VOD (with the folder on my desktop) but after that I always got an error when the download was on 100% even though I didnt change anything in the beginning(the whole thing with the other folders was to search for the problem after I got the error). VOD:https://www.twitch.tv/videos/906097114. Sorry for my confusing writing :)
LOGS:
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 907338248
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/907338248
Crop Start: Yes (02:30:00)
Crop End: Yes (02:50:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\Desktop,Downloads, etc\Kaan\20210209_907338248_Rocket League.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: D:\Desktop,Downloads, etc\Kaan\Temporary\TL_d974cede-bcdb-403c-a250-1092b4eb66ad

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1613215682%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A907338248%7D
Signature: 85c4f6cba32541ec21b2e2cee7d76a17f2b50395
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\Desktop,Downloads, etc\Kaan\Temporary\TL_d974cede-bcdb-403c-a250-1092b4eb66ad'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/857551764b9c26f3779e_kaaanez_41051379276_1612889909/chunked/index-muted-TR732WG3UM.m3u8
https://dqrpb9wgowsf5.cloudfront.net/857551764b9c26f3779e_kaaanez_41051379276_1612889909/audio_only/index-muted-TR732WG3UM.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/857551764b9c26f3779e_kaaanez_41051379276_1612889909/chunked/index-muted-TR732WG3UM.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1547

Starting parallel video chunk download
Number of video chunks to download: 97
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'D:\Desktop,Downloads, etc\Kaan\Temporary\TL_d974cede-bcdb-403c-a250-1092b4eb66ad'... done!

Download task ended with an error!

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   bei TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   bei TwitchLeecher.Services.Services.TwitchService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, CancellationToken cancellationToken)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
---> (Interne Ausnahme #0) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Interne Ausnahme #1) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Interne Ausnahme #2) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Interne Ausnahme #3) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Interne Ausnahme #4) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Interne Ausnahme #5) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Interne Ausnahme #6) System.IO.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by Franiac** [comment]
@JoniFresh And how much space is left on D:\ if you check in Explorer for example?

`Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung`

This message is not from TL, it is from the Windows system telling TL there is not enough space. I have never seen this message when there was enough space, so I assume you don't actually have enough...

Just a quick sanity check: `D:\Desktop,Downloads, etc\` is an odd folder name. Just to be sure, could you try a folder without the colons? I know it's nothing wrong with colons, just want to be sure it has nothing to do with the error...

**Comment by JoniFresh** [comment]
Thanks for the suggestion with the space on the drive. It works now (could´ve thought about this for myself XD). The weird named folders is just because my PC is 5 Years old and my 11 year old me thought it was a good idea to relocate my folders at 2 a.m. in a rush. I dont even know what I did there but I have to work with it :) Thanks for the nice and fast support. Other companys should cut a slice of of you as we say in germany. 
Good Night

**Comment by Franiac** [comment]
> Other companys should cut a slice of of you

@JoniFresh Das kann man aber auch falsch verstehen... man schneidet sich schließlich die Scheibe "davon" ab und nicht von der Person selbst 😄
