### ISSUE TITLE
conversion failed

### ISSUE THREAD

**Issue by CaptainGoldenCrow** [Franiac/TwitchLeecher#567]
so i've tried downloading several vods using this before, but it always pops up with the same error and i'm not sure what it means. i currently have "Disable conversion to mp4" disabled. would this fix it?

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 906422992
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/906422992
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\owner\Downloads\Tomato\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\owner\AppData\Local\Temp\TL_d4fe22d4-45a8-443d-b47b-c0d3e83930dc

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1613468393%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A906422992%7D
Signature: 92ccaa5e0b6fac150287926e1c9bae3411000147
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\owner\AppData\Local\Temp\TL_d4fe22d4-45a8-443d-b47b-c0d3e83930dc'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/chunked/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/720p60/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/720p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/480p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/audio_only/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/360p30/index-dvr.m3u8
https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://dqrpb9wgowsf5.cloudfront.net/64d7df77ce0603b8c1e5_tomato_40506003821_1612819110/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1805

Starting parallel video chunk download
Number of video chunks to download: 1805
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\owner\AppData\Local\Temp\TL_d4fe22d4-45a8-443d-b47b-c0d3e83930dc\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.ts'...

Creating output directory 'C:\Users\owner\Downloads\Tomato'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\owner\AppData\Local\Temp\TL_d4fe22d4-45a8-443d-b47b-c0d3e83930dc\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.ts'...
Command line arguments: -y -i "C:\Users\owner\AppData\Local\Temp\TL_d4fe22d4-45a8-443d-b47b-c0d3e83930dc\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Users\owner\Downloads\Tomato\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.mp4"

frame=351500 fps=915 q=-1.0 size= 4408064kB time=01:37:38.34 bitrate=6164.0kbits/s speed=15.2x
frame=351917 fps=914 q=-1.0 size= 4413440kB time=01:37:45.28 bitrate=6164.2kbits/s speed=15.2x
frame=352710 fps=915 q=-1.0 size= 4423424kB time=01:37:58.48 bitrate=6164.3kbits/s speed=15.3x
frame=353839 fps=917 q=-1.0 size= 4437504kB time=01:38:17.30 bitrate=6164.2kbits/s speed=15.3x
frame=353956 fps=916 q=-1.0 size= 4439040kB time=01:38:19.26 bitrate=6164.3kbits/s speed=15.3x
frame=353995 fps=914 q=-1.0 size= 4439552kB time=01:38:19.90 bitrate=6164.3kbits/s speed=15.2x
frame=354125 fps=913 q=-1.0 size= 4441088kB time=01:38:22.08 bitrate=6164.2kbits/s speed=15.2x
frame=354192 fps=912 q=-1.0 size= 4441856kB time=01:38:23.19 bitrate=6164.1kbits/s speed=15.2x
frame=354231 fps=911 q=-1.0 size= 4442368kB time=01:38:23.85 bitrate=6164.1kbits/s speed=15.2x
frame=354261 fps=910 q=-1.0 size= 4442880kB time=01:38:24.34 bitrate=6164.3kbits/s speed=15.2x
frame=354876 fps=910 q=-1.0 size= 4450560kB time=01:38:34.60 bitrate=6164.2kbits/s speed=15.2x
frame=355135 fps=910 q=-1.0 size= 4453888kB time=01:38:38.91 bitrate=6164.3kbits/s speed=15.2x
frame=355379 fps=909 q=-1.0 size= 4456960kB time=01:38:42.96 bitrate=6164.4kbits/s speed=15.2x
frame=356318 fps=910 q=-1.0 size= 4468736kB time=01:38:58.62 bitrate=6164.4kbits/s speed=15.2x
frame=356433 fps=909 q=-1.0 size= 4470272kB time=01:39:00.54 bitrate=6164.5kbits/s speed=15.2x
frame=356624 fps=908 q=-1.0 size= 4472576kB time=01:39:03.72 bitrate=6164.4kbits/s speed=15.1x
frame=356745 fps=908 q=-1.0 size= 4473856kB time=01:39:05.75 bitrate=6164.0kbits/s speed=15.1x
frame=358050 fps=910 q=-1.0 size= 4490240kB time=01:39:27.49 bitrate=6164.1kbits/s speed=15.2x
frame=359231 fps=911 q=-1.0 size= 4505088kB time=01:39:47.18 bitrate=6164.1kbits/s speed=15.2x
frame=359328 fps=910 q=-1.0 size= 4506368kB time=01:39:48.80 bitrate=6164.2kbits/s speed=15.2x
frame=359436 fps=909 q=-1.0 size= 4507648kB time=01:39:50.59 bitrate=6164.1kbits/s speed=15.2x
frame=359645 fps=909 q=-1.0 size= 4510464kB time=01:39:54.07 bitrate=6164.4kbits/s speed=15.1x
frame=360450 fps=910 q=-1.0 size= 4520448kB time=01:40:07.51 bitrate=6164.2kbits/s speed=15.2x
frame=361359 fps=910 q=-1.0 size= 4531968kB time=01:40:22.63 bitrate=6164.4kbits/s speed=15.2x
frame=361481 fps=909 q=-1.0 size= 4533504kB time=01:40:24.68 bitrate=6164.4kbits/s speed=15.2x
frame=361502 fps=908 q=-1.0 size= 4533760kB time=01:40:25.02 bitrate=6164.4kbits/s speed=15.1x
frame=361551 fps=907 q=-1.0 size= 4534272kB time=01:40:25.83 bitrate=6164.2kbits/s speed=15.1x
frame=361667 fps=906 q=-1.0 size= 4535808kB time=01:40:27.77 bitrate=6164.4kbits/s speed=15.1x
frame=361794 fps=905 q=-1.0 size= 4537344kB time=01:40:29.89 bitrate=6164.3kbits/s speed=15.1x
frame=362922 fps=907 q=-1.0 size= 4551424kB time=01:40:48.68 bitrate=6164.2kbits/s speed=15.1x
frame=364066 fps=909 q=-1.0 size= 4565760kB time=01:41:07.75 bitrate=6164.2kbits/s speed=15.1x
frame=364310 fps=908 q=-1.0 size= 4568832kB time=01:41:11.83 bitrate=6164.2kbits/s speed=15.1x
frame=364422 fps=907 q=-1.0 size= 4570368kB time=01:41:13.68 bitrate=6164.4kbits/s speed=15.1x
frame=364535 fps=905 q=-1.0 size= 4571648kB time=01:41:15.58 bitrate=6164.2kbits/s speed=15.1x
frame=364629 fps=904 q=-1.0 size= 4572928kB time=01:41:17.14 bitrate=6164.3kbits/s speed=15.1x
frame=365085 fps=904 q=-1.0 size= 4578560kB time=01:41:24.73 bitrate=6164.2kbits/s speed=15.1x
frame=365214 fps=903 q=-1.0 size= 4580352kB time=01:41:26.89 bitrate=6164.4kbits/s speed=15.1x
frame=366498 fps=905 q=-1.0 size= 4596224kB time=01:41:48.29 bitrate=6164.1kbits/s speed=15.1x
frame=366860 fps=905 q=-1.0 size= 4600832kB time=01:41:54.32 bitrate=6164.2kbits/s speed=15.1x
frame=366968 fps=904 q=-1.0 size= 4602112kB time=01:41:56.11 bitrate=6164.1kbits/s speed=15.1x
frame=367538 fps=905 q=-1.0 size= 4609536kB time=01:42:05.63 bitrate=6164.5kbits/s speed=15.1x
frame=367547 fps=903 q=-1.0 size= 4609536kB time=01:42:05.78 bitrate=6164.3kbits/s speed=  15x
frame=368070 fps=903 q=-1.0 size= 4616192kB time=01:42:14.48 bitrate=6164.5kbits/s speed=  15x
frame=368199 fps=902 q=-1.0 size= 4617728kB time=01:42:16.64 bitrate=6164.4kbits/s speed=  15x
frame=368253 fps=901 q=-1.0 size= 4618496kB time=01:42:17.53 bitrate=6164.5kbits/s speed=  15x
frame=368260 fps=899 q=-1.0 size= 4618496kB time=01:42:17.66 bitrate=6164.3kbits/s speed=  15x
frame=368504 fps=898 q=-1.0 size= 4621568kB time=01:42:21.71 bitrate=6164.4kbits/s speed=  15x
frame=368547 fps=896 q=-1.0 size= 4622080kB time=01:42:22.44 bitrate=6164.3kbits/s speed=14.9x
frame=368755 fps=895 q=-1.0 size= 4624640kB time=01:42:25.92 bitrate=6164.3kbits/s speed=14.9x
frame=368775 fps=893 q=-1.0 size= 4624896kB time=01:42:26.24 bitrate=6164.3kbits/s speed=14.9x
frame=369041 fps=892 q=-1.0 size= 4628224kB time=01:42:30.67 bitrate=6164.3kbits/s speed=14.9x
frame=369113 fps=890 q=-1.0 size= 4629248kB time=01:42:31.87 bitrate=6164.4kbits/s speed=14.8x
frame=369158 fps=888 q=-1.0 size= 4629504kB time=01:42:32.62 bitrate=6164.0kbits/s speed=14.8x
frame=369354 fps=887 q=-1.0 size= 4632064kB time=01:42:35.88 bitrate=6164.2kbits/s speed=14.8x
frame=369461 fps=886 q=-1.0 size= 4633600kB time=01:42:37.67 bitrate=6164.4kbits/s speed=14.8x
frame=369519 fps=883 q=-1.0 size= 4634112kB time=01:42:38.63 bitrate=6164.1kbits/s speed=14.7x
frame=369747 fps=882 q=-1.0 size= 4636928kB time=01:42:42.43 bitrate=6164.1kbits/s speed=14.7x
frame=369835 fps=881 q=-1.0 size= 4638208kB time=01:42:43.90 bitrate=6164.3kbits/s speed=14.7x
frame=369894 fps=880 q=-1.0 size= 4638976kB time=01:42:44.88 bitrate=6164.3kbits/s speed=14.7x
frame=369904 fps=878 q=-1.0 size= 4638976kB time=01:42:45.05 bitrate=6164.2kbits/s speed=14.6x
frame=370109 fps=877 q=-1.0 size= 4641536kB time=01:42:48.47 bitrate=6164.2kbits/s speed=14.6x
frame=370187 fps=876 q=-1.0 size= 4642560kB time=01:42:49.77 bitrate=6164.2kbits/s speed=14.6x
frame=370246 fps=874 q=-1.0 size= 4643328kB time=01:42:50.75 bitrate=6164.3kbits/s speed=14.6x
frame=370442 fps=873 q=-1.0 size= 4645632kB time=01:42:54.01 bitrate=6164.1kbits/s speed=14.6x
frame=370520 fps=872 q=-1.0 size= 4646656kB time=01:42:55.31 bitrate=6164.1kbits/s speed=14.5x
frame=370588 fps=871 q=-1.0 size= 4647680kB time=01:42:56.45 bitrate=6164.3kbits/s speed=14.5x
frame=370627 fps=869 q=-1.0 size= 4647936kB time=01:42:57.11 bitrate=6164.0kbits/s speed=14.5x
frame=370852 fps=868 q=-1.0 size= 4650752kB time=01:43:00.86 bitrate=6164.0kbits/s speed=14.5x
frame=370950 fps=868 q=-1.0 size= 4652032kB time=01:43:02.48 bitrate=6164.1kbits/s speed=14.5x
frame=371028 fps=866 q=-1.0 size= 4653056kB time=01:43:03.78 bitrate=6164.2kbits/s speed=14.4x
frame=371038 fps=864 q=-1.0 size= 4653312kB time=01:43:03.95 bitrate=6164.3kbits/s speed=14.4x
frame=371274 fps=864 q=-1.0 size= 4656128kB time=01:43:07.88 bitrate=6164.1kbits/s speed=14.4x
frame=371332 fps=863 q=-1.0 size= 4656896kB time=01:43:08.86 bitrate=6164.2kbits/s speed=14.4x
frame=371381 fps=862 q=-1.0 size= 4657408kB time=01:43:09.67 bitrate=6164.1kbits/s speed=14.4x
frame=371391 fps=859 q=-1.0 size= 4657664kB time=01:43:09.84 bitrate=6164.2kbits/s speed=14.3x
frame=371473 fps=859 q=-1.0 size= 4658944kB time=01:43:11.21 bitrate=6164.6kbits/s speed=14.3x
frame=371515 fps=858 q=-1.0 size= 4659456kB time=01:43:11.91 bitrate=6164.5kbits/s speed=14.3x
frame=371623 fps=856 q=-1.0 size= 4660480kB time=01:43:13.70 bitrate=6164.1kbits/s speed=14.3x
frame=371754 fps=855 q=-1.0 size= 4662272kB time=01:43:15.88 bitrate=6164.3kbits/s speed=14.3x
frame=371812 fps=853 q=-1.0 size= 4663040kB time=01:43:16.88 bitrate=6164.3kbits/s speed=14.2x
frame=371931 fps=852 q=-1.0 size= 4664320kB time=01:43:18.85 bitrate=6164.1kbits/s speed=14.2x
frame=371951 fps=851 q=-1.0 size= 4664576kB time=01:43:19.17 bitrate=6164.1kbits/s speed=14.2x
frame=372107 fps=849 q=-1.0 size= 4666624kB time=01:43:21.77 bitrate=6164.2kbits/s speed=14.1x
frame=372245 fps=848 q=-1.0 size= 4668416kB time=01:43:24.07 bitrate=6164.3kbits/s speed=14.1x
frame=372283 fps=847 q=-1.0 size= 4668928kB time=01:43:24.71 bitrate=6164.3kbits/s speed=14.1x
frame=372479 fps=846 q=-1.0 size= 4671232kB time=01:43:27.98 bitrate=6164.1kbits/s speed=14.1x
frame=372529 fps=845 q=-1.0 size= 4672000kB time=01:43:28.81 bitrate=6164.3kbits/s speed=14.1x
frame=372705 fps=844 q=-1.0 size= 4674048kB time=01:43:31.73 bitrate=6164.1kbits/s speed=14.1x
frame=372754 fps=842 q=-1.0 size= 4674816kB time=01:43:32.56 bitrate=6164.3kbits/s speed=  14x
frame=372930 fps=841 q=-1.0 size= 4676864kB time=01:43:35.49 bitrate=6164.1kbits/s speed=  14x
frame=372970 fps=840 q=-1.0 size= 4677376kB time=01:43:36.15 bitrate=6164.1kbits/s speed=  14x
frame=373039 fps=839 q=-1.0 size= 4678400kB time=01:43:37.30 bitrate=6164.3kbits/s speed=  14x
frame=373234 fps=838 q=-1.0 size= 4680704kB time=01:43:40.56 bitrate=6164.1kbits/s speed=  14x
frame=373342 fps=837 q=-1.0 size= 4681984kB time=01:43:42.35 bitrate=6164.0kbits/s speed=  14x
frame=373371 fps=836 q=-1.0 size= 4682496kB time=01:43:42.85 bitrate=6164.2kbits/s speed=13.9x
frame=373508 fps=834 q=-1.0 size= 4684288kB time=01:43:45.13 bitrate=6164.3kbits/s speed=13.9x
frame=373586 fps=833 q=-1.0 size= 4685056kB time=01:43:46.43 bitrate=6164.0kbits/s speed=13.9x
frame=373709 fps=833 q=-1.0 size= 4686848kB time=01:43:48.48 bitrate=6164.4kbits/s speed=13.9x
frame=373852 fps=831 q=-1.0 size= 4688640kB time=01:43:50.87 bitrate=6164.4kbits/s speed=13.9x
frame=374135 fps=831 q=-1.0 size= 4691968kB time=01:43:55.58 bitrate=6164.1kbits/s speed=13.8x
frame=374204 fps=830 q=-1.0 size= 4692992kB time=01:43:56.73 bitrate=6164.3kbits/s speed=13.8x
frame=374273 fps=829 q=-1.0 size= 4693760kB time=01:43:57.86 bitrate=6164.2kbits/s speed=13.8x
frame=374370 fps=828 q=-1.0 size= 4695040kB time=01:43:59.49 bitrate=6164.2kbits/s speed=13.8x
frame=374449 fps=827 q=-1.0 size= 4696064kB time=01:44:00.81 bitrate=6164.3kbits/s speed=13.8x
frame=374557 fps=826 q=-1.0 size= 4697344kB time=01:44:02.60 bitrate=6164.2kbits/s speed=13.8x
frame=374684 fps=826 q=-1.0 size= 4698880kB time=01:44:04.73 bitrate=6164.1kbits/s speed=13.8x
frame=374803 fps=825 q=-1.0 size= 4700416kB time=01:44:06.72 bitrate=6164.2kbits/s speed=13.8x
frame=374910 fps=824 q=-1.0 size= 4701696kB time=01:44:08.51 bitrate=6164.1kbits/s speed=13.7x
frame=374921 fps=823 q=-1.0 size= 4701952kB time=01:44:08.68 bitrate=6164.2kbits/s speed=13.7x
frame=375154 fps=822 q=-1.0 size= 4704768kB time=01:44:12.56 bitrate=6164.1kbits/s speed=13.7x
frame=375231 fps=821 q=-1.0 size= 4705792kB time=01:44:13.84 bitrate=6164.2kbits/s speed=13.7x
frame=375324 fps=821 q=-1.0 size= 4707072kB time=01:44:15.40 bitrate=6164.3kbits/s speed=13.7x
frame=375421 fps=820 q=-1.0 size= 4708096kB time=01:44:17.00 bitrate=6164.1kbits/s speed=13.7x
frame=375470 fps=819 q=-1.0 size= 4708864kB time=01:44:17.83 bitrate=6164.3kbits/s speed=13.7x
frame=375617 fps=819 q=-1.0 size= 4710656kB time=01:44:20.26 bitrate=6164.2kbits/s speed=13.6x
frame=375715 fps=818 q=-1.0 size= 4711936kB time=01:44:21.91 bitrate=6164.3kbits/s speed=13.6x
frame=375801 fps=817 q=-1.0 size= 4712960kB time=01:44:23.34 bitrate=6164.2kbits/s speed=13.6x
frame=375843 fps=816 q=-1.0 size= 4713472kB time=01:44:24.04 bitrate=6164.2kbits/s speed=13.6x
frame=375891 fps=815 q=-1.0 size= 4713984kB time=01:44:24.83 bitrate=6164.1kbits/s speed=13.6x
frame=375940 fps=814 q=-1.0 size= 4714752kB time=01:44:25.66 bitrate=6164.3kbits/s speed=13.6x
frame=376009 fps=814 q=-1.0 size= 4715520kB time=01:44:26.81 bitrate=6164.1kbits/s speed=13.6x
frame=376067 fps=813 q=-1.0 size= 4716288kB time=01:44:27.77 bitrate=6164.2kbits/s speed=13.5x
frame=376097 fps=811 q=-1.0 size= 4716544kB time=01:44:28.26 bitrate=6164.1kbits/s speed=13.5x
frame=376283 fps=810 q=-1.0 size= 4719104kB time=01:44:31.38 bitrate=6164.3kbits/s speed=13.5x
frame=376498 fps=810 q=-1.0 size= 4721664kB time=01:44:34.96 bitrate=6164.2kbits/s speed=13.5x
frame=376543 fps=809 q=-1.0 size= 4722432kB time=01:44:35.71 bitrate=6164.4kbits/s speed=13.5x
frame=376563 fps=807 q=-1.0 size= 4722688kB time=01:44:36.03 bitrate=6164.4kbits/s speed=13.5x
frame=376724 fps=807 q=-1.0 size= 4724480kB time=01:44:38.72 bitrate=6164.1kbits/s speed=13.4x
frame=376891 fps=806 q=-1.0 size= 4726528kB time=01:44:41.51 bitrate=6164.1kbits/s speed=13.4x
frame=377049 fps=806 q=-1.0 size= 4728576kB time=01:44:44.14 bitrate=6164.2kbits/s speed=13.4x
frame=377196 fps=805 q=-1.0 size= 4730368kB time=01:44:46.59 bitrate=6164.1kbits/s speed=13.4x
frame=377382 fps=805 q=-1.0 size= 4732672kB time=01:44:49.68 bitrate=6164.1kbits/s speed=13.4x
frame=377494 fps=804 q=-1.0 size= 4734208kB time=01:44:51.56 bitrate=6164.2kbits/s speed=13.4x
frame=377637 fps=803 q=-1.0 size= 4736000kB time=01:44:53.95 bitrate=6164.2kbits/s speed=13.4x
frame=377823 fps=803 q=-1.0 size= 4738304kB time=01:44:57.04 bitrate=6164.2kbits/s speed=13.4x
frame=377891 fps=802 q=-1.0 size= 4739072kB time=01:44:58.17 bitrate=6164.1kbits/s speed=13.4x
frame=377911 fps=801 q=-1.0 size= 4739328kB time=01:44:58.51 bitrate=6164.1kbits/s speed=13.4x
frame=378027 fps=800 q=-1.0 size= 4740864kB time=01:45:00.43 bitrate=6164.2kbits/s speed=13.3x
frame=378333 fps=800 q=-1.0 size= 4744704kB time=01:45:05.53 bitrate=6164.2kbits/s speed=13.3x
frame=378566 fps=800 q=-1.0 size= 4747776kB time=01:45:09.42 bitrate=6164.4kbits/s speed=13.3x
frame=378686 fps=799 q=-1.0 size= 4749056kB time=01:45:11.42 bitrate=6164.1kbits/s speed=13.3x
frame=378843 fps=799 q=-1.0 size= 4751360kB time=01:45:14.05 bitrate=6164.5kbits/s speed=13.3x
frame=379000 fps=798 q=-1.0 size= 4753152kB time=01:45:16.65 bitrate=6164.3kbits/s speed=13.3x
frame=379137 fps=797 q=-1.0 size= 4754688kB time=01:45:18.93 bitrate=6164.1kbits/s speed=13.3x
frame=379303 fps=797 q=-1.0 size= 4756992kB time=01:45:21.70 bitrate=6164.4kbits/s speed=13.3x
frame=379391 fps=796 q=-1.0 size= 4758016kB time=01:45:23.18 bitrate=6164.3kbits/s speed=13.3x
frame=379508 fps=796 q=-1.0 size= 4759552kB time=01:45:25.12 bitrate=6164.3kbits/s speed=13.3x
frame=379625 fps=795 q=-1.0 size= 4760832kB time=01:45:27.08 bitrate=6164.1kbits/s speed=13.2x
frame=379713 fps=794 q=-1.0 size= 4762112kB time=01:45:28.53 bitrate=6164.3kbits/s speed=13.2x
frame=379899 fps=794 q=-1.0 size= 4764416kB time=01:45:31.65 bitrate=6164.3kbits/s speed=13.2x
frame=380002 fps=793 q=-1.0 size= 4765696kB time=01:45:33.35 bitrate=6164.3kbits/s speed=13.2x
frame=380177 fps=793 q=-1.0 size= 4768000kB time=01:45:36.27 bitrate=6164.4kbits/s speed=13.2x
frame=380341 fps=792 q=-1.0 size= 4769792kB time=01:45:39.01 bitrate=6164.1kbits/s speed=13.2x
frame=380458 fps=792 q=-1.0 size= 4771328kB time=01:45:40.95 bitrate=6164.2kbits/s speed=13.2x
frame=380693 fps=791 q=-1.0 size= 4774400kB time=01:45:44.87 bitrate=6164.3kbits/s speed=13.2x
frame=380829 fps=791 q=-1.0 size= 4775936kB time=01:45:47.13 bitrate=6164.1kbits/s speed=13.2x
frame=380977 fps=790 q=-1.0 size= 4777984kB time=01:45:49.61 bitrate=6164.4kbits/s speed=13.2x
frame=381126 fps=790 q=-1.0 size= 4779776kB time=01:45:52.08 bitrate=6164.3kbits/s speed=13.2x
frame=381299 fps=789 q=-1.0 size= 4781824kB time=01:45:54.96 bitrate=6164.1kbits/s speed=13.2x
frame=381496 fps=789 q=-1.0 size= 4784640kB time=01:45:58.25 bitrate=6164.6kbits/s speed=13.1x
frame=381864 fps=788 q=-1.0 size= 4788992kB time=01:46:04.39 bitrate=6164.2kbits/s speed=13.1x
frame=381946 fps=788 q=-1.0 size= 4790272kB time=01:46:05.76 bitrate=6164.5kbits/s speed=13.1x
frame=382123 fps=787 q=-1.0 size= 4792320kB time=01:46:08.70 bitrate=6164.3kbits/s speed=13.1x
frame=382255 fps=787 q=-1.0 size= 4793856kB time=01:46:10.90 bitrate=6164.2kbits/s speed=13.1x
frame=382412 fps=786 q=-1.0 size= 4795904kB time=01:46:13.52 bitrate=6164.3kbits/s speed=13.1x
frame=382638 fps=786 q=-1.0 size= 4798720kB time=01:46:17.30 bitrate=6164.2kbits/s speed=13.1x
frame=382793 fps=785 q=-1.0 size= 4800768kB time=01:46:19.88 bitrate=6164.4kbits/s speed=13.1x
frame=382952 fps=785 q=-1.0 size= 4802816kB time=01:46:22.53 bitrate=6164.4kbits/s speed=13.1x
frame=383062 fps=784 q=-1.0 size= 4804096kB time=01:46:24.38 bitrate=6164.3kbits/s speed=13.1x
frame=383273 fps=784 q=-1.0 size= 4806656kB time=01:46:27.88 bitrate=6164.2kbits/s speed=13.1x
frame=383463 fps=783 q=-1.0 size= 4809216kB time=01:46:31.04 bitrate=6164.4kbits/s speed=13.1x
frame=383646 fps=783 q=-1.0 size= 4811520kB time=01:46:34.09 bitrate=6164.4kbits/s speed=13.1x
frame=383756 fps=782 q=-1.0 size= 4812800kB time=01:46:35.92 bitrate=6164.3kbits/s speed=  13x
frame=383984 fps=782 q=-1.0 size= 4815616kB time=01:46:39.72 bitrate=6164.3kbits/s speed=  13x
frame=384109 fps=781 q=-1.0 size= 4817408kB time=01:46:41.81 bitrate=6164.5kbits/s speed=  13x
frame=384355 fps=781 q=-1.0 size= 4820224kB time=01:46:45.91 bitrate=6164.2kbits/s speed=  13x
frame=384573 fps=781 q=-1.0 size= 4823040kB time=01:46:49.53 bitrate=6164.3kbits/s speed=  13x
frame=384750 fps=780 q=-1.0 size= 4825088kB time=01:46:52.50 bitrate=6164.1kbits/s speed=  13x
frame=384892 fps=780 q=-1.0 size= 4827136kB time=01:46:54.87 bitrate=6164.4kbits/s speed=  13x
frame=384925 fps=779 q=-1.0 size= 4827648kB time=01:46:55.42 bitrate=6164.5kbits/s speed=  13x
frame=385013 fps=778 q=-1.0 size= 4828672kB time=01:46:56.87 bitrate=6164.4kbits/s speed=  13x
frame=385142 fps=778 q=-1.0 size= 4830208kB time=01:46:59.03 bitrate=6164.3kbits/s speed=  13x
frame=385272 fps=777 q=-1.0 size= 4831744kB time=01:47:01.18 bitrate=6164.2kbits/s speed=12.9x
frame=385438 fps=777 q=-1.0 size= 4833792kB time=01:47:03.95 bitrate=6164.2kbits/s speed=12.9x
frame=385520 fps=776 q=-1.0 size= 4834816kB time=01:47:05.32 bitrate=6164.2kbits/s speed=12.9x
frame=385684 fps=775 q=-1.0 size= 4836864kB time=01:47:08.05 bitrate=6164.2kbits/s speed=12.9x
frame=385800 fps=775 q=-1.0 size= 4838400kB time=01:47:09.99 bitrate=6164.3kbits/s speed=12.9x
frame=385909 fps=774 q=-1.0 size= 4839680kB time=01:47:11.83 bitrate=6164.1kbits/s speed=12.9x
frame=386051 fps=774 q=-1.0 size= 4841728kB time=01:47:14.17 bitrate=6164.5kbits/s speed=12.9x
frame=386144 fps=773 q=-1.0 size= 4842752kB time=01:47:15.73 bitrate=6164.3kbits/s speed=12.9x
frame=386285 fps=772 q=-1.0 size= 4844544kB time=01:47:18.08 bitrate=6164.3kbits/s speed=12.9x
frame=386425 fps=772 q=-1.0 size= 4846336kB time=01:47:20.40 bitrate=6164.4kbits/s speed=12.9x
frame=386556 fps=771 q=-1.0 size= 4847872kB time=01:47:22.60 bitrate=6164.2kbits/s speed=12.9x
frame=386720 fps=771 q=-1.0 size= 4849920kB time=01:47:25.33 bitrate=6164.2kbits/s speed=12.8x
frame=386885 fps=770 q=-1.0 size= 4851968kB time=01:47:28.08 bitrate=6164.2kbits/s speed=12.8x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\owner\Downloads\Tomato\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.mp4: No space left on device
frame=387060 fps=769 q=-1.0 Lsize= 4854016kB time=01:47:30.98 bitrate=6164.0kbits/s speed=12.8x
video:4726824kB audio:128919kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\owner\AppData\Local\Temp\TL_d4fe22d4-45a8-443d-b47b-c0d3e83930dc'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
> Error writing trailer of C:\Users\owner\Downloads\Tomato\Tomato_Uncle and I are picking up groceries. We'll be back I promise_Jalopy.mp4: **No space left on device**

Well... pretty clear message 😄

**Comment by CaptainGoldenCrow** [comment]
oh damn sorry, i guess i missed that.
