### ISSUE TITLE
Error during downloading vods

### ISSUE THREAD

**Issue by KGPlay** [Franiac/TwitchLeecher#569]
When im trying to download vod I'm getting an error:

![image](https://user-images.githubusercontent.com/79373926/108603297-826f5880-73a7-11eb-9a5c-c8895cac004a.png)

Translation of second line:
the remote server returned an error: (404) Not Found

**Comment by Franiac** [comment]
I suppose you don't have the latest version installed -> [TL 1.8.2](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.2)
