### ISSUE TITLE
720p30 quality option is gone on VODs from the last 2 days?

### ISSUE THREAD

**Issue by jonas1015119** [Franiac/TwitchLeecher#570]
Checked multiple large channels (xqc, Soda, Hasan) and the options seems to have disappeared for the last two days VODs. Is it a Twitch thing?

**Comment by Franiac** [comment]
I don't find ANY VOD's from those streamers... so...

If the quality is not shown and the rest works well, it is definitely a Twitch thing, since the qualities are read from the Tiwtch API.

**Comment by jonas1015119** [comment]
xqcow und sodapoppin wären die Kanalnamen. Denke aber Twitch hat die Qualitätsstufe einfach entfernt

**Comment by llacb47** [comment]
Yeah, twitch side change.

**Comment by Franiac** [comment]
Yup, 30fps isn't there anymore...
