### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MarkAloha** [Franiac/TwitchLeecher#571]
1.8.2, 
win 10 64
url https://www.twitch.tv/videos/918715839
installation is in progress, and then an error

![11](https://user-images.githubusercontent.com/79455627/108707843-abb3f400-7521-11eb-8d3d-75c9b2b958a2.PNG)
![22](https://user-images.githubusercontent.com/79455627/108707847-ac4c8a80-7521-11eb-9abb-cf3a19c296ad.PNG)

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 918715839
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/918715839
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\downlound\20210218_918715839_Just Chatting.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: D:\downlound\TL_b8b0f75d-d01f-49ff-9a21-11d3620114cf

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1614067988%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A918715839%7D
Signature: 82610bb0ba9d85c4c9b6064f7a6de6d015bf4379
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\downlound\TL_b8b0f75d-d01f-49ff-9a21-11d3620114cf'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/chunked/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/720p60/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/720p30/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/480p30/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/audio_only/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/360p30/index-dvr.m3u8
https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://d2nvs31859zcd8.cloudfront.net/b391aa4fe7eeeb9fdc0d_mihalina__41750078878_1613638127/chunked/index-dvr.m3u8

Retrieving playlist...

Starting temporary download folder cleanup!
Deleting directory 'D:\downlound\TL_b8b0f75d-d01f-49ff-9a21-11d3620114cf'... done!

Download task ended with an error!

System.AggregateException: Произошла одна или несколько ошибок. ---> System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 52.85.114.81:443
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   в System.Net.WebClient.DownloadString(Uri address)
   в TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   в TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   в System.Threading.Tasks.Task.Execute()
   --- Конец трассировки внутреннего стека исключений ---
---> (Внутреннее исключение #0) System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 52.85.114.81:443
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   в System.Net.WebClient.DownloadString(Uri address)
   в TwitchLeecher.Services.Services.TwitchService.RetrieveVodPlaylist(Action`1 log, String tempDir, String playlistUrl)
   в TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass51_0.<StartQueuedDownloadIfExists>b__2()
   в System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Works perfectly here... the error is a timeout. Maybe your internet dropped out or something? Try again in later and see what happens, I cannot find anything wrong with the video or the download.

**Comment by MarkAloha** [comment]
Reinstalled the program, restarted the computer, turned off all applications (including antivirus), restarted the router - it did not help. I already wanted to reinstall Windows. Turned on the Firewall - everything worked. Thanks for the answer:)
