### ISSUE TITLE
Sub-Only DL

### ISSUE THREAD

**Issue by AR14H** [Franiac/TwitchLeecher#573]
I have looked through the 'cant download sub-only VODs' topics and I am fairly new so I wanted some clarifications. 

I am a mod/sub for the person im trying to download for. I am already subbed/mod for the channel so I am assuming the hang up is on their end? They need to change a setting to where anyone can view the VODs not just subs only. If they chance this setting the twitchleecher should then be able to download the VOD. Is this a correct assumption?

**Comment by Franiac** [comment]
Correct

**Comment by AR14H** [comment]
You the best, thank you for the clarification!
