### ISSUE TITLE
Application Stopped Opening

### ISSUE THREAD

**Issue by kurtweinstein** [Franiac/TwitchLeecher#575]
I've used this program previously, and I'm not sure what's changed. I'm on Windows 10, though it may have received an update.

Currently, TwitchLeecher is not opening. I attempt to launch it and it appears in the task bar, but the window never actually appears. I have not successfully been able to resolve this by rebooting my PC or uninstalling/reinstalling the program. Windows 10 (Pro 64-bit) is fully up-to-date; I have tried 1.8.2, 1.8.1, and 1.7.3, none of them will open for me. I do have the .NET Framework 4.5 installed.

My assumption is that, for some reason, a Windows update messed things up. But at this point I'm not sure how to grab any sort of logging to help determine what the issue is.

**Comment by Franiac** [comment]
TL 1.8+ needs .NET 4.8

Additionally you should check potential anti virus software. We have reocurring issues with false positives.

Other than that I don't have any ideas, why it shouldn't work.
