### ISSUE TITLE
[request] auto filename for crop video downloads

### ISSUE THREAD

**Issue by makedir** [Franiac/TwitchLeecher#576]
please implement a simple auto file name rename for crop downloads something like _startindex_endindex.mp4

**Comment by Franiac** [comment]
What do you mean by "index". There is no counter or something...

**Comment by makedir** [comment]
.... the word index is clear in this context. Time is a counter. I always find it super annoying to download with twitch leecher because I use the crop video function to download cuts. And Twitch leecher doesnt rename the files for that.

https://i.imgur.com/fx9Gpf0.png

start and end has to get into the file name. I made an example for it.

20210303_935367846_Just Chatting_startindex_endindex.mp4

**Comment by Franiac** [comment]
Ok, then I don't understand why you opend this issue... `{start}` and `{end}` are already there... hover your mouse over the questionmark in the preferences.

**Comment by makedir** [comment]
Nice. The app should auto add it when you click crop start and end.

**Comment by Franiac** [comment]
@makedir Nope, just because you want it that way does not mean other users want it, too. Most use the crop feature without putting the times into the filename. That's why we have the preferences page and everyone can decide for themselves. There is no "one size fits all" configuration in software 😄
