### ISSUE TITLE
rubiuscreativer

### ISSUE THREAD

**Issue by rubiuscreativer** [Franiac/TwitchLeecher#577]
Hi, I'm rubiuscreativer, this program is useless, it is only exclusive, Windows does not seem to me in just, I do not develop Ubuntu or even Apple

**Comment by RoarTruth** [comment]
> Hi, I'm rubiuscreativer, this program is useless, it is only exclusive, Windows does not seem to me in just, I do not develop Ubuntu or even Apple

@rubiuscreativer **It helped me. I use windows. Thank you @Franiac**

**Comment by Franiac** [comment]
@rubiuscreativer Thank you for sharing your intelligence with the world
