### ISSUE TITLE
1.8.3 crashes when trying to open any window except main

### ISSUE THREAD

**Issue by NordicPanda** [Franiac/TwitchLeecher#578]
Also creates a ton of error log files.
Windows 7 SP1 64 bit
![error](https://user-images.githubusercontent.com/63873505/110212376-211dae00-7eac-11eb-88d7-311aaa370866.png)
[03062021_033834_875__error.log](https://github.com/Franiac/TwitchLeecher/files/6095614/03062021_033834_875__error.log)

**Comment by carllapa** [comment]
Same here.

**Comment by Franiac** [comment]
Fuck... I messed up, sorry guys! New release is on the way

**Comment by Franiac** [comment]
Wait a minute.... do you guys have .NET 4.8 installed?

**Comment by Franiac** [comment]
If you go into RegEdit and go this path:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full`

there is a REG_DWORD named `Release`

What does the value in the parenthesis say? It should be `528040` or higher...

**Comment by Jezynka** [comment]
In Release I have 528049 (hex 80eb1). And Version says 4.8.03761 (in same registry path). Will try manually installing newest version of .NET if there is. (same as others, win7 sp1 x64)

**Comment by carllapa** [comment]
> In Release I have 528049 (hex 80eb1). And Version says 4.8.03761 (in same registry path). Will try manually installing newest version of .NET if there is. (same as others, win7 sp1 x64)

Exactly the same values here, 528049 & 4.8.03761

**Comment by Franiac** [comment]
This is a Windows 7 only problem. .NET 4.8 is missing an assembly on Win 7 that TL uses since 1.8.3 for whatever reason. Microsoft fucked that up obviously. I see what I can do.

Before I release 1.8.4 I'll come back to you in order to test if it works properly because I don't have any Win 7 machines (nobody should actually).

If one of you is willing to test the installer when ready shoot me an email: contact@franiac.com

**Comment by NordicPanda** [comment]
I also have Release 528049 and Version 4.8.03761. 
Is it possible to get 1.8.2 still?

**Comment by Franiac** [comment]
@NordicPanda wait 5 min for 1.8.4.... I'm on it

**Comment by Franiac** [comment]
@Jezynka Sent you the preview 1.8.4 installer via email (I write it here just in case it went to your spam folder)

**Comment by Franiac** [comment]
The assembly missing on Windows 7 was only used by TL in oder to draw the "Channel Name"combobox dropshadow. I removed the dropshadow (ohhhh nooooooo 😄) and the assembly.

Go get [TL 1.8.4](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.4) and you should be good again!

**Comment by carllapa** [comment]
> The assembly missing on Windows 7 was only used by TL in oder to draw the "Channel Name"combobox dropshadow. I removed the dropshadow (ohhhh nooooooo smile) and the assembly.
> 
> Go get [TL 1.8.4](https://github.com/Franiac/TwitchLeecher/releases/tag/v1.8.4) and you should be good again!

Many thanks for the effort of fixing this.
Windows 7 is still under extended maintenance period but I understand most developers don't care about this ancient OS.
You did and fixed our issue in a very short time frame also, you rock!
