### ISSUE TITLE
Version 1.8.4 install problem

### ISSUE THREAD

**Issue by megatux123** [Franiac/TwitchLeecher#579]
Hello Im not a programmer I have a problem with TwitchLeecher 1.8.4 it wont install. I use Windows 7 x64 SP1 fully updated also with NET Framework 4.8. The last version I used of TwitchLeecher was 1.8.2 without any issue.

Problem description:
1) First I uninstalled TwitchLeecher 1.8.2
2) When I tried to install TwitchLeecher 1.8.4 my antivirus "Avast Free Antivirus" issued a malware warning and closed the installation process. I think this is the first time Avast sounds the alarm in quite many TwitchLeecher versions installed up to now.
3) I disabled my antivirus and tried to install again checking there were no TwitchLeecher folders created beforehand.
4) I keep getting this error warning from TwitchLeecher installer:
"An error occured during the installation. Your system has not been modified. Please click "Close" to exit the Setup Wizard."
5) I have tried rebooting my computer and double checking there were no installation folders made. Nothing works always get the same error.

I have installed back TwitchLeecher 1.8.2 with my antivirus completely active and it installs correctly without a single warning or error.

Following the TwitchLeecher Github issues with installation problems I made a log with "TwitchLeecher_1.8.4.exe -l log.txt" command line in case it helps

Again I want to remark Im not a programmer but I believe TwitchLeecher is an impressive piece of software I like it very much, so I want to make a humble suggestion: have the developer considered making this program portable? would it be too difficult to make TwitchLeecher a download and use software without installations? just to copy it to a folder and ready to use?... I honestly think this feature would be worth the trouble.

That being said Windows 7 is the last Microsoft Operative System I will dare to use in my life, in my opinion that corporation has gone too far and now there is no way back to them, so I would appreciate to know if this install issue is because TwitchLeecher is only compatible with Windows 10 because Im definitely not upgrading my system no matter what.
[log.txt](https://github.com/Franiac/TwitchLeecher/files/6102877/log.txt)

**Comment by Franiac** [comment]
From the log:

```
Error 0x80070570: Failed to extract all files from container, erf: 1:4:0
[1308:1590][2021-03-08T16:55:09]e000: Error 0x80070570: Failed to begin and wait for operation.
[1308:1590][2021-03-08T16:55:09]e000: Error 0x80070570: Failed to extract payload: a0 from container: WixAttachedContainer
[1308:1590][2021-03-08T16:55:09]e312: Failed to extract payloads from container: WixAttachedContainer to working path: C:\Users\sysadmin\AppData\Local\Temp\{AEF53F43-EC89-4C2B-BC18-EBAA2AC65BFA}\.cr\TwitchLeecher_1.8.4.exe, error: 0x80070570.
[1308:16DC][2021-03-08T16:55:09]e000: Error 0x80070570: Failed while caching, aborting execution.
```
Basically the installer "unzips" itself before execution into a temporary folder. This is not controlled by me, but automated by the Windows installer system.

I cannot reproduce or see anything wrong on my end. Fact is, the installer was not touched since **7/28/2019** and I mean 100% not touched. There must be something weird going on on your system. Did you update Windows or any system tools like AntiVirus software recently or something like that?

**Comment by megatux123** [comment]
Hello thanks for the feedback I can only say my antivirus "Avast Free Antivirus" was the first to interrupt the installation process so my guess is my antivirus has hardwired something in my Windows 7 system to block TwitchLeecher further installation attemps.

I still get "An error occured during the installation. Your system has not been modified. Please click "Close" to exit the Setup Wizard." error with or without antivirus enabled. I have tried deleting temporary files everytime and also tried installing directly from the C: system directory since I use a secondary disk for downloads and file storage but no luck. Also tried with and without admin rights but nope.

I always install Avast with the minimum and most basic scan shields and stuff to prevent things like this, but I cannot see any kind of active blocking in its menus or anything. I can only say I have installed many TwitchLeecher versions up to 1.8.2 included and never had a single problem or warning until now with 1.8.4

Honestly I have no clue like I said Im not a programmer but I would like to ask again please consider the idea of making TwitchLeecher a portable software without the need of installation, maybe this is not possible but if it is then Im sure it will be a great improvement in the long run and worth the effort.

Please please pretty please.

Thank you anyway.

**Comment by megatux123** [comment]
Hello again please excuse the spam it happens since I didnt expect this install problem at all I wasnt ready to test it conveniently but I have discovered something new.

When I was finally going to blame it all to my antivirus "Avast" I could test a second 1.8.4 installation on a notebook computer where I completely removed Avast antivirus and never installed any Twitchleecher program before. This system is also Windows 7 x64 with NET Framework 4.8.

To my surprise I get the same exact error:
"An error occured during the installation. Your system has not been modified. Please click "Close" to exit the Setup Wizard."

And the log file also indicates:
"Failed to extract all files from container"...

So Im goind to leave this info here. Just to mention I can still install 1.8.2 in this laptop without any problems.

Thank you for you attention and sorry for being annoying.

**Comment by megatux123** [comment]
Hello again one last time.

I have discovered where is the problem it was a corrupted download.

The md5 hash of the 1.8.4 version I downloaded first was:
8e53496e2a095f79a07af060cb42b21d

And the md5 hash of a second 1.8.4 download I made and I can install without problem is:
05f2cbf2b560918810d48f45dee48fc3

Im sorry for the troubles I feel dumb now but on my defense I must say I download truckloads of Gigabytes every day and never had a corrupted download in years... at least I honestly dont remember the last time it happened to me and specially not from Github.

I suggest adding a md5 hash code for every file in the releases download page to prevent problems like this in the future.

I also would like to suggest one last time a portable version of Twitchleecher... only if it is technically posssible of course.

Thank you and excuse any inconvenience.

**Comment by Franiac** [comment]
Frankly, I never experienced a corrupted download myself, ever.

MD5 hash is a good idea but you have to be realistic. 99% of the users downloading TL don't know what a MD5 hash is or how to verify it. I don't see a huge benefit of adding it since it will be an unused feature. Usually you see MD5's when you are downloading software that requires IT skill to begin with (like operating systems or IT security software and such). And to be fair, TL not installing does not break anyone's leg. A re-download of a 30mb tool should be tolerable.

Though, this issue has shown what the error code for a corrupted file looks like in the installer. That helps for future issues, so it's not all in vein.

Thank you for your tests and the detailed explanations!
