### ISSUE TITLE
Download folder button

### ISSUE THREAD

**Issue by Zurlon** [Franiac/TwitchLeecher#580]
I understand the rationale behind the latest update removing the general "open download folder" button and replacing it with the individual buttons, but since this is a scrapped feature would it be possible for you to add it back as an option under settings? Personally it was incredibly useful to my workflow and with it not being a 'new' feature request as such I'd hope that this would be more doable than an outright new feature.

**Comment by Franiac** [comment]
I don't really see why. The download folder in the preferences is only the default setting that gets set in the download view automatically. The user can change this folder on every download independently if he desires. this makes the relationship between the download and the download folder a 1:1 dependency.

If you download like 5 videos and do NOT set the download folder individually and keep the default folder for every download, the individual button for each download will point the the same download folder (which is your default).

What's the difference between clicking the old button at the bottom and the button of the finished download? it's the same view, it's a single click with the same effect, nothing really changed.
