### ISSUE TITLE
Option to select a default resolution for downloads

### ISSUE THREAD

**Issue by jonas1015119** [Franiac/TwitchLeecher#582]
...so it doesnt go with 1080p60 on every new download. sometimes I forget to click on 720p60 and then wonder why the file is twice the size.
(Also when downloading multiple segments from the same vod, it would be great if the file name would automatically iterate with a _2 or something when it detects there already is a file with that name. Manually ticking the custom filename box to add it is a bit tedious.)

Thanks for all the work!

**Comment by Franiac** [comment]
#445
