### ISSUE TITLE
[MAC SUPPORT] Will there be support for apple devices any time soon? Thank you

### ISSUE THREAD

**Issue by sinanpalloks** [Franiac/TwitchLeecher#583]

**Comment by Franiac** [comment]
In theory the upcoming (no date) re-write of TL could run on Mac, but I don't own a Mac, don't want a Mac, and therefor cannot compile the application for Apple's ecosystem. If Apple wants me to buy a a shitty computer for way too much money, just to get a freeware application on their system, they actually can sod off 😄 

This is rather personal, but I don't support companies that milk their customers for shitty products. In addition to that I would need to purchase a 100$ developer account subscription just to be able to do anything with Apple. So, the answer is "Nah, thank you..." 😄
