### ISSUE TITLE
TV Support

### ISSUE THREAD

**Issue by hokkino** [Franiac/TwitchLeecher#584]
My TV Samsung its not supporting 1080p@61 (Source) option in the application (why is there 61fps and not 60?) and I dont know why, because I watch everything else in 1080p60 on my TV. Only when I download the second option 1280x720@60fps that I can play the video. Maybe a CODEC is doing this? Can I in anyway do a workaround in MKVtool and change the codec to watch in 1080p60 on my TV?

Thank you for the app!
![image](https://user-images.githubusercontent.com/80638635/111076351-bd5a3d00-84ca-11eb-99d9-9650719c943f.png)

**Comment by Franiac** [comment]
resolution and framerate values get provided by twitch and are dependent on the streamer. Same goes for the encoding settings and the codec itself. fps values are rounded, but 61 is a bit weird indeed. i don't know want this streamer is up to, but it looks not well set up. either way, nothing TL can do for you, unfortunately.
