### ISSUE TITLE
Status: error

### ISSUE THREAD

**Issue by Juan90980** [Franiac/TwitchLeecher#586]
note: this is translated by google translator

Tried downloading this video https://www.twitch.tv/videos/49944066/
using url search when i put it to download, i got status: error (after finishing almost all but the last process)
With this log:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 49944066
Selected Quality: 640x360 (Source)
Download Url: https://www.twitch.tv/videos/49944066
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\Rosa\Downloads\super mario 64.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1616500498%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A49944066%7D
Signature: 1de39ef23d6ec633bec9fcef10cb6d442c861a00
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d2nvs31859zcd8.cloudfront.net/9494de568e/basedurngod333221_6546923552_6546923552/chunked/highlight-49944066.m3u8
https://d2nvs31859zcd8.cloudfront.net/9494de568e/basedurngod333221_6546923552_6546923552/audio_only/highlight-49944066.m3u8

Playlist url for selected quality 640x360 (Source) is https://d2nvs31859zcd8.cloudfront.net/9494de568e/basedurngod333221_6546923552_6546923552/chunked/highlight-49944066.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 875

Starting parallel video chunk download
Number of video chunks to download: 875
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80\super mario 64.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80\super mario 64.ts'...
Command line arguments: -y -i "C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80\super mario 64.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Users\Rosa\Downloads\super mario 64.mp4"

[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[h264 @ 0000021595364e40] non-existing PPS 0 referenced
Last message repeated 1 times
[h264 @ 0000021595364e40] decode_slice_header error
[h264 @ 0000021595364e40] no frame!
[mpegts @ 000002159535d980] decoding for stream 1 failed
[mpegts @ 000002159535d980] Could not find codec parameters for stream 1 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80\super mario 64.ts':
Duration: 00:18:04.01, start: 749.930867, bitrate: 6968 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 94 kb/s
Stream #0:1[0x101]: Video: h264 ([27][0][0][0] / 0x001B), none, 29.97 fps, 29.97 tbr, 90k tbn, 180k tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 00000215955833c0] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
Stream #0:1 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Last message repeated 1 times

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Rosa\AppData\Local\Temp\TL_851812d3-72e5-49c8-a472-64001dda7c80'... done!

Download task ended with an error!

System.AggregateException: Se han producido uno o varios errores. ---> System.ApplicationException: An error occured while converting the video!
   en TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()
   --- Fin del seguimiento de la pila de la excepción interna ---
---> (Nº de excepción interna 0) System.ApplicationException: An error occured while converting the video!
   en TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
This is a source stream problem. Probably bad encoding settings of the streamer.

What you could do is downloading the video without mp4 conversion and trying to convert it manually with a video tool.

**Comment by Juan90980** [comment]
after downloading the ps (putting the option not to convert the mp4)
after using an external converter I got this: https://youtu.be/645vnyc9mX0
The truth is that I think it did not turn out as well as I expected

**Comment by Franiac** [comment]
A clear sign that the source material is corrupt. TL cannot fix broken streams, it just downloads what Twitch provides, sorry.
