### ISSUE TITLE
[Feature request] Download next vod while merging

### ISSUE THREAD

**Issue by EricWeichhart** [Franiac/TwitchLeecher#588]
Not sure if "request" is the best word, but rather ask if there are plans of it.

I noticed that between each download, the "Merging Files" and "Converting Video" process can take a bit of time, which could be used to start downloading the next file as well.

It is not a big deal, but I find myself wondering as sometimes it takes more time than the download itself. Either way, thanks for the amazing work!

**Comment by Franiac** [comment]
Not in the current download manager. I don't put any more time into it since I am nearly finished implementing the new NodeJS download manager...
