### ISSUE TITLE
Feature Request: Day of  the week as variable

### ISSUE THREAD

**Issue by TizianTitus** [Franiac/TwitchLeecher#589]
Hey, 

it would be nice to have a variable like "ID", "date", "game" as shown to the day of the week.
Thanks for the awesome tool!

-Titus

**Comment by Franiac** [comment]
Sorry, I actually don't understand what you are trying to say... what do you want to do where?

**Comment by TizianTitus** [comment]
Sorry for my bad english,
i want to have a variable, so i can write the day of the week in my filename at "filename tamplate"

Like this ones:
![Unbenannt](https://user-images.githubusercontent.com/25871509/112737962-03011600-8f5f-11eb-80ee-027f92864d1a.PNG)

**Comment by Franiac** [comment]
#523
