### ISSUE TITLE
Leecher -> Search -> Load limit: Only Today

### ISSUE THREAD

**Issue by pmcintyr** [Franiac/TwitchLeecher#592]
Hello, I am trying to return a list of twitch vod links from a filtered list of creator vods, that only keeps yesterday and todays vods. I see you integrated this filter in your load limit and was wondering if you could share with me how this was accomplished. Thank you so much for this product and sorry to bother you with this query :/ Also I thought of a cool feature to implement: multichannel query for the past broadcasts search

**Comment by Franiac** [comment]
https://github.com/Franiac/TwitchLeecher/blob/0224523f0b6816fc4ac0d41ae4e24c78ecc3867d/TwitchLeecher/TwitchLeecher.Services/Services/TwitchService.cs#L367
