### ISSUE TITLE
Leecher 404 error when downloading

### ISSUE THREAD

**Issue by ConfusedLizard** [Franiac/TwitchLeecher#593]
![image](https://user-images.githubusercontent.com/82261407/114264624-53807500-9a2f-11eb-89f3-cd6d291c95ec.png)
I cannot access the file to find the download log. The AppData file on my computer doesn't exist.

Version: 1.8

Video URL: https://www.twitch.tv/videos/977768937

OS: Windows 8.1

I search for the video using the URL as per normal, the video appears in Twitch Leecher and I click "Download".
I immediately get the pop up window as seen in the screenshot above.
I've tried searching for the channel to download the video via that route and same problem. 
I have no idea what I'm doing otherwise. I'm not an IT person and this is beyond me.

**Comment by Franiac** [comment]
Install the latest version...
