### ISSUE TITLE
All details were written to log file *ERROR*

### ISSUE THREAD

**Issue by KumjoTurk** [Franiac/TwitchLeecher#594]
Hello

I was downloading Twitch videos and then this came to the screen.

![error](https://user-images.githubusercontent.com/82412104/114451687-34751500-9be0-11eb-8c06-462bc602e40d.png)

**Comment by KumjoTurk** [comment]
I'm new,I don't know github :D

**Comment by Franiac** [comment]
Install the newest version...

**Comment by KumjoTurk** [comment]
Thank you,it worked!
