### ISSUE TITLE
Error finding a Temporary Directory

### ISSUE THREAD

**Issue by MarkusOnRepository** [Franiac/TwitchLeecher#600]
The best guess I can make is that it's deleting the folder before looking for the ts file, though that seems strange considering how it downloaded some other vods just fine. I'm on Windows 10 and I even decided to look at the temp folder and it seemed to be generating files and removing itself just fine.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 976364804
Selected Quality: 640x360@30fps
Download Url: https://www.twitch.tv/videos/976364804
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\Markus\Videos\Twitch Vods\Zoey's Twitch\20210405_monster hunter - it's hiiiigh rank (said like _high noon_ because i wear cowgirl wroggi armor and also because we're going in to high rank)_ZoeyProasheck_Monster Hunter Rise.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1619609517%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A976364804%7D
Signature: de204cfbd56f689b042479897a323ea7b3beb82c
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/chunked/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/720p60/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/480p30/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/audio_only/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/360p30/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/160p30/index-dvr.m3u8

Playlist url for selected quality 640x360@30fps is https://d1ymi26ma8va5x.cloudfront.net/a24a670d959d99975379_zoeyproasheck_41666683372_1617638456/360p30/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1206

Starting parallel video chunk download
Number of video chunks to download: 1206
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5\20210405_monster hunter - it's hiiiigh rank (said like _high noon_ because i wear cowgirl wroggi armor and also because we're going in to high rank)_ZoeyProasheck_Monster Hunter Rise.ts'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5\20210405_monster hunter - it's hiiiigh rank (said like _high noon_ because i wear cowgirl wroggi armor and also because we're going in to high rank)_ZoeyProasheck_Monster Hunter Rise.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5\20210405_monster hunter - it's hiiiigh rank (said like _high noon_ because i wear cowgirl wroggi armor and also because we're going in to high rank)_ZoeyProasheck_Monster Hunter Rise.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
That's the risk when using {title} in the filename template. Your temporary download path gets way too long. WIndows caps out at 259 characters. TL checks the download folder but not the temporary folder at the moment. I will fix that. But you cannot use such long filenames:

> C:\Users\Markus\AppData\Local\Temp\TL_5636d602-e66c-470a-b7e5-89fc609768c5\20210405_monster hunter - it's hiiiigh rank (said like _high noon_ because i wear cowgirl wroggi armor and also because we're going in to high rank)_ZoeyProasheck_Monster Hunter Rise.ts

You have to choose a custom filename for such long titles. Or rant at the streamer 😄
