### ISSUE TITLE
Trovo Support (Request)

### ISSUE THREAD

**Issue by RoarTruth** [Franiac/TwitchLeecher#602]
**"Trovo"** is a similar website for **streaming**. It would be amazing if you could add support for downloading **_past stream_** from **"Trovo"** in TwitchLeecher.

**Thank You** for making this amazing software.

**Comment by Franiac** [comment]
Given the fact that I had to google what Trovo is and a first look at the entire viewer count on the platform there is absolutely no reason to put in any effort in order to support it. YouTube would be much more useful, don't you think?
