### ISSUE TITLE
Videos crashing in VLC from a certain streamer

### ISSUE THREAD

**Issue by Akumadoken** [Franiac/TwitchLeecher#604]
Hi I've been having an issue with ASMR highlight videos crashing only in VLC when few seconds in. If I skip past the problematic second the video plays fine afterwards.

I'm using version 1.8.4

Windows 10 64bit

The Streamer is Dizzykitten
https://www.twitch.tv/dizzykitten

Here is a highlight for testing
https://www.twitch.tv/videos/1009459677

Once downloaded and played in VLC it crashes 8 seconds in.
Currently using the latest version of VLC 3.0.12

If you also try this one, it crashes 1 second in.
https://www.twitch.tv/videos/1001341760

TwitchLeecher download log:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1009459677
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/1009459677
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: D:\ASMR DizzyKitten\ASMR with Dizzy! #346.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\atlif\AppData\Local\Temp\TL_3eee5ce8-a6bb-404c-99c9-446f2ea86a27

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1620134909%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1009459677%7D
Signature: 2660483f225e96e686e2a2a3fb8b6ecdaac9d7d3
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\atlif\AppData\Local\Temp\TL_3eee5ce8-a6bb-404c-99c9-446f2ea86a27'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/chunked/highlight-1009459677.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/720p60/highlight-1009459677.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/720p30/highlight-1009459677.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/480p30/highlight-1009459677.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/audio_only/highlight-1009459677.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/360p30/highlight-1009459677.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/160p30/highlight-1009459677.m3u8

Playlist url for selected quality 1280x720@60fps (Source) is https://d1m7jfoe9zdc1j.cloudfront.net/4140242845100f1e0fba_dizzykitten_88351746962_5747924225/chunked/highlight-1009459677.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 440

Starting parallel video chunk download
Number of video chunks to download: 440
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\atlif\AppData\Local\Temp\TL_3eee5ce8-a6bb-404c-99c9-446f2ea86a27\ASMR with Dizzy! #346.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\atlif\AppData\Local\Temp\TL_3eee5ce8-a6bb-404c-99c9-446f2ea86a27\ASMR with Dizzy! #346.ts'...
Command line arguments: -y -i "C:\Users\atlif\AppData\Local\Temp\TL_3eee5ce8-a6bb-404c-99c9-446f2ea86a27\ASMR with Dizzy! #346.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "D:\ASMR DizzyKitten\ASMR with Dizzy! #346.mp4"

Video conversion complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\atlif\AppData\Local\Temp\TL_3eee5ce8-a6bb-404c-99c9-446f2ea86a27'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
She droppes frames... a lot actually. FFMPEG and with that the conversion to mp4 does not like that. You could download the original .ts file and try transcoding it via Handbrake for example, but the direct stream copy that TL uses does not like dropped frames at all and that is not an issue with TL but FFMPEG. Unfortunately I cannot help you here 😞
