### ISSUE TITLE
Fails to download a 45 hour stream

### ISSUE THREAD

**Issue by mgrandi** [Franiac/TwitchLeecher#605]
as far as I can search, i haven't found any existing issues on this, but it might be worded differently.

I am trying to download  45 hour stream that was national news to upload to internet archive, but it seems that twitch leecher is not outputting a file that is the full filesize

the stream is here, for now: https://www.twitch.tv/videos/951260262

I downloaded it in two formts, 720p and 160p and got the same result, a file that is only 19:16:43 (H:M:S) long

ffprobe output:

```plaintext
Input #0, mpegts, from '/mnt/d/TwitchLeecherOutput/20210316_002028_ludwig_951260262_Just Chatting_SLEEP STREAM AT MIDNIGHT NEVER ENDING STREAM !SUBATHON_284x160_30fps_000000_454727.ts':
  Duration: 19:16:43.49, start: 66.010000, bitrate: 677 kb/s
  Program 1
    Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 49 kb/s
    Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 284x160 [SAR 1:1 DAR 71:40], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
```

windows explorer:

![image](https://user-images.githubusercontent.com/802786/117527770-549bb800-af83-11eb-87b6-e7826ab2c76f.png)

the twitch leecher log:

```plaintext
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 951260262
Selected Quality: 284x160@30fps
Download Url: https://www.twitch.tv/videos/951260262
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: Yes
Output File: D:\TwitchLeecherOutput\20210316_002028_ludwig_951260262_Just Chatting_SLEEP STREAM AT MIDNIGHT NEVER ENDING STREAM !SUBATHON_284x160_30fps_000000_454727.ts
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: D:\TwitchLeecherTemp\TL_27cf1e70-b078-440e-aab9-108207934b98

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1620521050%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A951260262%7D
Signature: e320adee6f46816720ff23836dd506e5a4a99424
Sub-Only: No
Privileged: No

Creating temporary download directory 'D:\TwitchLeecherTemp\TL_27cf1e70-b078-440e-aab9-108207934b98'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/chunked/index-muted-4WOK8JFKLE.m3u8
https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/720p60/index-muted-4WOK8JFKLE.m3u8
https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/480p30/index-muted-4WOK8JFKLE.m3u8
https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/audio_only/index-muted-4WOK8JFKLE.m3u8
https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/360p30/index-muted-4WOK8JFKLE.m3u8
https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/160p30/index-muted-4WOK8JFKLE.m3u8

Playlist url for selected quality 284x160@30fps is https://dqrpb9wgowsf5.cloudfront.net/a8a6d13cc156a170664d_ludwig_41997977966_1615879219/160p30/index-muted-4WOK8JFKLE.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 16485

Starting parallel video chunk download
Number of video chunks to download: 16485
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'D:\TwitchLeecherOutput\20210316_002028_ludwig_951260262_Just Chatting_SLEEP STREAM AT MIDNIGHT NEVER ENDING STREAM !SUBATHON_284x160_30fps_000000_454727.ts'...

Starting temporary download folder cleanup!
Deleting directory 'D:\TwitchLeecherTemp\TL_27cf1e70-b078-440e-aab9-108207934b98'... done!

Download task ended successfully!
```

top snippet of the playlist:

```plaintext
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#ID3-EQUIV-TDTG:2021-03-18T05:08:28
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TWITCH-ELAPSED-SECS:0.000
#EXT-X-TWITCH-TOTAL-SECS:164847.895
#EXTINF:10.000,
0.ts
#EXTINF:10.000,
1.ts
#EXTINF:10.000,
2.ts
```
(164847 seconds is 45.79083 hours)

i also watched it download and it appeared to download all 16485 chunks of the file. Not sure where to debug on this one. the 160p version of the video file is around 5 GiB if you want to download to test it yourself

Even if you don't have time to implement a fix, if you point me in the right direction I could implement it for you, but you know the code base better than me :)

**Comment by Liz-chan** [comment]
You need to split the stream into 15 hour chunks.

**Comment by Franiac** [comment]
This is not a TL issue. FFMPEG does not handle those extremely big files. IF you turn off mp4 conversion, you'll get a working .ts file.

**Comment by Liz-chan** [comment]
> This is not a TL issue. FFMPEG does not handle those extremely big files. If you turn off mp4 conversion, you'll get a working .ts file.

Actually even the .ts files suffer from the same bug, so that's why I suggested splitting them which is the only way I can get them to work.

**Comment by Liz-chan** [comment]
> @Liz-chan It shouldn't, since the .ts files from the playlist are just merged into a single file on a binary level. I checked this a couple times and it worked on >60hr streams from GDQ. But videos of that length and size are uncommon. There could be all sorts of issues with video players or even file systems. It is generally not a good idea to store such long videos in a single file.

Yeah I'm not sure what's up with it, usually if a stream is longer than 24 hours I'll have issues and the duration will only be like 1 or 2 hours, and none of my media players will play it (vlc, mpv).

**Comment by Franiac** [comment]
VLC is based on FFMPEG. Could be an issue there, too.

**Comment by mgrandi** [comment]
Vlc isn't based on ffmpeg, it ha sits own codecs

And I'm not converting it to MP4, I'm leaving it as a .TS file

And isn't the merging just, concatenating the .ts files together?

**Comment by Franiac** [comment]
@mgrandi That's exactly what I said. The parts are merged on a binary level. Bug or no bug, there is nothing to do differently here. I cannot choose to merge them in a different way or something 😄

**Comment by mgrandi** [comment]
ok, so i put a breakpoint where TL starts concatenating the files and made a copy of the files, and then wrote  a quick python script to concatenate the parts in order, and then did a SHA256 sum of both the file I made and the file TL made, and they are identical

I also downloaded media player classic and it also shows the 19 hour 16 minute video length despite it being the entire video file

So this probably means that the mpegts format has some weird smallish upper limit or something? 

anyway, maybe twitch leecher should offer to split the files into multiple chunks when it detects a video longer than X length?

**Comment by Franiac** [comment]
I think a 15hr breakpoint sounds reasonable. What I don'T understand is the fact that I have some +60hr streams working and others not. Absolutely no clue what makes some files "corrupted".

**Comment by mgrandi** [comment]
I wonder if its because this vod has muted parts to it? I was going through my videos and found one that was 21 hours and that is fine...
