### ISSUE TITLE
Cannot search older vods

### ISSUE THREAD

**Issue by Dreamyvision616** [Franiac/TwitchLeecher#611]
Twitch leecher 1.8.4

Running on win 10 

Trying to download old vods from Reckful's channel, but twitch leecher can't seem to pull any of the vods past 2016, despite them being available on twitch. Downloading individual ones using URL works, but I can't seek past 2016.

**Comment by Dreamyvision616** [comment]
Additional issue: If you put in older URL's than Dec 25, 2015, they all show as that date, even if they're from before

**Comment by Franiac** [comment]
Please provide proper video ID's for reproduction.

**Comment by Dreamyvision616** [comment]
Here is an example: https://www.twitch.tv/videos/31721506?filter=all&sort=time

This vod is from dec 15th, 2015, but it shows as dec 25th 2015 as does every vod around it and from before. 

Also I'm attaching a picture showing the earliest possible vods that can be searched on leecher. Anything past these dates will not return on search. 

![81040d5fa86c7f6e1d18f569fd30c25a](https://user-images.githubusercontent.com/84700734/119572780-4b7f5900-bd81-11eb-89a4-3b2e6a230a1d.png)

**Comment by Franiac** [comment]
This is not a TL issue. The Twitch API provides faulty and even in some cases unparsable data. The 25th is not something TL comes up with, it's the exact value Twitch provides for the video. I remember we had this kind of stuff a couple years ago. Fact is, I cannot change bad data TL receives from Twitch. So unfortunately I cannot do anything about it, sorry.
