### ISSUE TITLE
Status: Error

### ISSUE THREAD

**Issue by Lizukh** [Franiac/TwitchLeecher#617]
While downloading a stream out of nowhere, it throws me that error and sets it to 100%.
The first time it happened I uninstalled it and installed it again and it was fixed, but now it does not work anymore, what do I 
![Captura](https://user-images.githubusercontent.com/86329633/123011306-8089c600-d396-11eb-912d-7aee6720d2a1.PNG)

**Comment by CodTheJay** [comment]
![image_2021-06-23_152858](https://user-images.githubusercontent.com/86365156/123115088-baf76f80-d437-11eb-8536-e2de580af8a8.png) I also have the same issue, but for me its at the end of merging files roughly about 90% it will cut to 100% and say error, I've tried 4-5 times now as I really really need this vod

**Comment by Franiac** [comment]
Can you guys please read the issue guide that says "READ THIS FIRST" and not simply ignore it?

Here it is again:

Help me beeing efficient, please! I am developing Twitch Leecher in my free time for no money. Contribute to the project by posting complete, structured and helpful issues which I can reproduce quickly without asking for missing information.

When creating a new issue please make sure you follow the below checklist:

- Take a look at the latest closed issues. Maybe yours has already been solved.
- If you have a problem with a download, provide the download log created by Twitch Leecher
- Provide the version of Twitch Leecher you are using
- Provide information about the video (Url, Channel, ID)
- Provide information about your operating system (e.g. Windows 10 64 Bit)
- Try to describe the problem as detailed as possible, I cannot read your mind
- Windows Insider Builds are NOT supported!

About Audio/Video Desync Issues:

Make sure to check for desync issues with VLC Media Player. A lot of video tools have immense trouble playing back downloaded Twitch streams correctly. Especially the following products introduce A/V desync:

- Windows Media Player
- Adobe Premiere (no joke, Adobe just does not care)

So if you are about to post a desync issue and you are using one of the above programs, please check the video in VLC first!

**Comment by KokatsuKitsune** [comment]
If you look at the top line of your log file it should read you the error- most likely (looking at the size of your videos) you are out of disk space to download them.
