### ISSUE TITLE
Status: Error after 100%

### ISSUE THREAD

**Issue by Za3eM** [Franiac/TwitchLeecher#625]
I'm trying to download a 6-hour VOD from yesterday, I even emptied a lot of my C: drive storage, and it still downloads the VOD and merges the files 100% then just tells me, status: error.
![image](https://user-images.githubusercontent.com/48319861/125783433-6c97e255-ad22-4109-af27-83f49c160517.png)

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1085721509
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/1085721509
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\user\Downloads\20210714_1085721509_Just Chatting.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\user\AppData\Local\Temp\TL_d8c4743d-1a89-47f7-baa5-1dda8c6fb1f8

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1626420546%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1085721509%7D
Signature: 769a9ed3fc11dc95f304b6bce95e0f9146796efd
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\user\AppData\Local\Temp\TL_d8c4743d-1a89-47f7-baa5-1dda8c6fb1f8'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/chunked/index-muted-8W4IU2C0YL.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/720p60/index-muted-8W4IU2C0YL.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/720p30/index-muted-8W4IU2C0YL.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/480p30/index-muted-8W4IU2C0YL.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/audio_only/index-muted-8W4IU2C0YL.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/360p30/index-muted-8W4IU2C0YL.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/160p30/index-muted-8W4IU2C0YL.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://d1m7jfoe9zdc1j.cloudfront.net/4768ba1eb3d8c9023c57_mizkif_42815500365_1626208154/chunked/index-muted-8W4IU2C0YL.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2422

Starting parallel video chunk download
Number of video chunks to download: 2422
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\user\AppData\Local\Temp\TL_d8c4743d-1a89-47f7-baa5-1dda8c6fb1f8\20210714_1085721509_Just Chatting.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\user\AppData\Local\Temp\TL_d8c4743d-1a89-47f7-baa5-1dda8c6fb1f8\20210714_1085721509_Just Chatting.ts'...
Command line arguments: -y -i "C:\Users\user\AppData\Local\Temp\TL_d8c4743d-1a89-47f7-baa5-1dda8c6fb1f8\20210714_1085721509_Just Chatting.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Users\user\Downloads\20210714_1085721509_Just Chatting.mp4"

[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 45538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 46438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 47338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 48238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 49138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 50038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 50938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 51838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 52738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 53638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 54538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 55438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 56338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 57238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 58138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 59038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 59938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 60838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 61738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 62638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 63538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 64438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 65338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 66238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 67138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 68038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 68938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 69838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 70738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 71638470).
frame=44323 fps=27858 q=-1.0 size=  553472kB time=00:12:19.81 bitrate=6128.6kbits/s speed= 465x
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 72538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 73438470).
frame=45323 fps=21022 q=-1.0 size=  566016kB time=00:12:36.51 bitrate=6129.2kbits/s speed= 351x
frame=45420 fps=16730 q=-1.0 size=  567296kB time=00:12:38.12 bitrate=6130.0kbits/s speed= 279x
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 74338470).
frame=45531 fps=13903 q=-1.0 size=  568576kB time=00:12:40.02 bitrate=6128.5kbits/s speed= 232x
frame=45633 fps=11954 q=-1.0 size=  569856kB time=00:12:41.69 bitrate=6128.8kbits/s speed=200x
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 75238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 77038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 77938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 78838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 79738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 80638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 81538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 82438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 84238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 85138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 86038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 86938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 87838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 88738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 90538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 91438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 92338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 93238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 94138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 95038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 95938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 96838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 97738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 98638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 99538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 100438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 101338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 102238470).
frame=64103 fps=14847 q=-1.0 size=  800512kB time=00:17:50.01 bitrate=6128.7kbits/s speed= 248x
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 103138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 104038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 105838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 106738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 107638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 108538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 109438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 110338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 111238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 112138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 113038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 113938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 114838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 116638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 117538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 118438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 119338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 120238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 121138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 122038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 122938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 123838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 124738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 125638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 126538470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 127438470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 128338470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 129238470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 130138470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 131038470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 131938470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 132838470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 133738470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 134638470).
[mpegts @ 0000025ba639dbc0] Packet corrupt (stream = 1, dts = 135538470).
frame=86816 fps=18020 q=-1.0 size= 1084160kB time=00:24:09.13 bitrate=6128.8kbits/s speed= 301x
frame=108502 fps=20404 q=-1.0 size= 1356032kB time=00:30:10.56 bitrate=6135.5kbits/s speed= 340x
frame=124412 fps=20994 q=-1.0 size= 1555712kB time=00:34:35.75 bitrate=6139.6kbits/s speed= 350x
frame=124515 fps=19230 q=-1.0 size= 1556992kB time=00:34:37.44 bitrate=6139.7kbits/s speed= 321x
frame=124620 fps=17621 q=-1.0 size= 1558272kB time=00:34:39.18 bitrate=6139.6kbits/s speed= 294x
frame=124718 fps=16310 q=-1.0 size= 1559552kB time=00:34:40.85 bitrate=6139.7kbits/s speed= 272x
frame=124817 fps=15171 q=-1.0 size= 1560832kB time=00:34:42.49 bitrate=6139.9kbits/s speed= 253x
frame=124914 fps=14243 q=-1.0 size= 1562112kB time=00:34:44.11 bitrate=6140.2kbits/s speed= 238x
frame=125028 fps=13374 q=-1.0 size= 1563392kB time=00:34:46.03 bitrate=6139.5kbits/s speed= 223x
frame=125129 fps=12645 q=-1.0 size= 1564672kB time=00:34:47.70 bitrate=6139.7kbits/s speed= 211x
frame=125231 fps=11957 q=-1.0 size= 1565952kB time=00:34:49.40 bitrate=6139.7kbits/s speed= 199x
frame=125309 fps=11339 q=-1.0 size= 1566976kB time=00:34:50.70 bitrate=6139.9kbits/s speed= 189x
frame=125411 fps=10794 q=-1.0 size= 1568256kB time=00:34:52.37 bitrate=6140.0kbits/s speed= 180x
frame=125510 fps=10283 q=-1.0 size= 1569536kB time=00:34:54.03 bitrate=6140.1kbits/s speed= 172x
frame=125618 fps=9825 q=-1.0 size= 1570816kB time=00:34:55.85 bitrate=6139.8kbits/s speed= 164x
frame=125715 fps=9401 q=-1.0 size= 1572096kB time=00:34:57.47 bitrate=6140.1kbits/s speed= 157x
frame=125823 fps=9006 q=-1.0 size= 1573376kB time=00:34:59.24 bitrate=6139.9kbits/s speed= 150x
frame=125921 fps=8649 q=-1.0 size= 1574656kB time=00:35:00.90 bitrate=6140.0kbits/s speed= 144x
frame=126020 fps=8324 q=-1.0 size= 1575936kB time=00:35:02.54 bitrate=6140.2kbits/s speed= 139x
frame=126122 fps=8033 q=-1.0 size= 1577216kB time=00:35:04.25 bitrate=6140.2kbits/s speed= 134x
frame=126230 fps=7765 q=-1.0 size= 1578496kB time=00:35:06.02 bitrate=6140.0kbits/s speed= 130x
frame=126335 fps=7510 q=-1.0 size= 1579776kB time=00:35:07.79 bitrate=6139.8kbits/s speed= 125x
frame=126437 fps=7271 q=-1.0 size= 1581056kB time=00:35:09.50 bitrate=6139.8kbits/s speed= 121x
frame=126536 fps=7047 q=-1.0 size= 1582336kB time=00:35:11.14 bitrate=6140.0kbits/s speed= 118x
frame=126638 fps=6842 q=-1.0 size= 1583616kB time=00:35:12.85 bitrate=6140.0kbits/s speed= 114x
frame=126732 fps=6644 q=-1.0 size= 1584896kB time=00:35:14.38 bitrate=6140.5kbits/s speed= 111x
frame=126834 fps=6455 q=-1.0 size= 1586176kB time=00:35:16.11 bitrate=6140.5kbits/s speed= 108x
frame=126945 fps=6280 q=-1.0 size= 1587456kB time=00:35:17.97 bitrate=6140.0kbits/s speed= 105x
frame=127052 fps=6115 q=-1.0 size= 1588736kB time=00:35:19.72 bitrate=6139.9kbits/s speed= 102x
frame=127151 fps=5957 q=-1.0 size= 1590016kB time=00:35:21.40 bitrate=6140.0kbits/s speed=99.4x
frame=127247 fps=5805 q=-1.0 size= 1591296kB time=00:35:23.00 bitrate=6140.3kbits/s speed=96.9x
frame=127349 fps=5661 q=-1.0 size= 1592576kB time=00:35:24.69 bitrate=6140.4kbits/s speed=94.5x
frame=127450 fps=5526 q=-1.0 size= 1593856kB time=00:35:26.35 bitrate=6140.5kbits/s speed=92.2x
frame=128534 fps=5434 q=-1.0 size= 1607424kB time=00:35:44.42 bitrate=6140.6kbits/s speed=90.7x
frame=128630 fps=5311 q=-1.0 size= 1608704kB time=00:35:46.04 bitrate=6140.8kbits/s speed=88.6x
frame=136681 fps=5529 q=-1.0 size= 1709568kB time=00:38:00.21 bitrate=6141.9kbits/s speed=92.2x
frame=139331 fps=5524 q=-1.0 size= 1742848kB time=00:38:44.37 bitrate=6142.5kbits/s speed=92.1x
frame=139430 fps=5406 q=-1.0 size= 1744128kB time=00:38:46.03 bitrate=6142.6kbits/s speed=90.2x
frame=145363 fps=5529 q=-1.0 size= 1818368kB time=00:40:24.91 bitrate=6142.9kbits/s speed=92.2x
frame=166028 fps=6197 q=-1.0 size= 2076928kB time=00:46:09.34 bitrate=6143.8kbits/s speed= 103x
frame=186369 fps=6829 q=-1.0 size= 2332160kB time=00:51:48.37 bitrate=6146.3kbits/s speed= 114x
frame=194968 fps=7006 q=-1.0 size= 2440192kB time=00:54:11.69 bitrate=6147.6kbits/s speed= 117x
frame=195066 fps=6869 q=-1.0 size= 2441472kB time=00:54:13.31 bitrate=6147.7kbits/s speed= 115x
frame=195167 fps=6742 q=-1.0 size= 2442752kB time=00:54:14.99 bitrate=6147.8kbits/s speed= 112x
frame=195267 fps=6618 q=-1.0 size= 2444032kB time=00:54:16.66 bitrate=6147.9kbits/s speed= 110x
frame=195368 fps=6499 q=-1.0 size= 2445312kB time=00:54:18.34 bitrate=6147.9kbits/s speed= 108x
frame=195470 fps=6388 q=-1.0 size= 2446592kB time=00:54:20.03 bitrate=6147.9kbits/s speed= 107x
frame=195578 fps=6279 q=-1.0 size= 2447872kB time=00:54:21.84 bitrate=6147.7kbits/s speed= 105x
frame=195680 fps=6171 q=-1.0 size= 2449152kB time=00:54:23.55 bitrate=6147.7kbits/s speed= 103x
frame=195782 fps=6065 q=-1.0 size= 2450432kB time=00:54:25.25 bitrate=6147.7kbits/s speed= 101x
frame=195887 fps=5964 q=-1.0 size= 2451712kB time=00:54:27.00 bitrate=6147.7kbits/s speed=99.5x
frame=195987 fps=5869 q=-1.0 size= 2452992kB time=00:54:28.67 bitrate=6147.7kbits/s speed=97.9x
frame=196085 fps=5777 q=-1.0 size= 2454272kB time=00:54:30.29 bitrate=6147.9kbits/s speed=96.3x
frame=196190 fps=5686 q=-1.0 size= 2455552kB time=00:54:32.04 bitrate=6147.8kbits/s speed=94.8x
frame=196291 fps=5600 q=-1.0 size= 2456832kB time=00:54:33.70 bitrate=6147.9kbits/s speed=93.4x
frame=196394 fps=5517 q=-1.0 size= 2458112kB time=00:54:35.45 bitrate=6147.8kbits/s speed=  92x
frame=196499 fps=5436 q=-1.0 size= 2459392kB time=00:54:37.20 bitrate=6147.7kbits/s speed=90.7x
frame=196596 fps=5357 q=-1.0 size= 2460672kB time=00:54:38.82 bitrate=6147.9kbits/s speed=89.4x
frame=196694 fps=5280 q=-1.0 size= 2461952kB time=00:54:40.44 bitrate=6148.0kbits/s speed=88.1x
frame=196794 fps=5205 q=-1.0 size= 2463232kB time=00:54:42.11 bitrate=6148.1kbits/s speed=86.8x
frame=196908 fps=5134 q=-1.0 size= 2464512kB time=00:54:44.01 bitrate=6147.8kbits/s speed=85.6x
frame=197006 fps=5063 q=-1.0 size= 2465792kB time=00:54:45.65 bitrate=6147.9kbits/s speed=84.4x
frame=197109 fps=4993 q=-1.0 size= 2467072kB time=00:54:47.36 bitrate=6147.9kbits/s speed=83.3x
frame=197210 fps=4928 q=-1.0 size= 2468352kB time=00:54:49.04 bitrate=6147.9kbits/s speed=82.2x
frame=197309 fps=4864 q=-1.0 size= 2469632kB time=00:54:50.70 bitrate=6148.0kbits/s speed=81.1x
frame=198278 fps=4828 q=-1.0 size= 2481664kB time=00:55:06.85 bitrate=6147.8kbits/s speed=80.5x
frame=200789 fps=4829 q=-1.0 size= 2513152kB time=00:55:48.69 bitrate=6148.0kbits/s speed=80.5x
frame=200879 fps=4767 q=-1.0 size= 2514432kB time=00:55:50.20 bitrate=6148.3kbits/s speed=79.5x
frame=206390 fps=4831 q=-1.0 size= 2583552kB time=00:57:22.02 bitrate=6148.8kbits/s speed=80.6x
frame=206499 fps=4771 q=-1.0 size= 2584832kB time=00:57:23.84 bitrate=6148.6kbits/s speed=79.6x
frame=206725 fps=4722 q=-1.0 size= 2587648kB time=00:57:27.61 bitrate=6148.6kbits/s speed=78.8x
frame=209990 fps=4738 q=-1.0 size= 2628608kB time=00:58:22.03 bitrate=6148.9kbits/s speed=  79x
frame=210093 fps=4681 q=-1.0 size= 2629888kB time=00:58:23.76 bitrate=6148.8kbits/s speed=78.1x
frame=216735 fps=4769 q=-1.0 size= 2713088kB time=01:00:14.44 bitrate=6149.1kbits/s speed=79.5x
frame=216830 fps=4714 q=-1.0 size= 2714368kB time=01:00:16.04 bitrate=6149.3kbits/s speed=78.6x
frame=217349 fps=4674 q=-1.0 size= 2720768kB time=01:00:24.68 bitrate=6149.1kbits/s speed=77.9x
frame=218586 fps=4648 q=-1.0 size= 2736384kB time=01:00:45.29 bitrate=6149.4kbits/s speed=77.5x
frame=218687 fps=4597 q=-1.0 size= 2737664kB time=01:00:46.97 bitrate=6149.5kbits/s speed=76.7x
frame=222103 fps=4619 q=-1.0 size= 2780416kB time=01:01:43.93 bitrate=6149.4kbits/s speed=  77x
frame=222204 fps=4567 q=-1.0 size= 2781696kB time=01:01:45.62 bitrate=6149.5kbits/s speed=76.2x
frame=223549 fps=4548 q=-1.0 size= 2798848kB time=01:02:08.04 bitrate=6150.2kbits/s speed=75.8x
frame=225389 fps=4530 q=-1.0 size= 2821632kB time=01:02:38.69 bitrate=6149.7kbits/s speed=75.5x
frame=225470 fps=4481 q=-1.0 size= 2822912kB time=01:02:40.04 bitrate=6150.3kbits/s speed=74.7x
frame=229430 fps=4508 q=-1.0 size= 2872576kB time=01:03:46.02 bitrate=6150.5kbits/s speed=75.2x
frame=229526 fps=4460 q=-1.0 size= 2873856kB time=01:03:47.64 bitrate=6150.7kbits/s speed=74.4x
frame=232716 fps=4479 q=-1.0 size= 2913536kB time=01:04:40.81 bitrate=6150.2kbits/s speed=74.7x
frame=233717 fps=4452 q=-1.0 size= 2926080kB time=01:04:57.47 bitrate=6150.3kbits/s speed=74.2x
frame=233818 fps=4408 q=-1.0 size= 2927360kB time=01:04:59.17 bitrate=6150.3kbits/s speed=73.5x
frame=238024 fps=4439 q=-1.0 size= 2980096kB time=01:06:09.25 bitrate=6150.5kbits/s speed=  74x
frame=238125 fps=4396 q=-1.0 size= 2981376kB time=01:06:10.96 bitrate=6150.5kbits/s speed=73.3x
frame=242264 fps=4432 q=-1.0 size= 3033088kB time=01:07:19.95 bitrate=6150.3kbits/s speed=73.9x
frame=243713 fps=4413 q=-1.0 size= 3051776kB time=01:07:44.10 bitrate=6151.5kbits/s speed=73.6x
frame=243830 fps=4371 q=-1.0 size= 3053056kB time=01:07:46.02 bitrate=6151.1kbits/s speed=72.9x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\user\Downloads\20210714_1085721509_Just Chatting.mp4: No space left on device
frame=243977 fps=4366 q=-1.0 Lsize= 3054592kB time=01:07:48.48 bitrate=6150.5kbits/s speed=72.8x
video:2980786kB audio:75121kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\user\AppData\Local\Temp\TL_d8c4743d-1a89-47f7-baa5-1dda8c6fb1f8'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
`av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\user\Downloads\20210714_1085721509_Just Chatting.mp4: No space left on device
frame=243977 fps=4366 q=-1.0 Lsize= 3054592kB time=01:07:48.48 bitrate=6150.5kbits/s speed=72.8x
video:2980786kB audio:75121kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!`

The message is pretty clear. If you enable mp4 conversion you actually need double the space on your disk since ffmpeg does not stream input to output files.
