### ISSUE TITLE
No downloads possible

### ISSUE THREAD

**Issue by Blabbelbrabber** [Franiac/TwitchLeecher#63]
Due to the new VOD format no downloads are possible anymore. Tried to download several streams from yesterday. He downloads like usual, but the mp4 only has the sound, not the video.

**Comment by Franiac** [comment]
Downloads work perfectly. There is not a new VOD format. there are uploads now, but the format is the exact same compared to broadcasts and highlights. please provide the download log and VOD urls. If download was not possible probably my inbox would explode.

**Comment by Blabbelbrabber** [comment]
VOD url is https://www.twitch.tv/gronkh/v/95506393
The log is attached.
[log_95506393.txt](https://github.com/Franiac/TwitchLeecher/files/542673/log_95506393.txt)

**Comment by Franiac** [comment]
The VOD is muted for a long time at the beginning. If you crop the first 5 or 10 minutes, it works as expected. This a common issue with all downloaders and cannot be fixed. If the streamer plays like 15 min copyrighted music at the beginning, the encoder fails basically because it gets no information about the stream. do not want to get too deep into details but basically..... copyright protected music is not the best thing.

**Comment by Blabbelbrabber** [comment]
Actually this is wrong.
1. It is not muted at the beginning. I can open the VOD in my browser, the sound is there, no copyrighted music.
2. I just tried another downloader, and it worked fine.
3. I know the issue with the muted sound at the beginning. I then use another software which can downloads this VODs without problems, so this is not an unfixable bug.
= So, it is obvious it is your program that causes the errors.

**Comment by Blabbelbrabber** [comment]
Also, with your software I can download the sound (whithout silence in the beginning, because it is not muted). I just don't get the video.

**Comment by Franiac** [comment]
Indeed I used the wrong VOD url for the test, duh....
A hint on the downloader that works would be great. I could check what ffmpeg parameters get used. I do not see anything wrong on mine.

**Comment by Blabbelbrabber** [comment]
Basically I just used Jdownloader. But it downloads the streams in a really bad quality. Thats why I prefer your software.
I just tested it with other VODs and now it works fine with them, but not with this specific VOD. Also, on another VOD downloader page I read the thing with the new format, and that it cannot be downloaded because of it. Other VODs, fine, but this special one has another format. I used this site: http://twitch.center/vodcutter
This VOD works fine: https://www.twitch.tv/deadbydaylight/v/96100920
But this: https://www.twitch.tv/gronkh/v/95506393 (the original problem one) doesn't work. I get the message "Unfortunately, Twitch has been switching to a new VOD format, making this tool unusable. There is nothing I can do about it, sorry for the inconvenience." So that's why I think there is a new format, maybe just for very long streams.

**Comment by Franiac** [comment]
so jdonwloader really manages to download this: https://www.twitch.tv/gronkh/v/95506393
i do not have it installed, but i recently checked the ffmpeg arguments it uses and they were the same like mine. i just want to make sure that you tried exactly this url, before i install jdownloader again and it does not work either :)
that message about the new format was from 2014 when Twitch switched to HLS streams.... i know this software and is was really old. Nothing changed recently.

**Comment by Franiac** [comment]
Just to make it visible to everyone: this is what ffmpeg tells me.

scroll down and it says: "Could not find codec parameters for stream 1 (Video: h264 ([27][0][0][0] / x001B), none): unspecified size Consider increasing the value for the 'analyzeduration' and 'probesize' options"

analyzeduration and probesize are already at maximum (2^32 / integer max value). so i am really curious now what jdownloader can do differently compared to me. i kinda doubt it works there either but i like to get convinced ;)

ffmpeg_x64.exe -y -i "D:\01 Bad\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "D:\test_bad.mp4"
ffmpeg version N-81894-g54220ce Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 60.101 / 57. 60.101
  libavformat    57. 51.102 / 57. 51.102
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
[hls,applehttp @ 00000000027324a0] Could not find codec parameters for stream 1 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls,applehttp, from 'D:\01 Bad\vod.m3u8':
  Duration: 00:03:00.00, start: 66.012989, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'D:\test_bad.mp4':
  Metadata:
    encoder         : Lavf57.51.102
    Stream #0:0: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=    2935kB time=00:03:00.00 bitrate= 133.6kbits/s speed= 937x
video:0kB audio:2902kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.139821%

**Comment by Blabbelbrabber** [comment]
Just checked the Jdownloader-Download, but also this is just the sound ...
Ok, did not know about the format was that old. :D
So, there is no way to download it for now?

**Comment by Blabbelbrabber** [comment]
Ok, the download with another beginning time just finished (I set it to 5 minutes), and now the video is there. WTF? :D It wasn't muted, that's why I haven't tried it this way.

**Comment by Franiac** [comment]
jep, like I thought, some streams get just messed up by Twitch somehow. and all the browser players are much more error-prone compared to that shitty ffmpeg.
sure you can still download it, like i said: in the download dialog just crop the start 00:00:10, and it works...

**Comment by Blabbelbrabber** [comment]
Yeah, whatever Twitch did to this VOD. :D Nevertheless, thanks for the help.
