### ISSUE TITLE
Open pull requests

### ISSUE THREAD

**Issue by Zurlon** [Franiac/TwitchLeecher#631]
I would just like to ask about the 2 open pull requests that other people have made; they are both features I would find useful (esp the timestamp parser). Since the code has already been written and is waiting for review, is there any timeline on when (if at all) those features could be merged into the main project so we can use them?

**Comment by Franiac** [comment]
I'll look into them... The date thingy is incomplete and the timestamp thingy is not well implemented in some areas. That's the general problem with PR's. Most of the time you're faster if you just do it yourself. That sounds absolutely egoistic and like an asshole but PR's that you can just merge are very rare, unfortunately.
