### ISSUE TITLE
Download task ended with an error!

### ISSUE THREAD

**Issue by Shirkyyy** [Franiac/TwitchLeecher#632]
Hello dude ! I'm currently using your program to download some VOD, but i get a lot of error while doing so ... 
Is there something i did wrong ? 

Full log from failed download : https://textuploader.com/takc6

![image](https://user-images.githubusercontent.com/88582028/128599493-7485e36f-118b-44df-854a-959b42ca30a5.png)

**Comment by Shirkyyy** [comment]
Tried the same with a different temp folder on another drive, but same result
New log : https://textuploader.com/takh2

**Comment by Franiac** [comment]
If the remote host closes the connection it is exactly that: Twitch decides that they don't want to play fair game anymore.

All jokes aside: These errors come and go, it may be an instability issue of their servers or whatever. The error is on Twitches side so there is nothing I can do about it, unfortunately.
