### ISSUE TITLE
Feature Request: Mass Download, Audio Format Download.

### ISSUE THREAD

**Issue by axel9546** [Franiac/TwitchLeecher#634]
Hi! I wanted to suggest, If it would be possible, to make 2 new feature:
- **Mass Download**: After we select twitch ID, select date range, select the output format (audio or video), and search for the vods, with a button, we can download all avaiable videos, without the need to download each one, from the list.
- **Audio Format Download**: Would be possible to download the vods in MP3 or AAC format, even without conversion, but ready into an audio format? Every time I download a video, I have to export it with an external software. Would be amazing if we can just download audio, or have a feature which does give only an audio file.

**Comment by Franiac** [comment]
See #518 

Audio only is already there. Twitch does not support it for every VOD, though
