### ISSUE TITLE
STRANGE DOWNLOAD ERROR

### ISSUE THREAD

**Issue by M3TT02** [Franiac/TwitchLeecher#639]
![Screenshot (13)](https://user-images.githubusercontent.com/89538551/130830425-fad7ffd7-63f7-41a7-bcfc-ec2790fbf6f8.png)
Hi guys, i download this softwere yesterday and i download same vod. Today i try to download another vod and the program gave me this error. Someone saw how to solve this error?

THX FOR THE HELP <3

**Comment by Franiac** [comment]
A server error 500 is a server-side error. That means something went wrong on Twitches' side. So there's nothing wrong with TL, it just tells you (in this case) that Twitch messed up.
