### ISSUE TITLE
Feature Request: Suspend download and download speed throttle

### ISSUE THREAD

**Issue by serapheus** [Franiac/TwitchLeecher#641]
It would be really useful to have the ability to suspend a download and/or throttle download speed.

I'm not the only one using my household internet and the only time I can really use full download bandwidth is late at night, meaning that as the program is now I can't use it during the day without inconveniencing others in my home. A speed throttle would fix this. But since the downloads can only be canceled not suspended, I can't even run the download in chunks when people are out of the house as often they will get home before the download is complete.

**Comment by Franiac** [comment]
#46
