### ISSUE TITLE
do not save Favourites.

### ISSUE THREAD

**Issue by zedd-0** [Franiac/TwitchLeecher#645]
- open program
- go to the settings
- enter a channel-name
- hit [+]

now i can use the favorite

- close the program
- go in the settings
- check favorite list

--> favorite list is empty.

the app do not save the favorites after closing.

p.s.
your spelling "favourite" (settings) is wrong?
my dictionary mark it red and change it to "favorite"...

thx 4 read

**Comment by Franiac** [comment]
Ever tried hitting the "Save" button? 😄 

"Favorite" is American English, "Favourite" is British English...

**Comment by zedd-0** [comment]
the GUI is a mess...
sry, i have to say this.

thx for the help.

**Comment by Franiac** [comment]
Sorry for not programming a perfect and business-ready GUI for a little side-project in my freetime.

**Comment by zedd-0** [comment]
i do not need a business-ready GUI,
and you do not have to.
a GUI like Win95 is good enough,... for me. :D
(i do not need graphics)

but a little bit 'fail-save' will be nice.
like auto remove spaces
or  auto remove url-links, instant of the pure channel name

these are the tiny thinks, that would male live a little better...


but on the end of the day... i can handle it...

**Comment by Franiac** [comment]
I am aware of that... doesn't give me more time to do stuff...
