### ISSUE TITLE
External video player not working (VLC)

### ISSUE THREAD

**Issue by davepusey** [Franiac/TwitchLeecher#648]
Enabled external video player option, and set path to "C:\Program Files\VideoLAN\VLC\vlc.exe"

Clicking on a search result opens VLC but then nothing happens. The idle VLC interface just sits there. No error messages or warnings appear. No video playback.

Tested in both 1.8.2 and 1.8.4 with identical results.

**Comment by Franiac** [comment]
I will not fix this for VLC. Changing this to m3u8 playlist files corrupts current user preferences. We cannot just switch from urls to m3u8 playlists. Not all video players take a playlist as an input parameter. So this stays as is and we have to hope for the VLC team to fix their stuff.
