### ISSUE TITLE
Converting error

### ISSUE THREAD

**Issue by nebojsapetrovic92** [Franiac/TwitchLeecher#652]
Ok, so the problem i'm having is that when i download a video, it all goes smoothly until the very end when upon the converting part, the program (version 1.8.4) shows me an error and that's it.
Below i will post the download log. Is it anything wrong on my end or something that should be fixed?

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1172292996
Selected Quality: 852x480@30fps
Download Url: https://www.twitch.tv/videos/1172292996
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\Sha\Downloads\20211009_1172292996_Among Us.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1635594648%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1172292996%7D
Signature: 1460b2e7aa9178297ff0a586a0955eb395902ff2
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/chunked/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/720p60/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/720p30/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/480p30/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/audio_only/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/360p30/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/160p30/index-dvr.m3u8

Playlist url for selected quality 852x480@30fps is https://d1m7jfoe9zdc1j.cloudfront.net/07d03e43764d35dde4a5_chilledchaos_44014557021_1633816548/480p30/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2417

Starting parallel video chunk download
Number of video chunks to download: 2417
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74\20211009_1172292996_Among Us.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74\20211009_1172292996_Among Us.ts'...
Command line arguments: -y -i "C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74\20211009_1172292996_Among Us.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Users\Sha\Downloads\20211009_1172292996_Among Us.mp4"

ffmpeg version 4.3.2-2021-02-27-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from 'C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74\20211009_1172292996_Among Us.ts':
Duration: 06:42:47.02, start: 64.018000, bitrate: 1576 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 329 kb/s
Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, unknown/smpte170m/unknown, progressive), 852x480, 30 fps, 30 tbr, 90k tbn, 2k tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'C:\Users\Sha\Downloads\20211009_1172292996_Among Us.mp4':
Metadata:
encoder         : Lavf58.45.100
Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, unknown/smpte170m/unknown, progressive), 852x480, q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 329 kb/s
Stream mapping:
Stream #0:1 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 8051 fps=0.0 q=-1.0 size=   46848kB time=00:04:28.37 bitrate=1430.0kbits/s speed= 537x
frame=16681 fps=16678 q=-1.0 size=   97024kB time=00:09:16.05 bitrate=1429.4kbits/s speed= 556x
frame=25237 fps=16822 q=-1.0 size=  147200kB time=00:14:01.21 bitrate=1433.5kbits/s speed= 561x
frame=33374 fps=16685 q=-1.0 size=  196352kB time=00:18:32.46 bitrate=1445.9kbits/s speed= 556x
frame=41376 fps=16549 q=-1.0 size=  244480kB time=00:22:59.20 bitrate=1452.1kbits/s speed= 552x
frame=49376 fps=16457 q=-1.0 size=  292864kB time=00:27:25.88 bitrate=1457.7kbits/s speed= 549x
frame=57207 fps=16343 q=-1.0 size=  339968kB time=00:31:46.92 bitrate=1460.5kbits/s speed= 545x
frame=64980 fps=16243 q=-1.0 size=  386048kB time=00:36:06.03 bitrate=1460.0kbits/s speed= 541x
frame=72778 fps=16171 q=-1.0 size=  433408kB time=00:40:25.92 bitrate=1463.6kbits/s speed= 539x
frame=80154 fps=16029 q=-1.0 size=  478208kB time=00:44:31.80 bitrate=1466.2kbits/s speed= 534x
frame=87420 fps=15892 q=-1.0 size=  521472kB time=00:48:34.04 bitrate=1466.0kbits/s speed= 530x
frame=94533 fps=15753 q=-1.0 size=  564480kB time=00:52:31.10 bitrate=1467.5kbits/s speed= 525x
frame=101760 fps=15653 q=-1.0 size=  608000kB time=00:56:32.04 bitrate=1468.4kbits/s speed= 522x
frame=109023 fps=15573 q=-1.0 size=  652032kB time=01:00:34.11 bitrate=1469.8kbits/s speed= 519x
frame=116033 fps=15469 q=-1.0 size=  694528kB time=01:04:27.77 bitrate=1471.0kbits/s speed= 516x
frame=122935 fps=15365 q=-1.0 size=  736512kB time=01:08:17.83 bitrate=1472.4kbits/s speed= 512x
frame=129853 fps=15275 q=-1.0 size=  778752kB time=01:12:08.44 bitrate=1473.9kbits/s speed= 509x
frame=136360 fps=15149 q=-1.0 size=  818176kB time=01:15:45.32 bitrate=1474.6kbits/s speed= 505x
frame=143141 fps=15066 q=-1.0 size=  859392kB time=01:19:31.39 bitrate=1475.5kbits/s speed= 502x
frame=149505 fps=14946 q=-1.0 size=  898048kB time=01:23:03.50 bitrate=1476.2kbits/s speed= 498x
frame=155941 fps=14847 q=-1.0 size=  937472kB time=01:26:38.05 bitrate=1477.4kbits/s speed= 495x
frame=162204 fps=14742 q=-1.0 size=  975616kB time=01:30:06.82 bitrate=1478.2kbits/s speed= 491x
frame=168433 fps=14643 q=-1.0 size= 1013504kB time=01:33:34.46 bitrate=1478.8kbits/s speed= 488x
frame=174611 fps=14547 q=-1.0 size= 1051136kB time=01:37:00.39 bitrate=1479.4kbits/s speed= 485x
frame=180740 fps=14456 q=-1.0 size= 1088512kB time=01:40:24.68 bitrate=1480.1kbits/s speed= 482x
frame=186805 fps=14366 q=-1.0 size= 1125376kB time=01:43:46.81 bitrate=1480.5kbits/s speed= 479x
frame=192977 fps=14291 q=-1.0 size= 1163008kB time=01:47:12.57 bitrate=1481.1kbits/s speed= 476x
frame=198868 fps=14202 q=-1.0 size= 1198848kB time=01:50:28.92 bitrate=1481.5kbits/s speed= 473x
frame=204801 fps=14117 q=-1.0 size= 1234944kB time=01:53:46.70 bitrate=1481.9kbits/s speed= 471x
frame=210449 fps=14023 q=-1.0 size= 1269504kB time=01:56:54.99 bitrate=1482.5kbits/s speed= 467x
frame=216018 fps=13930 q=-1.0 size= 1303552kB time=02:00:00.61 bitrate=1483.0kbits/s speed= 464x
frame=221458 fps=13835 q=-1.0 size= 1337088kB time=02:03:01.95 bitrate=1483.8kbits/s speed= 461x
frame=226757 fps=13728 q=-1.0 size= 1369600kB time=02:05:58.57 bitrate=1484.4kbits/s speed= 458x
frame=231660 fps=13613 q=-1.0 size= 1399296kB time=02:08:42.04 bitrate=1484.5kbits/s speed= 454x
frame=236545 fps=13497 q=-1.0 size= 1429248kB time=02:11:24.84 bitrate=1484.9kbits/s speed= 450x
frame=241175 fps=13378 q=-1.0 size= 1457152kB time=02:13:59.16 bitrate=1484.9kbits/s speed= 446x
frame=245763 fps=13249 q=-1.0 size= 1484544kB time=02:16:32.10 bitrate=1484.5kbits/s speed= 442x
frame=250497 fps=13150 q=-1.0 size= 1513216kB time=02:19:09.93 bitrate=1484.6kbits/s speed= 438x
frame=255107 fps=13049 q=-1.0 size= 1541120kB time=02:21:43.59 bitrate=1484.6kbits/s speed= 435x
frame=259525 fps=12939 q=-1.0 size= 1567744kB time=02:24:10.83 bitrate=1484.6kbits/s speed= 431x
frame=264113 fps=12845 q=-1.0 size= 1595648kB time=02:26:43.77 bitrate=1484.8kbits/s speed= 428x
frame=268538 fps=12750 q=-1.0 size= 1622784kB time=02:29:11.29 bitrate=1485.1kbits/s speed= 425x
frame=272638 fps=12644 q=-1.0 size= 1647872kB time=02:31:27.91 bitrate=1485.4kbits/s speed= 421x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\Sha\Downloads\20211009_1172292996_Among Us.mp4: No space left on device
frame=275926 fps=12504 q=-1.0 Lsize= 1667840kB time=02:33:17.52 bitrate=1485.5kbits/s speed= 417x
video:1322556kB audio:348231kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Sha\AppData\Local\Temp\TL_1085f6da-68c4-4c33-84b8-9b80aaff7f74'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
> Error writing trailer of C:\Users\Sha\Downloads\20211009_1172292996_Among Us.mp4: No space left on device

😄

**Comment by Franiac** [comment]
Nobody is laughing at anything. I just wanted to point out the needle in the hay stack. And sorry, that message is not made up by TL, that comes directly from FFMPEG.exe (the external tool that TL uses for conversion) trying to convert your video. So either ffmpeg is lying (which I don't believe) or you definitely have not enough sapce on your C:\ drive.

**Comment by Franiac** [comment]
And I just checked the video... we are talking about a nearly 7 hour long video broadcasted at 6000kbit/s.

That a good 20GB of download, and if you convert the video with ffmpeg to mp4, that adds another 20GB + overhead to the calculation (temporarily). So it could very well be that your 50GB of space aren't as much as you might think.
