### ISSUE TITLE
Uninstalling Twitch Leecher 1.8.4 not working

### ISSUE THREAD

**Issue by BWayzH** [Franiac/TwitchLeecher#659]
I can't found TL.msi
- [x] Windows Installer not working ![image](https://user-images.githubusercontent.com/90978624/146066511-542da44b-d405-4bc1-b5b5-7641b7cd5583.jpeg)![image](https://user-images.githubusercontent.com/90978624/146066562-f86dc9be-280e-4794-bb2c-210e30fcf44f.jpeg)![image](https://user-images.githubusercontent.com/90978624/146066595-aeb985d8-5c04-426f-920a-0b3513627354.jpeg)![image](https://user-images.githubusercontent.com/90978624/146066656-7083f0a3-dcd5-415f-9565-7724639add02.jpeg)![image](https://user-images.githubusercontent.com/90978624/146066680-f3f189da-869c-4c3c-88d8-f3837c8511b7.jpeg)

**Comment by Franiac** [comment]
There are 3 possibilities:

1. An anti virus software deleted the TL.msi from the Windows package cache (which holds installers for the sole purpose of uninstalling). This could happen if the anti virus software is bad and interprets the unsigned .msi file as hostile (which it is not).
2. You have some kind of cleanup tool running that (wrongly) "cleans up" the Windows package cache (some do, which is stupid)
3. You or something else accidentally deleted the package cache files

Either way, it's not possible that TL itself deletes its installer package cache. The package cache is managed by the Windows installer system. If files get deleted from there, applications are not able to uninstall anymore obviously.
