### ISSUE TITLE
idk what to do everytime i try to dowload it works but after the converting it just gives m é an error can anybody help thx 

### ISSUE THREAD

**Issue by JustForFunLP** [Franiac/TwitchLeecher#667]
ok so i use the latest version 1.8.4 this is the link i use https://www.twitch.tv/videos/1251775835 i have windows 10 64 bit version on my laptop and this is the error log i get everytime.....so i tryed to download a video from twitch works fine but heres comes the problem after the download it beginns to convert the media and when thats done i get an error 

this is the complete Log from Twitch Leecher version 1.8.4

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1252986816
Selected Quality: 1920x1080@59fps (Source)
Download Url: https://www.twitch.tv/videos/1252986816
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\samue\Downloads\20220104_1252986816_Crab Game.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1641498270%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1252986816%7D
Signature: 61867814370e79d43523626b1048fa455509926f
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/index-dvr.m3u8
https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/audio_only/index-dvr.m3u8

Playlist url for selected quality 1920x1080@59fps (Source) is https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1269

Starting parallel video chunk download
Number of video chunks to download: 1269
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/979.ts' failed! Trying again in 20s

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/267.ts' failed! Trying again in 20s
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/558.ts' failed! Trying again in 20s

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/842.ts' failed! Trying again in 20s
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/700.ts' failed! Trying again in 20s

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/138.ts' failed! Trying again in 20s

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/1261.ts' failed! Trying again in 20s
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/400.ts' failed! Trying again in 20s
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/e91696f724c620191850_cubycake_44280478540_1641327267/chunked/1115.ts' failed! Trying again in 20s
System.Net.WebException: Timeout für den Vorgang wurde überschritten.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass56_0.<DownloadParts>b__0(VodPlaylistPart part, ParallelLoopState loopState)

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8\20220104_1252986816_Crab Game.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8\20220104_1252986816_Crab Game.ts'...
Command line arguments: -y -i "C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8\20220104_1252986816_Crab Game.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Users\samue\Downloads\20220104_1252986816_Crab Game.mp4"

ffmpeg version 4.3.2-2021-02-27-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from 'C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8\20220104_1252986816_Crab Game.ts':
Duration: 03:31:24.65, start: 64.018000, bitrate: 6376 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 169 kb/s
Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 90k tbn, 120 tbc
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'C:\Users\samue\Downloads\20220104_1252986816_Crab Game.mp4':
Metadata:
encoder         : Lavf58.45.100
Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 90k tbn, 90k tbc
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 169 kb/s
Stream mapping:
Stream #0:1 -> #0:0 (copy)
Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 4782 fps=0.0 q=-1.0 size=   59904kB time=00:01:19.68 bitrate=6158.8kbits/s speed= 159x
frame= 5800 fps=5710 q=-1.0 size=   72704kB time=00:01:36.66 bitrate=6161.6kbits/s speed=95.2x
frame= 7416 fps=4893 q=-1.0 size=   92928kB time=00:02:03.60 bitrate=6158.8kbits/s speed=81.5x
frame=11418 fps=5633 q=-1.0 size=  143360kB time=00:03:10.29 bitrate=6171.6kbits/s speed=93.9x
frame=11485 fps=4518 q=-1.0 size=  144128kB time=00:03:11.42 bitrate=6168.0kbits/s speed=75.3x
frame=15494 fps=5093 q=-1.0 size=  194304kB time=00:04:18.21 bitrate=6164.3kbits/s speed=84.9x
frame=18381 fps=5188 q=-1.0 size=  230400kB time=00:05:06.34 bitrate=6161.1kbits/s speed=86.5x
frame=19075 fps=4718 q=-1.0 size=  239104kB time=00:05:17.90 bitrate=6161.3kbits/s speed=78.6x
frame=22561 fps=4966 q=-1.0 size=  282880kB time=00:06:16.02 bitrate=6162.8kbits/s speed=82.8x
frame=24361 fps=4827 q=-1.0 size=  305664kB time=00:06:46.01 bitrate=6167.2kbits/s speed=80.4x
frame=29164 fps=5257 q=-1.0 size=  365568kB time=00:08:06.05 bitrate=6161.3kbits/s speed=87.6x
frame=34484 fps=5702 q=-1.0 size=  432384kB time=00:09:34.72 bitrate=6163.2kbits/s speed=  95x
frame=37667 fps=5753 q=-1.0 size=  473088kB time=00:10:29.41 bitrate=6157.3kbits/s speed=96.1x
frame=42713 fps=6061 q=-1.0 size=  536576kB time=00:11:53.53 bitrate=6160.3kbits/s speed= 101x
frame=46822 fps=6200 q=-1.0 size=  588032kB time=00:13:02.03 bitrate=6159.8kbits/s speed= 104x
frame=51574 fps=6405 q=-1.0 size=  647680kB time=00:14:21.20 bitrate=6160.9kbits/s speed= 107x
frame=56962 fps=6660 q=-1.0 size=  715264kB time=00:15:51.01 bitrate=6161.2kbits/s speed= 111x
frame=59722 fps=6591 q=-1.0 size=  749824kB time=00:16:37.01 bitrate=6161.0kbits/s speed= 110x
frame=64447 fps=6740 q=-1.0 size=  808960kB time=00:17:55.75 bitrate=6160.3kbits/s speed= 113x
frame=70331 fps=6990 q=-1.0 size=  882944kB time=00:19:33.84 bitrate=6161.9kbits/s speed= 117x
frame=73743 fps=6982 q=-1.0 size=  925696kB time=00:20:30.69 bitrate=6161.8kbits/s speed= 117x
frame=79672 fps=7203 q=-1.0 size=  999936kB time=00:22:09.51 bitrate=6161.3kbits/s speed= 120x
frame=85185 fps=7367 q=-1.0 size= 1069056kB time=00:23:41.39 bitrate=6161.3kbits/s speed= 123x
frame=88454 fps=7332 q=-1.0 size= 1110016kB time=00:24:35.88 bitrate=6161.2kbits/s speed= 122x
frame=94583 fps=7528 q=-1.0 size= 1187072kB time=00:26:18.02 bitrate=6162.4kbits/s speed= 126x
frame=99982 fps=7653 q=-1.0 size= 1254656kB time=00:27:48.01 bitrate=6161.9kbits/s speed= 128x
frame=106466 fps=7849 q=-1.0 size= 1336064kB time=00:29:36.06 bitrate=6162.5kbits/s speed= 131x
frame=112808 fps=8021 q=-1.0 size= 1415424kB time=00:31:21.79 bitrate=6161.8kbits/s speed= 134x
frame=115782 fps=7949 q=-1.0 size= 1452800kB time=00:32:11.34 bitrate=6162.2kbits/s speed= 133x
frame=122062 fps=8102 q=-1.0 size= 1531648kB time=00:33:56.01 bitrate=6162.7kbits/s speed= 135x
frame=127698 fps=8204 q=-1.0 size= 1602304kB time=00:35:29.94 bitrate=6162.6kbits/s speed= 137x
frame=131939 fps=8213 q=-1.0 size= 1655552kB time=00:36:40.61 bitrate=6162.9kbits/s speed= 137x
frame=138061 fps=8334 q=-1.0 size= 1732352kB time=00:38:22.65 bitrate=6163.1kbits/s speed= 139x
frame=143340 fps=8399 q=-1.0 size= 1798400kB time=00:39:50.63 bitrate=6162.6kbits/s speed= 140x
frame=144925 fps=8250 q=-1.0 size= 1818112kB time=00:40:17.04 bitrate=6162.1kbits/s speed= 138x
frame=151126 fps=8365 q=-1.0 size= 1895936kB time=00:42:00.42 bitrate=6162.3kbits/s speed= 140x
frame=155277 fps=8363 q=-1.0 size= 1948160kB time=00:43:09.61 bitrate=6162.8kbits/s speed= 139x
frame=161248 fps=8457 q=-1.0 size= 2022912kB time=00:44:49.10 bitrate=6162.5kbits/s speed= 141x
frame=167416 fps=8556 q=-1.0 size= 2100224kB time=00:46:31.91 bitrate=6162.5kbits/s speed= 143x
frame=170312 fps=8487 q=-1.0 size= 2136832kB time=00:47:20.19 bitrate=6163.3kbits/s speed= 142x
frame=176263 fps=8570 q=-1.0 size= 2211072kB time=00:48:59.34 bitrate=6162.3kbits/s speed= 143x
frame=182200 fps=8648 q=-1.0 size= 2285824kB time=00:50:38.31 bitrate=6163.1kbits/s speed= 144x
frame=184794 fps=8568 q=-1.0 size= 2318080kB time=00:51:21.55 bitrate=6162.4kbits/s speed= 143x
frame=191026 fps=8656 q=-1.0 size= 2396416kB time=00:53:05.40 bitrate=6162.9kbits/s speed= 144x
frame=195604 fps=8666 q=-1.0 size= 2453760kB time=00:54:21.71 bitrate=6162.8kbits/s speed= 145x
frame=199211 fps=8635 q=-1.0 size= 2499072kB time=00:55:21.83 bitrate=6163.0kbits/s speed= 144x
frame=205225 fps=8705 q=-1.0 size= 2574592kB time=00:57:02.05 bitrate=6163.3kbits/s speed= 145x
frame=207799 fps=8630 q=-1.0 size= 2606592kB time=00:57:44.96 bitrate=6162.6kbits/s speed= 144x
frame=211970 fps=8622 q=-1.0 size= 2659072kB time=00:58:54.46 bitrate=6163.1kbits/s speed= 144x
frame=217807 fps=8683 q=-1.0 size= 2732032kB time=01:00:31.76 bitrate=6162.5kbits/s speed= 145x
frame=221272 fps=8648 q=-1.0 size= 2775552kB time=01:01:29.51 bitrate=6162.7kbits/s speed= 144x
frame=226658 fps=8688 q=-1.0 size= 2843136kB time=01:02:59.28 bitrate=6162.8kbits/s speed= 145x
frame=231467 fps=8704 q=-1.0 size= 2903552kB time=01:04:19.43 bitrate=6163.1kbits/s speed= 145x
frame=233146 fps=8605 q=-1.0 size= 2924544kB time=01:04:47.40 bitrate=6162.9kbits/s speed= 143x
frame=238856 fps=8656 q=-1.0 size= 2996224kB time=01:06:22.59 bitrate=6163.1kbits/s speed= 144x
frame=242388 fps=8627 q=-1.0 size= 3040512kB time=01:07:21.42 bitrate=6163.1kbits/s speed= 144x
frame=247810 fps=8664 q=-1.0 size= 3108608kB time=01:08:51.79 bitrate=6163.4kbits/s speed= 144x
frame=253628 fps=8715 q=-1.0 size= 3181312kB time=01:10:28.77 bitrate=6162.8kbits/s speed= 145x
frame=256806 fps=8675 q=-1.0 size= 3221248kB time=01:11:21.72 bitrate=6163.0kbits/s speed= 145x
frame=262776 fps=8729 q=-1.0 size= 3296256kB time=01:13:01.22 bitrate=6163.3kbits/s speed= 146x
frame=268692 fps=8779 q=-1.0 size= 3370240kB time=01:14:39.82 bitrate=6163.0kbits/s speed= 146x
frame=270338 fps=8691 q=-1.0 size= 3390976kB time=01:15:07.26 bitrate=6163.1kbits/s speed= 145x
frame=276482 fps=8747 q=-1.0 size= 3468032kB time=01:16:49.66 bitrate=6163.2kbits/s speed= 146x
frame=280994 fps=8752 q=-1.0 size= 3524608kB time=01:18:04.88 bitrate=6163.1kbits/s speed= 146x
frame=285715 fps=8762 q=-1.0 size= 3583744kB time=01:19:23.56 bitrate=6163.0kbits/s speed= 146x
frame=291605 fps=8808 q=-1.0 size= 3657728kB time=01:21:01.73 bitrate=6163.2kbits/s speed= 147x
frame=294097 fps=8750 q=-1.0 size= 3688960kB time=01:21:43.25 bitrate=6163.2kbits/s speed= 146x
frame=299542 fps=8781 q=-1.0 size= 3757312kB time=01:23:14.02 bitrate=6163.3kbits/s speed= 146x
frame=305402 fps=8823 q=-1.0 size= 3830784kB time=01:24:51.69 bitrate=6163.3kbits/s speed= 147x
frame=307917 fps=8769 q=-1.0 size= 3862272kB time=01:25:33.58 bitrate=6163.3kbits/s speed= 146x
frame=313582 fps=8805 q=-1.0 size= 3933440kB time=01:27:08.03 bitrate=6163.5kbits/s speed= 147x
frame=318676 fps=8824 q=-1.0 size= 3997184kB time=01:28:32.91 bitrate=6163.3kbits/s speed= 147x
frame=321273 fps=8774 q=-1.0 size= 4029952kB time=01:29:16.20 bitrate=6163.6kbits/s speed= 146x
frame=326766 fps=8804 q=-1.0 size= 4098560kB time=01:30:47.74 bitrate=6163.2kbits/s speed= 147x
frame=330376 fps=8783 q=-1.0 size= 4143872kB time=01:31:47.90 bitrate=6163.3kbits/s speed= 146x
frame=335203 fps=8794 q=-1.0 size= 4204544kB time=01:33:08.35 bitrate=6163.5kbits/s speed= 147x
frame=340288 fps=8812 q=-1.0 size= 4268288kB time=01:34:33.10 bitrate=6163.4kbits/s speed= 147x
frame=342862 fps=8765 q=-1.0 size= 4300800kB time=01:35:16.03 bitrate=6163.7kbits/s speed= 146x
frame=348679 fps=8801 q=-1.0 size= 4373504kB time=01:36:52.94 bitrate=6163.4kbits/s speed= 147x
frame=354870 fps=8846 q=-1.0 size= 4451328kB time=01:38:36.13 bitrate=6163.7kbits/s speed= 147x
frame=356749 fps=8783 q=-1.0 size= 4474624kB time=01:39:07.45 bitrate=6163.3kbits/s speed= 146x
frame=362902 fps=8826 q=-1.0 size= 4551936kB time=01:40:50.02 bitrate=6163.5kbits/s speed= 147x
frame=367660 fps=8832 q=-1.0 size= 4611584kB time=01:42:09.30 bitrate=6163.5kbits/s speed= 147x
frame=371131 fps=8809 q=-1.0 size= 4655104kB time=01:43:07.15 bitrate=6163.5kbits/s speed= 147x
frame=377182 fps=8848 q=-1.0 size= 4730880kB time=01:44:48.02 bitrate=6163.4kbits/s speed= 148x
frame=380236 fps=8815 q=-1.0 size= 4769280kB time=01:45:38.90 bitrate=6163.5kbits/s speed= 147x
frame=386050 fps=8846 q=-1.0 size= 4841984kB time=01:47:15.79 bitrate=6163.3kbits/s speed= 147x
frame=392194 fps=8884 q=-1.0 size= 4919296kB time=01:48:58.19 bitrate=6163.6kbits/s speed= 148x
frame=394468 fps=8835 q=-1.0 size= 4947712kB time=01:49:36.10 bitrate=6163.5kbits/s speed= 147x
frame=400468 fps=8870 q=-1.0 size= 5023232kB time=01:51:16.11 bitrate=6163.8kbits/s speed= 148x
frame=405718 fps=8888 q=-1.0 size= 5088768kB time=01:52:43.60 bitrate=6163.5kbits/s speed= 148x
frame=408637 fps=8855 q=-1.0 size= 5125376kB time=01:53:32.26 bitrate=6163.5kbits/s speed= 148x
frame=414155 fps=8878 q=-1.0 size= 5194752kB time=01:55:04.21 bitrate=6163.7kbits/s speed= 148x
frame=417862 fps=8861 q=-1.0 size= 5241088kB time=01:56:06.01 bitrate=6163.5kbits/s speed= 148x
frame=421560 fps=8846 q=-1.0 size= 5301504kB time=01:57:34.63 bitrate=6156.2kbits/s speed= 148x
frame=426805 fps=8862 q=-1.0 size= 5376512kB time=01:59:25.31 bitrate=6146.9kbits/s speed= 149x
frame=428934 fps=8815 q=-1.0 size= 5404928kB time=02:00:07.42 bitrate=6143.3kbits/s speed= 148x
frame=434358 fps=8836 q=-1.0 size= 5480192kB time=02:01:58.72 bitrate=6134.1kbits/s speed= 149x
frame=439749 fps=8855 q=-1.0 size= 5554688kB time=02:03:48.65 bitrate=6125.5kbits/s speed= 150x
frame=441779 fps=8807 q=-1.0 size= 5589248kB time=02:04:39.48 bitrate=6121.7kbits/s speed= 149x
frame=447650 fps=8836 q=-1.0 size= 5662976kB time=02:06:17.34 bitrate=6122.3kbits/s speed= 150x
frame=452088 fps=8836 q=-1.0 size= 5718528kB time=02:07:31.30 bitrate=6122.6kbits/s speed= 150x
frame=455100 fps=8809 q=-1.0 size= 5756160kB time=02:08:21.52 bitrate=6122.7kbits/s speed= 149x
frame=460873 fps=8835 q=-1.0 size= 5828608kB time=02:09:57.71 bitrate=6123.3kbits/s speed= 149x
frame=463983 fps=8810 q=-1.0 size= 5867776kB time=02:10:49.55 bitrate=6123.8kbits/s speed= 149x
frame=469552 fps=8832 q=-1.0 size= 5937408kB time=02:12:22.37 bitrate=6124.0kbits/s speed= 149x
frame=475300 fps=8857 q=-1.0 size= 6009600kB time=02:13:58.18 bitrate=6124.6kbits/s speed= 150x
frame=477548 fps=8817 q=-1.0 size= 6037760kB time=02:14:35.64 bitrate=6124.8kbits/s speed= 149x
frame=483447 fps=8844 q=-1.0 size= 6111744kB time=02:16:13.95 bitrate=6125.2kbits/s speed= 150x
frame=489308 fps=8870 q=-1.0 size= 6185216kB time=02:17:51.63 bitrate=6125.7kbits/s speed= 150x
frame=491832 fps=8835 q=-1.0 size= 6216960kB time=02:18:33.70 bitrate=6125.9kbits/s speed= 149x
frame=497665 fps=8860 q=-1.0 size= 6290176kB time=02:20:10.94 bitrate=6126.4kbits/s speed= 150x
frame=501795 fps=8854 q=-1.0 size= 6341888kB time=02:21:19.76 bitrate=6126.7kbits/s speed= 150x
frame=505857 fps=8846 q=-1.0 size= 6392832kB time=02:22:27.47 bitrate=6127.0kbits/s speed= 149x
frame=511950 fps=8875 q=-1.0 size= 6469376kB time=02:24:09.00 bitrate=6127.5kbits/s speed= 150x
frame=514551 fps=8844 q=-1.0 size= 6501888kB time=02:24:52.35 bitrate=6127.6kbits/s speed= 149x
frame=519921 fps=8860 q=-1.0 size= 6569216kB time=02:26:21.86 bitrate=6128.0kbits/s speed= 150x
frame=525669 fps=8882 q=-1.0 size= 6641408kB time=02:27:57.67 bitrate=6128.5kbits/s speed= 150x
frame=528385 fps=8852 q=-1.0 size= 6675456kB time=02:28:42.94 bitrate=6128.6kbits/s speed= 149x
frame=533601 fps=8865 q=-1.0 size= 6740736kB time=02:30:09.85 bitrate=6128.9kbits/s speed= 150x
frame=536730 fps=8844 q=-1.0 size= 6779904kB time=02:31:02.01 bitrate=6129.0kbits/s speed= 149x
frame=540567 fps=8834 q=-1.0 size= 6828032kB time=02:32:05.95 bitrate=6129.2kbits/s speed= 149x
frame=546135 fps=8852 q=-1.0 size= 6897920kB time=02:33:38.77 bitrate=6129.6kbits/s speed= 149x
frame=549281 fps=8831 q=-1.0 size= 6937344kB time=02:34:31.18 bitrate=6129.8kbits/s speed= 149x
frame=553696 fps=8831 q=-1.0 size= 6992640kB time=02:35:44.78 bitrate=6130.0kbits/s speed= 149x
frame=559244 fps=8848 q=-1.0 size= 7062272kB time=02:37:17.22 bitrate=6130.4kbits/s speed= 149x
frame=562435 fps=8828 q=-1.0 size= 7102208kB time=02:38:10.41 bitrate=6130.5kbits/s speed= 149x
frame=568321 fps=8850 q=-1.0 size= 7175680kB time=02:39:48.54 bitrate=6130.6kbits/s speed= 149x
frame=573436 fps=8861 q=-1.0 size= 7242240kB time=02:41:20.29 bitrate=6128.8kbits/s speed= 150x
frame=575538 fps=8825 q=-1.0 size= 7268608kB time=02:41:55.32 bitrate=6128.9kbits/s speed= 149x
frame=581134 fps=8842 q=-1.0 size= 7338496kB time=02:43:28.59 bitrate=6129.0kbits/s speed= 149x
frame=585058 fps=8831 q=-1.0 size= 7387904kB time=02:44:34.02 bitrate=6129.4kbits/s speed= 149x
frame=589672 fps=8833 q=-1.0 size= 7445504kB time=02:45:50.91 bitrate=6129.4kbits/s speed= 149x
av_interleaved_write_frame(): No space left on device
Error writing trailer of C:\Users\samue\Downloads\20220104_1252986816_Crab Game.mp4: No space left on device
frame=592490 fps=8832 q=-1.0 Lsize= 7480832kB time=02:46:37.86 bitrate=6129.6kbits/s speed= 149x
video:7284720kB audio:198973kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\samue\AppData\Local\Temp\TL_69df610d-0a61-419e-9bbf-f3cb4f6945c8'... done!

Download task ended with an error!

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ApplicationException: An error occured while converting the video!
   bei TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.ApplicationException: An error occured while converting the video!
   bei TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()<---

can anyone solve this ?
PS i'm sorry for the error log language it is because i am german

**Comment by Franiac** [comment]
> Error writing trailer of C:\Users\samue\Downloads\20220104_1252986816_Crab Game.mp4: No space left on device

Your SSD/HDD does not have enough space left
