### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by GoodNames18** [Franiac/TwitchLeecher#669]
every time i try to download video from xqcow it say error after done download

![17-59-40 January-10-2022](https://user-images.githubusercontent.com/41176431/148747616-17f80f26-3f4c-4803-ac5d-7bee0ee17882.jpg)

**Comment by Franiac** [comment]
Please provide the download log as described [here](https://github.com/Franiac/TwitchLeecher#support--issues)

**Comment by GoodNames18** [comment]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.8.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1258540829
Selected Quality: 1920x1080@59fps (Source)
Download Url: https://www.twitch.tv/videos/1258540829
Crop Start: Yes (00:00:00)
Crop End: Yes (00:05:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\verge\Videos\xQcOW GETTING EVERY SINGLE PERSON MALD ON THE INTERNET OVER LOOKING AT DRAWINGS. CHALLENGE_ JOURNALIST DIFFICULTY LULW. 5R4355654646465435513RFREGNoPixel GTA RP 052115_start-000000_end-000500.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1641926238%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1258540829%7D
Signature: e349ce133c71817f76561d3a7065b52b6ce1584e
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/chunked/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/720p60/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/480p30/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/audio_only/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/360p30/index-dvr.m3u8
https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@59fps (Source) is https://d1m7jfoe9zdc1j.cloudfront.net/89f280dfe5fc417ce908_xqcow_39333096185_1641763267/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 3891

Starting parallel video chunk download
Number of video chunks to download: 30
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26\xQcOW GETTING EVERY SINGLE PERSON MALD ON THE INTERNET OVER LOOKING AT DRAWINGS. CHALLENGE_ JOURNALIST DIFFICULTY LULW. 5R4355654646465435513RFREGNoPixel GTA RP 052115_start-000000_end-000500.ts'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26\xQcOW GETTING EVERY SINGLE PERSON MALD ON THE INTERNET OVER LOOKING AT DRAWINGS. CHALLENGE_ JOURNALIST DIFFICULTY LULW. 5R4355654646465435513RFREGNoPixel GTA RP 052115_start-000000_end-000500.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26\xQcOW GETTING EVERY SINGLE PERSON MALD ON THE INTERNET OVER LOOKING AT DRAWINGS. CHALLENGE_ JOURNALIST DIFFICULTY LULW. 5R4355654646465435513RFREGNoPixel GTA RP 052115_start-000000_end-000500.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, VodPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass50_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
The temporary folder path is too long (>256 characters)

> C:\Users\verge\AppData\Local\Temp\TL_fe6e4ce1-d52c-45cc-b73e-9a99635fda26\xQcOW GETTING EVERY SINGLE PERSON MALD ON THE INTERNET OVER LOOKING AT DRAWINGS. CHALLENGE_ JOURNALIST DIFFICULTY LULW. 5R4355654646465435513RFREGNoPixel GTA RP 052115_start-000000_end-000500.ts

Do not use the title in the filename template or choose a different temporary folder that is shorter (e.g. "C:\Streams\").

#663 will point that out in the future.

**Comment by GoodNames18** [comment]
anyway i can dm you?
