### ISSUE TITLE
Constant errors when trying to download any VOD to any storage drive

### ISSUE THREAD

**Issue by Rudylmaolive** [Franiac/TwitchLeecher#671]
Constant errors when trying to download any VOD to any storage drive

Heya! I currently rely on TwitchLeecher for my entire job and right now, whenever I download a VOD i just get an Error message, no matter what the file size is, no matter what the drive, or VOD is, I just get an error message. Im using Windows 11 Pro.

PC Specification:
AMD Ryzen 9 3900XT
32GB DDR4 Ram
RTX 3080 GPU
2 External Drives 1 TB drives
2 Internal 1 TB drives

![image](https://user-images.githubusercontent.com/97810123/149658150-b7088163-1eac-4965-9fb3-ba49aef55f87.png)

**Comment by Franiac** [comment]
Please provide the download logs.
