### ISSUE TITLE
About the download being disabled if stream is still live.

### ISSUE THREAD

**Issue by Pozolo** [Franiac/TwitchLeecher#676]
I'm wondering if this is because the changes on twitch or a deliberate decision. Personally i download the stream of an art streamer that keeps the VOD up until the end of the stream before deleting it, that way you can check the work of past hours without him taking a warning DMCA (he has music on). With this new change I lose the ability to download it before he deletes the VOD. Is it possible to have that feature back?
Thank you.

**Comment by Franiac** [comment]
This is a deliberate decision. And I want to make the following points clear:

1. If the streamer decides to delete his streams, you should not have them either
2. If he is an art streamer and at the same time uses copyright protected media on his stream, he contradicts himself or is basically a hypocrite. Probably he would be pissed if someone stole and used his art, right?
3. I don't provide the means to download illegal streams (which they are, when downloaded and containing copyright protected media).

Creating art while using others art illegally... cannot support that, sorry.

How come I react so sensitive? I am a musician with an album on the market. So no, that "feature" won't come back ever again..
