### ISSUE TITLE
Cyrillic titles after 2.0.1 update shows in wrong encoding.

### ISSUE THREAD

**Issue by alex-wazovskiy** [Franiac/TwitchLeecher#677]
Cyrillic titles after 2.0.1 update shows in wrong encoding.
How it should be:
`Elysium RP 🦋 И что нам с этим делать? - 015`
How it shows in TL after update:
`Elysium RP рџ¦‹ Р С‡С‚Рѕ РЅР°Рј СЃ СЌС‚РёРј РґРµР»Р°С‚СЊ_ - 015`
Online encoding converter service recognized this one as WINDOWS-1251 encoding.

Before update there was no problem with Cyrillic titles.

**Comment by Franiac** [comment]
That seems to be an issue with the new Helix API returning different data. Please provide a video link so I can test.

**Comment by alex-wazovskiy** [comment]
https://www.twitch.tv/videos/1278841441?filter=archives&sort=time

**Comment by Franiac** [comment]
I will probably roll out 2.0.2 tomorrow with this fix. But I want to wait a little bit more in case something other comes up until then.
