### ISSUE TITLE
Question Re: New "Features"

### ISSUE THREAD

**Issue by jonas1015119** [Franiac/TwitchLeecher#678]
**"The download button in the search result view is desabled if the video is currently streamed live"**

Is this due to the API or just a random change on your side? 
Because its terrible either way, some people might want this as an option for some reason, but I honestly dont see why. 
Saving a stream while its still going because the vod might get deleted or because you want to get a section up fast is incredibly important, imagine having to wait an entire day to download something from a 24 hours stream! For long broadcasts being able to download chunks while its still going is essential.

**Comment by Franiac** [comment]
Discussed [HERE](https://github.com/Franiac/TwitchLeecher/issues/673#issuecomment-1024701157) and [HERE](https://github.com/Franiac/TwitchLeecher/issues/676#issuecomment-1024514727)
