### ISSUE TITLE
An error occurred during installation 

### ISSUE THREAD

**Issue by ttwk8198** [Franiac/TwitchLeecher#680]
![Untitled1](https://user-images.githubusercontent.com/59794930/151688091-676fef3f-d19b-4010-bf55-527be730b915.png)

Hi, I just downloaded the latest 2.0.2 version from the link provided here, but I am unable to install it and the error simply says "Your system has not been modified. Click "Close" to exit the Setup Wizard". What does that even mean and how do I solve it? Thank you.

**Comment by Franiac** [comment]
Are you familiar with running something in cmd.exe?

You can run "TwitchLeecher_2.0.2.exe -l log.txt" in order to get 2 logfiles from the installation process. Post the contents here and maybe I can help.

**Comment by ttwk8198** [comment]
It seems like the problem resolved itself... Sorry I could not provide the log to find out what the problem was. All I did was shutdown my pc, go to bed and it successfully installed next morning. Tried restarting pc before that, but that didn't work. Anyway, thank you for the help and I really appreciate you creating this program. This is honestly the best twitch vod downloader.
