### ISSUE TITLE
Cant download live streams

### ISSUE THREAD

**Issue by skyfox1977** [Franiac/TwitchLeecher#681]
- The download button in the search result view is disabled if the video is currently streamed live

So, this is the absolute worst thing in the new version and need to be reverted or make it an option to still download the already streamed parts as I almost ALWAYS download the beginning of streams while they are still are live to make sure I can watch a whole stream in case the vod gets marked as deleted during a stream. I need to get back to the older version again JUST because of this.

**Comment by Franiac** [comment]
#673
