### ISSUE TITLE
Can't download from ongoing streams anymore

### ISSUE THREAD

**Issue by mdeutschmann** [Franiac/TwitchLeecher#684]
One "new feature" of 2.0.2 is a serious regression for me.  TL now detects ongoing streams ("LIVE") and refuses to download them.

I frequently download from ongoing streams -- I just use the clipping feature to grab chunks out of the start or middle.  I've gone back to 1.8.4 for now so I can continue doing this.

**Comment by Franiac** [comment]
#673
