### ISSUE TITLE
"An error occured while converting the video"

### ISSUE THREAD

**Issue by Chocolate025** [Franiac/TwitchLeecher#689]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.2

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1287119530
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/1287119530
Crop Start: Yes (00:56:00)
Crop End: Yes (02:56:33)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Users\choco\Desktop\20220204_Mizkif_1287119530.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1644142687%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1287119530%7D
Signature: 4ea3c2ea44cd8a52fdde5da4c8356dd4901eaca4
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/720p60/index-dvr.m3u8'
Playlist for quality '720p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/720p30/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/audio_only/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/360p30/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/160p30/index-dvr.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d1m7jfoe9zdc1j.cloudfront.net/b3144f30d9c724ab745d_mizkif_45409179117_1644012957/chunked/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1966

Starting parallel video chunk download
Number of video chunks to download: 725
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340\20220204_Mizkif_1287119530.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340\20220204_Mizkif_1287119530.ts'...
Command line arguments: -y -ss 10 -i "C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340\20220204_Mizkif_1287119530.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -t 7233 "C:\Users\choco\Desktop\20220204_Mizkif_1287119530.mp4"

ffmpeg version 5.0-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100
Input #0, mpegts, from 'C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340\20220204_Mizkif_1287119530.ts':
Duration: 02:00:50.00, start: 3412.032000, bitrate: 6405 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 164 kb/s
Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 90k tbn
Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
C:\Users\choco\Desktop\20220204_Mizkif_1287119530.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\choco\AppData\Local\Temp\335e6e45f36f4cc28aadea0400dcd340'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while converting the video!
   at TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
> C:\Users\choco\Desktop\20220204_Mizkif_1287119530.mp4: Permission denied

This comes from ffmpeg while trying to convert the video to mp4

[THIS](https://superuser.com/questions/1528624/permission-denied-in-batch-file-for-ffmpeg-windows) suggests to check your anti virus software.

[THIS](https://www.reddit.com/r/ffmpeg/comments/9scm7v/comment/hnbbdbq/?utm_source=share&utm_medium=web2x&context=3) also suggests to check your anti virus software

[THIS](https://www.reddit.com/r/ffmpeg/comments/9scm7v/comment/hookpqe/?utm_source=share&utm_medium=web2x&context=3) suggests that the output folder is too long

It seems ffmpeg is not liked by some anti virus tools, so that would be my first guess. Do you have anything running on your machine that is not only Windows Defender? Putting stuff on Desktop by the help of a console program (ffmpeg.exe) perhaps seems "fishy" to your tool.

**Comment by Chocolate025** [comment]
I have AVG so that could be blocking the download? Would you suggest disabling it or saving it at a different location?

**Comment by Chocolate025** [comment]
After I changed the download location nothing went wrong, thanks for the help and for making this program!
