### ISSUE TITLE
Only able to download half the stream

### ISSUE THREAD

**Issue by FosumFox** [Franiac/TwitchLeecher#69]
I tried to download a specific VoD that was streamed before 2015 that's a highlight, but every time I tried doing it, it'll only download what seems to be the first half and that's it, after that the video breaks and stops.

**Comment by Franiac** [comment]
See #58 

FFMPEG is not error-prone vs dropped frames and other hickups in the source stream. if the streamer had connection issues (a few milliseconds are enough), FFMPEG will refuse to merge the VOD parts correctly.

**Comment by FosumFox** [comment]
It actually seems to be affected by the chunked system, since I had able to download that specific stream and others by the same streamer before when it was just separated by a couple of .flv files, but can no longer and it's not related to FFmpeg or TwitchLeecher, it seems.
