### ISSUE TITLE
Impossible to download a sub-only video

### ISSUE THREAD

**Issue by royal44** [Franiac/TwitchLeecher#694]
Hello,

After downloading the v2.0.2, I connected twice to activate the sub-only support (the star is green) but it's still impossible to download the video I want (https://www.twitch.tv/videos/1291100429). I have the message "This video is sub-only! etc". Tried to relaunch the app, same issue.

Thanks!

**Comment by royal44** [comment]
![image](https://user-images.githubusercontent.com/1247555/153069774-7f1f7054-6234-4438-99d4-4744eb805d2d.png)

**Comment by Franiac** [comment]
This looks weird, indeed. Can you try to disable and enable sub-only support again?

**Comment by Franiac** [comment]
and just to make sure: you are definitely subscribed to that channel, right?

**Comment by Franiac** [comment]
Dammit, I found the error. That's on me, sorry... TL 2.0.3 incoming 😄

**Comment by Franiac** [comment]
So, this bug is fixed, but for you that just means you get another warning with 2.0.3, because you are not subscribed to that channel.

**Comment by royal44** [comment]
Sorry, I'm not a subscriber haha I guess that's why it doesn't... What wat the bug you discovered in this case?
