### ISSUE TITLE
No Genre option in file name save. {genre}

### ISSUE THREAD

**Issue by MrDummyNL** [Franiac/TwitchLeecher#696]
Until 1.8.x version, i can save videos with genre name in it.
But since new version 2.x, it's now removed. The title is kinda useless because it can very long text.

I need only genre name so i can see what genre it has in each video. Other options are good.

Oh, genre is same as category btw. {category} is also good.

Maybe new API has no option for it?

**Comment by Franiac** [comment]
From the release notes:

> Filename wildcards {game} and {fps} have been removed (not available in new API)
