### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by Franiac** [Franiac/TwitchLeecher#7]
Provide a portable version of Twitch Leecher.

-> needs a flag in the code marking it as portable
-> setting should be saved in executing directory instead of %appdata%

**Comment by Franiac** [comment]
With the new update notification and the fact that it needs 3 clicks to upgrade Twitch Leecher with a new installer (run installer -> click upgrade -> done), I decided not to provide a portable version.
On a clean uninstall of TL through MSI I can clean up everything (appdata folder, registry,...). all this would be left behind, if the portable version just got deleted.

**Comment by 0ldi** [comment]
So making a portable version is very difficult for you? I would like to have this, at least in the future.

**Comment by Franiac** [comment]
I don't see any advantage of a portable version. If you install it, everything is where it should be, you have update checks, semi-automated update installers and persistent preferences accross versions. There is no reason why you would not want to install TL.
