### ISSUE TITLE
Error when trying to login in my account & paid VODs

### ISSUE THREAD

**Issue by flijloku** [Franiac/TwitchLeecher#70]
![1111111111](https://cloud.githubusercontent.com/assets/14862821/20100032/e21d4256-a5d4-11e6-98eb-35a0f04d8fe2.JPG)

And if I understand correctly, the paid VOD can download only subscribers? It is not entirely clear from README.md. This is misleading, that everybody can download it.

**Comment by Franiac** [comment]
It is very clear that only subscribers to a channel can actually download the VODs behind the paywall. Everything else would be straight against Twitch TOS and Twitch Leecher would get banned from the API. Twitch Leecher surely does not help anyone with downloading VODs he has not paid for,

As for the error: It seems like Twitch had some problems with their Authentication Servers recently... If Twitch does not even respond with an error message, TL cannot sign you in. Maybe try it again later.

**Comment by flijloku** [comment]
Thank you!
