### ISSUE TITLE
Downloaded and installed TL 2.0.3, I open it and it's just a blank grey screen

### ISSUE THREAD

**Issue by TeamGB** [Franiac/TwitchLeecher#703]
I have downloaded the TL 2.0.3.exe file and installed it as is. 
I open the app and it's just a blank grey background. 
I uninstalled and reinstalled it multiple times and it is still the same issue as shown below:

![Screenshot 2022-02-14 211059](https://user-images.githubusercontent.com/99690560/153947198-278b055b-5049-47a6-9911-70a3950be4c4.jpg)

I also get this error when the app loads up before the blank grey screen:

![Screenshot 2022-02-14 211920](https://user-images.githubusercontent.com/99690560/153948454-9947a2f4-6e3e-4bd2-ac83-3e26822a8682.jpg)

This is the error log:

[01192022_014247_342_AM_error.log](https://github.com/Franiac/TwitchLeecher/files/8064107/01192022_014247_342_AM_error.log)

This error appeared when I had TL 1.8.4 installed but everything within the app worked perfectly fine.

My laptop operating system is Windows 10 64 Bit.

I'm no coder so whatever you can do to help will be much appreciated.

**Comment by Franiac** [comment]
Ok, go to `%appdata%\TwitchLeecher` in your Explorer. There's a file named `runtime.xml`. Please post the contents here. But make sure to remove the Access Tokens first. I am interested in the `<Application>` part of the file.

**Comment by Franiac** [comment]
sorry, incomplete instructions... i meant to open the file in notepad.... but as the error already says... it's empty anyways.

So here's what you do: You delete it 😄 (no joke) and start TL again.

**Comment by TeamGB** [comment]
Deleting it worked. 

It all seems to be working fine now.

Thank you.
