### ISSUE TITLE
Important Question

### ISSUE THREAD

**Issue by Hamza9236** [Franiac/TwitchLeecher#704]
How do I update Twitch Leecher, it's staying at 1.8.4 and I can't download any VODS.

**Comment by Franiac** [comment]
You download The [TL 2.0.3](https://github.com/Franiac/TwitchLeecher/releases/tag/v2.0.3) installer and update? What's the problem?

**Comment by Hamza9236** [comment]
Never mind, I just found the link to get 2.0.3, also, do I have to download
the versions in order, or can I skip from 1.8.4 to 2.0.3?

**Comment by Franiac** [comment]
no, all higher versions are in-place upgrades, no need to install the versions in between.
