### ISSUE TITLE
deletes temp files without merging??

### ISSUE THREAD

**Issue by luckybuzz** [Franiac/TwitchLeecher#705]
hi Franiac and thanks so much for all your hard work.

i read through the 5 most recent pages of closed issues and mine appears to be different from the others.

running version 2.0.3 on Windows 8.1
trying to download streams from https://www.twitch.tv/insomniac_rap

as far as i can tell, it finishes downloading all the chunks, and says it's going to merge them into one file... but then it deletes the temp files without the merge actually happening??  here is the log text:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1283757675
Selected Quality: 360p (640x360)
Download Url: https://www.twitch.tv/videos/1283757675
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: Yes
Output File: C:\Users\isaacq\Downloads\twitchvids\Insomniac_rap\20220201_1283757675_freestyle rhymes, bonus daytime bars.ts
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\isaacq\Downloads\twitchvids\9e558d8594e64695bcbfc3b14dd69aff

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1644981090%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3A464457110%2C%22version%22%3A2%2C%22vod_id%22%3A1283757675%7D
Signature: 14fae7457bf6ba000baf13913c81c1daf7aa7760
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\isaacq\Downloads\twitchvids\9e558d8594e64695bcbfc3b14dd69aff'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '720p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/chunked/index-dvr.m3u8'
Playlist for quality '720p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/720p30/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/audio_only/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/360p30/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/160p30/index-dvr.m3u8'

Playlist url for selected quality '360p (640x360)' is 'https://d1m7jfoe9zdc1j.cloudfront.net/cd8726e73767cb114060_insomniac_rap_45372164941_1643752848/360p30/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 757

Starting parallel video chunk download
Number of video chunks to download: 757
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\isaacq\Downloads\twitchvids\Insomniac_rap\20220201_1283757675_freestyle rhymes, bonus daytime bars.ts'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\isaacq\Downloads\twitchvids\9e558d8594e64695bcbfc3b14dd69aff'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\isaacq\Downloads\twitchvids\Insomniac_rap\20220201_1283757675_freestyle rhymes, bonus daytime bars.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\isaacq\Downloads\twitchvids\Insomniac_rap\20220201_1283757675_freestyle rhymes, bonus daytime bars.ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
> 'C:\Users\isaacq\Downloads\twitchvids\Insomniac_rap\20220201_1283757675_freestyle rhymes, bonus daytime bars.ts

seems like a part of this path is not existing. I am unsure actually if the filename is also a problem. Please check if the path `C:\Users\isaacq\Downloads\twitchvids\Insomniac_rap` actually exists. And as a test, you could go for a very simple filename like `test.ts` or simething, because maybe the colon in the filename is an issue.

Cannot put my finger on it yet...

**Comment by luckybuzz** [comment]
the problem is definitely related to the title of the stream, as it worked fine when i changed my filename template to include just the date and stream ID.  thanks for your quick reply!

**Comment by Franiac** [comment]
hmmm, it seems ffmpeg.exe (the tool that converts the .ts file to .mp4) does not like colons. Windows has no problem with it and TL substitutes illegal characters with an underscore already. Seems that I need another illegal characters list....

**Comment by Franiac** [comment]
so I have tried a lot of things and I cannot replicate this error. I have tried the exact same title you got and I saw you did not even have mp4 conversion enabled. So I don't actually know what the problem on your end was. I will close this as unresolved. Maybe it was just a temporary permission issue and another process (like Explorer) blocked the path.
