### ISSUE TITLE
Login not working new update

### ISSUE THREAD

**Issue by santi-sd** [Franiac/TwitchLeecher#711]
New update makes me (almost unable) to log in.

I just updated to the latest version and I am not able to log into my Twitch account to connect Twitch Leecher.
The login screen is frozen. Except it still functions. But I can't see what's going on. The image attached is what I see. 

When I hit cancel, it shows me what it actually looks like for a split second. By using tab I was able to input my login successfully but not input the security code.

I am running Windows 11 Home 2022-02 Cumulative Update for Windows 11 for x64-based Systems (KB5010414).

Is there anymore information I should provide?

![image](https://user-images.githubusercontent.com/53580086/154753522-1c3310e2-5d9f-4931-8ded-2a9f5069d57c.png)

**Comment by Franiac** [comment]
It does not seem that there is anyone else with the same issue so I must assume, this is something only happening on your machine. Do you have firewalls, av tools, other security software that could prevent loading the login form correctly? I cannot reproduce any of this, unfortunately.
