### ISSUE TITLE
Getting game info

### ISSUE THREAD

**Issue by povanspring** [Franiac/TwitchLeecher#712]
Since Twitch Leecher is using the new API, it lost the ability to know what the game is in all areas. I don't understand why this is because a quick search returned a saying that [you need to use the Games API](https://discuss.dev.twitch.tv/t/how-to-know-which-game-id-belongs-to-which-game/23752) to translate a stream or video's "game_id" to the game's title and also to get the "box_art_url" of the game's thumbnail. This can be used both for searching and the filename game name wildcard that previously existed.

This seems like it would be a pretty simple thing to re-implement after it's removal since all this data is still accessible but maybe in a different place than before. I, unfortunately, don't have the programming skills or knowledge of TwitchLeecher's inner workings to do this myself.

**Comment by Franiac** [comment]
You are talking about the V5 API that gets shut down on February 28th. The `game_id` is no longer part of the video response. Every video in the search response would need that:

1. Get the video ID
2. Get the stream from the API that video originates from
3. Get the game ID from that stream
4. Get the game from the API
5. Get the info and thumbnail

This is more than 5 requests per video in the search result view. Given the fact that you can search by date and possibily can have 500 videos, that would make > 2500 requests to the API per search. You have 800 calls per minute... that the threshold. So no, game info is not coming back 😄
