### ISSUE TITLE
Download quality shows 720p twice

### ISSUE THREAD

**Issue by CapriKornus** [Franiac/TwitchLeecher#715]
Hi, recently while downloading VODs, the quality setting shows 720p twice while 1080p is not shown. This issue was seen in 2.0.2 as well as 2.0.4. Please check images attached. This has started recently as in only for newer VODs. I see older videos showing the 1080p option. 1080p not available for VODS after February 15th (maybe 16th, definitely not since 17th).

Attached images are for VODs dated Feb 21st and 15th respectively.

Video URL: https://www.twitch.tv/videos/1305442266
Channel : https://www.twitch.tv/gamingoncaffeine
OS : Windows 10 64-bit

![TL2 0 4 2x 720p](https://user-images.githubusercontent.com/3309947/155018337-c85c604c-9508-48e1-8456-e2f7f1d4b9a1.png)
![TL2 0 4 20220215](https://user-images.githubusercontent.com/3309947/155018356-76803cde-138f-42bd-8cad-e8243a70e716.png)

**Comment by Franiac** [comment]
TL only gets, what Twitch provides. If you check [https://www.twitch.tv/videos/1305442266](https://www.twitch.tv/videos/1305442266) on the Twitch website, there also are two 720p entries, one of which is "720p@60 (Source)" and the other is just "720p@60".

Nothing wrong here... I think if someone streams at 720p, Twitch "fills in" the mandatory source quality with the same stream.
