### ISSUE TITLE
Make available on Choco

### ISSUE THREAD

**Issue by LawranceFung** [Franiac/TwitchLeecher#716]
Are there any plans to make TwitchLeecher installable via Chocolatey?  I don't feel it's necessary but some people strongly prefer it.

**Comment by Franiac** [comment]
> I don't feel it's necessary

Me too 😄 

Chocolatey is not average Joe's tool. I would even say that 99% of the TL userbase does not even know what it is. I don't want to put any of the already very little time I can spend on TL into this.
