### ISSUE TITLE
1.8.4

### ISSUE THREAD

**Issue by GoodNames18** [Franiac/TwitchLeecher#717]
its 1 version below working? cause this day i can't even search twitch via channel, urls, ids
![10-42-43 February-23-2022](https://user-images.githubusercontent.com/41176431/155253945-07a5815a-6a71-4bd3-98a8-e942a3d476b4.jpg)

**Comment by GoodNames18** [comment]
oh I see shutdown, but why permanent shutdown?

**Comment by Franiac** [comment]
Software and API technology move forward. Twitch uses Helix now, so the old API has to go... kinda normal stuff to do as a tech company. Same reason nobody uses Windows 2000 anymore...
