### ISSUE TITLE
Non Working

### ISSUE THREAD

**Issue by dualityzinho** [Franiac/TwitchLeecher#718]
what i need to do? anybody can help me, please? ![image](https://user-images.githubusercontent.com/100284543/155312181-91a109ca-721d-487d-b98e-74cc7cbc885e.png)

**Comment by tezJR** [comment]
You can try the solution in here, which is working for me: https://github.com/Franiac/TwitchLeecher/issues/703

**Comment by Franiac** [comment]
I will roll out a fix for that shortly...

**Comment by Franiac** [comment]
should not happen anymore with 2.0.5

**Comment by dualityzinho** [comment]
> should not happen anymore with 2.0.5

![image](https://user-images.githubusercontent.com/100284543/155439567-bc7fa8ea-a21f-4a62-8044-0cbdf974121a.png)
Look... :/
