### ISSUE TITLE
Twitch authentication through browser.

### ISSUE THREAD

**Issue by kilpsz** [Franiac/TwitchLeecher#720]
Hello

For some reason I can't get twitch to send me an SMS and I have no clue what authenticator app is. Was wondering if you could make it like streamlink twitch GUI where it just opens up the default browser and you can just connect through that.

**Comment by Franiac** [comment]
TL shows a Chromium browser... the login form you get presented is the actual Tiwtch login form from their website. So there is no difference.

Handling the login by the sytem browser would mean that I have to change the current redirect url for Twitch Leecher. This means EVERY current installation anywhere on the planet would stop working immediately. That's the basic reason why there is an in-app browser in the first place. I am aware that OAuth authentication should be managed by the external browser, but making this switch is quite a thing, unfortunately
