### ISSUE TITLE
Twitch Leecher cant download after update 2.0.5

### ISSUE THREAD

**Issue by simulador79** [Franiac/TwitchLeecher#722]
Hello

thanks for the awesome application you guys have created.
Im having a problem since I installed the new update 2.0.5
I used to be able to download twitch videos while there were still going live.
And it would download until whatever stage the video was.
Now with the new update i cant download while still live videos.
I need to wait for it to finish to download it.
please help
thanks

**Comment by Franiac** [comment]
#687

**Comment by simulador79** [comment]
thank you for the great software you created and thanks for sending me the answer to my question.
all the best

**Comment by Franiac** [comment]
thank you for understanding!

**Comment by simulador79** [comment]
thank you for creating such amazing application
