### ISSUE TITLE
If the stream is in live you cant download it, before you can

### ISSUE THREAD

**Issue by PittKiss** [Franiac/TwitchLeecher#724]

**Comment by PittKiss** [comment]
![image](https://user-images.githubusercontent.com/78313838/156234326-eb8d9ce4-693c-4900-b61c-404fc6b0c071.png)

**Comment by PittKiss** [comment]
![image](https://user-images.githubusercontent.com/78313838/156234447-d8bcb554-cabf-451c-a548-479f5ff07e1c.png)

**Comment by PittKiss** [comment]
Only you can download if the stream is ending

**Comment by Franiac** [comment]
#687

**Comment by dark-swordsman** [comment]
All I wanted to say is that I think most of your reasons are silly for disabling downloads of live content. 

- If people don't want VODs, they can just disable that on Twitch
- If someone made a mistake, there is a good chance someone already clipped it or downloaded it, or probably even already used yt-dlp to acrhive the streams as they go live
- I understand not releasing broken software, but this isn't a professional application. Even professional engineers will release experimental or unstable features under a lock/flag.

It's really just a shame. I guess I can use yt-dlp, but this just unnecessarily complicates things for no reason. If you cared about the privacy and content control of Twitch streamers, you wouldn't have released this software.

**Comment by Franiac** [comment]
And I said I don't want to see other issues discussing it... have fun with yt-dlp.
