### ISSUE TITLE
twitch leecher download issue 

### ISSUE THREAD

**Issue by darkren24** [Franiac/TwitchLeecher#725]
Good morning everyone, today I opened the twitch leecher application to download a live from the previous day and I find that when I put the link of the video, the app tells me that there is no such link. I tried to put my ID in the other tab and it tells me the same thing, my channel does not exist. Is it happening to someone else? I have the latest version 1.8.4

**Comment by Franiac** [comment]
No you don't have the latest TL version...

#692
