### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Bano12345** [Franiac/TwitchLeecher#726]
Hi,

I recently downloaded the latest version (2.0.5) and when I came to download a vod, it is coming as an error. The error comes after it completes the download.

![image](https://user-images.githubusercontent.com/87618006/156659857-6c99d8ee-a398-4461-a312-860dfe3469a6.png)

**Comment by Franiac** [comment]
Download log please...

**Comment by Franiac** [comment]
> D:\Data\Pendrive Backup (Given with pratical dve)\SoundBooth\20220228_Alinity_1410972147.mp4: Permission denied

We had this a couple times in the past and every singe time it was due to antivirus software (mostly AVAST or AVG) not allowing ffmpeg.exe to write on the disk. That's 99% not a TL issue.

**Comment by Bano12345** [comment]
Yes you are right. Thanks for your help! By the way your program is extremely useful.
