### ISSUE TITLE
2 or more computers using Twitch Leecher on the same twitch api token

### ISSUE THREAD

**Issue by bobvargas** [Franiac/TwitchLeecher#727]
Hi I would like to know since Twitch Leecher 2.05 how do you use twitch Api token on twitch leecher on 2 or more computers without having to login everytime on a new computer? 

Thanks

**Comment by Franiac** [comment]
I don't...

**Comment by bobvargas** [comment]
ok thanks

**Comment by Franiac** [comment]
What made you think TL did something like that? Just wondering 😄
