### ISSUE TITLE
cannot download vod's while channel is live

### ISSUE THREAD

**Issue by doferd** [Franiac/TwitchLeecher#729]
i know i could in the older version but the newest version won't let me do it. is there a solution to this?

**Comment by xentumm** [comment]
any solutions?

**Comment by aeycs** [comment]
Yeah, the new version isn't working for live vods for me either. All other vods work (including the streamer's previous vods), but the vod of the broadcast that's currently live doesn't work until the stream goes offline. Then that vod works too. Hopefully this can be fixed?

**Comment by Maouniel** [comment]
https://github.com/Franiac/TwitchLeecher/issues/687

**Comment by doferd** [comment]
> #687

ah i see. well its my hope that franiac will add the feature down the line because its really a life saver when the old version was around. so franiac if you are reading this, please add this feature back to the newest version because i would be really happy if you would :)

**Comment by xentumm** [comment]
> > #687
> 
> ah i see. well its my hope that franiac will add the feature down the line because its really a life saver when the old version was around. so franiac if you are reading this, please add this feature back to the newest version because i would be really happy if you would :)

which version work with live channel i tryied with 1.8 doesnt work

**Comment by xentumm** [comment]
> > #687
> 
> ah i see. well its my hope that franiac will add the feature down the line because its really a life saver when the old version was around. so franiac if you are reading this, please add this feature back to the newest version because i would be really happy if you would :)

when i try 1.7/8 im getting no video found error
