### ISSUE TITLE
Real time download

### ISSUE THREAD

**Issue by LamAnLeTran** [Franiac/TwitchLeecher#730]
![image](https://user-images.githubusercontent.com/43964495/156926639-b2d94e65-199c-420d-9e4f-7bfaf745c2f6.png)

**Comment by LamAnLeTran** [comment]
Hi i've been using TL for a while now and it's really useful. Usually i download video from real time stream, not full vod. With the new update I can't download a part of the live video with specific time anymore. And my streamer always private video after stream so I can't download after the stream end. Can you check out this one please.

**Comment by Zeekablee** [comment]
#687

**Comment by AndrejKorjakin** [comment]
Can you bring back this feature?
