### ISSUE TITLE
Download during the live

### ISSUE THREAD

**Issue by oGustavoco** [Franiac/TwitchLeecher#732]
I want to know why they blocked downloads during live, we need to cut lives while they are still on live, it delays us

We want to know if there is any way to return this option

**Comment by Physikbuddha** [comment]
+1 on this. I had to upgrade to version 2.x and are now blocked by this.

My use case is:
The video is not muted as long as the stream is still live. I used to download the stream while the streamer played his outro, so I could download the entire stream without muted segments. Now this is no longer possible.

If making the download button available for currently running streams tends to confuse users, maybe a feature switch in the settings panel to enable this might work.

Of course, the most awesome solution to my use case would be "Download the VOD of a still running stream, and keep downloading new segments as long as the stream is running", so I would end up with the complete unmuted stream in the end. But this could be difficult to implement, and I don't want to demand anything.

In the end, just enabling the download button for live streams would be great.

**Comment by Franiac** [comment]
#733
