### ISSUE TITLE
Problem ?

### ISSUE THREAD

**Issue by madrina4** [Franiac/TwitchLeecher#737]
When I click on search it does not respond...
I Have Win7x64 pro

**Comment by Franiac** [comment]
I lost my magic wand, so I currently cannot read you mind...

Please provide the necessary information as demanded in the issue template

**Comment by Hekonu** [comment]
none of the search options are working for me either - there really isn't anything else to it.
Searching a name of /any/ channel makes the search section red
Searching a video says theres no video to be found, several or one (I tried multiple to make sure it wasn't specific to a channel), same issue with just individual video ID digits
![twitchleecher issues](https://user-images.githubusercontent.com/57606037/158044377-98c79cbd-67fd-4f75-893f-d497a699701c.png)

I am using Win10x64

**Comment by Franiac** [comment]
@Hekonu you left out the most important information... the TL version. Because my guess is that you are on TL 1.8.x.... and that's not supported anymore.
