### ISSUE TITLE
Download unpublished vods as mod

### ISSUE THREAD

**Issue by Dschogo** [Franiac/TwitchLeecher#740]
Hey another feature request,

like stated in the title, enable downloading unpublished vods as mod. Would be a nice addition, cuz twitchs own downloader is yeah... sloooooowwww. 

Not sure if its hard to implement, or if its just passing a mod token and getting the link in a different get_videos response including the unpublished ones.

Thats it :D

**Comment by Dschogo** [comment]
Okey, maybe not so important, since you can make the vod public for a second, start the download, and unpublish it directly after starting. Download completes sucessfully like normal.

**Comment by Franiac** [comment]
I will not use the private API for such a feature. My goal ist to only use the private API if there is no way around it. And as you mentioned the appropriate workaround, I don't see this feature as necessary right now.
