### ISSUE TITLE
freeze window

### ISSUE THREAD

**Issue by choosey14** [Franiac/TwitchLeecher#741]
Hi!
I ´ve downloaded latest twitch leecher version 2.0.5.exe
When I run leecher and click `connect´ to authorize my twitch, the window freezes.  
I´m using windows 11.

much appreciate help. Choosey_

**Comment by Franiac** [comment]
Since you are pretty alone with this issue I must assume it is a local problem on your machine since I cannot reproduce it locally. My first guess would be that you potential anti virus software is blocking the internal browser that should be displayed after the TL start in order to log in.

**Comment by MindlessGonzo** [comment]
I'm encountering the same issue. I have uninstalled and reinstalled and even disabled the only virus protection I had, Windows Defender.

**Comment by choosey14** [comment]
I solved the problem.
I downloaded leecher on another disk. But few days later, when I open the app it said something about ´worng with chanel token. and the problem of the freeze window repeats.

**Comment by choosey14** [comment]
Okey. problem solved. Just installe leecher to another place into ur pc. try different disk, documents...

**Comment by Franiac** [comment]
I don't really understand what a freezing window has to do with the install folder but I'm glad you figured it out.

**Comment by MindlessGonzo** [comment]
I just tried that. The login window at one point did not even show text or inputs. Once restarted, the problem persisted. I have attempted to reinstall in another place. I have no other disk on this PC to install to.
