### ISSUE TITLE
how do i download a sub-only video?

### ISSUE THREAD

**Issue by fabioalba821** [Franiac/TwitchLeecher#742]
Hi!
How do i download a sub-only video?
I've already paid for a subscription to that channel.
When I try to download it with twitchleecher it tells me "you need to enable sub-only video download support". 
How should I activate it?

**Comment by Franiac** [comment]
the "Star" button in the header 😄

**Comment by TomasTokaMrazek** [comment]
@Franiac Can you consider moving this under Settings or think about different UX? Star is usually represented as icon for Favorite. I personally also had to Google how to enable sub-only support.

**Comment by Franiac** [comment]
The star icon is used by Twitch on its subscribe buttons everwhere. What actually IS missing is a little TL manual or wiki. But that is not my priority.
