### ISSUE TITLE
Error with downloading a file (log file included)

### ISSUE THREAD

**Issue by JamieLee2k** [Franiac/TwitchLeecher#744]
I asked someone to change the clip to add more to it from a VOD and I think this is how this error occured but I can't be sure, When trying to download a video I get this error, this is the link: (https://www.twitch.tv/videos/1433267523)

> System.NullReferenceException: Object reference not set to an instance of an object.

 >at TwitchLeecher.Services.Services.FilenameService.SubstituteWildcards(String filename, TwitchVideo video, TwitchVideoQuality quality, Nullable`1 cropStart, Nullable`1 cropEnd)
   at TwitchLeecher.Gui.ViewModels.SearchResultViewVM.DownloadVideo(String id)

**Comment by Franiac** [comment]
That has nothing to do with anything you did. You just found a bug in TL 😄

**Comment by Franiac** [comment]
Tl 2.0.6 fixes this issue
