### ISSUE TITLE
[FEATURE REQUEST] - Create folders by adding "/<foldername>/" behind the filename template.

### ISSUE THREAD

**Issue by Goelant** [Franiac/TwitchLeecher#745]
It's all in the title, and maybe it already exists by another way :)

My goal is to put my VODs in a single new folder for each VOD. That way I can put every assets I used for this single stream in this single folder.

Thanks a lot for this great tool !

**Comment by Franiac** [comment]
That is an oddly specific usecase. I don't see how the majority of users would benefit from such an implementation. I think there are much more important features in the queue. You still need to manually insert the assets yourself, so just creating a folder while doing so is not much more work. This feature provides too little advantages and would be used by such a small fraction of the userbase that I don't want to put any time in it.
