### ISSUE TITLE
Option "Create subfolders for favourite channels" does not actually create subfolders

### ISSUE THREAD

**Issue by KryptonicDragon** [Franiac/TwitchLeecher#747]
In the "Preferences" menu, there is an option titled "Create subfolders for favourite channels". 
Given that it says "create" in the name, I was under the impression it would, well, *create* the folder(s) when I download VoDs from favourited channels. 
It does not. Instead, the option simply appends the channel name to the default "Download Folder" path when you go to download a VoD from a favourited channel. So, if the subfolder doesn't exist (even though the base "Download Folder" does exist), the download will fail, frustratingly after downloading the VoD but before merging the parts.

<details>
<summary>Here is a log from when that happens (click to expand)</summary>
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1439161237
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/1439161237
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: Yes
Output File: D:\Twitch\SovietWomble\20220328 - [1439161237] [VoD] - This prison has more leaks than a colander..ts
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\Kryreon\AppData\Local\Temp\6cd9fddb8dd2445898bcebcb446ae0ba

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1648566410%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1439161237%7D
Signature: 100a588b771596f773fdf11eb650f98bb9c515a0
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Kryreon\AppData\Local\Temp\6cd9fddb8dd2445898bcebcb446ae0ba'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/720p60/index-dvr.m3u8'
Playlist for quality '720p' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/720p30/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/audio_only/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/360p30/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/160p30/index-dvr.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d1ymi26ma8va5x.cloudfront.net/5d907e0135b327664b05_sovietwomble_45080643052_1648462561/chunked/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 137

Starting parallel video chunk download
Number of video chunks to download: 137
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'D:\Twitch\SovietWomble\20220328 - [1439161237] [VoD] - This prison has more leaks than a colander..ts'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Kryreon\AppData\Local\Temp\6cd9fddb8dd2445898bcebcb446ae0ba'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Twitch\SovietWomble\20220328 - [1439161237] [VoD] - This prison has more leaks than a colander..ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Twitch\SovietWomble\20220328 - [1439161237] [VoD] - This prison has more leaks than a colander..ts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at TwitchLeecher.Services.Services.ProcessingService.ConcatParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, String concatFile)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---
</details>

Perhaps you could add another option titled something like "Create subfolder if it doesn't exist", and rename "Create subfolders for favourite channels" to something like "Favourite channels download to subfolder". Then, enabling both options would have the desired behavior. 
Or simply make the "Create subfolders for favourite channels" option do exactly what it says.

This also reveals another issue where the destination folder not existing causes the download to fail at an inconvenient part of the process. Maybe add a popup/warning dialog if you click on "Download" on the "Download Video" page, and the destination folder doesn't exist?

Twitch Leecher v2.0.6
Windows 10 Pro x64 v21H2 (Build 19044.1586)

P.S. Thanks for the cool app, helps with the dragon's hoard!

**Comment by Franiac** [comment]
You just interpreted a lot of weird stuff into a simple bug 😄 

If mp4 conversion is disabled in the preferences, the creation of the channel subfolders does not get triggered, resulting in the given error from the log. That's all... I'll fix that and everything will work.
