### ISSUE TITLE
ERROR SEARCH

### ISSUE THREAD

**Issue by Justonsant** [Franiac/TwitchLeecher#748]
if you select a date range earlier than January 2019, an error occurs and the search highlights stops. manually through the twitch control panel or through the TL by ID, highlights from this time period are downloaded without problems. version 2.0.6, log attached
[03282022_110359_309_PM_error.log](https://github.com/Franiac/TwitchLeecher/files/8366892/03282022_110359_309_PM_error.log)

**Comment by Justonsant** [comment]
Justonsant channel from 2018-06-01 to 2019-02-01
![crop](https://user-images.githubusercontent.com/66955780/160756262-0d5b4ae4-3c8e-4ca4-9a91-9265ad048b12.JPG)

**Comment by Franiac** [comment]
Yup, can reproduce... should be an easy fix for the next version, thx
