### ISSUE TITLE
Cannot install Leecher

### ISSUE THREAD

**Issue by GaroK** [Franiac/TwitchLeecher#750]
I remember using this program, but then I deleted it.

Now when I try to install it, it thinks I want to update and trying to do this returns this 
![image](https://user-images.githubusercontent.com/30365395/160894365-61bc7004-d7e8-41d1-a367-267ba7947b27.png)

**Comment by Franiac** [comment]
Are you familiar with running programs in command line?

You can run the installer in command line with `TwitchLeecher_2.0.7.exe -l log.txt`

The installer will show up normally. Try to click through it and let it run into the error. One or two logfiles will be created in the same folder where the installer is. Please post both files here, then we can see what's going on.

**Comment by GaroK** [comment]
Here's what came out of it:
[log.txt](https://github.com/Franiac/TwitchLeecher/files/8391846/log.txt)

**Comment by GaroK** [comment]
Thanks, everything worked out.

**Comment by evilkoolade** [comment]
unsubscribe.

somewhere in the sands of time 

    On Friday, April 1, 2022, 01:07:03 PM CDT, Dominik Rebitzer ***@***.***> wrote:  
 
 


Closed #750.
