### ISSUE TITLE
Change the folder via the text field provided

### ISSUE THREAD

**Issue by 1upCAD** [Franiac/TwitchLeecher#752]
_Adding this again since my entire other issue was closed for one reason but did not address this one._

Please allow the ability to change the folder via the text field provided. Pasting or typing should be available rather than just the limitation of the folder selection button.

A very simple ask, which is super common in other download software.

**Comment by Franiac** [comment]
That did not fall under the bus... It's on my list, no worries. Just because I close issues, does not mean I don't make notes.

**Comment by 1upCAD** [comment]
Thank you.

**Comment by Franiac** [comment]
#803
