### ISSUE TITLE
Can't install Twitch Leecher

### ISSUE THREAD

**Issue by makerkym** [Franiac/TwitchLeecher#754]
I used this program before and it worked fine. I uninstalled the previous version, because somehow it wasn't able to upgrade TL version I was in (2.0.5 -> 2.0.7) But it still wouldn't upgrade. It always leads me to 
![Screenshot (301)](https://user-images.githubusercontent.com/102943161/161481273-345654d6-daa4-4679-8c96-c3ce64a005f4.png)

I went to the closed issues and the closest to what I am facing is this one #750. However, even after I did it, it still wouldn't work. I don't know what to do now. Here is the log txt if you need it.
[log.txt](https://github.com/Franiac/TwitchLeecher/files/8406984/log.txt)

**Comment by Franiac** [comment]
Thx for the log.

> [27CC:5834][2022-04-04T13:36:43]e000: Error 0x80070070: Failed to set end of file.
[27CC:5834][2022-04-04T13:36:43]e000: Error 0x80070070: Failed to extract all files from container, erf: 1:B:0
[27CC:0AF8][2022-04-04T13:36:43]e000: Error 0x80070070: Failed to begin and wait for operation.
[27CC:0AF8][2022-04-04T13:36:43]e000: Error 0x80070070: Failed to extract payload: a0 from container:

The error code 0X80070070 is an MSI installer error stating your drive is full (`not engough space on disk`).

If this is the case, you know how to solve it 😄 

If this is NOT the case, the only additional cause could be anti virus software not letting the installer write files on disk. We had false positives mostly in AVAST anti virus. SO check your anti virus software if you have something installed.

Other than that the issue does not have anything to do with your old uninstalled version of TL. Everything seems to be ok considering the log.

**Comment by makerkym** [comment]
Ah ok! I am installing it at the D drive tho which has ample amount of space, does it matter the C drive space?

**Comment by Franiac** [comment]
Yes, the Windows installer system always extracts the payload files to the temporary folder. Per default that is on your C:\ drive.

**Comment by makerkym** [comment]
Thanks! I have managed to install it! It is just that my C drive is filling up so much up till there are no free storage left! I have to check on that, but that is a completely separate problem! Thanks again for the fix!
