### ISSUE TITLE
Make possible to run installer silent.

### ISSUE THREAD

**Issue by SteffoSpieler** [Franiac/TwitchLeecher#757]
I tried to add Twitch Leecher to winget but it fails in the install process, because `This installer can only run in full UI mode!`.
Would be awesome if you could make it possible to run the installer in silentmode.

winget-pkgs PR: https://github.com/microsoft/winget-pkgs/pull/57102

**Comment by Franiac** [comment]
Sorry, that is not at all on my priority list. 99% of TL users do not even know what WinGet is. I don't want to put in time into this right now.
