### ISSUE TITLE
Error with downloading a file included the Log file 

### ISSUE THREAD

**Issue by randomuser24-212** [Franiac/TwitchLeecher#759]
im using Windows 10 64 Bit 

its a problem with downloading the video

> Download task has been started!
> 
> TWITCH LEECHER INFO
> --------------------------------------------------------------------------------------------
> Version: 2.0.7
> 
> VOD INFO
> --------------------------------------------------------------------------------------------
> VOD ID: 1410712157
> Selected Quality: 1080p60 (1920x1080)
> Download Url: https://www.twitch.tv/videos/1410712157
> Crop Start: No
> Crop End: Yes (01:00:00)
> 
> OUTPUT INFO
> --------------------------------------------------------------------------------------------
> Disable Conversion: No
> Output File: C:\Users\Downloads\202239_Crystalst_Crystal Clear's Final Eval _) Day 78.mp4
> FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
> Temporary Download Folder: C:\Users\AppData\Local\Temp\7db12664ce154bf985034cb0fdba9876
> 
> Retrieving VOD access information... done!
> 
> ACCESS INFO
> --------------------------------------------------------------------------------------------
> Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1649869389%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3A513183843%2C%22version%22%3A2%2C%22vod_id%22%3A1410712157%7D
> Signature: ca11c9cea7d30c0feeb96ca92d78d691945a1e2c
> Sub-Only: No
> Privileged: No
> 
> Creating temporary download directory 'C:\Users\AppData\Local\Temp\7db12664ce154bf985034cb0fdba9876'... done!
> 
> Retrieving playlist information for all VOD qualities... done!
> 
> PLAYLIST INFO
> --------------------------------------------------------------------------------------------
> Playlist for quality '1080p60' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/index-muted-7ZB0E8X64R.m3u8'
> Playlist for quality '720p60' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/720p60/index-muted-7ZB0E8X64R.m3u8'
> Playlist for quality '480p' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/480p30/index-muted-7ZB0E8X64R.m3u8'
> Playlist for quality 'Audio Only' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/audio_only/index-muted-7ZB0E8X64R.m3u8'
> Playlist for quality '360p' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/360p30/index-muted-7ZB0E8X64R.m3u8'
> Playlist for quality '160p' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/160p30/index-muted-7ZB0E8X64R.m3u8'
> 
> Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/index-muted-7ZB0E8X64R.m3u8'
> 
> Retrieving playlist... done!
> Parsing playlist... done!
> Number of video chunks: 11398
> 
> Starting parallel video chunk download
> Number of video chunks to download: 360
> Maximum connection count: 10
> 
> Parallel video chunk download is running...
> 
> Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/120-unmuted.ts' failed! Trying again in 20s
> System.Net.WebException: The remote server returned an error: (403) Forbidden.
>    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
>    at System.Net.WebClient.DownloadData(Uri address)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
> 
> Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/120-unmuted.ts' failed! Trying again in 20s
> System.Net.WebException: The remote server returned an error: (403) Forbidden.
>    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
>    at System.Net.WebClient.DownloadData(Uri address)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
> 
> Downloading file 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/120-unmuted.ts' failed! Trying again in 20s
> System.Net.WebException: The remote server returned an error: (403) Forbidden.
>    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
>    at System.Net.WebClient.DownloadData(Uri address)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
> 
> Starting temporary download folder cleanup!
> Deleting directory 'C:\Users\AppData\Local\Temp\7db12664ce154bf985034cb0fdba9876'... done!
> 
> Download task ended with an error!
> 
> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/120-unmuted.ts' after 3 retries!
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
>    at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/120-unmuted.ts' after 3 retries!
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
>    at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
>    at System.Threading.Tasks.Task.Execute()
> ---> (Inner Exception #0) System.ApplicationException: Could not download file 'https://d1ymi26ma8va5x.cloudfront.net/0f518a324ba0bc6c3565_crystalst_32848684991_7205186747/chunked/120-unmuted.ts' after 3 retries!
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
> <---
>

**Comment by Franiac** [comment]
Twitch playlist error, maybe transcoding was not completed yet. Also seems like the video has muted parts. Not a TL issue.
