### ISSUE TITLE
Download all VODs from result list (with date from/to selection)

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#76]
Would be nice to have a simple one-click feature that downloads all videos since the last one downloaded, or even just download all. Having to one-by-one select each one is painful.

**Comment by Franiac** [comment]
Download all from the last one makes no sense. If the last downloaded video is from channel "x" and you have now a search result open from channel "y", "download all since the last one" is quite unintuitive.

Download all with an additional "date from/to selection" would be reasonable, though.

**Comment by dsnvwlmnt** [comment]
Well, most people have one channel. Ideally we want to open the program, auto search (this setting exists) and auto download (this doesn't) vods since the last one downloaded. This would even be a 0-click backup. *drool*

Since some rare people have more than one channel they want to download from, you could have a setting "restrict to one channel" or something, which would lock editing the channel name when "download all from one channel" is selected. Or something. I'll leave it to you, you've done great.

**Comment by JohnMcLear** [comment]
I'd like to be able to open Twitch Leacher and have it auto download streams from a given array of broadcasters.  I want to minimize it and not have to think about it again.

**Comment by Franiac** [comment]
I see the use case for that. Issue #105 in combination with the option to select multiple VODs for downloading works towards this. A fully automated "download bot" is indeed a cool feature but currently TL is not able to handle this. First the new download manager has to be implemented (Issue #46 ).
Then we would need some kind of configuration dialog to set up the list of streamers and the start date for each of them.
Error handling is another huge issue here. If certain VODs fail to download I need to show them to the user and ask for an action what to do with them (retry, delete,...). In addition to that I require persistant download logging. TL has to know, which VOD's already have been downloaded. So maybe even a little database is required to store this information.

At the moment TL is not capable of handling all those requirements and I do not see from whom I could steal the freetime to implement all that. This is not just a little feature, that's way more.

**Comment by Franiac** [comment]
See #152 and #153 

Closing this one accordingly
