### ISSUE TITLE
Error when downloading VODs

### ISSUE THREAD

**Issue by SirenSoul94** [Franiac/TwitchLeecher#760]
Tried to download a couple of VODs, but it always ends in an error after the merging step.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1450765522
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/1450765522
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: C:\Program Files\Twitch Leecher\Downloads\20220409_Elajjaz_A short Malenia tutorial.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1650182486%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1450765522%7D
Signature: 009aec87b0cdc3caeb6c06df271ed30a3f976931
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/chunked/highlight-1450765522.m3u8'
Playlist for quality '720p60' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/720p60/highlight-1450765522.m3u8'
Playlist for quality '480p' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/480p30/highlight-1450765522.m3u8'
Playlist for quality 'Audio Only' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/audio_only/highlight-1450765522.m3u8'
Playlist for quality '360p' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/360p30/highlight-1450765522.m3u8'
Playlist for quality '160p' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/160p30/highlight-1450765522.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d2nvs31859zcd8.cloudfront.net/e1546d2f58f666033bdb_elajjaz_66006806255_8283452152/chunked/highlight-1450765522.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 100

Starting parallel video chunk download
Number of video chunks to download: 100
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into 'C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61\20220409_Elajjaz_A short Malenia tutorial.ts'...

Executing 'C:\Program Files\Twitch Leecher\ffmpeg.exe' on 'C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61\20220409_Elajjaz_A short Malenia tutorial.ts'...
Command line arguments: -y -i "C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61\20220409_Elajjaz_A short Malenia tutorial.ts" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy "C:\Program Files\Twitch Leecher\Downloads\20220409_Elajjaz_A short Malenia tutorial.mp4"

ffmpeg version 5.0-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100
Input #0, mpegts, from 'C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61\20220409_Elajjaz_A short Malenia tutorial.ts':
Duration: 00:16:35.00, start: 21996.032000, bitrate: 8382 kb/s
Program 1
Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 131 kb/s
Stream #0:1[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:2[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, unknown/smpte170m/unknown, progressive), 1920x1080, 60 fps, 60 tbr, 90k tbn
C:\Program Files\Twitch Leecher\Downloads\20220409_Elajjaz_A short Malenia tutorial.mp4: Permission denied

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\stern\AppData\Local\Temp\2c88adaa1d804690a97704a03e748f61'... done!

Download task ended with an error!

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ApplicationException: An error occured while converting the video!
   bei TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.ApplicationException: An error occured while converting the video!
   bei TwitchLeecher.Services.Services.ProcessingService.ConvertVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsIndeterminate, String sourceFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
That's a "Permission denied" from ffmpeg.exe which tries to convert the video from .ts to .mp4.

We had a couple of these errors in the past and every time it was the antivirus software denying write operations. Mostly AVAST, some AVG... pretty sure that's your problem here, too.

**Comment by SirenSoul94** [comment]
Thanks, changed some settings and ran the program as administrator and that helped.
