### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by MerlynG** [Franiac/TwitchLeecher#761]
I use Twitch Leecher 1.8.4

I can't download these videos (it shows no video found):
https://www.twitch.tv/videos/1458516737
https://www.twitch.tv/videos/1417408427

![image](https://user-images.githubusercontent.com/103439301/164291065-3d5756fc-1198-44c1-8f24-1b5d6c40bd10.png)

I can't even find my channel (it shows the channel field in red and clicking on search doesn't do anything):
merlin__g (https://www.twitch.tv/merlin__g)

![image](https://user-images.githubusercontent.com/103439301/164291008-61f6362f-b50c-4e06-9a6c-f0aa398beafa.png)

I'm using Windows 10 Pro 64 bits

**Comment by Franiac** [comment]
TL 1.8.4 support has been dropped in February when Twitch took down the old API. You have to use TL 2.x.x
