### ISSUE TITLE
Parallel merging\converting of video and downloading of a next one in queue

### ISSUE THREAD

**Issue by Divin1ty666** [Franiac/TwitchLeecher#762]
Hi! Would be nice to have this feature, because it usually takes long for merging\converting video and during that time nothing is being downloaded even if there are videos in a queue....

**Comment by Franiac** [comment]
May I ask you about your PC specs? A 8 hour video merges and converts in less than a minute on my rig, and that's nothing special (5600X with PCIe 4 NVMe SSD).

**Comment by Divin1ty666** [comment]
5775C, but i store downloads on my 6Tb HDD rather than on SSDs. So it takes like same amount of time or even more to convert and merge than to download video itself.

**Comment by Franiac** [comment]
i think overall you would be a lot faster by downloading to the ssd, and later moving the files to the hdd. surely the sequential reads and writes kills any hdd. in the end its video processing... and that's not meant to happen on a hdd in 2022. I don't say you can't, but you also don't open up videos in Adobe Premiere or something from a hdd and edit from there, right?
