### ISSUE TITLE
Is there a limit to a vod download length? Issue downloading a 36hr vod.

### ISSUE THREAD

**Issue by SayuOkami** [Franiac/TwitchLeecher#763]
Hello! My name is Sayu and I'm a partnered streamer on Twitch.

I'm having an issue downloading this vod here:
https://www.twitch.tv/videos/1410448308

The vod is roughly 36 hours long. The issue is that when I download it, the output is always "Completed", but the downloaded video is always 10:21:07 length long. (98.8 GB)
This is not a storage issue, as I'm downloading to a live server in my garage that has an immense amount of storage space. I'm still downloading other vods perfectly fine.

A few other details here:
-Twitch Leecher version is 2.0.7 and was when I tried downloading the vod.
-I tried downloading it twice, each time it was the exact same length. (10:21:07)
-In the "Downloads" section while downloading, it does display "Length" as 36hrs and correct details for the vod.

I don't currently have a log file for it because it was "Completed" each time, but I can definitely get one once I try to download it again. I'm so sorry this is probably very lacking in details, I'm not very good with technology, but I'll do my best to describe anything needed!
Thank you so much, any assistance is greatly appreciated!

**Comment by SayuOkami** [comment]
Ah! I do have mp4-conversion disabled.
Just for convenience, I believe there was another small reason that made it better to do non-mp4 downloads.

I actually had the same issue happen just today, with a 48hr exact, vod. Where it said "Status: Done" and it outputted as 21:29:15. I do have the logs for it this time since I noticed:

*****************************************************************************
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1412042481
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/1412042481
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: Yes
Output File: \\PTOLEMY\storage\Sayu\Twitch\Vods\[01.03.2022][DAY 13] BOOMER 2YR TWITCH ANNI !SUBATHON [2min per sub] !goals Elden Ring+Genshin HARD DOMAINS.ts
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: \\PTOLEMY\storage\Sayu\Temp\6baef9c083a740c69dca3d484c40c7ce

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1651127750%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1412042481%7D
Signature: b68baedb7d4df34f85539dafe1c2bc70ad62cead
Sub-Only: No
Privileged: No

Creating temporary download directory '\\PTOLEMY\storage\Sayu\Temp\6baef9c083a740c69dca3d484c40c7ce'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/chunked/index-muted-5DXU1LXZZJ.m3u8'
Playlist for quality '720p60' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/720p60/index-muted-5DXU1LXZZJ.m3u8'
Playlist for quality '480p' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/480p30/index-muted-5DXU1LXZZJ.m3u8'
Playlist for quality 'Audio Only' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/audio_only/index-muted-5DXU1LXZZJ.m3u8'
Playlist for quality '360p' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/360p30/index-muted-5DXU1LXZZJ.m3u8'
Playlist for quality '160p' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/160p30/index-muted-5DXU1LXZZJ.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d2vjef5jvl6bfs.cloudfront.net/a34d5eaf1bba17a896a0_sayu_45700251869_1646146565/chunked/index-muted-5DXU1LXZZJ.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 17280

Starting parallel video chunk download
Number of video chunks to download: 17280
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Merging all VOD parts into '\\PTOLEMY\storage\Sayu\Twitch\Vods\[01.03.2022][DAY 13] BOOMER 2YR TWITCH ANNI !SUBATHON [2min per sub] !goals Elden Ring+Genshin HARD DOMAINS.ts'...

Starting temporary download folder cleanup!
Deleting directory '\\PTOLEMY\storage\Sayu\Temp\6baef9c083a740c69dca3d484c40c7ce'... done!

Download task ended successfully!

**Comment by Franiac** [comment]
The log is clean and the possiblitly that TL did something wrong is therefor minimal (especially without mp4 conversion that could mess up a lot). TL downloads the playlist and merges the files at binary level. That's a task that is independent of size. Are you sure your video player actually can handle such a huge files properly? 48hr streams in a single file is actually not a great idea. Maybe it would be best to enable mp4 conversion and cut the video into 4 oder 5 parts.
