### ISSUE TITLE
Fatal UI Error

### ISSUE THREAD

**Issue by Circumflexer** [Franiac/TwitchLeecher#764]
Windows 10, x64
I have that problem on every version
![image](https://user-images.githubusercontent.com/104516181/165556629-4d676e20-470a-479e-a490-49339a15c76e.png)

logs:
System.TypeInitializationException: Инициализатор типа "System.Net.ServicePointManager" выдал исключение. ---> System.TypeInitializationException: Инициализатор типа "System.Net.ComNetOS" выдал исключение. ---> System.Configuration.ConfigurationErrorsException: Система конфигурации не прошла инициализацию ---> System.Configuration.ConfigurationErrorsException:  Неизвестный раздел конфигурации startup. (D:\Twitch Leecher\TwitchLeecher.exe.Config line 3)
   в System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   в System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   в System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Configuration.ConfigurationManager.PrepareConfigSystem()
   в System.Configuration.ConfigurationManager.GetSection(String sectionName)
   в System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   в System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   в System.Diagnostics.DiagnosticsConfiguration.Initialize()
   в System.Diagnostics.DiagnosticsConfiguration.get_Sources()
   в System.Diagnostics.TraceSource.Initialize()
   в System.Net.Logging.InitializeLogging()
   в System.Net.Logging.get_On()
   в System.Net.ComNetOS..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.ServicePointManager..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.ServicePointManager.set_ServerCertificateValidationCallback(RemoteCertificateValidationCallback value)
   в TwitchLeecher.App.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Franiac** [comment]
Please post the contents of the following file: `D:\Twitch Leecher\TwitchLeecher.exe.config`

**Comment by Circumflexer** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
  <system.net>
    <defaultProxy useDefaultCredentials="true" />
  </system.net>
</configuration>

**Comment by Circumflexer** [comment]
![image](https://user-images.githubusercontent.com/104516181/165626796-d9bd6f28-0e28-4800-ae0b-c20e9b17bff3.png)

**Comment by Franiac** [comment]
I cannot reproduce this issue. The config is absolutely fine.
