### ISSUE TITLE
Split "audio only" to smaller parts for my SD card in my car

### ISSUE THREAD

**Issue by DonKingMat** [Franiac/TwitchLeecher#765]
This is not a message about a bug nor is it a feature enhancement request.
It's just a little giveback to you all as a small information.

So that I can listen to my favourite streamers in the car in a relaxed way, I use this great tool to download "audio only".

After leeching "audio only" stuff from my favourite I want to cut up an hour-long audio file into smaller pieces. For example, into 15-minute packets. This way, I can fast-forward a bit on the car steering wheel while driving, in case I don't like a small part of the downloaded stream.

With locally available ffmpeg on my Windows PC without any nasty extra tools **(*)** from the web, I cut up an audio file of several hours quite simply with this:

- Open PowerShell
- Change to the download folder
- Execute simple splitting by `ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i .\20220429_MyFavoriteStreamer_1463055221.mp4 -f segment -segment_time 900 -c copy '2022.04.29 MyFavoriteStreamer %03d.mp4'`

In my case with my radio in my car, it behaves in such a way that the file name (at the end of the command given above) is shown in the radio display.

I am sure you're able to convert the ffmpeg options to your own needs.
The fancy `%03d` will help automatically count up from `000` to how much chunks you will have after snipping.

Remove the options `-hwaccel cuda -hwaccel_output_format cuda` if you do not have CUDA **(*)** installed for using you local GPU performance while transcoding.

I thought I'd just put this little practical tip here in the community. I hope it is useful. Enjoy and enhance this issue if you want.

_Thanks a lot @Franiac for this great tool!_

> **(*)** Well ... Just grab [ffmpeg](https://ffmpeg.org/download.html#build-windows) on top and put the extracted 7z folder into your c:\progra~1 path. On top you can use [CUDA](https://developer.nvidia.com/cuda-downloads) for the hardware acceleration.

**Comment by Franiac** [comment]
Thx for this input. Maybe it would be great to open up a wiki at some point in order to preserve these things. I am closing this now (because I don't want to keep issues open forever) but it is definitely marked as "put in wiki" 😄
