### ISSUE TITLE
Can't Connect with Twitch

### ISSUE THREAD

**Issue by liz-matthews** [Franiac/TwitchLeecher#768]
Downloaded the newest version (2.0.7) and the "Connect with Twitch" screen shows. Clicking the "-> Connect" button brings up the twitch login screen but I can't interact with the input fields. Clicking on the Username or Password input field doesn't seem to select it or I can't type anything into the fields. I am on Windows 10 64 bit.

**Comment by Franiac** [comment]
This is a kinda old issue. Is this still relevant?
