### ISSUE TITLE
Feature Request: Auto Split video function

### ISSUE THREAD

**Issue by rwp140** [Franiac/TwitchLeecher#769]
My apologies if this is not the right place to suggest, but at the time i neither could find the best place, nor see the same suggestion, regardless a lot of projects often have a suggestion/request tag available so this is not to far from appropriate.

A Auto Split video function available in settings would greatly save time when uploading VODs to YouTube, allowing for managing YouTube's. All it needs to do is automatically divide a video after every x hours as a setting available in settings or/and in y parts as a toggle at download, (E.I. every four hours or in 3 parts).

**Comment by Franiac** [comment]
#335
