### ISSUE TITLE
Suggestion: Make Download Screen Title Field Interactable

### ISSUE THREAD

**Issue by dsnvwlmnt** [Franiac/TwitchLeecher#77]
On the Download Video screen, it would be nice if the Title field were a text field so that we can copy/paste from it. As it stands, when i want to change the filename to include the title, i have to transcribe the whole thing, for every single video.

And/or having an option to have the stream title in the filename would be nice, not just the Game. So instead of
YYYYMMDD_VodIdNumber_Game.mp4
you could do
YYYYMMDD_VodIdNumber_Game_Title.mp4

Thanks for the program, it's streamlined my life significantly!

**Comment by Franiac** [comment]
Again, please take a look at the preferences and the filename template. Hover over the questionmark to see all available wildcards (title is one of them)

**Comment by dsnvwlmnt** [comment]
Damn, you nailed this program more than i thought. Thanks. Sorry.
