### ISSUE TITLE
I can't login !

### ISSUE THREAD

**Issue by mynameisji** [Franiac/TwitchLeecher#770]
Login page isn't work at all.
![loginerror](https://user-images.githubusercontent.com/70356119/169203278-99436530-0dbf-4abf-adad-c5f4db3c36db.PNG)

Please Help. This is the lastest version 2.0.7!!

**Comment by Estebandido1232** [comment]
same happening to me. 

I click log in but it does nothing.

**Comment by flo3501** [comment]
I got the same problem what can i Do ?
