### ISSUE TITLE
Can no longer download VODs whilst stream is live

### ISSUE THREAD

**Issue by jstrat231** [Franiac/TwitchLeecher#771]
Would it be possible to check why you can no longer download a segment whilst the stream is live? The download button is grayed out now.

For example.

Streamer a is live for 1 hour.  I want to download segment 30 mins - 40 mins   but you can no longer do that.

**Comment by tinryan** [comment]
I have been having this issue as well. The feature was available before v2.0 came out.

**Comment by dartyytrad** [comment]
[https://github.com/Franiac/TwitchLeecher/issues/733](https://github.com/Franiac/TwitchLeecher/issues/733)
