### ISSUE TITLE
+Feature Request: Reorder queued videos

### ISSUE THREAD

**Issue by JoKKa1** [Franiac/TwitchLeecher#775]
It would be helpful if there was a way to reorder the items in the queue. 
 Being able to drag and drop them up or down, or maybe buttons to move them up or down.

A potential first phase could be to mark an item to be at the top of the queue.  Maybe some sort of button to move it to the top of the queue so it looks like this: 
![image](https://user-images.githubusercontent.com/33069328/174913382-fa95c1a0-25ea-435e-9dc5-ad8a649e4601.png)

**Comment by Franiac** [comment]
Included in #46
