### ISSUE TITLE
Download vods in parts

### ISSUE THREAD

**Issue by WolfgangPonce** [Franiac/TwitchLeecher#776]
Hey, first of all you software is awesome and you're doing a great job!

My suggestion is to be able to download the video in parts, because sometimes editing a 6-hour long vod or more makes Premiere really slow, so the solution is to download in parts. Usually 2-hour long ones works just fine for me.
So maybe having a text box like "Split vod in parts: x" so you can type how many parts you want it to be cut into would really help.

Thanks for everything o/

**Comment by Franiac** [comment]
#335
