### ISSUE TITLE
NEW ISSUE

### ISSUE THREAD

**Issue by Kolegen** [Franiac/TwitchLeecher#779]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1471356546
Selected Quality: Source (1920x1080)
Download Url: https://www.twitch.tv/videos/1471356546
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: F:\Shylily\lastofusday2.mp4
FFMPEG Path: G:\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\XxX\AppData\Local\Temp\451c26dc82af4a928695c35aba702536

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1656507404%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A1471356546%7D
Signature: e0b1ed9e07c8651d37d535e9a7ab2e657383ebcd
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\XxX\AppData\Local\Temp\451c26dc82af4a928695c35aba702536'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality 'Source' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/chunked/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/720p60/index-dvr.m3u8'
Playlist for quality '480p30' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/480p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/audio_only/index-dvr.m3u8'
Playlist for quality '360p30' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/360p30/index-dvr.m3u8'
Playlist for quality '160p30' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/160p30/index-dvr.m3u8'

Playlist url for selected quality 'Source (1920x1080)' is 'https://dgeft87wbj63p.cloudfront.net/3044764bdad60acae354_shylily_39349507800_1651342291/chunked/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 1530

Starting parallel video chunk download
Number of video chunks to download: 1530
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating output directory 'F:\Shylily'...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\XxX\AppData\Local\Temp\451c26dc82af4a928695c35aba702536'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Shylily'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   at TwitchLeecher.Services.Services.DownloadService.CheckOutputDirectory(Action`1 log, String outputDir)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Shylily'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at TwitchLeecher.Shared.IO.FileSystem.CreateDirectory(String directory)
   at TwitchLeecher.Services.Services.DownloadService.CheckOutputDirectory(Action`1 log, String outputDir)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Well:

> Could not find a part of the path 'F:\Shylily'

Normally TL does not lie about such a thing. Does F:\Shylily exist? The probability is very high that is does not 😄
