### ISSUE TITLE
Download Greyed Out

### ISSUE THREAD

**Issue by iancomline** [Franiac/TwitchLeecher#782]
Not seen this before but the download button is greyed out on this particular video and can't download it.

![image](https://user-images.githubusercontent.com/21229444/177172268-78884bd6-c18c-476e-b60f-19f3db8e7eaf.png)

Not had issues with any other videos from the same streamer with muted parts.

**Comment by iancomline** [comment]
> That is because it is live. So the download option is disabled.

What do you mean by 'live'? This is a video dated back to October 2021.

**Comment by Franiac** [comment]
Tl detects live streams actually through the thumbnail. Currently live streamed VOD's do have this thumbnail. Somehow this video seems to be borked so hard that it never got a correct thumbnail by Twitch. Therefor TL thinks it is still live and does not let you download it. Not really a TL issue but a Twitch fuckup.

**Comment by LostPhysx** [comment]
Maybe this IS a twitch fuckup, but there could be a double check to allow downloads on videos older than (72h) even if the thumbnail has the "live" badge
