### ISSUE TITLE
Show UI dates in local computers format

### ISSUE THREAD

**Issue by matthewvukomanovic** [Franiac/TwitchLeecher#783]
All dates are shown using WPFs default language of en-US.
If that is not the date format that you are used to seeing then it is distracting.

* affected screens are search screen and downloading screen

I have already coded the change to override WPF's default language properties.
As far as I can tell you are not using the displayed dates anywhere in the system so there shouldn't be any issues.

**Comment by Franiac** [comment]
I actually find it way more distracting to see `Dienstag, 13. März 2022` in an all english UI.

I get what you are aiming for but as long as there is no multi-language UI, the dates should be displayed in the same language (currently en-US).

On a sidenote: Do check code from StackOverflow even if it looks promising. You are using deprecated properties in your PR. Just a hint 😄
