### ISSUE TITLE
VOD Sub Only doesn't work

### ISSUE THREAD

**Issue by Keykey388** [Franiac/TwitchLeecher#786]
Hello,

I have never managed to take sub only vods despite the green star being activated and the message "sub-only video download support is currently enabled". I have version 2.0.7. When I try to download a video, I get the following message: "this video is sub-only but you are not subscribed to the channel".

Can you help me please? Thanks a lot. Best regard

**Comment by Franiac** [comment]
> this video is sub-only but you are not subscribed to the channel

Well, ARE you actually subscribed to the channel you are trying to download from?
