### ISSUE TITLE
Cannot Install Twitch Leecher

### ISSUE THREAD

**Issue by Theotherguy1223** [Franiac/TwitchLeecher#787]
![TwitchLeecherError](https://user-images.githubusercontent.com/12008758/183232039-d08e3bda-f535-4153-815c-e180ff61b7b1.png)

[log.txt](https://github.com/Franiac/TwitchLeecher/files/9274318/log.txt)

Checklist:

- Found Similar issues previously, their fixes did not work for me.
- Version 2.0.7
- had version 1.8.x before, suddenly didn't work, could not find any videos/channels/IDs, nothing
Tried to update with 2.0.7 installer, same error. Removed all files manually and cleaned registry with Ccleaner.
Still cannot install.
- Windows 10 Pro.

**Comment by Franiac** [comment]
you can run the installer via command line like this:

`TwitchLeecher_2.0.7.exe -l log.txt`

Click through the installer, let it do its thing until it errors out. There will be one or more log files next to the installer. Show me the log files...

**Comment by Theotherguy1223** [comment]
> you can run the installer via command line like this:
> 
> `TwitchLeecher_2.0.7.exe -l log.txt`
> 
> Click through the installer, let it do its thing until it errors out. There will be one or more log files next to the installer. Show me the log files...

I already provided the log file in my initial post, but here it is again:
[log.txt](https://github.com/Franiac/TwitchLeecher/files/9356296/log.txt)

**Comment by Franiac** [comment]
There must be more than one log file. The execution logfile is missing. SOmething like `log_0.txt`. Just send them all, please.

**Comment by Theotherguy1223** [comment]
> There must be more than one log file. The execution logfile is missing. Something like `log_0.txt`. Just send them all, please.

Apologies, here they are:
[log.txt](https://github.com/Franiac/TwitchLeecher/files/9359230/log.txt)
[log_000_TL.txt](https://github.com/Franiac/TwitchLeecher/files/9359231/log_000_TL.txt)

This time, for some reason, It wanted to uninstall it, but I do not have it installed... It still failed anyway

**Comment by Franiac** [comment]
> Found Similar issues previously, their fixes did not work for me.

That is because you re the only one so far with this issue.

`MainEngineThread is returning 1603`

That is an error code of the Windows Installer system. That error code is documented my Microsoft and basically what they say is "could be everything". So I feel like this error code is for issues even MS don't understand. Sometimes it's a permission issue, sometimes it is anti virus, somethines it is the installer being unable to delete old files.

I honestly don't know what I should do here. I do not have a lever I can pull to fix anything. Something on your system causes the installer to crash and even the log file does not tell me what it is.

The only thing you could do is check the Windows event log. Go to Windows event viewer -> Windows Logs -> Category Application or Setup. Meybe you find something interesting there.

**Comment by Theotherguy1223** [comment]
> The only thing you could do is check the Windows event log. Go to Windows event viewer -> Windows Logs -> Category Application or Setup. Meybe you find something interesting there.

I ran the installer with both log files again, just to be sure.
[log.txt](https://github.com/Franiac/TwitchLeecher/files/9366034/log.txt)
[log_000_TL.txt](https://github.com/Franiac/TwitchLeecher/files/9366035/log_000_TL.txt)
just in case something changed. And it did, it didn't want to uninstall this time, it wanted to install, but still failed.


Event Viewer Registered 3 entries:
![image](https://user-images.githubusercontent.com/12008758/185242338-d3e7c7e0-df2f-48c4-bfef-517fc92e1150.png)

 
<details>
  <summary>Restore Point</summary>
  
`Successfully created restore point (Process = C:\Users\Madog\AppData\Local\Temp\{81765533-EB45-4A96-9935-0FA0A2E42CD2}\.be\TwitchLeecher.exe -q -burn.elevated BurnPipe.{32EAEE44-0410-4F20-BE2F-4590A7AF91A2} {327DBA98-927B-4F37-93F5-25699C664AB2} 25992; Description = Twitch Leecher 2.0.7).`
  
</details>
<details>
  <summary>MsiInstaller 1040</summary>
  
`Beginning a Windows Installer transaction: C:\ProgramData\Package Cache\{FE96584C-AB61-4212-99A3-790756CB7701}v2.0.7.0\TL.msi. Client Process Id: 43640.`
  
</details>
<details>
  <summary>MsiInstaller 1042</summary>
  
`Ending a Windows Installer transaction: C:\ProgramData\Package Cache\{FE96584C-AB61-4212-99A3-790756CB7701}v2.0.7.0\TL.msi. Client Process Id: 43640.`
  
</details>


I don't know what to do with this Data, so I hope this either helps, or helps you get more info.
I can give you more info if you want, I just don't know what/where to look.

**Comment by Franiac** [comment]
Those events are normal and nothing special. Sorry mate, I don't know. Something's borked on your system. I have no further ideas.

**Comment by Theotherguy1223** [comment]
> Those events are normal and nothing special. Sorry mate, I don't know. Something's borked on your system. I have no further ideas.

Alright, if I figure something out, I'll reply here. Thank you for trying.

**Comment by Theotherguy1223** [comment]
I finally found the source of the issue, it was a corrupted .NET framework, and a corrupted Windows install service.
