### ISSUE TITLE
Change "Open Download Folder" button behavior to automatically select file in Explorer window

### ISSUE THREAD

**Issue by 1bakedpotato** [Franiac/TwitchLeecher#788]
This is a feature request to modify the "Open Download Folder" button. Currently, it simply launches a Windows Explorer process to display the folder of a downloaded file.

It would be even more convenient to also have the new Explorer process automatically select the downloaded file within that folder.

**Comment by 1bakedpotato** [comment]
This PR basically changes the previous behavior of ultimately running:
    `explorer.exe "path\to\download_dir\`
into:
    `explorer.exe /select,"\path\to\download_dir\download_file.ext"`

This `/select` switch behavior can be found at this archived KB: https://web.archive.org/web/20150602220856/https://support.microsoft.com/en-us/kb/152457

**Comment by Franiac** [comment]
Ok, good point... I will test this.

**Comment by Franiac** [comment]
#803
