### ISSUE TITLE
All .ts files play perfectly and in sync. The resultant .mp4 file, however, does not. A manual workaround fixes the issue.

### ISSUE THREAD

**Issue by Solar-Plexus** [Franiac/TwitchLeecher#79]
**Version:** 1.3.3
**Url:**  [https://www.twitch.tv/aaron215/v/45403767](https://www.twitch.tv/aaron215/v/45403767)
**OS:** Windows 10 64-bit
**log:** http://pastebin.com/fryeA9ma

I've watched the entire source video numerous times and have never experienced any playback issues.

During troubleshooting, I played back all .ts files (made sure it was all of them) in secession and they all played perfectly. I then ran `ffmpeg -f concat -i mylist.txt -c copy output.ts` to merge all .ts files, where 'mylist.txt' is the .txt file I made that lists all .ts files. http://pastebin.com/9QYmkwNs

This resulted in a single .ts file that works as expected and has no issues. From here, a simple ffmpeg remux to mp4 will work obviously and I can attest that testing the resultant mp4 video has it working perfectly with no issues as well.

However when you let twitch leecher process the video, the resultant .mp4 file says that the video is about twenty minutes long instead of an hour and one cannot seek beyond those twenty minutes during playback. The video will keep playing after the time limit and will then experience heavy playback (speeding up and slowing down, glitching)and audio sync issues.

This issue happened on both computers I have tried, both Windows 10 64-bit.
Here's another video where this occurs as well: https://www.twitch.tv/socony/v/45156744. Trying a random recent 2016 video works fine.

**Comment by Franiac** [comment]
Thank you very much for your input, much appreciated. I am not that familiar with ffmpeg and issues with it are kinda hard do deal with for me. Your approach with merging the ts files first is interesting.

How long does that take for let's say a 3 hour VOD? I could possibily include that operation within TL.

Your approach could also fix issue #78. So far I did not know about the concat option. Really good hint and possibly a game changer for 2 or 3 bugs that I was unable to deal with up til now.

**Comment by Franiac** [comment]
btw. what were your ffmpeg arguments for converting to mp4? did you set analyzeduration and probesize? and have you tried to crop the video and export only the first 10minutes and check the A/V sync?
Others have problems with A/V sync only when cropping so I am kinda corious if merging also helps with this behavior.

**Comment by Franiac** [comment]
Alright, thanks again. I am going to follow that trace.

**Comment by Franiac** [comment]
I have tried the concat command with ffmpeg. The problem is, due to the lack of PPS information (keyframes) in the stream, errors are getting thrown and ffmpeg quits wit exit code != 0. The concatination works, though. So the resulting ts file works perfectly, but ffmpeg quits with an error code. This is super bad for TL because I cannot judge if ffmpeg really had an error or not.
We needed someone here that really knows that streaming stuff. Video encoding is super weird to me.

**Comment by Franiac** [comment]
Sorry, I fucked up. It seems to work properly. And it actually solves multiple issues where streams did not get encoded entirely. There are VODs that are 6hrs long for example and after processing with ffmpeg the resulting video is only 26min long. Concatinating the ts files first solves this.

**Comment by Franiac** [comment]
🎉

**Comment by Solar-Plexus** [comment]
Nice! Just downloaded a vid and it worked great. Glad I could help. 👍

**Comment by Franiac** [comment]
This issue seems to break many things regarding A/V desync. See issue #96 for further discussion. I will probably roll it back and rethink again...
