### ISSUE TITLE
Twitch leecher logged out and doesn't show any options 

### ISSUE THREAD

**Issue by Zurisaitobi** [Franiac/TwitchLeecher#791]
Hi

I was downloading content normally when suddenly twitch leecher closed and showd me this
![image](https://user-images.githubusercontent.com/111396694/184997986-2571661d-bd71-4642-b5f1-16670d0c6dd1.png)

I tried to connect again, but the program just looks like this

![image](https://user-images.githubusercontent.com/111396694/184998059-4e2b4ea7-dc10-4e96-b6f8-dd0affdab29f.png)

Did something happened?

**Comment by Zurisaitobi** [comment]
Already tried to uninstall it and install it back, even past versions

**Comment by Franiac** [comment]
See #800 this will change anyways
