### ISSUE TITLE
Problem with sub-mode clips

### ISSUE THREAD

**Issue by SeyFish** [Franiac/TwitchLeecher#793]
Hello
I am sub a there a channel and I would like to download the reruns but these are in sub-mod as I am sub normally I should be able to download them but that is not the case. A message is displayed telling me that the videos are in sub-mod how to do?

**Comment by Franiac** [comment]
Is this still a thing? I can confirm sub-only downloads working for the channels I am subbed to. The difficulty here is that I cannot reproduce the error since I do not have the same context (you login and subscriptions).
