### ISSUE TITLE
Feature request: Turn pc off when download is Finish

### ISSUE THREAD

**Issue by AnImEpRo3690** [Franiac/TwitchLeecher#794]
Hi !
Thanks a lot for your great work !

I use it a lot archiving my favorite Streamer but it can last 5-10 hours(Depend on the Length of the Streams) and Some Streams are usually during the night.

So, A "Turn pc off when download is Finish" Feature would be nice.

Just left the PC and Download Running then When the Download Finished, it automatically turns the PC Off.

Thanks a lot.

**Comment by Franiac** [comment]
#233
