### ISSUE TITLE
Twitch Log-In not available since version 2.0.7

### ISSUE THREAD

**Issue by flo3501** [Franiac/TwitchLeecher#795]
- Version 2.0.7 (with 2.0.6 everything was working fine)
- Windows 11 Home 21H2 64 Bit (Surface Pro 8)
- After I installed Version 2.0.7 I can't login with my twitch information anymore.
  When I click on Log-in / or Sign Up nothing happens. Also when I type in the fields nothing happens. Also I can't click in the password                                                field. (Screenshot [attached)](https://prnt.sc/ZDZuON2ZT6lf)

**Comment by Franiac** [comment]
I think Twitch is onto something fucky... see #800 

Lots of changes to the authentication form. I am looking into it. Closing this one for #800
