### ISSUE TITLE
Feature Inquiry: Closed Captions / Subtitles still impossible?

### ISSUE THREAD

**Issue by Peabody0815** [Franiac/TwitchLeecher#796]
Hey @Franiac 

sorry to open an issue for this, but I didn't know where else to put it:
I know in 2019 you already tackled the issue of closed captions/subs and came to the conclusion that it wasn't possible (back then).

IIRC Twitch has updated their API quite a lot since then, so maybe you can take another look at this?

Either way, thank you so very much for all your hard work on this excellent piece of software.

Keep up the great work and stay healthy!

**Comment by Franiac** [comment]
You mean downloading chat?

**Comment by Peabody0815** [comment]
Na. I give a rat's ass about twitch chat. I mean closed captions aka subtitles as written in the title

**Comment by Franiac** [comment]
I don't know any possibility the get these from the new API, unfortunately.

**Comment by Peabody0815** [comment]
Ah damn. Too bad.
