### ISSUE TITLE
Can't dl vod

### ISSUE THREAD

**Issue by Soulivan71** [Franiac/TwitchLeecher#797]
Hi Im having pb after some sc of dl, and Im having enough storage so I don't understand why the dl failed with error below.

- Provide information about your operating system -> Windows 10 64 Bit

TL Logs :
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 2.0.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 1587033434
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/1587033434
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: P:\20220910_LittleBigWhale_1587033434.mp4
FFMPEG Path: D:\Program Files\Twitch Leecher\ffmpeg.exe
Temporary Download Folder: C:\Users\X\AppData\Local\Temp\X

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: X
Signature: 6e4638346f4296de0e83f91190f9190c4774e7f5
Sub-Only: No
Privileged: No

Creating temporary download directory 'X'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/chunked/index-muted-BPBDGGY46Z.m3u8'
Playlist for quality '720p60' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/720p60/index-muted-BPBDGGY46Z.m3u8'
Playlist for quality '480p' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/480p30/index-muted-BPBDGGY46Z.m3u8'
Playlist for quality 'Audio Only' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/audio_only/index-muted-BPBDGGY46Z.m3u8'
Playlist for quality '360p' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/360p30/index-muted-BPBDGGY46Z.m3u8'
Playlist for quality '160p' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/160p30/index-muted-BPBDGGY46Z.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://dgeft87wbj63p.cloudfront.net/f684b3778c5970c2ee30_littlebigwhale_46045866060_1662806469/chunked/index-muted-BPBDGGY46Z.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 6349

Starting parallel video chunk download
Number of video chunks to download: 6349
Maximum connection count: 10

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'X'... done!

Download task ended with an error!

System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   à System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   à System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   à TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
---> (Exception interne #0) System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   à System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   à System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   à TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2()
   à System.Threading.Tasks.Task.Execute()
---> (Exception interne #0) System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Exception interne #1) System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Exception interne #2) System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Exception interne #3) System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Exception interne #4) System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Exception interne #5) System.IO.IOException: Espace insuffisant sur le disque.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   à TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState)
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

**Comment by AnImEpRo3690** [comment]
Have the Same problem but on a different Stream

**Comment by Soulivan71** [comment]
Thx but not solving my issue :(

**Comment by Soulivan71** [comment]
> Have the Same problem but on a different Stream

Thx but not solving my issue :(

**Comment by Soulivan71** [comment]
@Franiac

**Comment by 51st-JoNay** [comment]
I just started having the same problem today. Logs say "not enough disk space", but I have 1.3 TB available on the disk I'm downloading my leeches too.

**Comment by Franiac** [comment]
TL does not lie about disk space since it is an error Windows throws not TL. There are 2 download paths in the preferences, the temporary download path and the final download path.

> Temporary Download Folder: C:\Users\X\AppData\Local\Temp\X
> Output File: P:\20220910_LittleBigWhale_1587033434.mp4

Probably your C:\ drive is full...

**Comment by Soulivan71** [comment]
> TL does not lie about disk space since it is an error Windows throws not TL. There are 2 download paths in the preferences, the temporary download path and the final download path.
> 
> > Temporary Download Folder: C:\Users\X\AppData\Local\Temp\X
> > Output File: P:\20220910_LittleBigWhale_1587033434.mp4
> 
> Probably your C:\ drive is full...

How I can fix this yeah my c is full that's why I dl it on an extern disk

**Comment by Franiac** [comment]
Like I said... TL preferences
