### ISSUE TITLE
TwitchLeecher VS TwitchLink

### ISSUE THREAD

**Issue by cheese-steak** [Franiac/TwitchLeecher#799]
![compare](https://user-images.githubusercontent.com/98674847/192077375-b32a64ea-385e-4600-b8c9-479e712f1c18.png)

I found this project [devhotteok/TwitchLink](https://github.com/devhotteok/TwitchLink) a few hours ago and compared with TwitchLeecher.

I still don't understand why you blocked the live-vod download.
I don't know why you are rejecting issues that are asking for features already in other projects.
#46 #174 #184 #233 #673 #783 #790

**Comment by akosirmpr** [comment]
is TwitchLink safe to use?

**Comment by cheese-steak** [comment]
> is TwitchLink safe to use?

Seems safe.

1. Open source with multiple stars and forks
2. VirusTotal says it's safe (just checked this morning)
(No security vendors and no sandboxes flagged this file as malicious)

The source code is also Public.

**Comment by Franiac** [comment]
How disrespectful does one need to be to make an issue about discrediting thousands of hours of work I put into this tool including the support. I stated multiple times I am a father now and I don't have the time anymore to heavily work on TL. You can take a hike, dude...
