### ISSUE TITLE
Remember Search window position when switching screens

### ISSUE THREAD

**Issue by theultramage** [Franiac/TwitchLeecher#80]
If you leave the Search screen - by going to Downloads, or Preferences - the only way to return is to click Search again. This takes you back to the top of the search listing. This might be intended, but can still be a nuisance. Note that it remembers the position when downloading a single stream.

**Comment by Franiac** [comment]
The single download dialog used to be an actual modal dialog, that is why the scroll position is retained. In all other cases the view gets totally removed and recreated if shown again for a very low memory profile. Could be implemented in the future but low priority (current A/V desync bugs are more important and my freetime is rare atm).

**Comment by Franiac** [comment]
Actually I already had this implemented... There was just a little bug that prevented it from working

🎉
