### ISSUE TITLE
Download works, but creating file fails.

### ISSUE THREAD

**Issue by MaximMuenchen** [Franiac/TwitchLeecher#87]
I cannot download several streams with TwitchLeecher 1.3.3. The downloads itself always seem to work, but when it is creating the final video file, it stops arround 97%. When this happens, the complete video file is useless. This can be reproduced on my system, it was not a one time thing.

I did not run out of discspace. I'm using Windows 7, 64bit.

Two examples: https://www.twitch.tv/gronkh/v/114454230 and https://www.twitch.tv/pietsmiet/v/104974967

Any ideas?

This is the log for one of the streams:

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.3

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 114454230
Selected Quality: 1920x1080@60fps
Download Url: https://www.twitch.tv/gronkh/v/114454230
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Twitch\20170113_114454230_IRL.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Maxim\AppData\Local\Temp\TL_89228eaf-7ce4-4221-bedc-fa2555dbb68b

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3Anull%2C%22vod_id%22%3A114454230%2C%22expires%22%3A1484454806%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 8d46d880c0be51aa31e7d0d08e21d0a70782767c
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Maxim\AppData\Local\Temp\TL_89228eaf-7ce4-4221-bedc-fa2555dbb68b'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/high/index-dvr.m3u8
https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/medium/index-dvr.m3u8
https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/low/index-dvr.m3u8
https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/mobile/index-dvr.m3u8
https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/audio_only/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps is https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 15884

Starting parallel video chunk download
Number of video chunks to download: 15884
Maximum connection count: 10

Parallel video chunk download is running...

Downloading file 'https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/chunked/index-0000014999-Tp3C.ts?start_offset=10286796&end_offset=11221155' failed! Trying again in 20s

Downloading file 'https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/chunked/index-0000007949-7HEy.ts?start_offset=16833708&end_offset=17769383' failed! Trying again in 20s
System.Net.WebException: Ausnahmefehler während einer WebClient-Anforderung. ---> System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.WebClient.DownloadBitsState.RetrieveBytes(Int32& bytesRetrieved)
   bei System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)
System.Net.WebException: Ausnahmefehler während einer WebClient-Anforderung. ---> System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.WebClient.DownloadBitsState.RetrieveBytes(Int32& bytesRetrieved)
   bei System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Downloading file 'https://vod-secure.twitch.tv/v1/AUTH_system/vods_4bbf/gronkh_24226478736_582825423/chunked/index-0000009779-4L0G.ts?start_offset=1869660&end_offset=2804395' failed! Trying again in 20s
System.Net.WebException: Ausnahmefehler während einer WebClient-Anforderung. ---> System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.WebClient.DownloadBitsState.RetrieveBytes(Int32& bytesRetrieved)
   bei System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadData(Uri address)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass59_0.<DownloadParts>b__0(IVodPlaylistPartExt part, ParallelLoopState loopState)

Download of all video chunks complete!

Creating local m3u8 playlist for FFMPEG... done!
Writing playlist to 'C:\Users\Maxim\AppData\Local\Temp\TL_89228eaf-7ce4-4221-bedc-fa2555dbb68b\vod.m3u8'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -i "C:\Users\Maxim\AppData\Local\Temp\TL_89228eaf-7ce4-4221-bedc-fa2555dbb68b\vod.m3u8" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Twitch\20170113_114454230_IRL.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Maxim\AppData\Local\Temp\TL_89228eaf-7ce4-4221-bedc-fa2555dbb68b'... done!

Download task ended with an error!

System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ApplicationException: An error occured while encoding the video!
   bei TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass53_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.ApplicationException: An error occured while encoding the video!
   bei TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String playlistFile, String outputFile, CropInfo cropInfo)
   bei TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass53_0.<StartQueuedDownloadIfExists>b__2()
   bei System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Not entirely correct... the download fails and because of that the processing fails also:

System.Net.WebException: Ausnahmefehler während einer WebClient-Anforderung. ---> System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.

Maybe a hickup on the Tiwtch server. TL tried to download all VOD parts and Twitch did not provide it. Sometimes Twitch servers are unstable. Sometimes it happens on unstable connections, sometimes because of internet provider disconnects.

Both VOD downloads worked for me perfectly today... da kann ich also nicht wirklich was machen ;)
