### ISSUE TITLE
Too many search results

### ISSUE THREAD

**Issue by notAtable** [Franiac/TwitchLeecher#92]
Hey Franiac,

since the upgrade to 1.3.4 searches for Channels with a bigger search result than 100 return 1040 videos (so for searches with 250, 500 and 1000 results).

Cheers and thanks for all the good work.

**Comment by Franiac** [comment]
Channel name?

**Comment by notAtable** [comment]
Sevadus

**Comment by Franiac** [comment]
Confirmed... I messed that one up during the switch from API version 3 to 5 :(

**Comment by Franiac** [comment]
Fixed
