### ISSUE TITLE
New twitch URL format

### ISSUE THREAD

**Issue by w4hnsinn** [Franiac/TwitchLeecher#93]
The new twitch url format isn't accepted by Twitch Leecher.

Format is changed as follows:
https://www.twitch.tv/channel/v/111111111
-->
https://www.twitch.tv/videos/111111111

Note:
If the channelname is known, it is currently still possible to simply edit the URL manually and paste that into twitch leecher.

**Comment by Franiac** [comment]
Damn right you are. Yea, they introduce a lot of work with their new API.

**Comment by Franiac** [comment]
Fixed
