### ISSUE TITLE
Problem with editing downloaded vods

### ISSUE THREAD

**Issue by elkolorado** [Franiac/TwitchLeecher#95]
Hey. I've have problem, when I downloaded the vods in source 1920x1080p 30fps quality, I am able to watch it, but when it comes to editing in program such as Adobe Premiere CC the error appears "The file has no audio or video streams".

If I reencode it with program like "Handbrake" it works properly.

Not sure if its mine computer fault or the program itself.
Thanks in advance!

**Comment by Franiac** [comment]
That is a known Premiere bug that Adobe is unable to fix. They have not fixed it for years. Their official statement is indeed to use Handbreake. Either it is pure incompetence or plain laziness. But nothing related to TL or the VODs.

**Comment by elkolorado** [comment]
I see. Thanks for answer 👍
