### ISSUE TITLE
overcoming 504 Gateway Timeout

### ISSUE THREAD

**Issue by tezJR** [Franiac/TwitchLeecher#98]
I sometimes get a 504 Gateway Timeout repeatedly, which naturally causes TL to fail. Restarting the download works. The lost time and data is a difficulty though. Is there a way I can pause the download for a longer period so it is more likely to complete when a server's flaky?

**Comment by Franiac** [comment]
Well, TL cannot fix a bad internet connection. #68 was already introduced to get over shorter disconnects. #46 is planned. But even #46 won't fix a bad connection. I need something like a retry count and then give up. I cannot go ahead and let the download run forever and ever and ever until finally all parts are somehow downloaded (I mean I could, but it makes no sense).
Maybe I could introduce the retry count and wait time betewwn the retries as an option in the preferences. But like I said, TL cannot and will not fix a bad internet connection. It can only somewhat smoothen it out.

**Comment by tezJR** [comment]
Is there a way for me to identify if the cause is my ISP or a remote server when it occurs?

I'd appreciate it if you could introduce the retry count and wait time between retries as an option please.

**Comment by Franiac** [comment]
there are certainly tools that can do this, but I personally do not know a specific one. some routers support pinging a remote serve. this way you could perhaps see if your internal LAN/WLAN is laggy or if it is the internet connection

**Comment by Franiac** [comment]
See #100
