### ISSUE TITLE
Encoding error i think.

### ISSUE THREAD

**Issue by masterbustero2** [Franiac/TwitchLeecher#99]
I have been getting this error after i download a video i think it has something to do with encoding? I tried swapping temp file location did not work and tried swapping to 30fps nope here is end of log (I changed some file location names) 
Also windows 10 64bit, Twitch Leecher version 1.3.6 and channel trying to download Admiral_bahroo https://www.twitch.tv/videos/116806651

Creating directory 'C:\Users\ Computer\Desktop\stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_25a15fd3-e3e7-475d-b78f-ed8cb8e91500'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/chunked/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/high/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/medium/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/low/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/mobile/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/audio_only/index-dvr.m3u8

Playlist url for selected quality 1280x720@30fps is https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/high/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 419

Starting parallel video chunk download
Number of video chunks to download: 419
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local file list for FFMPEG... done!
Writing file list to 'C:\Users\ Computer\Desktop\stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_25a15fd3-e3e7-475d-b78f-ed8cb8e91500\parts.txt'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -f concat -safe 0 -i "C:\Users\Leanne's Computer\Desktop\ stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_25a15fd3-e3e7-475d-b78f-ed8cb8e91500\parts.txt" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\ Computer\Desktop\ stuff\Twitch Vods\20170124_Admiral_Bahroo_Small 1life Chill stream _ Twitter @AdmiralBahroo.mp4"

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\ Computer\Desktop\ stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_25a15fd3-e3e7-475d-b78f-ed8cb8e91500'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String partList, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String partList, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

(I used this short stream as a test download)

**Comment by Franiac** [comment]
Please always post the entire log. i cannot see if you cropped the VOD (and at what times) or not.

**Comment by masterbustero2** [comment]
OW sorry also I did not crop it at all

**Comment by masterbustero2** [comment]
I'm not at my computer right now but I can do it later today

**Comment by masterbustero2** [comment]
Here is full log i did not change file locations names because that is way to much to go through

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.3.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 116806651
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/116806651
Crop Start: Yes (00:00:01)
Crop End: Yes (00:13:34)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\20170124_Admiral_Bahroo_Small 1life Chill stream _ Twitter @AdmiralBahroo.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_2ddcc47b-c179-4cee-8598-910e09a44c36

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22user_id%22%3A71561333%2C%22vod_id%22%3A116806651%2C%22expires%22%3A1486162050%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%2C%22https_required%22%3Afalse%7D
Signature: 88de7b367dc357fcc3bdf1d501d62f4170152bb1
Sub-Only: No
Privileged: No

Creating directory 'C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_2ddcc47b-c179-4cee-8598-910e09a44c36'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/chunked/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/high/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/medium/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/low/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/mobile/index-dvr.m3u8
https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/audio_only/index-dvr.m3u8

Playlist url for selected quality 1280x720@60fps is https://vod154-ttvnw.akamaized.net/4a226f4f89_admiral_bahroo_24320196240_588682767/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 419

Starting parallel video chunk download
Number of video chunks to download: 419
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Creating local file list for FFMPEG... done!
Writing file list to 'C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_2ddcc47b-c179-4cee-8598-910e09a44c36\parts.txt'... done!

Executing 'C:\Program Files\Twitch Leecher\ffmpeg_x64.exe' on local playlist...
Command line arguments: -y -f concat -safe 0 -i "C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_2ddcc47b-c179-4cee-8598-910e09a44c36\parts.txt" -analyzeduration 2147483647 -probesize 2147483647 -c:v copy -c:a copy -bsf:a aac_adtstoasc -ss 1 -t 813 "C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\20170124_Admiral_Bahroo_Small 1life Chill stream _ Twitter @AdmiralBahroo.mp4"


Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Leanne's Computer\Desktop\Buster's stuff\Twitch Vods\Twitch Leecher\Temp Files\TL_2ddcc47b-c179-4cee-8598-910e09a44c36'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String partList, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ApplicationException: An error occured while encoding the video!
   at TwitchLeecher.Services.Services.TwitchService.EncodeVideo(Action`1 log, Action`1 setStatus, Action`1 setProgress, Action`1 setIsEncoding, String ffmpegFile, String partList, String outputFile, CropInfo cropInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass55_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
Crop Start: Yes (00:00:01)
Crop End: Yes (00:13:34)

That does not look like you were not cropping :)

**Comment by Franiac** [comment]
I tested it and if you do not crop (do not actiave those cropping checkboxes) the VOD downloads without errors. As for the issue when you actually are cropping please see #96
